### ISSUE TITLE
OAI: LAC-required metadataPrefix

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#1003]
For ETD-MS metadata, set `metadataPrefix` as `oai_etdms`
(this is not a namespace prefix but a metadata standard prefix for oai requests)

**Comment by piyapongch** [comment]
I have added the prefix.

**Comment by anayram** [comment]
All good. Sample tests:

http://plano.library.ualberta.ca:8983/fedora/rest/oai?verb=ListMetadataFormats
oai_etdms prefix comes through

http://plano.library.ualberta.ca:8983/fedora/rest/oai?verb=ListRecords&metadataPrefix=oai_etdms
