### ISSUE TITLE
OAI: LAC-required date granularity

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#1006]
From http://www.bac-lac.gc.ca/eng/services/theses/Pages/harvesting.aspx

> Date granularity: You must use the UTC date granularity of YYYY-MM-DDThh:mm:ssZ for the following OAI elements:
> ```
> <responseDate>
> <earliestDatestamp>
> <datestamp>
> ```

**Comment by piyapongch** [comment]
I have used the format for <earliestDatestamp> and <datestamp>. I will fix the <responseDate>.

**Comment by piyapongch** [comment]
The `<responseDate>` is correct according to OAI-PMH.xsd schema. It uses element type, dateTime. Do you want to change the `<responseDate>` to oai:UTCdataetimeType? This change will apply to all metadataPrefix.

**Comment by piyapongch** [comment]
I think I know how to change it without changing the schema.

**Comment by piyapongch** [comment]
I have changed response date for all verbs to UTC date format. You can check them on plano.

**Comment by anayram** [comment]
All good, tested date granularity in all three elements:

Sample tests:
https://era-test.library.ualberta.ca/oai?verb=Identify
http://plano.library.ualberta.ca:8983/fedora/rest/oai?verb=Identify
http://plano.library.ualberta.ca:8983/fedora/rest/oai?verb=ListRecords&metadataPrefix=oai_etdms
