### ISSUE TITLE
OAI: LAC-required repository url

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#1007]
From LAC's OAI requirements at http://www.bac-lac.gc.ca/eng/services/theses/Pages/harvesting.aspx :

> **2.6 Repository URL**
> The repository URL should be replaced with the valid URL. LAC's Repository URL in its "Identify" responses is http://oai.collectionscanada.gc.ca/oai/oai.php

**Comment by piyapongch** [comment]
In our response, the baseUrl is https://era.library.ualberta.ca/oai. I think it should be working. We will create a proxy to the URL that redirect to our OAI Provider, http://gillingham.library.ualberta.ca:8080/fedora/rest/oai. Here is the response.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OAI-PMH xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:etd_ms="http://www.ndltd.org/standards/metadata/etdms/1.0/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd
    http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd
    http://www.ndltd.org/standards/metadata/etdms/1.0/ http://www.ndltd.org/standards/metadata/etdms/1-0/etdms.xsd">
    <responseDate>2016-03-08T11:00:13.016-07:00</responseDate>
    <request verb="Identify">http://localhost:8080/fedora/rest/oai?verb=Identify</request>
    <Identify>
        <repositoryName>ERA: Education and Research Archive</repositoryName>
        <baseURL>https://era.library.ualberta.ca/oai</baseURL>
        <protocolVersion>2.0</protocolVersion>
        <adminEmail>eraadmi@ualberta.ca</adminEmail>
        <earliestDatestamp>2016-03-01T18:42:27Z</earliestDatestamp>
        <deletedRecord>no</deletedRecord>
        <granularity>YYYY-MM-DDThh:mm:ssZ</granularity>
    </Identify>
</OAI-PMH>

**Comment by anayram** [comment]
I think this can be closed @piyapongch 

Identify requests return the correct baseURL
`<baseURL>https://era.library.ualberta.ca/oai</baseURL>
`
https://era-test.library.ualberta.ca/oai?verb=Identify
http://plano.library.ualberta.ca:8983/fedora/rest/oai?verb=Identify

**Comment by piyapongch** [comment]
Do we need to support http? Right now, we support only https.

**Comment by piyapongch** [comment]
If harvester point to http://era-test.library.ualberta.ca/oai, the server will redirect to https.

**Comment by anayram** [comment]
@pbinkley @piyapongch can this be closed?
Not sure if there is still a question of whether we need to support http.

**Comment by pbinkley** [comment]
No, I don't see any reason to support http. Go ahead and close.
