### ISSUE TITLE
All logged in users able to edit official collections

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#1008]
If there was a "very high" priority label I would flag this with it. I just discovered that any logged in users can edit official collections. This is me logged in as myself (regular user) editing a community. One of our users has already edited a number of our official collections (with good intentions):

![screen shot 2016-03-08 at 5 24 22 pm](https://cloud.githubusercontent.com/assets/12801010/13621199/f1094384-e552-11e5-8bb0-e34e30c7288a.png)

Delete button also appears in the sub collections beneath - I didn't follow through with testing if that's also enabled...

![screen shot 2016-03-08 at 5 27 28 pm](https://cloud.githubusercontent.com/assets/12801010/13621234/2f75ebfe-e553-11e5-8b77-54832650138d.png)

**Comment by pgwillia** [comment]
At least part of this was solved in https://github.com/ualbertalib/HydraNorth/issues/992

**Comment by pgwillia** [comment]
@sfbetz we added this behaviour back in September.  https://github.com/ualbertalib/HydraNorth/issues/92 Remind me again what the difference between "official" and "admin" collections are?

**Comment by weiweishi** [comment]
Admin collection is user can't deposit into, like theses or dataverse.
Official allows users to deposit

I think it indicates we should separate editing description from adding to
collection? That's going to be a much bigger task than changing Cancan.
Maybe it's easier to hide the edit button from interface for regular users.

2016年3月9日星期三，pgwillia <notifications@github.com> 写道：

> @sfbetz <https://github.com/sfbetz> we added this behaviour back in
> September. #92 <https://github.com/ualbertalib/HydraNorth/issues/92>
> Remind me again what the difference between "official" and "admin"
> collections are?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1008#issuecomment-194417564>
> .
>


-- 

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfbetz** [comment]
My understanding: official collections and communities will appear on browse pages, and will appear in deposit form. They should all be owned by admin. 

Users should be able to browse and deposit into official collections, but should not be able to edit, delete, or add collections to official collections.

**Comment by sfbetz** [comment]
Admin users should be able to do all the things...

**Comment by pgwillia** [comment]
I spent the morning trying to figure out how to prevent a non-admin user from editing official collections but still be able to deposit into it. I couldn't find a way to make this happen. Suggestions appreciated!

In the interest of speed I can implement @weiweishi suggestion. I can only show the edit action to admin users and users with the correct permissions when the collection is not official. This doesn't prevent the user from editing the collection, just removes the link.  If a user ends up at collections/<id>/edit of their own accord, they would be able to edit the collection metadata.

**Comment by sfbetz** [comment]
That sounds like a good stopgap solution. Thanks for your quick work on this!
