### ISSUE TITLE
Allow users to search across collections from a community

### ISSUE THREAD

**Issue by criedlberger** [ualbertalib/HydraNorth#1010]
This was originally a part of #961 but needs a separate issues due to it's complexity.

**Comment by leahvanderjagt** [comment]
Hi there! I've had a few users ask me about the search w/in community feature. Can we confirm that this is something we decided to leave alone? I'm not sure of the status given this ticket. Thanks in advance! Leah

**Comment by sfbetz** [comment]
Captured in specs for CollectionsNorth gem. Won't fix for Sufia 6
