### ISSUE TITLE
Collections disappearing from edit page

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#1016]
I think that an old bug has resurfaced. Collection appears to be dropping out of the edit page. See here: https://era.library.ualberta.ca/files/bg257h774/edit

This item is in the Daily Record collection, but on edit, collection disappears from that field. :(

Sounds like #916 has reappeared?

**Comment by sfbetz** [comment]
Consequence of this bug = items being pulled out of collections each time they are are edited and saved.

**Comment by pgwillia** [comment]
I think this might be because the javascript that scopes the collection depending on community doesn't select (or re-select) any existing selection(s).

**Comment by mbarnett** [comment]
The best way to fix this would probably be to render the page with only collections for the item's current community in that dropdown, and then only run the javascript on community changes.

Right now I think it generates that dropdown with all collections, and then immediately on page load runs the javascript to re-load the collection list with only the collections for the selected community, which is both inefficient and requires duplicating the selection logic between the view and js.

**Comment by pgwillia** [comment]
:+1:

**Comment by pgwillia** [comment]
This does fix the bug reported but I noticed that
- the batch edit page allows the user to select more than one community/collection pair.  All collection selection boxes are limited to the community selection highest on the page.
![screenshot from 2016-03-15 11-32-05](https://cloud.githubusercontent.com/assets/1220762/13787442/969e50ca-eaa1-11e5-95db-e02d5676c65c.png)
- the file edit page never updates the collections with the changing of community
![screenshot from 2016-03-15 11-33-47](https://cloud.githubusercontent.com/assets/1220762/13787528/eb50feb0-eaa1-11e5-8a82-18c08db26ec1.png)
  - the workaround for this change is to update once for the community change and then make a collection change. If the collection is not in the community chosen it will not be in the selection box.

@leahvanderjagt want a quick demo to double check this is the expected behaviour?

**Comment by mbarnett** [comment]
I missed the batch edit. File edit was working for me, but I'll double check.

> the workaround for this change is to update once for the community change and then make a collection change. If the collection is not in the community chosen it will not be in the selection box.

I don't know if this makes sense or is solvable in a general sense. If a file is in Community A but Collection X (which is not a member of A), we could put X in the second drop-down (although it's going to be an ugly hack to make that work), but if the user changes the Community to B and then back to A (say their finger slipped, or they were curious), they'll have "lost" the ability to select the Community A/Collection X combination.

I think we either need to enforce this Collection-has-to-be-in-the-selected-Community logic, or abandon it and go back to the full collection list. There's too many corner cases if we try to straddle the line somehow.

**Comment by mbarnett** [comment]
My understanding coming out of discussion with @pgwillia , @sfbetz, and @leahvanderjagt  :

1) There is no case in which an item can legitimately belong to a Community and a Collection that is not in that Community. It a user has placed an item into a personal collection, it is ok if when editing that item, the form "loses" that personal collection, and only presents official collections in the selected Community. 

2) @sfbetz and @leahvanderjagt are going to discuss the upload form's ability to place an item into multiple Communities and Collections simultaneously, which does not currently work with this fix (all Collection select boxes on the page are scoped to the first selected Community). 

Background: Although the upload form allows items to be placed in multiple Communities/Collections simultaneously, there are a number of bugs that currently impact items in multiple Communities/Collections: only the first Community/Collection selected is visible when visiting an item, when editing an item only one Community/Collection may be selected and there is no ability to see or edit any other Communities/Collections the item was added to in the upload process (which may lead to the loss of those other Communities/Collections when saving the item after editing), and there may be other bugs impacting various other parts of the site that we haven't encountered yet.

Possible paths forward here include:

* Remove the multiple Community/Collection ability on the upload page, keeping the scope of this fix as-is, and create a new ticket (likely an epic) to get multiple Communities/Collections working across the site. The downside of this is that we're removing functionality that self-deposit users may (or may not) be using at the moment, however buggy and underdeveloped it is. This may create additional work for admins facilitating batch uploads, which will still be usable for placing items into multiple Communities/Collections. 

* Fix the upload form to work with this fix when selecting multiple Communities/Collections. This would rescope this ticket from a Medium to Large and likely add 2 days of development time. The downside is that we're sinking development time into a feature that we know doesn't work well, and which may change in implementation when we go to fix items in multiple Communities/Collections across all of ERA, potentially negating some work done here.

* Rescope this ticket to include fixing items in multiple Communities/Collections across all of ERA, changing this ticket from a Medium to an Extra-Large or Epic. The downside here is that this is considerable scope-creep in the current sprint, and we're significantly delaying a deployment of a fix for a high-priority bug that is currently in Production.

My view is that option #3 is the least-desirable outcome from a scope and Project Management perspective. We will need to spend time fleshing out how multiple Communities/Collections should work across ERA, and how it impacts other features on the site, which will make this ticket much harder to close. Fixing multiple Communities/Collections is probably best suited to several dedicated tickets on its own.

**Comment by pgwillia** [comment]
@mbarnett https://github.com/ualbertalib/HydraNorth/commit/6948951a957c1344e260de6b41d068d7b993463e is the change we looked at last Friday.

**Comment by weiweishi** [comment]
Thanks for the summary @mbarnett 

I think it makes sense to temporarily disable the multiple communities/collections on the deposit form, as we can still handle it from the rails console if needed. 

I also agree that we should create a separate epic and look into these issues separately, and look into how underlying data model should be in place to support this feature. This is also tightly related to some of the PCDM collection designs, and it would ultimately change the way we handle (multiple) nested collections.  So it may not make much sense to invest too much time into it, if it's not a high priority for @leahvanderjagt and @sfbetz .

**Comment by leahvanderjagt** [comment]
Sonya and I both agree that Matt's first listed path is what we should do.
I can think some important use cases for multiple communities/collections
so the epic is needed, but let's fix what we need to now, and have
consistent presentation of community/collection assignment in deposit and
edit.

One question I had:
When a user edits an item that has originally had multiple
community/collections assigned and is presented with the first assigned
community/collection (as agreed here) then saves their edits, does the item
lose the association to the rest of the communities/collections? If so,
that would not be good -  we need some way to keep that data.

**Comment by mbarnett** [comment]
That needs some investigation, because I'm not sure what happens in such cases at the moment. I'll try to have an answer on this shortly.

**Comment by pbinkley** [comment]
A lot of this will have to be revisited after PCDM anyway, and the
incorporation of Peel will bring new requirements for community and
collection membership, so I agree with the proposed direction.
