### ISSUE TITLE
OAI: ETDMS / DC Metadata Mapping to New URI Prefixes

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/HydraNorth#1017]
Re-mapping all fields to new namespace URI.

**Comment by piyapongch** [comment]
I am waiting for audit process to update data to correct namespace URI.

**Comment by piyapongch** [comment]
I have mapped all Fedora 4 properties to oai_etdms element using incorrect namespace uri.

**Comment by piyapongch** [comment]
The mapping will need to be changed when the Fedora properties have been changed to correct namespace uri.

**Comment by anayram** [comment]
All tests look ok with the current mappings.

Should we keep this ticket open until the mappings are updated after Fedora properties have been changed to correct uris and new prefixes?

**Comment by piyapongch** [comment]
Here are namespace uri prefixes on the repository.

PREFIX premis: <http://www.loc.gov/premis/rdf/v1#>
PREFIX nt: <http://www.jcp.org/jcr/nt/1.0>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hydragroup: <http://projecthydra.org/ns/auth/group#>
PREFIX hydraacl: <http://projecthydra.org/ns/auth/acl#>
PREFIX ualname: <http://terms.library.ualberta.ca/name/>
PREFIX xsi: <http://www.w3.org/2001/XMLSchema-instance>
PREFIX mode: <http://www.modeshape.org/1.0>
PREFIX xmlns: <http://www.w3.org/2000/xmlns/>
PREFIX oai: <http://www.openarchives.org/OAI/2.0/>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX model: <info:fedora/fedora-system:def/model#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX fedoraconfig: <http://fedora.info/definitions/v4/config#>
PREFIX mix: <http://www.jcp.org/jcr/mix/1.0>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX authz: <http://fedora.info/definitions/v4/authorization#>
PREFIX oai-id: <http://www.openarchives.org/OAI/2.0/oai-identifier>
PREFIX relsext: <info:fedora/fedora-system:def/relations-external#>
PREFIX image: <http://www.modeshape.org/images/1.0>
PREFIX sv: <http://www.jcp.org/jcr/sv/1.0>
PREFIX test: <info:fedora/test/>
PREFIX ualterms: <http://terms.library.ualberta.ca/>
PREFIX ualid: <http://terms.library.ualberta.ca/id/>
PREFIX uatermsid: <http://terms.library.library.ca/identifiers/>
PREFIX ualplace: <http://terms.library.ualberta.ca/place/>
PREFIX scholarsphere: <http://scholarsphere.psu.edu/ns#>
PREFIX ualsubj: <http://terms.library.ualberta.ca/subject/>
PREFIX ualdate: <http://terms.library.ualberta.ca/date/>
PREFIX ualrole: <http://terms.library.ualberta.ca/role/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX fedora: <http://fedora.info/definitions/v4/repository#>
PREFIX marcrel: <http://id.loc.gov/vocabulary/relators/>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
PREFIX ualthesis: <http://terms.library.ualberta.ca/thesis/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX webacl: <http://www.w3.org/ns/auth/acl#>
PREFIX xs: <http://www.w3.org/2001/XMLSchema>
PREFIX ualidentifier: <http://terms.library.ualberta.ca/identifiers/>
PREFIX ualtitle: <http://terms.library.ualberta.ca/title/>
PREFIX etdms: <http://www.ndltd.org/standards/metadata/etdms/1.0/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

**Comment by pbinkley** [comment]
Can close this after deployment.
