### ISSUE TITLE
Collections facets not updating when collection titles are changed

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#1022]
It looks like collection titles in facets aren't updating to match changes to collection titles. I renamed the collection "taken for grant-ed" several weeks ago to "workshop materials" (SSHRC). However, the old collection title is still being listed as a facet.

![screen shot 2016-03-14 at 5 07 55 pm](https://cloud.githubusercontent.com/assets/12801010/13762887/a1560e76-ea07-11e5-9be0-b8a33ea4f78a.png)

The items are all in the correct collection, and seem to be listing the collection title correctly on the item show page. it just seems that the facets aren't updating.

Here is the collection to test with: https://era.library.ualberta.ca/collections/44558s61g?page=2

**Comment by pbinkley** [comment]
We need to force reindexing of the member items. This will happen when we
do the big audit fix, but we can run these 13 items manually.

**Comment by sfbetz** [comment]
Thanks Peter! 

Glad it's not a bug.

**Comment by pbinkley** [comment]
Decision: we'll manually reindex items in collections whose names change, until after PCDM. Leah will notify Peter/Weiwei when this happens.
