### ISSUE TITLE
Clicking on any name listed as 'Additional contributor' returns all ERA items

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#1025]
If you click on a name listed under 'Additional Contributors' on an item screen (e.g., https://era.library.ualberta.ca/files/0k225c055#.VuwbKdUrK72) you are returned all ERA items.

Form of the link URL from example above: https://era.library.ualberta.ca/catalog?contributor=%22Chambers%2C+Thane%22&search_field=advanced

**Comment by pbinkley** [comment]
Note index in the url: contributor instead of contributor_sim (or whatever the suffix should be)
