### ISSUE TITLE
Comprehensive performance diagnosis spike

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1033]
Look into the performance bottlenecks across our current architecture, and detemine what easy wins there might be to improve performance in the UI.

**Comment by pbinkley** [comment]
This came up at LDCX: https://wiki.duraspace.org/display/FF/Performance+and+Scalability+Test+Plans  . If we could contribute some numbers as a by-product of our diagnostics, that would be nice.

**Comment by mbarnett** [comment]
I've pushed a branch (https://github.com/ualbertalib/HydraNorth/tree/1033_performance_testing) that adds profiling instrumentation to Hydranorth when run in a development environment. Appending a ```?trace=1``` query parameter to any URL will cause a ```profile-stack.html``` file to be written to the Rails root folder containing a visualization of the relative time spent in each method in the callstack during the page render. Note that this file is rewritten each time you visit a URL with ```trace=1``` set, so rename the file after a page load if you want to keep it around. 

Note that percentages and times in the profile refer only to time in the *Ruby* process. If a request takes 6 seconds total and of that spends 1 second in Ruby and 5 seconds in Fedora (meaning that the Ruby thread is blocked waiting on IO to return from Fedora) , then a call that takes 43% in a trace takes 43% of *1 second*, not all 6.

I'm attaching files containing callstacks that illustrate hotspots in several highly trafficed areas of the application, and will be opening tickets to try to alleviate these issues. Once they're removed, it will probably be worthwhile to re-profile to see if additional hotspots can be identified that were "hidden" by these initial issues. It would also be good to take additional measurements on a machine with much larger collections, as we may be able to identify superlinear hotspots that aren't obvious in collections with only a handful of items in them.

[Profiles](https://github.com/ualbertalib/HydraNorth/files/198648/Profiles.zip)

The file ```profile-stack-my-files-master.html``` shows two major hotspots when visiting the my files page in my dashboard with 10 generic files that I've uploaded: 

1) ```Sufia::GenericFile::Batches#processing?``` which is called 10 times (one per file on the page) to determine whether to render the "spinner" that is shown when a file has been uploaded but not yet characterized -- these 10 calls consume 43.21% of the total render time.

2) ```GenericFileHelper#render_collection_list``` which is called 10 times (one per file on the page) to populate the "Is part of: " links on each file in the list -- these 10 calls consume another 30.38% of the total render time.

The file ```profile-stack-my-files-master.html``` likewise shows two major hotspots when viewing a GenericFile show page:

1) ```Sufia::GenericFile::Batches#processing?```, called once, as above -- consuming 10.05% of the total render time.

2) ```Sufia::GenericFile::Batches#related_files```, called once, to attempt to populate a list of "related files" at the bottom of the page (these files, if there are any, would be other files in the batch) -- this call consumes 23.70% of the total page render time.

The file ```profile-stack-collection-show-master.html``` contains the profile generated when visiting a collection containing three items. It shows 3 hotspots, all similar to the above:

1) ```Sufia::GenericFile::Batches#processing?```, called three times, as above -- consuming 30.10% of the total render time.

2) ```GenericFileHelper#render_collection_list``` which is called 3 times (one per file on the page) to populate the "Is part of: " links on each file in the list -- these 3 calls consume another 28.00% of the total render time.

3) ```GenericFileHelper#render_collection_list``` strangely called once more in a separate partial, consuming another 10.43% of the total render time.

**Comment by mbarnett** [comment]
I think the common themes to these results so far are:

1) Calls to methods in ```GenericFile::Batch``` are extremely expensive, mostly because the seem to involve very heavyweight calls to ```Ldp::Resource::RdfSoruce#graph```.

2) 2 of these 3 hotspots are to determine whether or not to show a spinner, and whether or not to show "related files". We're paying a lot for tiny features that are shown only rarely.
