### ISSUE TITLE
OAI: private items metadata exposed through GetRecord requests

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#1035]
I was testing items with different access permissions to see if metadata was exposed via OAI and found that if you have a private item's oai identifier you can access its metadata.

For example, I created a private item in plano titled 'testprivateitem'

The metadata does not come through if I search for it, which is great:
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_dc&verb=Search&property=dcterms:title&value=testprivateitem

But it does if I request GetRecord through its oai identifier.
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_dc&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t73t945s04z

In theory if someone knows a noid assigned to a private item (and knows how arks are constructed) s/he would be able to replicate an item's ark and get metadata for private objects.

**Comment by pbinkley** [comment]
It also doesn't come up in a date range OAI query that ought to include it:
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_dc&verb=ListIdentifiers&from=2016-03-28T00:00:00Z
. Do we know if that query respects the status of the item, while GetRecord
doesn't? If so, maybe we can adapt the GetRecord process to call Solr or
otherwise retrieve the access restrictions, which won't be too expensive
since it only applies to a single record.

**Comment by sfarnel** [comment]
My thought would be that the OAI metadata visibility should mirror the
visibility we have locally. That is, open items: metadata visible, item
accessible; UA access: metadata visible, item accessible with ccid; private
items: metadata not visible, item not visible; embargoed items: metadata
not visible, item not visible while under embargo; after embargo lifts can
be one of the other types. Policy decision for @leahvanderjagt :)

On Tue, Mar 29, 2016 at 3:20 PM, Peter Binkley <notifications@github.com>
wrote:

> It also doesn't come up in a date range OAI query that ought to include it:
>
> http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_dc&verb=ListIdentifiers&from=2016-03-28T00:00:00Z
> . Do we know if that query respects the status of the item, while GetRecord
> doesn't? If so, maybe we can adapt the GetRecord process to call Solr or
> otherwise retrieve the access restrictions, which won't be too expensive
> since it only applies to a single record.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1035#issuecomment-203109943>
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
That probably goes beyond what we can achieve at the technical level
without a major investment of development time. The OAI server doesn't
currently have any authentication. Permissions are not stored as part of
the main Fedora object, and any access to related objects is very expensive
in processing time when applied one-by-one to large result sets. I think
ultimately we may want to develop our own Solr-based OAI server in order to
get easy access to all the information about an object, but for now we'll
have to live with some constraints.

**Comment by sfarnel** [comment]
is it possible to at least only make the open items metadata available? i
believe we'd talked about that before.

On Wed, Mar 30, 2016 at 11:17 AM, Peter Binkley <notifications@github.com>
wrote:

> That probably goes beyond what we can achieve at the technical level
> without a major investment of development time. The OAI server doesn't
> currently have any authentication. Permissions are not stored as part of
> the main Fedora object, and any access to related objects is very expensive
> in processing time when applied one-by-one to large result sets. I think
> ultimately we may want to develop our own Solr-based OAI server in order to
> get easy access to all the information about an object, but for now we'll
> have to live with some constraints.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1035#issuecomment-203535206>
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
yes, that's the bit we need to solve in this ticket. We can't go live with
OAI if it's giving away metadata for private items.

**Comment by anayram** [comment]
I think that the metadata visibility policies @sfarnel mentioned are working well now except for the problem described in this issue.

For instance, I can see metadata for open items and for ccid-protected items. In those two cases the metadata should be public so OAI exposure is ok.

@piyapongch was wondering what priority should be assigned to

**Comment by sfarnel** [comment]
great; thanks peter. just wanted to make sure that was doable.

On Wed, Mar 30, 2016 at 11:22 AM, Peter Binkley <notifications@github.com>
wrote:

> yes, that's the bit we need to solve in this ticket. We can't go live with
> OAI if it's giving away metadata for private items.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1035#issuecomment-203538085>
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by leahvanderjagt** [comment]
I was writing a response re: the CCID protected items - was looking at the
OAI-PMH protocol to see if authentication is mentioned, which it isn't, but
there are plenty of posts/discussion about it online that point to
authenticated access as an acceptable use case for OAI. The future-solution
Peter proposed with the solr-base OAI server should reflect the protocol
and also (I hope) each scenario Sharon listed.

On Wed, Mar 30, 2016 at 11:22 AM, Sharon Farnel <notifications@github.com>
wrote:

> great; thanks peter. just wanted to make sure that was doable.
>
> On Wed, Mar 30, 2016 at 11:22 AM, Peter Binkley <notifications@github.com>
> wrote:
>
> > yes, that's the bit we need to solve in this ticket. We can't go live
> with
> > OAI if it's giving away metadata for private items.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/1035#issuecomment-203538085
> >
> >
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1035#issuecomment-203538593>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by sfarnel** [comment]
Thanks Leah!

On Wed, Mar 30, 2016 at 11:25 AM, leahvanderjagt <notifications@github.com>
wrote:

> I was writing a response re: the CCID protected items - was looking at the
> OAI-PMH protocol to see if authentication is mentioned, which it isn't, but
> there are plenty of posts/discussion about it online that point to
> authenticated access as an acceptable use case for OAI. The future-solution
> Peter proposed with the solr-base OAI server should reflect the protocol
> and also (I hope) each scenario Sharon listed.
>
> On Wed, Mar 30, 2016 at 11:22 AM, Sharon Farnel <notifications@github.com>
> wrote:
>
> > great; thanks peter. just wanted to make sure that was doable.
> >
> > On Wed, Mar 30, 2016 at 11:22 AM, Peter Binkley <
> notifications@github.com>
> > wrote:
> >
> > > yes, that's the bit we need to solve in this ticket. We can't go live
> > with
> > > OAI if it's giving away metadata for private items.
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ualbertalib/HydraNorth/issues/1035#issuecomment-203538085
> > >
> > >
> >
> >
> >
> > --
> > Sharon Farnel
> > Metadata Coordinator
> > University of Alberta Libraries
> > sharon.farnel@ualberta.ca
> > 780-492-3685
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/1035#issuecomment-203538593
> >
> >
>
>
>
> --
> ___________________________________________________________
>
>
>
>
> *Leah VanderjagtDigital Repository Services Librarian University of
> Albertat. 780.492.3851 *
> *leahv@ualberta.ca <leahv@ualberta.ca> *
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1035#issuecomment-203540058>
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
​Once we're working against Solr that will all be much much easier, since
we'll just imitate the queries that Sufia uses, and Solr contains all the
information we need. If I had realized at the start how difficult the
Fedora-based OAI package would be to adapt to HydraNorth, I'd have started
us on a Solr-based approach. But for now I just want to get the thing done.

**Comment by pbinkley** [comment]
@piyapongch has determined that a new module is necessary to handle GetRecord requests, to filter out non-public items in the same way as other requests do.

**Comment by piyapongch** [comment]
Currently, the GetRecord verb works by parsing the id and get only the object itself. There is no way to know about permission. I will need to rewrite the GetRecord verb using JCR-SQL2 that might have an effect on performance. This also will take some time. With all issues that I have to finish, we might not be able to lunch next week.

**Comment by anayram** [comment]
Fixed. Closing ticket.
