### ISSUE TITLE
OAI: oai_etdms metadataPrefix not working with GetRecord requests

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#1036]
It looks like the oai_etdms metadata prefix only works with some oai verbs and not others.

GetRecord & metadataPrefix oai_dc works fine:
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_dc&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t7dn39x2787
whereas GetRecord with the oai_etdms metadata prefix doesn't:
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t7dn39x2787

ListRecords and ListIdentifiers w/ oai_etdms work ok:
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=ListRecords
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=ListIdentifiers

**Comment by anayram** [comment]
@piyapongch

**Comment by piyapongch** [comment]
The fedora3handle property is not in the correct format. It should be
http://hdl.handle.net/10402/era.39091 or http://hdl.handle.net/10048/39091.

I am using the handle to create the LAC unique identifier.


Piyapong.

**Comment by piyapongch** [comment]
I will add code to catch the error and ignore the incorrect handle.

Piyapong.

**Comment by anayram** [comment]
Is the handle problem related to #1004 ?

**Comment by anayram** [comment]
Or is it because the record has a fake handle that the request doesn't work?

That seems to be the case because this works:
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_dc&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t73197xn10w

**Comment by anayram** [comment]
Also, I have not been able to use date range OAI queries with the oai_etdms metadataPrefix

Example:
these work
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=ListIdentifiers
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=ListRecords

but these don't
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=ListIdentifiers&from=2016-03-28T00:00:00Z
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=ListRecords&from=2016-03-28T00:00:00Z

**Comment by piyapongch** [comment]
Try them again.

Piyapong.

**Comment by anayram** [comment]
Everything works now. Thanks @piyapongch  Closing now.
