### ISSUE TITLE
ERA migration - metadata

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#104]
As the metadata team, we want to migrate metadata from existing ERA into the DAMS so that it can function in the new environment consistently with new metadata.
Note: depends on Data Dictionary #103 
- [ ] Hydra North team agrees upon a structure for local namespaces
- [ ] image items currently of ERA item type 'research material' are identified and labeled with item type 'image'
- [ ] metadata is transformed according to the specifications outlined in the Data Dictionary
- [ ] migrated metadata is stored in Fedora, indexed and searchable in Solr consistently with new metadata

**Comment by awakaruk** [comment]
Sharon and I offer this priority list for migration between now and launch:
CRI - images
OSRIN
Department of Political Science
Library Staff Publications
MACT
Department of Biological Sciences
Faculty of Nursing

**Comment by sfbetz** [comment]
Metadata team breaking this down into smaller issues as per metadata migration repo. Will add back as individual issues
