### ISSUE TITLE
GenericFileHelper#render_collection_list is sloooow

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1040]
This helper method renders "Is part of: <collection>" information for generic files on collection and my files pages. This information *should* be available on the generic file's solr record, but for some reason calls to this method are calling into ActiveFedora and ultimately triggering calls to ```ActiveFedora::LdpResource#build_graph```.

Needs investigation as to why this is happening so that we can just rely on the (fast) solr data for rendering these labels.

This is part of the work coming out of #1033

**Comment by pbinkley** [comment]
Closed by #1058
