### ISSUE TITLE
Sufia::GenericFile::Batches#related_files is sloooow

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1041]
This is used to (attempt) to render a list of "Related Files" when viewing a Generic File's information. A "related file" appears to be any file that was uploaded in the same batch as the file being viewed.

As far as I can tell, most (or all?) files in the system were uploaded in their own batch, so this "Related Files" section rarely if ever appears when viewing a file (I cannot find any examples of it). Nevertheless we're paying the cost of *trying* to render the list each time a user tries to view a file.

I think the simplest solution here is simply to remove the rarely-shown section and eliminate the calls to ```Sufia::GenericFile::Batches#related_files``` entirely.

This is part of the work coming out of #1033

**Comment by johnhuck** [comment]
related_files wouldn't be related to an aspect of the modelling in an earlier version of pcdm, which had pcdm:hasRelatedFile for external metadata would it? If it were, it could be a legacy artifact at this point, because I think may have gone away in the latest pcdm model. Here's an older discussion around its use: https://github.com/duraspace/pcdm/wiki/Related-Files

Current pcdm: https://wiki.duraspace.org/display/FF/GenericWork+-+GenericFile+Model%2C+Design%2C+and+Implementation+Discussions

**Comment by mbarnett** [comment]
I don't believe so -- AFAICT this is unrelated to anything in PCDM. It's purely a Sufia/UI concept where it wants to show "sibling" files that were uploaded with the same batch id.

**Comment by pbinkley** [comment]
I think the user story behind this was from the original Sufia idea of a
self-deposit general-purpose repository, where a batch would be a bunch of
items uploaded by a given user at one time with shared metadata - say an
album of photos of the same event.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
I agree @mbarnett . All migrated objects are in their own batch, and unless users upload multiple files at once through the deposit form, there will be no use for this piece of information. @sfbetz @leahvanderjagt any concerns?

Batch objects also inflates our Fedora repository. So we should clear these objects out (probably after PCDM as they are phased out in Sufia 7 as well).

**Comment by leahvanderjagt** [comment]
If the question is whether we may have a user story where a user wants to
upload multiple items with one common metadata description with one deposit
action then I think we do have use cases to imagine, probably not on the
side of IR but perhaps yes on the data side.

I might be misinterpreting the question though, so please correct me if I
am not understanding correctly.

On Fri, Apr 1, 2016 at 12:33 PM, Weiwei Shi <notifications@github.com>
wrote:

> I agree @mbarnett <https://github.com/mbarnett> . All migrated objects
> are in their own batch, and unless users upload multiple files at once
> through the deposit form, there will be no use for this piece of
> information. @sfbetz <https://github.com/sfbetz> @leahvanderjagt
> <https://github.com/leahvanderjagt> any concerns?
>
> Batch objects also inflates our Fedora repository. So we should clear
> these objects out (probably after PCDM as they are phased out in Sufia 7 as
> well).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1041#issuecomment-204505950>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by sfbetz** [comment]
I think this also makes a lot of sense. 

@leahvanderjagt, this has no impact on users' ability to upload many files at the same time with shared metadata. It's just the process of ERA checking *every time* to see if an item was uploaded as part of a group of many items and then displaying them as related works. PCDM will provide much more sophisticated ways of displaying relationships (multifile items, muti-work works), and we also have other elements that can more effectively display relationships (related item url, communities and collections). 

I will say that even if users use the multi-upload option to add multiple files at once, there's no guarantee that those items are related in any way other than convenience, so maybe it's not really that useful a piece of information anyway?

**Comment by leahvanderjagt** [comment]
Ah, OK thank you. Yes, I'm with you Sonya. Does not seem useful.

On Fri, Apr 1, 2016 at 1:17 PM, Sonya Betz <notifications@github.com> wrote:

> I think this also makes a lot of sense.
>
> @leahvanderjagt <https://github.com/leahvanderjagt>, this has no impact
> on users' ability to upload many files at the same time with shared
> metadata. It's just the process of ERA checking *every time* to see if an
> item was uploaded as part of a group of many items and then displaying them
> as related works. PCDM will provide much more sophisticated ways of
> displaying relationships (multifile items, muti-work works), and we also
> have other elements that can more effectively display relationships
> (related item url, communities and collections).
>
> I will say that even if users use the multi-upload option to add multiple
> files at once, there's no guarantee that those items are related in any way
> other than convenience, so maybe it's not really that useful a piece of
> information anyway?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1041#issuecomment-204529629>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pbinkley** [comment]
Closed by #1058
