### ISSUE TITLE
Add community title to collection title in OAI ListSets

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1049]
E.g. https://era.library.ualberta.ca/collections/44558v74z should appear as **"Faculty of Education / Graduate Research Showcase"** (where "Faculty of Education" is the community title). This is to make it clear to users what a collection is, since many collections only make sense within the context of the community. A collection has the property  ```ns002:belongsToCommunity = 44558r56d ```, which provides the noid of the community. This is in the ual identifiers namespace, the one that is being changed by the fix script.

**Comment by piyapongch** [comment]
The namespace prefix, ualidentifiers has been added. The community name has been added to ListSets, setName.

**Comment by anayram** [comment]
Community names added. Closing.
