### ISSUE TITLE
OAI - metadata

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#105]
As the metadata team, we want to be able to enable OAI harvesting of Hydra North metadata in multiple formats, including OAI_DC and ETDMS.
Note: depends on OAI providers #38, Data Dictionary #103
- [ ] metadata for OAI is transformed according to the specifications outlined in the Data Dictionary (see #843 and #845)
- [ ] OAI harvesting includes complete and valid OAI_DC and OAI_ETDMS  

Part of #570 - see https://github.com/ualbertalib/HydraNorth/issues/570#issuecomment-142340497

**Comment by piyapongch** [comment]
I have started on adding ETDMS metadata. I will have a meeting with Sharon and Mariana this afternoon and apply to the OAI Provider module.

**Comment by anayram** [comment]
Specs for HydraNorth OAI metadata https://docs.google.com/a/ualberta.ca/document/d/18t2ApNmm7029nP_RiUdeb4ilnfJfZ5R1HSBT4vvTM58/edit?usp=sharing

**Comment by sfarnel** [comment]
Captured in a series of more specific issues.
