### ISSUE TITLE
Show 'stack' of access labels for collections for admin

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1053]
For administrator, in lists of communities and collections, use item permission types to display multiple labels representing the access categories within. 

So, if a collection has a mix of ccid protected and open access materials, display both labels "Open Access" and "University of Alberta" together in a stack. If just OA, display only "Open Access". Only Administrators should see these labels.

**Comment by sfbetz** [comment]
As an administrator, I want to be able to view material by access level so I can easily identify open vs restricted items.

**Comment by pbinkley** [comment]
Will recreate if user story emerges.
