### ISSUE TITLE
Investigate implementation of ResourceSync

### ISSUE THREAD

**Issue by gsharder** [ualbertalib/HydraNorth#1056]
Spec: http://www.openarchives.org/rs/toc

One of the takeaways from a presentation and follow-up discussion with Herbert Van de Sompel at COAR re: interoperability and indexing by search engines.

**Comment by pbinkley** [comment]
ResourceSync will be included in Dataverse 4

**Comment by pbinkley** [comment]
In addition to adding into our codebase, let's look at what would be involved in putting in a PR to current Sufia 7 for this

**Comment by pbinkley** [comment]
Make sure this works with the new download link structure in #1071

**Comment by pgwillia** [comment]
Based on Scholarsphere, we're using this third party [sitemap gem](https://github.com/viseztrance/rails-sitemap).  To add the attributes specified by ResourceSync we'd likely have to fork this project.

The library from CDL [resync gem](https://github.com/CDLUC3/resync) is a possible candidate to aid in implementing a ResourceSync compatible sitemap.

**Comment by pgwillia** [comment]
Rather than make the available tech fit our project, @gsharder @pbinkley what is our driving use case for investigating this?

**Comment by pgwillia** [comment]
- [ ] The  [sitemap gem](https://github.com/viseztrance/rails-sitemap) implements a sitemap attribute lastmod, which we are not currently taking advantage of.
- [ ] use robots.txt as method for discovery using sitemap directive

Another format compatible with sitemap is Syndication feed like RSS or Atom
ResourceSync assumes that this sitemap based document will be used to create, update, delete or audit the content in a mirror or aggregator repository elsewhere.

- [ ] rs:md
  - [ ] capability [at|from,until]
  - [ ] change [type]
  - [ ] **type [hash, length]** <-- would be easy to add
- [ ] rs:ln
  - [ ] href [rel,type]

- [ ] suggests mirrored content for machine access to preserve response time on main server

**Comment by pgwillia** [comment]
https://github.com/mjgiarlo/resync forked rails-sitemap to add resync in 2014
