### ISSUE TITLE
Privacy for email addresses

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#106]
As a user, I want my email address to be hidden from non-admin users, so that I can protect my privacy.

**Comment by weiweishi** [comment]
We do have the user story but never speculate it. 
@pbinkley @sfbetz  Does the following make sense:
[ ] for new user, they will be redirected to edit_profile page first, and filled out their names before proceeding. 
[ ] for migrated users, if they don't have first/last name in the record, they will be redirect to edit_profile page to provide information after their first login in Hydranorth

**Comment by pgwillia** [comment]
I think this issue was referring to the email addresses as user id on the users page (comes from Sufia)
![image](https://cloud.githubusercontent.com/assets/1220762/9891593/8afba810-5bc4-11e5-983e-65fed68d65f7.png)

**Comment by weiweishi** [comment]
Okay. I'll create a new issue for the profile update then. Thanks

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pbinkley** [comment]
Duplicate of #189
