### ISSUE TITLE
Confusing user message to access embargo objects

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1066]
When accessing objects that are embargoed, it gives a confusing error message to the user that they can access it after logging in with CCID. 

![screen shot 2016-04-22 at 10 22 57 am](https://cloud.githubusercontent.com/assets/2047614/14748033/b5ade44e-0874-11e6-8c46-aba3703d1eaf.png)

But after they logged in with CCID, they still see the same error message. 
![screen shot 2016-04-22 at 10 28 50 am](https://cloud.githubusercontent.com/assets/2047614/14748089/0ef0f4e2-0875-11e6-8cdd-170c8b8c5541.png)

**Comment by leahvanderjagt** [comment]
I'd call this priority medium. I'd like to know the difficulty level before
we decide whether it goes in front of PCDM work.

It will only affect users who have received a URL or handle for an
embargoed item. This would not be too many, but will affect theses in ERA
under extended embargo and other items users have self-embargoed.

On Fri, Apr 22, 2016 at 10:29 AM, Weiwei Shi <notifications@github.com>
wrote:

> When accessing objects that are embargoed, it gives a confusing error
> message to the user that they can access it after logging in with CCID.
>
> [image: screen shot 2016-04-22 at 10 22 57 am]
> <https://cloud.githubusercontent.com/assets/2047614/14748033/b5ade44e-0874-11e6-8c46-aba3703d1eaf.png>
>
> But after they logged in with CCID, they still see the same error message.
> [image: screen shot 2016-04-22 at 10 28 50 am]
> <https://cloud.githubusercontent.com/assets/2047614/14748089/0ef0f4e2-0875-11e6-8cdd-170c8b8c5541.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1066>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *



View the *3rd annual Research Data Management Week
<https://library.ualberta.ca/research-support/data-management/rdm-events>*
*schedule
<https://docs.google.com/document/d/1fhBjbAjUbQSimAgcz1kAAj8Wr0dLu9C3lEMdCJr2Lxc/edit>*
 and *register*
<https://docs.google.com/a/ualberta.ca/forms/d/1M9D4Ip5-tr7sYAgUQbeDzlH5RevTmZ__MWtvKaJ45w0/viewform>
for sessions!

**Comment by sfbetz** [comment]
The real issue here is that ERA has a single blanket statement for unauthorized access. We need two separate statements: 1 for access of CCID protected items that prompts user to sign in. 2. For access of private items that says something  like "you do not have access to this item..."

Will be closed with #1073

**Comment by pbinkley** [comment]
Part of #1073
