### ISSUE TITLE
Tweak migration scrip to capture foxml's lastModifiedDate into fedora:lastModified

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#1074]
From conversation with @weiweishi, @pbinkley. To be modified in migration script before the next unembargo date.

In new fedora there are two "last modified dates":
`fedora:lastModified `- currently capturing last uploaded or modified date in _current_ fedora
and
`dcterms:modified` - captures last modified date in _old_ fedora

The migration script will be tweaked to capture last modification date from old fedora's
`<foxml:property NAME="info:fedora/fedora-system:def/view#lastModifiedDate" VALUE="2016-04-05T19:01:25.317Z"/>`

into both fields (currently this date is only captured in `dcterms:modified`).

For instance, the following object has
fedora:lastModified 2016-04-19T16:40:36.621Z
while the last time this item was changed was in old ERA on 2016-04-05T19:01:25.317Z
Link:
https://plano.library.ualberta.ca/files/5h73px40b

Related to #820

**Comment by leahvanderjagt** [comment]
This needs to be completed before the next migration of theses from thesisdeposit to era mid-June 2016.

**Comment by weiweishi** [comment]
@anayram @pbinkley fedora:lastModified date is a system generated date, so it reflects the migration date and is generated automatically. We can update this field through SPARQL after the fact, but just wondering if it's necessary to do so. Once the objects are modified, they will both reflect the last modified date of the objects and will be in line with each other.

**Comment by anayram** [comment]
For OAI we need a date that reflects the last date of any changes to metadata or files. This date is captured in OAI <datestamp> and is used by clients to know when to re-harvest metadata for an object.

Could we have a separate property (maybe dcterms:modified) that
1) preserves last modification in previous repository
2) is updated when any changes are done in the current repository
?

**Comment by weiweishi** [comment]
@anayram yes dcterms:modified preserves the last modified date from previous repository, and is updated when the object is modified. 
Upon new modification in current repository, dcterms:modified will be updated from the rails layer, and fedora:lastModified will be updated from the fedora layer, so there will be a couple of millisecond difference between the two values. And we did identify this issue #1061 which means date_modified is using the wrong timezone right now. But this field should meet the need for OAI to have the last date of any changes to the object.

**Comment by anayram** [comment]
Great, yes, dcterms:modified should then be mapped for OAI datestamp, I'll add this info to the relevant ticket #820

**Comment by anayram** [comment]
@weiweishi should we close this ticket given that we will use dcterms:modified?

**Comment by weiweishi** [comment]
Yes @anayram I think so. I will go ahead and close it.
