### ISSUE TITLE
restricted communities in the deposit form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1075]
- [x] Dataverse has been set as "is_admin_set" and should not appear in the community list in the deposit form. 
- [x] Faculty of Graduate Studies should also be set with "is_admin_set", and should be removed from the community list on the deposit form

**Comment by pgwillia** [comment]
@weiweishi can you confirm that the two communities you've named have been set as is_admin_set = true?

**Comment by sfbetz** [comment]
I noticed a rogue thesis in this collection today. I checked and it looks like FGSR and Theses and Dissertation collections are still appearing in drop-down menu for regular users. I was able to deposit an item to this collection with my sfbetz account: 
![screen shot 2016-08-09 at 4 38 52 pm](https://cloud.githubusercontent.com/assets/12801010/17536093/db3f04c8-5e4f-11e6-9f2a-a62d33f5a17a.png)

**Comment by weiweishi** [comment]
@sfbetz Please try again. I think there were issues last time when I set the flags (if I remember correctly the tagged release was not deployed successfully), and I had revert the is_admin_set to false on these two collections. I've just set their is_admin_set to true now and seems to have fixed the issue. I'm sorry about the oversight! I hope it's not too much trouble to clean up!

**Comment by sfbetz** [comment]
Fixed! that collection doesn't show up in deposit form or edit form at all. Glad it was an easy fix! I will close...
