### ISSUE TITLE
Security Headers

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#1081]
From securityheaders.io
![screenshot from 2016-05-02 10-07-03](https://cloud.githubusercontent.com/assets/1220762/14959716/e0a2a136-104d-11e6-9881-095314e7a9e8.png)
![screenshot from 2016-05-02 10-07-23](https://cloud.githubusercontent.com/assets/1220762/14959718/e1f9357c-104d-11e6-9bbe-058c388063ad.png)

**Comment by weiweishi** [comment]
Probably need @henryzhang87's attention, as it's related to Apache configuration

**Comment by leahvanderjagt** [comment]
@pbinkley can the dev team please groom this issue and add to IR if high priority, keep in hydranorth2 if in scope of current work, or future if is not immediately pressing

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#102
