### ISSUE TITLE
When deposit to collection with special id, id is not saved

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1088]
e.g. "Computing science technical report ID" field isn't saving.

(spun off from #920)

Uncertain whether this bug applies to all saving (e.g. via the rails console)

**Comment by pgwillia** [comment]
Looks like [self.edit_form_class = Hydranorth::Forms::GenericFileEditForm](https://github.com/ualbertalib/HydraNorth/blob/2a724060897e116f0fb99fd72ec952d5ee9c4a7e/app/controllers/concerns/hydranorth/files_controller_behavior.rb#L15) is used to filter relevant attributes from the provided params:
```
[204, 213] in /usr/lib64/ruby/gems/2.1.0/gems/sufia-6.2.0/app/controllers/concerns/sufia/files_controller_behavior.rb
   204:     end
   205: 
   206:     # this is provided so that implementing application can override this behavior and map params to different attributes
   207:     def update_metadata
   208:       file_attributes = edit_form_class.model_attributes(params[:generic_file])
=> 209:       actor.update_metadata(file_attributes, params[:visibility])
   210:     end
   211: 
   212:     def update_visibility
   213:       actor.update_metadata({}, params[:visibility])
```

This is why trid, title and description are not being persisted.

**Comment by pgwillia** [comment]
These are the permitted params for Cstr
```[{:title=>[]}, {:creator=>[]}, {:contributor=>[]}, {:subject=>[]}, {:resource_type=>[]}, :trid, :language, {:spatial=>[]}, {:temporal=>[]}, {:description=>[]}, :date_created, :license, :rights, :is_version_of, :source, :related_url, {:belongsToCommunity=>[]}, {:hasCollectionId=>[]}]```

The problem with title and description is we're giving it a String and it's expecting an array. I feel like this may have been solved elsewhere?
