### ISSUE TITLE
Update test thesis metadata for migration spec 

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1101]
I've marked one spec as pending: https://github.com/ualbertalib/HydraNorth/commit/87fe704250f3969328c320e64f35476fe8e1c5c5 - Mariana sent a new version of the thesis test metadata, but loading it caused other problems with parsing the abstract. Probably an easy fix but I want to get the Sprint41 branch merged.

**Comment by pbinkley** [comment]
@weiweishi will check whether this test passes with @anayram 's latest xml

**Comment by leahvanderjagt** [comment]
@pbinkley can the dev team please groom this issue and add to IR if high priority, keep in hydranorth2 if in scope of current work, or future if is not immediately pressing
