### ISSUE TITLE
Sufia7 [CCM]: Implement CollectionBehaviour Module

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1123]
The point of this ticket is to provide nesting of collections

###### Location: CollectionNorth
- [x] Investigate existing sufia 7 features vs what we have in Hydranorth to figure out the specific behaviours to implement here. (Make This it's own ticket) (estimate: 8)
- [ ] Using outcome of #1122, create a new module in the CollectionNorth gem that includes the CollectionBehaviour module from Sufia, and adds any necessary logic for implementing nesting.
- [x] Also, add logic to implement the is_official behaviour from Hydranorth.

(Estimate: 8)

**Comment by pbinkley** [comment]
is_official is no longer needed since we are not allowing user collections, therefore every collection is official

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#49
