### ISSUE TITLE
Sufia7 [CCM]: Gather requirements for data model for Communities

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1124]
**Needs clarification with Stakeholder to clarify requirements**

**Comment by pbinkley** [comment]
We have consensus on:

- single-parent model: no object or collection can belong to more than one parent collection
- community-specific:
  - no work can belong directly to a community; it must belong to a collection. It inherits its community membership from its parent
  - Community membership is still to be a facet, however, as are all intermediate collections' memberships

**Comment by mbarnett** [comment]
- how does the requirement to facet by Community impact the PCDM data model wrt Solr joins for collections/do Collections only point at items and not the other way around, and do we need to change that?

**Comment by sfbetz** [comment]
Layouts for community and collection views: 

https://docs.google.com/presentation/d/1INXmuNfTPFGVC9sMAh8iLYzD2FnBCPkAEKCF3Su4Vqk/edit

https://docs.google.com/presentation/d/195k-GIB4C2W7KFrqna6XMki8IGxvWaZx_HGBXZSYzh8/edit#slide=id.p

**Comment by weiweishi** [comment]
Specs for the community model is in:
https://drive.google.com/open?id=1kYA8oihoJypf9FkZc0rUd3kaAJvtq6xtppP3lNLsuMg
