### ISSUE TITLE
Sufia7 [CCM]: Implement CommunityBehaviour Module

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1125]
###### Location: CollectionNorth
- [ ] Using outcome of #1124, create a new module in the CollectionNorth gem that includes the CollectionBehaviour module from CollectionNorth, and adds any necessary logic for implementing Communities. 
- [ ] Alter the CollectionBehaviour module to add the concept of Community membership.

**Estimate: 4**

**Comment by pbinkley** [comment]
@leahvanderjagt agrees that Communities can contain only Collections, not works directly. The migration process will therefore reassign objects that currently belong directly to Communities, if any still exist at that point. Objects will therefore inherit their Community membership from their parent Collection.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#50
