### ISSUE TITLE
Sufia7 [CCM]:  Overide Works and Catalog partials to display Collections AND Communities Info

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1127]
###### Location: CollectionNorth

Note the plurals below. You need to account for multiples of each!
- [ ]  Override partials associated with the Collection Show page to show Communities title the collection belongs to
- [ ] Override partials associated with the Works Show page to show Communities and Collections title the work belongs to.
  - [ ] Use breadcrumb structure to represent collection and community on show page, to make duplicated collection and community names less ambiguous, and to more clearly communicate collection structure

**Estimate: 2**

**Comment by pbinkley** [comment]
Follow the guidance provided by Sonya and Leah in their "Collections Specs from Leah"

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#52
