### ISSUE TITLE
OAI: Charactor encoding problem

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/HydraNorth#1137]
The one that I have found is ’. It is encoded to ? in OAI response. Here are sample objects on Gillingham. 
- 44558d306
- 44558d39p
- 44558d40f
- 44558d47c

**Comment by piyapongch** [comment]
Here is the XSL.
[metadata.xsl.txt](https://github.com/ualbertalib/HydraNorth/files/284886/metadata.xsl.txt)

**Comment by pbinkley** [comment]
Here's how one of the items is rendered by Fedora: view-source:
http://mycombe.library.ualberta.ca:8080/fedora/rest/prod/44/55/8d/30/44558d306/fcr:export?format=jcr/xml
. Note that the regular apostrophe in the ns003:license element is escaped,
but the right apostrophe in the ns003:description element is the correct
two-byte utf-8 character.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by piyapongch** [comment]
I will check on the transformation process.

**Comment by anayram** [comment]
Quickly tested the namespace transformation process but it does not change that particular character.

the same **opening** apostrophe character (html entity `&rsquo;`) is carried through from thesisdeposit
https://thesisdeposit.library.ualberta.ca/public/view/item/uuid:0610dc47-9deb-4eb3-8183-9d0631682a3d/fo.xml
into fedora:
`<dc:description>Canada’s premier daily information service about Parliament and the federal government</dc:description>`
but is not escaped anywhere.

**Comment by piyapongch** [comment]
It is a correct character in XML with utf-8 encoding. I think it should be fine.

**Comment by piyapongch** [comment]
Can I close this issue? We can re-open it if LAC has a problem with this.

**Comment by anayram** [comment]
Yes. I am closing this now.
