### ISSUE TITLE
OAI: Adding namespaces to metadata elements

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/HydraNorth#1138]
I have created XSLT Servlet Filter to transform the OAI response and add namespaces to the metadata elements. The plugin has been updated and deployed on era-test. It is ready to test. The URL is http://oai.library.ualberta.ca/oai?verb=Identify.

**Comment by anayram** [comment]
Looking good!

@piyapongch @sfarnel 
1. Even though this should not cause any problems we should probably remove
`http://www.ndltd.org/standards/metadata/etdms/1.0/ http://www.ndltd.org/standards/metadata/etdms/1-0/etdms.xsd`
from the `OAI-PMH` root element (not needed)

1. Can we add the `xsi` namespace to the record-level root element?
E.g. adding
`xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"`
to elements `etd_ms:thesis` and `oai_dc:dc`
This way records will be valid if/when pulled off the larger OAI response context.

**Comment by sfarnel** [comment]
That makes good sense to me. what do you think @piyapongch
<https://github.com/piyapongch>

On Fri, May 27, 2016 at 10:22 AM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> Looking good!
>
> @piyapongch <https://github.com/piyapongch> @sfarnel
> <https://github.com/sfarnel>
> 1. Even though this should not cause any problems we should probably remove
> http://www.ndltd.org/standards/metadata/etdms/1.0/
> http://www.ndltd.org/standards/metadata/etdms/1-0/etdms.xsd
> from the OAI-PMH root element (not needed)
>
>    1. Can we add the xsi namespace to the record-level root element? E.g.
>    adding xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" to
>    elements etd_ms:thesis and oai_dc:dc This way records will be valid
>    if/when pulled off the larger OAI response context.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1138#issuecomment-222190768>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEevTKHsm4nBXNehq6KvoANjVJ18jPRWks5qFxpOgaJpZM4Inugr>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by piyapongch** [comment]
I have tried to add it in my stylesheet, but it did not work. Here is my stylesheet.
[metadata.xsl.txt](https://github.com/ualbertalib/HydraNorth/files/342248/metadata.xsl.txt)

**Comment by anayram** [comment]
Thanks Piyapong, will check this on Monday.

**Comment by anayram** [comment]
@piyapongch the attached stylesheet is working for me.

Also, In the process of testing the transformation I noticed a problem with dates: ETD-MS does not allow datetime with granularity `yyyy-mm-ddT00:00:00Z` so I added a template to replace those dates with years. Not sure, maybe you want to do this change in the OAI code instead, but added it here in case it helps.

[metadata.xsl.tar.gz](https://github.com/ualbertalib/HydraNorth/files/346673/metadata.xsl.tar.gz)

**Comment by piyapongch** [comment]
I will try it and look at the source code for date format.

**Comment by piyapongch** [comment]
Is the date field apply only to ETD-MS? I think your XSLT applies to all metadata format.

**Comment by anayram** [comment]
@piyapongch 

Just checked with @sfarnel and here are the rules we need to implement:

- When date has granularity `yyyy-mm-ddT00:00:00Z`
discard time and timezone info (i.e. discard everything starting from T)
- When dates contain `/`, replace with `-`

These changes apply to all metadata formats.

Thank you!

**Comment by piyapongch** [comment]
Your stylesheet change to yyyy format. Do you want date format to be yyyy-mm-dd for all metadata format? I have apply your stylesheet on era-test. You should be able to check it at, https://era-test.library.ualberta.ca/oai?verb=Identify.

**Comment by piyapongch** [comment]
I have just noticed that it did not add xmlns:xsi to the results.

**Comment by piyapongch** [comment]
I think the transfer might ignore it because it already declares at the top level element.

**Comment by anayram** [comment]
@piyapongch 

Yes, that might be why the transformer is ignoring the attribute insertion. That change was low priority so I think we can leave it as is.

The attached stylesheet has the date rules we need.
[metadata.xsl.tar.gz](https://github.com/ualbertalib/HydraNorth/files/354815/metadata.xsl.tar.gz)

**Comment by piyapongch** [comment]
I have update the stylesheet on era-test. It does not seem to affect much on performance. I will leave the date format transformation on the stylesheet. You might want to check it and we can close this issue.

Thanks,

**Comment by anayram** [comment]
All good, closing ticket.
