### ISSUE TITLE
Sufia7 [CCM]: Adapt views to current Hydranorth Theme

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1142]
###### Location: Hydranorth7

Ideally for now:
- [ ] porting the CSS from current Hydranorth over
- [ ] port current homepage over (but fix the fact that it's all implemented in a layout for some reason)
  - [ ] Javascript for homepage
- [ ] port the various themed error pages over (404, 500, etc).

Other parts of the theme will be adapted on a case-by-case basis for the time being

Ideally we won't need to override a ton of view files from Sufia 7 just to implement our theming changes

**estimate: 8**

**Comment by pbinkley** [comment]
@leahvanderjagt agrees with minimal-css-changes approach, and notes that we'll need to think out the integration of ERA A+V into the site
