### ISSUE TITLE
Sufia7 [CCM]: Create repository and engine/rails project for "CollectionNorth" and "Hydranorth7"

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1145]
Hopefully with better names than either of those!

###### Estimate: 1

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/scarecrow is HydraNorth7 but needs a better name.

**Comment by criedlberger** [comment]
Repositories and Engine/Rails projects have been created as CollectionNorth and Hydranorth2
