### ISSUE TITLE
Edit form will not accept revisions to title field

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1147]
Reported by user, I have replicated problem with this test item. 
https://era.library.ualberta.ca/files/bzg64tm03g/

Cannot change the title. I think other fields are OK. Edit form also looks a bit wonky. 
<img width="718" alt="screen shot 2016-05-26 at 3 27 59 pm" src="https://cloud.githubusercontent.com/assets/5807708/15590641/f54b554a-2355-11e6-81ee-ba2483c39151.png">

**Comment by mbarnett** [comment]
@pgwillia is this the issue you mentioned you had fixed this morning?

**Comment by pgwillia** [comment]
I noticed this when addressing #1088. I'm working out the details presently -- you'll find the same problem with the description. 

The part I'm having trouble with at the moment is that the same view partial is used by both files and collections and the input expected for each is of a different type.

The reason this doesn't work in the first place is that we allow multiple values for the file title as metadata, but only present a single field for editing.

**Comment by leahvanderjagt** [comment]
Ah I see. Re: priority, we really won't have a lot of users making title/description changes, and we don't make many of those changes in mediated deposit help either. I'd call this important but not urgent.

**Comment by weiweishi** [comment]
closed with #1088
