### ISSUE TITLE
Sufia7 [CCM]: Allow for Multilevel faceting of collection and community nesting

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1149]
To allow for a decent user experience with collections and communities, we will need to accommodate multilevel indexing and faceting of search results by collection and community.
- [ ] Multilevel faceting by collection or community (**estimate: 8**)
- [ ] Solr Indexing of the multilevel hierarchy of an item's collection and community (**estimate: 4**)

This issue ties into #1126.

**Comment by pbinkley** [comment]
We'll get guidance from the stakeholders on how these facets ought to be displayed before we work on this.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#53
