### ISSUE TITLE
Fedora4 Investigation

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#115]
Understand and document important Fedora4 features and API.

**Comment by pbinkley** [comment]
At launch, we might put up the external triplestore for use by metadata team to check migrated metadata, with no commitment to keep it up. We'll evaluate this closer to launch.

**Comment by pbinkley** [comment]
Further testing: Marmotta (LOD platform)

**Comment by piyapongch** [comment]
I've got OpenRDF-Sesame working. I will be working on Apache Marmotta Triple Store in next couple of days.
