### ISSUE TITLE
Sufia7 [CCM]: Infrastructure: Dedicated performance tests

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1152]
Tricia to investigate and potentially setup a dedicated workstation that performs continuous integration testing on the code base, with tests to alert us of significant performance degradation after code changes.

Write tests to check speed of homepage, search results, collection page, generic file page, download page.

**Potential estimate: 24**

**Comment by pbinkley** [comment]
Neal has a partial ansible playbook for Jenkins.

**Comment by pgwillia** [comment]
wasn't able to use @nmacgreg jenkins playbook on the ubuntu workstation.  Unfortunately installed by hand.  See https://github.com/ualbertalib/Developer-Handbook/tree/jenkins for details.

**Comment by pgwillia** [comment]
- [ ] need to give the workstation jenkins user read rights to https://username@code.library.ualberta.ca/git/ansible-dev.git or ssh://root@code.library.ualberta.ca/var/lib/git/ansible-dev.git

**Comment by weiweishi** [comment]
pending creating credentials for internal git repo. will be captured in a separate ticket.

**Comment by pgwillia** [comment]
created Ticket#20160815103512 with the help desk
