### ISSUE TITLE
Sufia7 [CCM]: Infrastructure: ActiveJob/Queueing Investigation

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1153]
Sufia 7 has switched to the ActiveJob API, which allows for pluggable backend job queue implementations. We need to determine whether or not we want to stick with Redis/Resque for job queueing, or leverage something JMS-based for potential gains in areas like re-indexing directly with Fedora

We're timeboxing this decision to 8 hours.

**Comment by pbinkley** [comment]
Potential use cases

- triggering update of external triplestore
- triggering ingest of datastream into Swift
- update Solr from Fedora on update outside Rails
- etc.

**Comment by pgwillia** [comment]
Good discussion of [how ActiveJob works](https://karolgalanciak.com/blog/2016/09/25/decoding-rails-magic-how-does-activejob-work/?utm_source=rubyweekly&utm_medium=email)

**Comment by pbinkley** [comment]
Industry standard is Sidekiq - let's start there
