### ISSUE TITLE
Custom sorting for results in Community items browse

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1156]
As discussed with @criedlberger -

When you go to a Community, and there are items w/o collections and collections inside that community, the 'sort by relevance' ranking does not make much sense to the end user, who is still in browsing mode. Ideally, collections would be listed first, followed by items. 

This would be a low priority enhancement.

**Comment by sfbetz** [comment]
Sort options specified in CollectionsNorth gem. Won't fix for Sufia 6.
