### ISSUE TITLE
Front page contains http download of sign-in form

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1159]
The front page of ERA in production currently attempts to download http://era.library.ualberta.ca/users/sign_in. It gets redirected to https, but it causes the page to be flagged as insecure in Firefox's location bar. The request seems to be caused by an attempt to load the thumbnail of a ccid-protected item in the "Recent Documents" box (currently https://era.library.ualberta.ca/downloads/3j333490f?file=thumbnail)

Just for context: This problem of ccid-protected thumbnails shows up elsewhere too. If you aren't logged in and you browse a collection that contains a ccid-protected item, you get that bar at the top of the results telling you you need to log in to see "this item". If you log in, you're taken to a thumbnail image. I assume this is what triggered the message, and Sufia assumes that it is what you were trying to see when you logged in.

**Comment by pgwillia** [comment]
This is the solr document for the item.  Note that it is in the public group.
```
{
        "system_create_dtsi":"2015-10-12T01:37:42Z",
        "system_modified_dtsi":"2015-10-23T12:56:26Z",
        "active_fedora_model_ssi":"GenericFile",
        "has_model_ssim":["GenericFile"],
        "id":"5d86p191r",
        "object_profile_ssm":["{\"id\":\"5d86p191r\",\"mime_type\":\"application/pdf\",\"format_label\":[\"Portable Document Format\"],\"file_size\":[\"960314\"],\"last_modified\":[\"2015:10:12 21:06:17-06:00\"],\"filename\":[\"20100705DailyRecordNon-Pro.pdf\"],\"original_checksum\":[\"613c709d7c8073d59fcc130f5ecb5526\"],\"rights_basis\":[],\"copyright_basis\":[],\"copyright_note\":[],\"well_formed\":[\"true\"],\"valid\":[\"true\"],\"status_message\":[],\"file_title\":[\"untitled\"],\"file_author\":[],\"page_count\":[\"84\"],\"file_language\":[],\"word_count\":[],\"character_count\":[],\"paragraph_count\":[],\"line_count\":[],\"table_count\":[],\"graphics_count\":[],\"byte_order\":[],\"compression\":[],\"color_space\":[],\"profile_name\":[],\"profile_version\":[],\"orientation\":[],\"color_map\":[],\"image_producer\":[],\"capture_device\":[],\"scanning_software\":[],\"exif_version\":[],\"gps_timestamp\":[],\"latitude\":[],\"longitude\":[],\"character_set\":[],\"markup_basis\":[],\"markup_language\":[],\"bit_depth\":[],\"channels\":[],\"data_format\":[],\"offset\":[],\"frame_rate\":[],\"label\":\"20100705DailyRecordNon-Pro.pdf\",\"depositor\":\"eraadmi@ualberta.ca\",\"relative_path\":null,\"import_url\":null,\"part_of\":[],\"resource_type\":[\"Report\"],\"title\":[\"Daily Record, Monday, July 5, 2010\"],\"creator\":[\"Toronto Stock Exchange\"],\"contributor\":[],\"description\":[\"\"],\"rights\":\"Use of this product is restricted to current faculty,...\",\"publisher\":[],\"date_created\":\"2010/07/05\",\"date_modified\":\"2014-05-01T02:46:33.355+00:00\",\"subject\":[\"Stock exchanges--Canada--Tables—Periodicals\",\"Toronto Stock Exchange—Periodicals\"],\"language\":\"English\",\"identifier\":[],\"related_url\":null,\"source\":null,\"proxy_depositor\":null,\"on_behalf_of\":null,\"date_uploaded\":\"\",\"license\":\"I am required to use/link to a publisher's license\",\"trid\":\"\",\"ser\":\"\",\"temporal\":[],\"spatial\":[],\"is_version_of\":\"\",\"unicorn\":\"\",\"fedora3uuid\":\"uuid:e3169666-36ec-4bbf-800d-76f9f8af2705\",\"fedora3handle\":\"http://hdl.handle.net/10402/era.17474\",\"ingestbatch\":\"3197xn63x\",\"hasCollection\":[\"Daily Record (Toronto Stock Exchange)\"],\"belongsToCommunity\":[\"wh246v792\"],\"hasCollectionId\":[\"44558s34k\"],\"year_created\":\"2010\",\"remote_resource\":null,\"degree_grantor\":\"\",\"dissertant\":\"\",\"supervisor\":[],\"committee_member\":[],\"department\":[],\"specialization\":\"\",\"date_submitted\":\"\",\"date_accepted\":\"\",\"graduation_date\":\"\",\"alternative_title\":[],\"thesis_name\":\"\",\"thesis_level\":\"\",\"proquest\":\"\",\"abstract\":\"\",\"batch_id\":\"xp68kh818\",\"embargo_id\":null,\"lease_id\":null}"],
        "mime_type_tesim":["application/pdf"],
        "depositor_ssim":["eraadmi@ualberta.ca"],
        "depositor_tesim":["eraadmi@ualberta.ca"],
        "resource_type_tesim":["Report"],
        "title_tesim":["Daily Record, Monday, July 5, 2010"],
        "creator_tesim":["Toronto Stock Exchange"],
        "rights_tesim":["Use of this product is restricted to current faculty,..."],
        "date_created_tesim":["2010/07/05"],
        "date_created_ssi":"2010/07/05",
        "date_modified_dtsi":"2014-05-01T02:46:33Z",
        "subject_tesim":["Stock exchanges--Canada--Tables—Periodicals",
          "Toronto Stock Exchange—Periodicals"],
        "language_tesim":["English"],
        "isPartOf_ssim":["xp68kh818"],
        "license_tesim":["I am required to use/link to a publisher's license"],
        "fedora3uuid_tesim":["uuid:e3169666-36ec-4bbf-800d-76f9f8af2705"],
        "fedora3handle_tesim":["http://hdl.handle.net/10402/era.17474"],
        "ingestbatch_tesim":["3197xn63x"],
        "hasCollection_ssim":["Daily Record (Toronto Stock Exchange)"],
        "hasCollection_tesim":["Daily Record (Toronto Stock Exchange)"],
        "belongsToCommunity_tesim":["wh246v792"],
        "hasCollectionId_ssim":["44558s34k"],
        "hasCollectionId_tesim":["44558s34k"],
        "year_created_tesim":["2010"],
        "label_tesim":["20100705DailyRecordNon-Pro.pdf"],
        "file_format_tesim":["pdf (Portable Document Format)"],
        "file_size_is":960314,
        "read_access_group_ssim":["public",
          "university_of_alberta"],
        "edit_access_person_ssim":["eraadmi@ualberta.ca"],
        "_version_":1515826695758675968,
        "timestamp":"2015-10-23T12:56:27.867Z",
        "score":4.955325},
```

**Comment by pbinkley** [comment]
After discussion with @leahvanderjagt , the preferred solution is to check permissions when building a link to a thumbnail, and link to the generic thumbnail if the user doesn't have permission to download this item. We would need to be careful about the caching, so that the user would not still see the cached generic thumbnail after they log in. If this is more than a couple hours work, though, let's discuss leaving it for now.

We must change the http call to https, though, to prevent browsers from showing the encryption of the site as incomplete.

**Comment by pgwillia** [comment]
@pbinkley @leahvanderjagt do you have a preferred 'generic thumbnail' for display?

**Comment by pbinkley** [comment]
I was assuming the default one that Sufia shows when an item hasn't been
characterized:
https://github.com/projecthydra/sufia/blob/6.x-stable/app/assets/images/default.png
.

**Comment by leahvanderjagt** [comment]
Yes, that's the one.

On Wed, Jun 1, 2016 at 10:41 AM, Peter Binkley <notifications@github.com>
wrote:

> I was assuming the default one that Sufia shows when an item hasn't been
> characterized:
>
> https://github.com/projecthydra/sufia/blob/6.x-stable/app/assets/images/default.png
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1159#issuecomment-223052357>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFieXEPNv5l_bmppml_I66Rt_APsV7eZks5qHbYsgaJpZM4Iqqw4>
> .
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pgwillia** [comment]
@henryzhang87 can we change 
./hydra/roles/hydra/templates/production.rb.j2:  # config.force_ssl = true
so that the line is uncommented? I think this is the key to having the login redirects stay https

**Comment by pgwillia** [comment]
@mbarnett @pbinkley See my June 7 comment.
