### ISSUE TITLE
Test suite needs attention

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1180]
We have reports that all the specs are running twice, or that they are extremely slow. Let's have a look at whether something has changed that can be fixed.

**Comment by pgwillia** [comment]
Some discussion on 88691a7 lead @mbarnett and I to conclude that we need to remove https://github.com/ualbertalib/HydraNorth/blob/master/lib/tasks/spec.rake#L6-L8 for efficiency in running the specs. When we have a functional CI server again we should revisit whether or not this task definition is necessary -- shouldn't rspec already be able to handle tags?

**Comment by pgwillia** [comment]
```rake spec```
Finished in 27 minutes 40 seconds (files took 9.58 seconds to load)
404 examples, 0 failures, 6 pending
```bundle exec rake cispec RAILS_ENV=test```
Finished in 23 minutes 60 seconds (files took 9.8 seconds to load)
386 examples, 0 failures, 5 pending
