### ISSUE TITLE
Add admin-set id

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1185]
We will add a multivalued admin-set-id field, which will be visible only to ERA Admin, and we will populate it with values provided by ERA Admin to track groups such as batch ingest groupings or license investigation groupings. It will be up to ERA Admin to track these ids and provide new ones as needed. This field will be searchable and facetable for ERA Admin, so that it is easy to see all the items that belong to a given admin set.

**Comment by leahvanderjagt** [comment]
I should be able to figure out this piece of things in July/August. Need to think through the best way to gather investigations together/what our reporting needs are.

**Comment by weiweishi** [comment]
captured in #1218
