### ISSUE TITLE
Generate CSV report from batch ingest task

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1186]
The batch ingest task will generate a CSV report containing the identifier, url, title, (other fields, @leahvanderjagt @weiweishi?), which will be delivered to ERA Admin after an ingest is complete, so that a list of ingested items with their urls can be emailed to the external partner who requested the ingest.

**Comment by leahvanderjagt** [comment]
@weiweishi I suggest that we finalize the required fields to be returned to ERA Mediated Help as we run the next few batch ingest jobs. We may have different requirements for faculty publications vs. a batch loaded collection of images, etc.

**Comment by pbinkley** [comment]
We still need a list of needed fields from @leahvanderjagt - related to #1188, which is HydraNorth2 work, so this is not urgent.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#100

**Comment by weiweishi** [comment]
Met with @leahvanderjagt and talked about her requirement for the reports needed for current HN batch ingest process. And they are small changes. Reopen the issue to capture the changes I will make.
