### ISSUE TITLE
Automated, schedule-driven batch ingests

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1188]
We will develop a process that will receive completed Google Sheets containing lists of items to be batch ingested, and run the ingest jobs on a regular schedule. A report will be delivered to ERA Admin; errors will be caught and handled so that broken or duplicate items are not ingested. This could be modelled on the Avalon batch ingest work (which will soon be WIP). It could use the Google Sheets API to pull information. The purpose is to allow ERA Admin (or the student assistants) to compose ingest batches in spreadsheets with appropriate metadata etc., have those batches ingested by a nightly/weekly job, and receive status information and reports of items ingested (as in #1186).

**Comment by leahvanderjagt** [comment]
Just FYI I'm hoping we can complete this in July/August.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#99
