### ISSUE TITLE
Sorting by anything other than relevance does not work in current ERA for the Grant Assist (Social Science and Humanities) community/collections

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1192]
It looks as though in all lists related to this collection (search results + item browse in collections) the sorting options other than relevance do not work. Perhaps the reindexing work @pbinkley was running for these items ( #1171) will resolve this problem?

**Comment by weiweishi** [comment]
will wait until PR #1246 in place to verify this issue is fixed.
