### ISSUE TITLE
CCID-protected items to be barred from "recent items" box on front page

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1196]
@leahvanderjagt will decide whether they should be included in recent items list (for Google to harvest)

**Comment by pbinkley** [comment]
```read_access_group_ssim:public -read_access_group_ssim:"university of alberta"``` will do the trick

**Comment by leahvanderjagt** [comment]
I've thought this over and I can't set a blanket policy to suppress item
metadata for CCID protected items throughout the application. Aside from
the licensed resources collection, there are other collections in ERA that
are CCID protected with active user communities, and those users should, I
think, be allowed to browse metadata before they make a decision to log
into the application.

Regarding the sitemap - if this means that CCID protected items show up in
the sitemap, that's OK. As long as Google can't present the item w/o CCID
login it doesn't matter.

I still would like to have the item that shows on the front page of ERA
under 'recent items' to not be a CCID protected item. Is that difficult?

Leah

On Thu, Jun 16, 2016 at 1:16 PM, Peter Binkley <notifications@github.com>
wrote:

> read_access_group_ssim:public -read_access_group_ssim:"university of
> alberta" will do the trick
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1196#issuecomment-226585509>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFieXKAmY8SjunEsP6gaPpodf4PUJbxXks5qMaEbgaJpZM4I3s97>
> .
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Coordinator University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pbinkley** [comment]
Just a thought: if it turns out to be difficult to exclude CCID-protected items in the query, could we work around the problem by excluding the frequently-updated collections that contain CCID-protected items?

**Comment by leahvanderjagt** [comment]
Yes, that would be fine.

On Sat, Jun 18, 2016 at 9:44 AM, Peter Binkley <notifications@github.com>
wrote:

> Just a thought: if it turns out to be difficult to exclude CCID-protected
> items in the query, could we work around the problem by excluding the
> frequently-updated collections that contain CCID-protected items?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1196#issuecomment-226949121>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFieXLQ-vPw7HMDsQxcGFUA8hIYhe3-Hks5qNBJigaJpZM4I3s97>
> .
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Coordinator University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pgwillia** [comment]
Note to self:
search_params_logic = [:default_solr_parameters, :add_query_to_solr, :add_facet_fq_to_solr, :add_facetting_to_solr, :add_solr_fields_to_query, :add_paging_to_solr, :add_sorting_to_solr, :add_group_config_to_solr, :add_facet_paging_to_solr, :show_only_generic_files, :add_access_controls_to_solr_params]

**Comment by leahvanderjagt** [comment]
Would you like a list? I can generate one easily. Let me know. --Leah

On Mon, Jun 20, 2016 at 2:45 PM, Leah Vanderjagt <leahv@ualberta.ca> wrote:

> Yes, that would be fine.
>
> On Sat, Jun 18, 2016 at 9:44 AM, Peter Binkley <notifications@github.com>
> wrote:
>
>> Just a thought: if it turns out to be difficult to exclude CCID-protected
>> items in the query, could we work around the problem by excluding the
>> frequently-updated collections that contain CCID-protected items?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ualbertalib/HydraNorth/issues/1196#issuecomment-226949121>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AFieXLQ-vPw7HMDsQxcGFUA8hIYhe3-Hks5qNBJigaJpZM4I3s97>
>> .
>>
>
>
>
> --
> ___________________________________________________________
>
>
>
>
> *Leah VanderjagtDigital Repository Services Coordinator University of
> Albertat. 780.492.3851 <780.492.3851> *
> *leahv@ualberta.ca <leahv@ualberta.ca> *
>
>


-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Coordinator University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pgwillia** [comment]
@leahvanderjagt that's not necessary.  I was able to exclude the CCID items without any problems.  PR ready to merge and demo for next release.

**Comment by leahvanderjagt** [comment]
Great!

On Wed, Jun 22, 2016 at 3:57 PM, pgwillia <notifications@github.com> wrote:

> @leahvanderjagt <https://github.com/leahvanderjagt> that's not necessary.
> I was able to exclude the CCID items without any problems. PR ready to
> merge and demo for next release.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/1196#issuecomment-227889586>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFieXHrk6xIc8vHln9i0hQkn7KRj2Q15ks5qOa_FgaJpZM4I3s97>
> .
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Coordinator University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *
