### ISSUE TITLE
Upgrade to Ruby 2.3.3

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1198]
When @henryzhang87 has add the ruby231 package to our repository, test it in our ansible-built dev environment and deploy to production when ready.

**Comment by pbinkley** [comment]
We still need an upgraded passenger package.

**Comment by pgwillia** [comment]
many deprecation nags with updated ruby.  Should resolving be part of this issue?

**Comment by pgwillia** [comment]
testcustom6 repo now contains both ruby 2.3.1 and passenger 5.0.29

**Comment by weiweishi** [comment]
need to test on test stack to verify the new version will work

**Comment by pbinkley** [comment]
Our strategy is to lock the ruby version to pre-2.3.1 versions for apps that need to be protected from an upgrade (DMP, Discovery)

**Comment by pbinkley** [comment]
We've decided to include Bundler in the Ruby 2.3.3 rpm.
