### ISSUE TITLE
Decoding HTML tags in text fields

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1203]
Now with the fix to #704 in place, proper html tags can be handled in the text fields. But migrated objects from Thesis Deposit and Dataverse might have the html tags encoded with their html entities (& lt; & gt; & amp; etc.). When rendering the views, these html entities need to be decoded, so that it can be displayed properly as a HTML text.  This can be used for decoding on the view:
https://github.com/ualbertalib/HydraNorth/blob/9eba023736bfb2ea2d73b8fc3f851cbe76a02fcf/lib/tasks/migration.rake#L238

**Comment by weiweishi** [comment]
The HTML decoding already handles the description field. Next dataverse import will fix the issue on the dataverse objects.

**Comment by weiweishi** [comment]
@johnhuck Your dataverse metadata transformation and a complete new dataverse migration will close this ticket.

**Comment by johnhuck** [comment]
@weiweishi , understood. I have requested a new Dataverse extract from Piyapong and will aim to have the metadata ready for you this sprint.

**Comment by weiweishi** [comment]
@johnhuck Piyapong is away - I wonder if @henryzhang87 can help you for the Dataverse data dump.

**Comment by johnhuck** [comment]
Thanks for the information, @weiweishi . I'll contact Henry to see what we can do.

**Comment by johnhuck** [comment]
I have the latest export from Henry and need only make a small adjustment to my stylesheet to the add html formatting for multi-values to dcterms:description that we talked about a few months ago. @pbinkley had suggested either a pair of `<br/>` tags between values or wrapping each value in `<div>` tags. Is there a preference either way?

**Comment by johnhuck** [comment]
@weiweishi @pbinkley : The html markup coming from Dataverse is already escaped (half escaped: &lt; is, but &gt; is not). This being the case, I think the best thing would be if the tags I'm adding were also escaped for the sake of consistency. Would you agree?

I'm not sure how I would decode the escaped html in the content in the stylesheet.

I see lots of &lt;p&gt; tags in the abstracts, so a set of div tags on its own is probably the best idea for abstracts, as we discussed.

**Comment by pbinkley** [comment]
That makes sense - let's try the the escaped version of the added tags and
make sure that Sufia displays it correctly.

**Comment by johnhuck** [comment]
Here is the output ready for ingest. These are all the records for all currently released studies. 

This seems to be the folder I put the output in before, so I'll continue that practice.

https://drive.google.com/a/ualberta.ca/folderview?id=0B3s6m1gxi006flkta2JBSmkwVjc2Ti1kSXZHX2RmLVQyNjNjQkoweDFwQkNmMEhwSGg1OWs&usp=sharing

Note that I have identified escaped ampersands in the title, subject, as well as the description field. These are escaped in the Dataverse output. Also note that there are two cases of double escaped ampersands (`&amp;amp;`) in 10026 and 10060, also so escaped in the Dataverse output.

We should be aware that there is always the chance that some previously released Dataverse studies will have been withdrawn. The export process gives me all currently released studies, but doesn't identify studies that have been withdrawn. You would only discover those items by comparing the set of currently released studies to a previous set of currently released studies. I'm not sure how you want to identify those items in ERA, but let me know if I can do anything to help.

This has actually happened, and let us to add a step in the export process to ensure that I was only getting metadata for currently released studies.

**Comment by johnhuck** [comment]
Here is the link to my stylesheet, for your interest. (I had git problems this afternoon, so it took me a while to get them sorted out and get my latest changes committed.)

https://github.com/ualbertalib/metadata/blob/master/stylesheets/dataverse_DDI_to_ERA_dcterms.xsl

**Comment by weiweishi** [comment]
Thanks @johnhuck. I can handle the withdrawn studies by comparing the file names in two directories, and remove the ones that are not in the new ingest folder. I will write a task for this, and add to README.

**Comment by weiweishi** [comment]
latest Dataverse ingest is completed, and the HTML tags in the description field are now handled properly.  A PR is in place for minor fixes #1257

**Comment by johnhuck** [comment]
Next time I'll deal with the double escaped ampersands myself. I don't know why I didn't think to do it this time.

**Comment by johnhuck** [comment]
@weiweishi I just noticed that the DOIs on the Dataverse items are no longer active links. I think the markup must have been stripped at some point, because the DOI is given twice (the display text and href value, I presume). Example: https://era.library.ualberta.ca/files/c0c483j509#.V-RTZZMrKHo

**Comment by johnhuck** [comment]
@pbinkley @weiweishi Not sure if Peter saw my comment on this before closing this issue, but there seems to be a problem with the markup of the DOI links, so that they are just text and not a clickable link. If you would prefer to open a new ticket to address this, that's fine.

**Comment by weiweishi** [comment]
We closed the ticket as the remaining problem doesn't relate to this issue. I'm running the fixing job in the console, and will double check the script. If any coding is needed, I will open another ticket.

**Comment by weiweishi** [comment]
Verified that script is updated in #1257 and is in tag 1.6.

**Comment by johnhuck** [comment]
@weiweishi OK, great! I see it's fixed now. Just wanted to make sure the issue didn't fall through the cracks.
