### ISSUE TITLE
Only 10 Collections showing in pop-up when nesting collections

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#1207]
That pop-up should be an unwieldy list of all of the collections in the repository, but for some reason on Plano, when signed in as dittest@ualberta.ca, it was only listing 10 collections.

This is blocking use of the collection nesting functionality.

**Comment by pgwillia** [comment]
Likely https://github.com/ualbertalib/HydraNorth/blob/Sprint44/app/controllers/concerns/hydranorth/collections/admin_nesting_targets.rb#L6 and the default_search_parameters rows: 10

**Comment by pgwillia** [comment]
see if I can reuse collection_search_builder

**Comment by pgwillia** [comment]
Hmmm. So it looks like #1193 created a new global variable @target_collections which replaces @user_collections in the sort_and_per_page.html.erb templates.  @user_collections is @target_collections (has_model:Collection) plus the restrictions that a) the user can edit and b) the collections are is_official and NOT is_community.

I think one possbile fix is to remove the logic providing @target_collections and add the ```unless current_user && current_user.admin?``` logic to https://github.com/ualbertalib/HydraNorth/blob/da2661cf7d785355aa73e040fabe6e7a4d1e2f85/app/controllers/concerns/hydranorth/collections/selects_collections.rb#L30.

I don't completely understand @mbarnett's approach so I'm probably missing a critical part to this.  Thoughts?

**Comment by pgwillia** [comment]
@weiweishi, you merged #1193.  Could you help me to identify if my branch 1207_admin_user_collections_limit is fixing the right thing?

**Comment by pgwillia** [comment]
@user_collections is not in any of the gems.  Looks like this is something that we introduced to solve the same problem as @target_collections.

**Comment by weiweishi** [comment]
Thanks for investigating into this. On this basis, I think we can proceed with confidence that this won't break anything else.  When @mbarnett is back, maybe he can comment if this change will introduce any other unforeseen issues.

**Comment by pgwillia** [comment]
I noticed that my change breaks the community view page for admins. There does need to be seperate @user_collections and @target_collections

**Comment by mbarnett** [comment]
(chiming in way late) Yeah, @user_collections is the collection that renders for the collection partial on any kind of index page. @target_collections *should* contain any valid collection that an admin could nest something in @user_collections into. (so, in general, @ user_collections should be filtered by the current page, but @target_collections should be more or less everything).
