### ISSUE TITLE
Owasp Ror CheatSheet: Security Related Headers check failed

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#121]
``` gem install dawnscanner ```

``` [root@hydranorth hydranorth]# dawn . ```
16:25:38 [!] dawn: Owasp Ror CheatSheet: Security Related Headers check failed
16:25:38 [$] dawn: Severity: info
16:25:38 [$] dawn: Priority: unknown
16:25:38 [$] dawn: Description: To set a header value, simply access the response.headers object as a hash inside your controller (often in a before/after_filter). Rails 4 provides the "default_headers" functionality that will automatically apply the values supplied. This works for most headers in almost all cases.
16:25:38 [$] dawn: Solution: Use response headers like X-Frame-Options, X-Content-Type-Options, X-XSS-Protection in your project.
16:25:38 [$] dawn: Evidence:
16:25:38 [$] dawn:      {:filename=>"./spec/controllers/users_spec.rb", :matches=>[]}
16:25:38 [$] dawn:      {:filename=>"./spec/controllers/users_controller_spec.rb", :matches=>[]}
16:25:38 [$] dawn:      {:filename=>"./app/controllers/application_controller.rb", :matches=>[]}
16:25:38 [$] dawn:      {:filename=>"./app/controllers/catalog_controller.rb", :matches=>[]}
16:25:38 [$] dawn:      {:filename=>"./app/controllers/users_controller.rb", :matches=>[]}
16:25:38 [$] dawn:      {:filename=>"./app/controllers/generic_files_controller.rb", :matches=>[]}

**Comment by criedlberger** [comment]
It seems that this is a known bug for dawnscanner, see https://github.com/thesp0nge/dawnscanner/issues/38

**Comment by pgwillia** [comment]
not an issue
