### ISSUE TITLE
1.3: transfer ownership link leads to file download

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1220]
the link is

```
https://era-test.library.ualberta.ca/files/test02f4752g755/transfers/new
```

And must be being fooled by the new download link routes.

**Comment by pgwillia** [comment]
Could you move 
```
  get 'files/:id/*file' => 'downloads#show', format: false
  get 'files/:id' => 'downloads#show', constraints: WantsThumbnailConstraint
```
to below the ```mount Sufia:Engine => '/'``` line?

**Comment by pgwillia** [comment]
Nm. Has the same impact on all the thumbnails as adding the section of the Sufia routes for files above it.

**Comment by mbarnett** [comment]
it seems like

```ruby
  get 'files/:id' => 'downloads#show', constraints: WantsThumbnailConstraint
  mount Sufia:Engine => '/'
  get 'files/:id/*file' => 'downloads#show', format: false
```

should work? Otherwise, just duplicate the routes from Sufia for transfers

**Comment by pbinkley** [comment]
I tried various rearrangements, but not that one. i think I've accomplished
the same thing by adding :show to the except: list in the Generic File
routes  block that I restored from Sufia 6:

resources :generic_files, path: :files, except: [:index, :show] do
The specs are almost done, so I'm thinking I'll stick with mine so as to
get a PR merged more quickly and hopefully get a release cut today -- does
that make sense to you? You can see mine in the transfers branch (I
squashed the commits so you need to do a fresh pull).

Peter



Peter Binkley, Ph.D., MLIS / Digital Initiatives Technology Librarian /
peter.binkley@ualberta.ca
2-10K Cameron Library / University of Alberta / Edmonton, Alberta / Canada
T6G 2J8
phone 780-492-3743 / fax 780-492-9243

**Comment by pgwillia** [comment]
@mbarnett's solution **seems** to work for me.  Still testing -- my resque wasn't running and may have been confusing the issue for me.
