### ISSUE TITLE
Collections with custom identifiers

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#1224]
Some external user collections, e.g., Bio Sci Fish Skeletal Images, have custom identifiers that may need to be displayed (and possibly searchable and browsable), but which do not require changes to the deposit form, etc. These are mapped to dcterms:identifier with a prefix added to the data, e.g., fsecatalogue:F8882 to avoid having to create a new property in the model for each such collection. The policy and procedures for such cases needs to be fully articulated and documented.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#98
