### ISSUE TITLE
Redirected urls for thumbnails use http instead of https

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1232]
Thumbnail links using the old url structure get redirected using http instead of https, which results in the browser flagging the page as insecure: e.g. 

```
https://era.library.ualberta.ca/downloads/rj430710c?file=thumbnail
```
to
```
http://era.library.ualberta.ca/files/rj430710c?file=thumbnail
```
to
```
https://era.library.ualberta.ca/files/rj430710c?file=thumbnail
```
The old-fashioned links seem to be generated by ```render_thumbnail_tag```, which hasn't been overridden.

**Comment by pbinkley** [comment]
It appears that all redirects go to http - because the app servers run on http, and it's haproxy that add https, presumably.

**Comment by pgwillia** [comment]
Revisit of #1159

**Comment by pbinkley** [comment]
@mbarnett notes: 

> It  looks like the simplest solution for this would be to ensure that HAProxy is setting the  X-Forwarded-Proto header to https when it passes the traffic upstream to Rails. Then Rails will take care of generating matching protocol redirects with no intervention.

> Here's a quick SO answer about doing so with nginx. I don't imagine it's much more difficult to do the same thing with haproxy http://stackoverflow.com/questions/10432266/https-redirect-for-rails-app-behind-proxy 

That leaves the problem with ```render_thumbnail_tag``` generating the old-fashioned link in the first place. I'll look at that.

**Comment by pgwillia** [comment]
@pbinkley http://serverfault.com/a/428822 looks to have the HAProxy equivalent ```http-request set-header X-Forwarded-Proto https if { ssl_fc }```. If we can make that work the render_thumbnail_tag is a non-issue. Maybe don't spend a lot of time on this.

**Comment by pbinkley** [comment]
good point. No need for perfectionism here.

**Comment by henryzhang87** [comment]
add a line to haproxy as suggested
