### ISSUE TITLE
Duplicate ERA handles concatenated in single field

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#1242]
@weiweishi: maybe part of audit fixes?

While checking OAI identifiers I found some items with duplicate handles, e.g.:
`<etd_ms:identifier>http://hdl.handle.net/10402/era.27657http://hdl.handle.net/10402/era.27657</etd_ms:identifier>`

Looks like some original foxml items, e.g.:
https://thesisdeposit.library.ualberta.ca/public/view/item/uuid:b10e0728-a324-4fa5-8680-fa7be0cd8845/fo.xml
contain duplicate handles, e.g.:
`<dcterms:identifier xsi:type="dcterms:URI">http://hdl.handle.net/10402/era.27657</dcterms:identifier>
<dcterms:identifier xsi:type="dcterms:URI">http://hdl.handle.net/10402/era.27657</dcterms:identifier>`

Those duplicate values were migrated into a single fedora3handle field, e.g.:
`fedora3handle
http://hdl.handle.net/10402/era.27657http://hdl.handle.net/10402/era.27657`
in the migrated Fedora item at:
http://mycombe.library.ualberta.ca:8080/fedora/rest/prod/b8/51/5p/81/b8515p81r

**Comment by weiweishi** [comment]
Thanks for spotting this. The script didn't expect the duplicated values in
the original foxml. I will make a change in script and also add it as an
instance in audit.

Thanks

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mbarnett** [comment]
@weiweishi check to see if you fixed this

**Comment by weiweishi** [comment]
identified 125 objects with duplicated value in fedora3handle. Fixed them in the console.
