### ISSUE TITLE
Review the OAI date-stamped harvest list

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1255]
- is complete?

**Comment by weiweishi** [comment]
@pbinkley what do you mean by "date-stamped harvest list"?

**Comment by pbinkley** [comment]
This must have been an OAI concern: harvest items changed before date X, and then starting their next harvest from date X - there was a conceivable case where items could be missed. I'll try to recover the problem case.

**Comment by pbinkley** [comment]
Here's the scenario I'm worried about: the async job of the oai server might fool clients into thinking their harvest is up to date when it isn't.

- 1:00 oaiserver generates response content
- 2:00 item A changes; change is not yet reflected in OAI content
- 3:00 client harvests changes since last harvest; does not get change to item A
- 4:00 oaiserver generates response content, now contains change to item A timestamped to 2:00
- 5:00 client harvests changes since last harvest at 3:00 - misses change to item A since it was earlier than last harvest

@piyapongch is this scenario possible?

**Comment by leahvanderjagt** [comment]
@pbinkley can the dev team please groom this issue and add to IR if high priority, keep in hydranorth2 if in scope of current work, or future if is not immediately pressing

**Comment by piyapongch** [comment]
The oai provider queries data from Fedora4 JCR (ModeShape). The response gets generated from the query results. What has been persisted in the repository will be in the response.  The scenario will not happen because oai provider does not cache response content.
