### ISSUE TITLE
Non-CCID login sends user into 'please log in using your CCID' loop

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1256]
If I try to log in using the Non-CCID login, I get the below screen
![non-ccid-login-result](https://cloud.githubusercontent.com/assets/5807708/18369129/01aaa11e-75e1-11e6-9738-7a5d9ec41c54.png)

I can still log in using my CCID and access admin privileges, but this is new today, so I have marked this high in case we sent something into production that has affected authentication, or if there is something in ERA's environment that has changed which is prompting this behaviour.

**Comment by pbinkley** [comment]
Fixed account in rails console
