### ISSUE TITLE
Add Sample Data to Sufia 7 (lincoln)

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1263]
- 10 random users
- 10 random collections
- 1000 real items, randomly associated with users and collections

**Comment by pgwillia** [comment]
@weiweishi suggested migrating plano data to satisfy this. https://github.com/psu-stewardship/scholarsphere/pull/272 is one approach for migrating Sufia 6 to Sufia 7 constructs.

**Comment by pgwillia** [comment]
chemheritage is doing this too. https://github.com/chemheritage/chf-sufia/wiki/sufia-7-upgrade-notes

**Comment by pgwillia** [comment]
Turns out the export to json is in sufa6 -- https://github.com/projecthydra/sufia/commit/dd99fd3019969d23f51ca552ee18269b9bf9f4ff

**Comment by pgwillia** [comment]
Should work to update https://github.com/projecthydra/sufia/wiki/Sufia-6-to-Sufia-7-Migration

**Comment by pgwillia** [comment]
@sfbetz and @leahvanderjagt: I've created a sufia_migrate gem to export data from Plano and import to Lincoln. There are currently 829 GenericWorks and 387 Collections.  Here is an example of a work in a collection https://lincoln.library.ualberta.ca/concern/generic_works/73666610d. Just a heads up that it looks like not all of the collections relationships were maintained. Also, plano was loaded with metadata only objects so lincoln similarly does not have files/thumbnails for the works either.  Let me know if you need anything else for your evaluation of Sufia 7.1. admin@hydranorth.ca owns the majority of the works (355).

**Comment by pgwillia** [comment]
Lincoln is back in working order. Sorry for the inconvenience.

@weiweishi ```rake curation_concerns:solr:reindex``` took 392m0.054s

**Comment by pgwillia** [comment]
@sfbetz, admin@hydranorth.ca owns most of the works, but no collections -unfortunately.  It's password is password.

Any of these works should have collections:
```
        "0g354g600",1,
        "0g354g618",1,
        "0v838204v",1,
        "1n79h584z",1,
        "2801ph697",1,
        "3j333365w",1,
        "3j3333665",1,
        "47429b46j",1,
        "47429b47t",1,
        "5q47rq36h",1,
        "5x21tg746",1,
        "73666610d",1,
        "8c97kr614",1,
        "8w32r703q",1,
        "8w32r719m",1,
        "b2773x09r",1,
        "b8515p821",1,
        "bg257g35d",1,
        "bg257g49r",1,
        "c247dt42f",1,
        "cr56n2394",1,
        "d791sh61r",1,
        "db78td465",1,
        "df65v916p",1,
        "f4752j101",1,
        "f7623f222",1,
        "f7623f28q",1,
        "fq977w22d",1,
        "gx41mh976",1,
        "h989r4501",1,
        "hm50tt04g",1,
        "hq37vq06j",1,
        "ht24wj50x",1,
        "ht24wk69v",1,
        "j098zc61d",1,
        "j9602176p",1,
        "j9602181j",1,
        "jh343t77j",1,
        "jm214q803",1,
        "jq085m22q",1,
        "k0698893g",1,
        "kd17cv01t",1,
        "kp78gh743",1,
        "m039k632m",1,
        "m039k651t",1,
        "m613mz82x",1,
        "m613mz84g",1,
        "mk61rj25h",1,
        "mp48sf20n",1,
        "nc580p162",1,
        "pg15bg28r",1,
        "pv63g1576",1,
        "qr46r225j",1,
        "t435gf50d",1,
        "td96k374r",1,
        "tx31qk08g",1,
        "vm40xt03z",1,
        "vq27zp50n",1,
        "vq27zp51x",1,
        "xg94hq99z",1,
        "xk81jm87d",1,
        "zc77sr25s",1,
        "zc77sr262",1,
        "zg64tn447",1,
        "zg64tn59v",1,
        "zk51vh89m",1,
        "zk51vh91n",1,
        "zs25xb030",1,
        "zw12z650d",1
```

Any of these collections should have works (unfortunately no way to see the collections
```
        "0p0968387",1,
        "1c18dh005",1,
        "1g05fc979",1,
        "1n79h5814",1,
        "3484zj47s",1,
        "3f4626986",1,
        "4x51hk22s",1,
        "5138jg255",1,
        "5h73px435",1,
        "7m01bn06x",1,
        "8623j020j",1,
        "8g84mn735",1,
        "9306t082z",1,
        "9593tw510",1,
        "cr56n2351",1,
        "dj52w6087",1,
        "f7623f20h",1,
        "fj236340s",1,
        "fx719n778",1,
        "g732db34h",1,
        "j67315009",1,
        "k0698888m",1,
        "k930bz14c",1,
        "kk91fm93s",1,
        "m039k631b",1,
        "mk61rj158",1,
        "n870zs18z",1,
        "ng451j72f",1,
        "pg15bg24n",1,
        "pk02cc06z",1,
        "rj430579w",1,
        "tm70mw806",1,
        "zw12z646t",1
```
