### ISSUE TITLE
rails-sitemap todos

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#1270]
- [ ] We could also throw some more logging into the rake task to try to make the logs more useful. I'm thinking at least result counts for the query, counters for each GenericFile and Collection seen, & a catchall third branch on the case statement to make sure we're not falling through it somehow. 
- [ ] log rake task complete
- [ ] https://github.com/viseztrance/rails-sitemap/issues/20

**Comment by weiweishi** [comment]
will reopen if needed.
