### ISSUE TITLE
Sufia 7 review year_created label 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1272]
In Sufia 7

We will need to review sources and possibly find better sources to have high-quality date information, and also need to think if we can use a better label, and external predicate for the field. Should we change it to year_publication. We need to decide if we want to make the field revisable, and if it's through the regular edit form. And we should make the property visible, and give it a proper label on the UI.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#97
