### ISSUE TITLE
Spike: Investigate HydraNorth in CentOS7

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1273]
This is a spike to investigate the compatibility of Hydra North in CentOS 7
- [ ] To create a golden image with CentOS 7
- [ ] Put in Hydranorth to test where and what is broken
- [ ] timebox: 8hrs.

**Comment by pgwillia** [comment]
- [x] update golden-centos.ks for Centos7
- [ ] update hydranorth playbook for testcustom7 repo and other centos 7 idiosyncracies
