### ISSUE TITLE
DOI status for OAI

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1279]
- [x] Include DOI as an identifier field in metadata body (replacing ARK), using the full DOI URI in the format: https://doi.org/10.7939/FEXDSF
- [x] Identifier in OAI item header should use ERA noids with a shoulder "1/", giving the full form "oai:era.library.ualberta.ca:1/<noid>"
- [x] Metadata field: UALId<"http://terms.library.ualberta.ca/id/">:doi

**Comment by pgwillia** [comment]
#1276 
Private items are excluded. Items without a DOI (i.e. Dataverse should present their external DOI)

**Comment by jefferya** [comment]
Timing question: if the OAIProvider executes between the time a Hydra object is created but before the DOI request is send and EZID response assigned to the object then problems. How to mitigate the timing problem? How often might this happen and what are the implications?
