### ISSUE TITLE
DOI label on the object display page

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1284]
- [ ] To display the DOI label on object page, and other places as stakeholders specified.

**Comment by sfbetz** [comment]
![2016-09-29_16-22-41](https://cloud.githubusercontent.com/assets/12801010/18974663/ae41d092-8661-11e6-87f8-d73c374bdf72.png)

**Comment by sfbetz** [comment]
Requirements:
-remove "Actions" Heading
-Move "Analytics" link up below "download the full-sized PDF"
-Add Share heading (or rename "Actions")
-add Permanent link (DOI): above other share options. Populate field with DOI link 

-Add field below link for ERA DOI: populate field with DOI.

We don't need DOI in the search results list.

**Comment by pgwillia** [comment]
#1276 
Permenant link may be nil for some items (i.e. Dataverse), so this section should be hidden. DOI may also be 'unavailable' for some items (i.e. Private items) and can still be displayed to the user and admin.

**Comment by sfbetz** [comment]
The DOIs should be displayed like this: https://doi.org/10.1629/22161

CrossRef (a major DOI registration agency) has updated their documentation to drop the .dx from the DOI url. This will become the new standard for published article DOIs, so one we should probably follow as well.

**Comment by murny** [comment]
Example of what this label change will look like (if there was a PDF link it would be above the analytics):
![image](https://cloud.githubusercontent.com/assets/1930474/20077087/29447b28-a4f8-11e6-948e-fcdb92730438.png)

Regarding:
-Add field below link for ERA DOI: populate field with DOI.

Assuming there is nothing to do for this anymore?

**Comment by leahvanderjagt** [comment]
Looks good.

___________________________________________________________




*Leah VanderjagtDigital Repository Services Coordinator University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by murny** [comment]
After talking to Leah, I have added a field for DOI under the descriptions section in between "Date created" and "License information". Example of what this might look like:
![image](https://cloud.githubusercontent.com/assets/1930474/20079571/8c87b8bc-a502-11e6-9b2d-4bf49f08ce87.png)
