### ISSUE TITLE
EBSCO French Interface showing up

### ISSUE THREAD

**Issue by linds37** [ualbertalib/HydraNorth#1285]
Hi. I was helping a student after a class this afternoon in the Rutherford lab. We followed the get it link from an article search and he ended up in the EBSCO French interface. I can't reproduce the problem, so just something to watch for, I guess.
- Lindsay

**Comment by weiweishi** [comment]
@redlibrarian I believe this ticket should belong to https://github.com/ualbertalib/Discovery?

**Comment by redlibrarian** [comment]
Thanks @weiweishi I'll move it over to the Discovery repository.
