### ISSUE TITLE
Old download links are appearing in citation_pdf_url meta tag

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1288]
E.g. ```<meta name="citation_pdf_url" content="https://era.library.ualberta.ca/downloads/8910jx67q"/>```

Replace with the current download link, in this case ```https://era.library.ualberta.ca/files/8910jx67q/PR_19_118.pdf```.

Same with download links in ResourceSync elements in sitemap.xml:

```<rs:ln href="/downloads/2r36tz87h" rel="content" hash="urn:sha1:2b1822668a964ba8914e655b21cbb41a741960db" length="4272036" type="image/jpeg"/>```

href should be ```/files/8910jx67q/PR_19_118.pdf```

**Comment by mbarnett** [comment]
Looks like the wrong URL is also in the opengraph and twitter card meta tags. We should do a quick audit to make sure we're not calling ```sufia.download_url``` anywhere anymore.

**Comment by weiweishi** [comment]
We will try to put this in tag 1.6, and will time the release date to monitor the Google Scholar search results.

**Comment by mbarnett** [comment]
I can't recreate the sitemap part of this issue locally (it uses the correct path for me, and based on the code I don't see how it would use the old structure). Other than that, the fix is in https://github.com/ualbertalib/HydraNorth/pull/1290

**Comment by pgwillia** [comment]
Sitemap was fixed by #1267

**Comment by mbarnett** [comment]
Oh well that explains that mystery 😉
