### ISSUE TITLE
oaiprovider: sample identifier doesn't exist

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#1295]
The sample identifier given in the [Identify](https://era.library.ualberta.ca/oai?verb=Identify) response is `<oai-id:sampleIdentifier>oai:era.library.ualberta.ca:ark:/54379/t7227mp68v</oai-id:sampleIdentifier>`, but this identifier [does not exist](https://era.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:era.library.ualberta.ca:ark:/54379/t7227mp68v). 

Replace it with `oai:era.library.ualberta.ca:ark:/54379/b8515q959`, which is a thesis and can demonstrate the etdms as well as dc format (unless @leahvanderjagt has another preference)

**Comment by weiweishi** [comment]
now replace it with doi instead of ark.

**Comment by jefferya** [comment]
Should match format in #1279. 

Can the replacement sample in the original issue be checked, I receive a "requested identifier doesn't exist" message. 

Location for change:
https://github.com/ualbertalib/fcrepo4-oaiprovider/blob/master/src/main/resources/spring/oai.xml#L76
