### ISSUE TITLE
Quarantine user deposits?

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1296]
Anna and I noticed a number of spam deposit attempts, all saved as private items, from user n******y@yahoo.com. I disabled the account as Admin. 
The user was able to upload a number of files. We are not touching these files in case they are corrupt. 

How do we handle this? I'd like to quarantine the objects or just delete and purge them. None of them are labeled as executables but they are obviously spam (e.g. I'm pretty sure no one wants to deposit desktop.ini to ERA). 

Should Anna and I just delete these items?

**Comment by pbinkley** [comment]
Not a development issue - the problem items have been deleted.
