### ISSUE TITLE
Remaining Triplestore work

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1306]
This is the remaining work after our initial triplestore ticket #139 
## Triplestore Works
- [ ] Test fcrepo-indexing-triplestore to make sure that automatically update is working properly
- [ ] Import PREMIS metadata into the triplestore
- [ ] Decision on the selection of triplestore for production
- [ ] Setup triplestore production server
- [ ] Index Fedora4 production server to selected triplestore

**Comment by zschoenb** [comment]
Can we see if the Premis metadata can be made operational and available in the triplestore? This data could serve an important role in auditing as time goes on.

**Comment by piyapongch** [comment]
There are some sample data in Fuseki. You need to select audit dataset and
query. It has 59 triples. The subject is still not correct. I will need to
do more testing.

Piyapong.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#96
