### ISSUE TITLE
Can't edit thesis abstract due to absent graduation date value

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1319]
@piyapongch 
I need to edit the abstract of this thesis:

https://era.library.ualberta.ca/files/cb2773v94t

But when I do so, I can't select Fall 2016 (2016-11) from the dropdown menu, and ERA is demanding that I enter that. Can you please look at this?

Thanks, 
Leah

**Comment by weiweishi** [comment]
fixed in 1.7.1
