### ISSUE TITLE
Update preservation documentation

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#1336]
Update documentation on stack and preservation status and workflows. May relate to Preservation Epic (#1251).

Collection Inventory Spreadsheet here: https://docs.google.com/spreadsheets/d/1HDa6X_9P3uHf1ZJJzCsd2wVdkngafQn_emq7RzP0c6k/edit#gid=0

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/pushmi-pullyu#5
