### ISSUE TITLE
DOI for Thesis: use dissertant if presents

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1337]
Thesis objects should only have a dissertant and not creator(s). (some exceptions might be in early migrated objects). 
- [ ] Use dissertant value in datacite_metadata for EZID
- [ ] Validate the presence of either dissertant or creator information in DOI metadata validation
- [ ]  Dissertant information takes precedence for thesis objects, if both dissertant and creator fields present.

**Comment by murny** [comment]
Fix for this is in master. Just needs to be deployed?

**Comment by weiweishi** [comment]
Thanks! I will tag a new release. @henryzhang87 will deploy it after the break.
