### ISSUE TITLE
datacite requirement for date_created/year_created in HydraNorth2

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1339]
Sufia 7
We will make #592 a separate discussion to work through the implication of implementation date_published as a required field. We will use missing value for year_created for initial implementation. More thorough thinking is required for Sufia 7 #1272

We will also

 give the Metadata team a fresh data dump for all objects including date_created, year_created and date_accepted, and review the year_created value.
 generate report for Metadata team for any null value resource_type objects to review.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#121
