### ISSUE TITLE
Once DOI implementation is complete, update OAI to ensure DOI is shared as metadata

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1340]
As a repository administrator, I want to provide DOIs as part of metadata shared via OAI harvest so that we are providing permanent IDs instead of persistent links wherever possible. We don't want to wait until Fedora 4.7 to implement this. 

We discussed this briefly at standup - I will tag @pbinkley, @piyapongch , @johnhuck .

**Comment by weiweishi** [comment]
We need to include a condition in the OAI work to handle objects that don't have DOIs.
