### ISSUE TITLE
Document the AIP for lightweight preservable ERA items

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#1341]
-AIP documentation should be understandable by anyone on the team, and new devs

**Comment by sfarnel** [comment]
AIP definition working document [here](https://docs.google.com/document/d/15qVr8naWHvUI1wgTLn-53zo4QO9QH3GMjXDCeLGq_sQ/edit#heading=h.sqqxwzm2947u).

**Comment by umarqasim** [comment]
There is a good resource to look at http://etdplusdemo.educopia.org/ for creating a light-weight AIP pipeline. This project is based on Sufia but they also added some additional useful preservation micro-services. Here is a text from their documentation

What the Curation Workbench has added to Sufia:

The Curation Workbench is built on the Sufia platform and has incorporated multiple curation tools to allow users to evaluate supplementary materials, by automatically performing multiple preservation actions including virus scans, finer-tuned file format identification and characterization, and personally identifiable information scans. Customizable configurations allow each institution to design its own curation rules and workflows. Additionally, the outputs of these tools along with other technical and descriptive metadata added by a user can be downloaded as a package that includes the files and associated metadata in a METS.xml file. (http://etdplusdemo.educopia.org/help)

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/pushmi-pullyu#6
