### ISSUE TITLE
Set up development infrastructure for Swift (spike for investigation)

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#1342]
-We need a vagrant or docker environment running swift avail to developers to push data from HydraNorth into
-Need to make sure special configuration matches production environment, eg. versioning
-training and review for devs
-maybe talk to Scholars Portal about their setup
-ansible playbook (if vagrant)
-ask Hydra community if anyone else is using Swift / OpenStack in production with Sufia

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/pushmi-pullyu#11
