### ISSUE TITLE
Swift / Fedora ingest audit trail

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#1343]
- we want Fedora to keep a record of the timestamp, checksum and link to Swift to record the fact that the preservation action took place
- question: how do we manage the audit trail, given that a change to it constitutes a change to the object and therefore triggers another preservation request? Do we keep the audit trail separately? Where?
- reconciliation between Fedora and Pushmi-Pullyu to detect and fix unfulfilled preservation requests after a given lapse of time - in the short term, this is just to ensure the preservation requests are always acted on
- assumptions:
  - deletions will not propagate to Swift: if items need to be purged from Swift, that must be done manually

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/pushmi-pullyu#7
