### ISSUE TITLE
Remove DOI field from submission form and edit form

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#1344]
Let's remove the DOI field from the item submission form!
![screen shot 2017-01-20 at 11 10 05 am](https://cloud.githubusercontent.com/assets/12801010/22160104/2e5c38e2-df01-11e6-99d0-773a14cfaf42.png)
I don't think it's in the edit form, but let's double check and remove from there as well, just in case.

**Comment by murny** [comment]
This has been fixed in master (https://github.com/ualbertalib/HydraNorth/pull/1345). Ready for release. (@weiweishi)

**Comment by weiweishi** [comment]
Hot fix release 1.7.3 deployed on production.
