### ISSUE TITLE
OAI registration error

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#1347]
Received in eraadmi@ualberta.ca when openarchives try to register ERA's OAI provider. 

We received a request to register the following repository:

Base URL: https://era.library.ualberta.ca/oai
adminEmail: eraadmi@ualberta.ca

### Checking ListIdentifiers response

REQUEST:
https://era.library.ualberta.ca/oai?verb=ListIdentifiers&metadataPrefix=oai_dc&set=44558r69g
GET
FAIL: Failed to extract responseDate
FAIL: The response to the ListIdentifiers verb with metadataPrefix oai_dc
contained no identifiers. Without at least one identifier, we cannot proceed
with the validation tests.
FAIL: ABORT: No identifiers in response to ListIdentifiers. Without an
identifier we cannot proceed with validation tests.

## Summary - *failure*

* Uses https URIs (not specified in protocol)
* Total tests passed: 7
* Total warnings: 0
* Total error count: 3
* Validation status: FAILED

Complete log available at
http://www.openarchives.org/Register/ValidateSite?log=WEAPEPNI

**Comment by piyapongch** [comment]
Error response needs to have responseDate tag.
- [ ] Add responseDate tag in error response.
