### ISSUE TITLE
Wrong verb reported in error message

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/HydraNorth#1351]
(this is low priority)

A ListRecords request with a badly formed timestamp returns an error message, as it should, but the error message reports the verb as "ListIdentifiers".

e.g. 

```?verb=ListRecords&metadataPrefix=oai_dc&from=2017-01-15T00:00:0```

Returns

```
<?xml version="1.0" encoding="utf-8"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
   <request verb="ListIdentifiers" metadataPrefix="oai_dc"/>
   <error code="badArgument">Invalid format: "2017-01-15T00:00:0" is too short</error>
</OAI-PMH>
```

**Comment by jefferya** [comment]
Also, Wrong verb reported in error message for "Sets are not enabled" message on the verb "ListIdentifiers". Looked through other verbs - seem ok.
