### ISSUE TITLE
Associate a restricted set of items with more than one community-collection pair

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/HydraNorth#1359]
As admin, I need to be able to associate a specific set of items with more than one community-collection pair so that I don't ingest files more than once and create duplicate DOIs for duplicate items in ERA.

Notes:

This problem only relates to 160 items in ERA. Otherwise Leah will mitigate problem via communications. 

1. It's OK to display community and collection pairing at item level that doesn't group the community and collection together
2. A user should be able to get to the items via either community-collection pair from the community browse page
3. No need to amend the edit form, but we know this will create issues for the edit form for any object with multiple comm-coll pairs
4. Weiwei will use a batch update process rather than batch ingest to associate items with more than one community.
5. If this is too much work Leah will explain situation to Chair.

**Comment by leahvanderjagt** [comment]
Just checked an item example. 
https://era.library.ualberta.ca/files/c8g84mm25b#.WML1nRIrKCQ

Verified:
-Item record shows both comm-collections 
-Can browse to both via Comm-Coll interface

**Comment by weiweishi** [comment]
@leahvanderjagt confirms this can be closed.
