### ISSUE TITLE
Admin can find files of specific users

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#136]
Enhancement to "all files" tab: 

- [x] admin (only) can limit to a given user
- [x] owners of individual files are listed 
- [x] Selection of users should be with an autocomplete dropdown: start typing a user's email address, see the users who match. 
- [x] The id for the owning user of a file should be link, causing the tab to be limited to that user's files. 
- [x] The tab should have a clear indication of the user to whom it is limited when in a limited view: "Files of Peter Binkley (peter.binkley@ualberta.ca)".

**Comment by sfbetz** [comment]
As admin there's an "all files" tab. @criedlberger has added a "search for user" that will filter all files by user. Can filter one user at a time. Requires some theming help from @nnunn  before completion.
