### ISSUE TITLE
Spike: Investigate use of Travis to track Sufia changes

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#137]
Look at setting up a Travis environment that can run Hydra North tests on an environment that includes the latest Sufia commit from master.

**Comment by pgwillia** [comment]
To add to travis-ci.org user needs to be an admin of HydraNorth repo.  I only have pull/push access.

**Comment by pbinkley** [comment]
This looks promising for managing scenarios we want to test: https://github.com/thoughtbot/appraisal . Note the section on Travis CI integration.

**Comment by pbinkley** [comment]
Testing of current commits in Travis is working. Testing to track Sufia master will move to a #155
