### ISSUE TITLE
7.3 Admin user's public profile

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#14]
as admin, I do not want the items I own because of administrative history (e.g. batch ingest) to appear as my items in any researcher page or user profile, so that users are not confused about the ownership of these items (i.e., admin users have no public profile) size:small

- note: we don not  yet have full admin user worked out - but this just requires the ability for a class of user which does not have a public profile
- currently users can be in "public" or "registered" groups, but there is also an "admin" role which can be added to users, and they can do anything - not much documentation about this

Testing

- admin user creates item: confirm that the item is not displayed in public profile of admin user

**Comment by pgwillia** [comment]
Closed by pull request #27.
