### ISSUE TITLE
migration - log script

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#148]

**Comment by weiweishi** [comment]
A sample log for successful migration:

[INFO  2015-04-21 15:09:59] Processing the file lib/tasks/migration/metadata/uuid_f6cf8a6b-68fd-40ee-afab-35a159b3b001.xml
[INFO  2015-04-21 15:09:59] Get the current version of DCQ
[INFO  2015-04-21 15:09:59] Download File scan0001-5.jpg
[INFO  2015-04-21 15:10:00] This object contains only one DS datastreams
[INFO  2015-04-21 15:10:00] Download the original foxml uuid:f6cf8a6b-68fd-40ee-afab-35a159b3b001
[INFO  2015-04-21 15:10:03] Create Metadata for new GenericFile:
[INFO  2015-04-21 15:10:03] Add original FOXML to the datastream
[INFO  2015-04-21 15:10:03] Save the file
[INFO  2015-04-21 15:10:18] Generic File created id:p8419h683
[INFO  2015-04-21 15:10:18] Add file to collection ["uuid:3f5739f8-4344-4ce5-9f85-9bda224b41d7"]and community ["uuid:d04b3b74-211d-4939-9660-c390958fa2ee"] if needed
[INFO  2015-04-21 15:10:24] Finish migrating the file
[INFO  2015-04-21 15:10:24] START: verify if migration is successful
[INFO  2015-04-21 15:10:28] file migrated successfully

A sample log for failed migration:
[INFO  2015-04-21 11:29:39] **************FINISH: Migrate ERA objects *******************
[INFO  2015-04-21 11:31:59] **************START: Migrate ERA objects *******************
[INFO  2015-04-21 11:31:59] +++++++ START: object ingest lib/tasks/migration/metadata +++++++
[INFO  2015-04-21 11:32:01] Processing the file lib/tasks/migration/metadata/uuid_1f87cdeb-54ab-438e-9bcb-270b1cc9a051.xml
[INFO  2015-04-21 11:32:01] Get the current version of DCQ
[INFO  2015-04-21 11:32:01] Download File Oil sands marshes - 1 Intro.mov
[INFO  2015-04-21 11:32:10] Download File Oil sands marshes - 2 Stress gradient - Amplitude.mov
[INFO  2015-04-21 11:32:21] Download File Oil sands marshes - 3 Stress gradient - Water sampling 1 clarity.mov
[INFO  2015-04-21 11:32:32] Download File Oil sands marshes - 4 Stress gradient - Water sampling 2 chemistry.mov
[INFO  2015-04-21 11:32:45] Download File Oil sands marshes - 5 Stress gradient - Water sampling 3 conductivity.mov
[INFO  2015-04-21 11:32:48] Download File Oil sands marshes - 6 Stress gradient - Sediment sampling.mov
[INFO  2015-04-21 11:32:59] Download File Oil sands marshes - 7 Wet meadow IBI.mov
[INFO  2015-04-21 11:33:35] Download File Oil sands marshes - 8 SAV IBI.mov
[INFO  2015-04-21 11:34:01] Download File Oil sands marshes - 9 Conclusion.mov
[INFO  2015-04-21 11:34:08] This object contains more than one DS datastreams
[INFO  2015-04-21 11:34:08] Creating zip file from all download files.
[INFO  2015-04-21 11:34:08] Removing downloaded individual files.
[ERROR 2015-04-21 11:34:08] undefined local variable or method `zip_file' for main:Object, ["/var/www/sites/hydranorth/lib/tasks/migration.rake:193:in `block in migrate_object'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:117:in `glob'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:117:in `migrate_object'", "/var/www/sites/hydranorth/lib/tasks/migration.rake:65:in `block (2 levels) in <top (required)>'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'", "/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'", "/usr/bin/rake:33:in `<main>'"]
[INFO  2015-04-21 11:34:08] **************FINISH: Migrate ERA objects *******************
