### ISSUE TITLE
migration - users

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#150]
Bring over users first so that items can be linked to them as depositor.

* ensure devise unconfirmed and can gain confirmation of email instructions
* create field for ERA user id
* some users may have CCID associated with their account - can we discard this? And deal with it later when Shibboleth is part of our environment? (Question for Amanda)

**Comment by pgwillia** [comment]
Will admin users be created as part of the migration?  This would solve #183

**Comment by weiweishi** [comment]
current admin users in ERA will be migrated. New admin users won't be there
- e.g dittest etc.

**Comment by pbinkley** [comment]
That's one where we'll want to force a password change, or at least change
the password ourselves pre-migration. The dev team should not need access
to the real eraadmin password to work on the migrated data.

Peter


Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
We can reset the password on Production manually for the admin users after the migration. Does #183 only refer to real eraadmin?

**Comment by pbinkley** [comment]
No, eraadmin does not need to change.
