### ISSUE TITLE
migration - test data set with regresssion tests

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#151]
* at least one example/test per collection
* ownership 
  * Thesis - admin vs student as depositor
  * multiple ownership
* URI vs String
* embargo
* old licences
* dates

**Comment by pgwillia** [comment]
https://robots.thoughtbot.com/test-rake-tasks-like-a-boss

**Comment by weiweishi** [comment]
data will available in lib/migration/test-metadata.
