### ISSUE TITLE
Theses can be edited by admin, but belong to user

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#158]
We want the thesis to belong to the user (i.e. show up in their dashboard), but not be editable by the user, only by admin.

**Comment by criedlberger** [comment]
The following items should be included in the "My Files" tab:

                                             | I Deposit                              | Mediated Deposit
----------------------------------- | ----------------------------------- | -----------------------------------
 I Can Edit                            | Depositor: me                      | Depositor: Admin
                                                                                             Edit Access: me
I Can;t Edit                           |                                              | Depositor: Admin
                                                                                              Read Access: me
