### ISSUE TITLE
Clarify requirements: permissions and audit history when admin edits on behalf of user

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#159]
When admin edits an item that belongs to a user, we do not want the ownership if the item to change to admin.
But what do we want to appear in the audit history? Are there cases where we would want that change to be attributed to the user and not to admin?
Consult with Amanda and Umar, and look back at Leah's spreadsheet.

**Comment by pbinkley** [comment]
Related to #49

**Comment by pbinkley** [comment]
@leahvanderjagt and @umarqasim is there anything here that needs to be kept alive?

**Comment by leahvanderjagt** [comment]
Yes re: if admin edits an item belonging to a user, the ownership should
stay with the user.

I think that the audit should be accurate re: the identity behind an
action. So if it was Admin, it should show admin.

Umar, what do you think from a policy standpoint? I can't think of a use
case where I wouldn't want to know the precise identity re: action taken on
an item.

On Wed, Mar 30, 2016 at 2:13 PM, Peter Binkley <notifications@github.com>
wrote:

> @leahvanderjagt <https://github.com/leahvanderjagt> and @umarqasim
> <https://github.com/umarqasim> is there anything here that needs to be
> kept alive?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/159#issuecomment-203613197>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by weiweishi** [comment]
Related to #1304

**Comment by sfbetz** [comment]
We feel this is resolved
