### ISSUE TITLE
Upgrade to Sufia 6

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#161]
Following these instructions https://github.com/projecthydra/sufia/releases/tag/v6.0.0

- [x]  rspec ./spec/controllers/my/all_controller_spec.rb:53 # My::AllController#index User should respond with success
- [x]  rspec ./spec/controllers/my/all_controller_spec.rb:58 # My::AllController#index User shows the correct files
- [x]  rspec ./spec/controllers/my/all_controller_spec.rb:79 # My::AllController Admin should respond with success
- [x]  rspec ./spec/controllers/my/all_controller_spec.rb:84 # My::AllController Admin shows the correct files
- [x]  rspec ./spec/controllers/users_controller_spec.rb:18 # UsersController#index requesting html should test users
- [x]  rspec ./spec/controllers/users_controller_spec.rb:26 # UsersController#index requesting json should display users
- [x]  rspec ./spec/controllers/users_controller_spec.rb:35 # UsersController#index query users does not find the expected user via email
- [x]  rspec ./spec/controllers/users_controller_spec.rb:40 # UsersController#index query users finds the expected user via email
- [x]  rspec ./spec/controllers/users_controller_spec.rb:45 # UsersController#index query users finds the expected user via display name
- [x]  rspec ./spec/controllers/users_controller_spec.rb:60 # UsersController#index query users uses the base query
- [x]  rspec ./spec/controllers/users_spec.rb:7 # UsersController
- [x]  rspec ./spec/controllers/users_spec.rb:8 # UsersController
- [x]  rspec ./spec/controllers/users_spec.rb:29 # UsersController admin #lock_access
- [x]  rspec ./spec/controllers/users_spec.rb:35 # UsersController admin #unlock_access
- [x]  rspec ./spec/controllers/users_spec.rb:19 # UsersController admin #edit when admin attempts to edit another profile no redirect to show profile
- [x]  rspec ./spec/controllers/users_spec.rb:47 # UsersController not admin #lock_access
- [x]  rspec ./spec/controllers/users_spec.rb:53 # UsersController not admin #unlock_access
- [x]  rspec ./spec/features/admin_delete_spec.rb:20 # delete admin can delete
- [x]  rspec ./spec/features/admin_delete_spec.rb:26 # delete admin see batch delete
- [x]  rspec ./spec/features/admin_delete_spec.rb:45 # delete user can't delete
- [x]  rspec ./spec/features/admin_delete_spec.rb:49 # delete user doesn't see batch delete
- [x]  rspec ./spec/features/admin_home_spec.rb:11 # admin homepage
- [x]  rspec ./spec/features/catalog_search_spec.rb:44 # catalog searching p finds {P,S}
- [x]  rspec ./spec/features/catalog_search_spec.rb:53 # catalog searching NOT p finds {Q,R}
- [x]  rspec ./spec/features/catalog_search_spec.rb:62 # catalog searching p AND q finds {S}
- [x]  rspec ./spec/features/catalog_search_spec.rb:71 # catalog searching p OR q finds {P,Q,S}
- [x]  rspec ./spec/features/catalog_search_spec.rb:80 # catalog searching NOT(p AND q) finds {P,Q,R}
- [x]  rspec ./spec/features/catalog_search_spec.rb:89 # catalog searching NOT(p OR q) finds {R}
- [x]  rspec ./spec/features/coauthor_spec.rb:32 # coauthor abby shares work @ included
- [x]  rspec ./spec/features/coauthor_spec.rb:36 # coauthor abby shares work @ not included
- [x]  rspec ./spec/features/coauthor_spec.rb:40 # coauthor abby shares work but not a user
- [x]  rspec ./spec/features/coauthor_spec.rb:48 # coauthor abby shares work barbara can edit and feature
- [x]  rspec ./spec/features/collection/collection_spec.rb:19 # collection show collection as admin should show a theses collection
- [x]  rspec ./spec/features/collection/collection_spec.rb:31 # collection show collection as user should not show a theses collection
- [x]  rspec ./spec/features/lock_user_spec.rb:12 # lock_user user with unlocked access can sign in
- [x]  rspec ./spec/features/lock_user_spec.rb:17 # lock_user user with locked access can not sign in
- [x]  rspec ./spec/features/lock_user_spec.rb:27 # lock_user admin can lock user
- [x]  rspec ./spec/features/lock_user_spec.rb:36 # lock_user admin can unlock user
- [x]  rspec ./spec/features/lock_user_spec.rb:52 # lock_user non-admin cannot lock or unlock user
- [x]  rspec ./spec/models/ability_spec.rb:24 # Ability a user with no roles
- [x]  rspec ./spec/models/ability_spec.rb:25 # Ability a user with no roles
- [x]  rspec ./spec/models/ability_spec.rb:26 # Ability a user with no roles
- [x]  rspec ./spec/models/ability_spec.rb:29 # Ability a user with no roles
- [x]  rspec ./spec/models/ability_spec.rb:30 # Ability a user with no roles
- [x]  rspec ./spec/models/ability_spec.rb:31 # Ability a user with no roles
- [x]  rspec ./spec/models/ability_spec.rb:39 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:40 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:41 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:42 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:44 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:45 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:46 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:47 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:49 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:50 # Ability a registered user
- [x]  rspec ./spec/models/ability_spec.rb:57 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:58 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:59 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:60 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:62 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:63 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:64 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:65 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:67 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:68 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:69 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:70 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:72 # Ability a user in the admin group
- [x]  rspec ./spec/models/ability_spec.rb:73 # Ability a user in the admin group
- [x]  rspec ./spec/models/user_spec.rb:5 # User need to confirm a new user
- [x]  rspec ./spec/models/user_spec.rb:21 # User can lock and unlock user access

**Comment by pgwillia** [comment]
- [ ] problem with devise confirmation mailing
- [ ] problem with batch upload

**Comment by pgwillia** [comment]
Confirmation mailing was an anomaly -- not able to reproduce.

**Comment by pgwillia** [comment]
Seen while batch upload failing
```
GenericFilesController::create rescued Ldp::HttpError
        STATUS: 409 Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#primaryType to node /dev/6w/92/4b/87/6w924b87t
```

**Comment by pbinkley** [comment]
In order to prevent clamav errors in the tests on travis, I had to comment
out the constraint that clamav should not loaddb in test env. Maybe we can
look at this on Monday.

https://github.com/ualbertalib/HydraNorth/pull/164/files#diff-ae64e46a6d22ff74e201915e26418e57R1

Peter

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243
