### ISSUE TITLE
Item Submission Transaction Investigation

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/HydraNorth#162]
* What happens when some of component fail to update or persist the data and how we will handle them?
  * Fedora
  * Solr
  * MySQL
  * Resque & Redis
* Is there any transaction implemented in Sufia?
* Which component has transaction support?
* How about distributed transaction?

**Comment by pgwillia** [comment]
I'll park some info about what redis stores here for now: https://gist.github.com/pgwillia/5b6f800c253ea707b2e7
