### ISSUE TITLE
Workflow: adding files/collections to a collection

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#165]
Currently, under the parent collection there is a "Add file" and "Add collection" button. This seems to imply a workflow where you go find the things you want to add to the current collection; but in fact you are led into a workflow that does not take your starting collection as context. Rather, you select what you want to add, and then you select the collection you want to add to, regardless of where you started. This leaves the user (well, me) confused at the point when they are selecting items/collections: "what am I selecting these for again?". This will get worse when there are lots of collections and items. Of course, most of the work of adding to collections will be done at migration or ingest time, so this can be expected to be a rarely-used feature.

**Comment by weiweishi** [comment]
Duplication of issue #909 for adding collection to collection.  
Items can be added to collection during deposit/editing within the form.
