### ISSUE TITLE
User page usability issue

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#173]
1)On this page below, the user table column is centered, the table rows are aligned to the left. In some cases, the values in the row are mis-aligned with their corresponding table column headers. For example files deposited. 

Functionality: 
   -  sorting by User Name looks like not work
   -  Clicked User ID, error pages
![image](https://cloud.githubusercontent.com/assets/2047614/7069493/5642ec2e-de96-11e4-9629-77fa61e56c1a.png)

2) On the top-left corner,  email address is displayed twice. 

![image](https://cloud.githubusercontent.com/assets/2047614/7069446/0a508826-de96-11e4-969e-0a2a07105c02.png)

**Comment by nnunn** [comment]
I have fixed the double email issue. I looks like the other issues are fixed as well, but I'm not completely sure...

**Comment by pgwillia** [comment]
I don't know if 2) was really a bug.  
If User Name is filled out in the profile
![image](https://cloud.githubusercontent.com/assets/1220762/7754993/21662bb8-ffae-11e4-8035-da0e7aa876af.png)
Then the email address isn't repeated.
![image](https://cloud.githubusercontent.com/assets/1220762/7755004/3ce328dc-ffae-11e4-8676-60b133a3c7a8.png)

I'm seeing the same behaviour that's described in the master branch.
Clicking on 
![image](https://cloud.githubusercontent.com/assets/1220762/7755264/12a39d8e-ffb0-11e4-8e8c-952de366b157.png) does nothing when I'd expect that it would sort the users.
Clicking on 
![image](https://cloud.githubusercontent.com/assets/1220762/7755289/3fb94418-ffb0-11e4-820d-fb13239ce7bf.png) results in an error 
![image](https://cloud.githubusercontent.com/assets/1220762/7755298/4f71d0f0-ffb0-11e4-8c32-545a87698079.png)
