### ISSUE TITLE
User page when not logged in

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#179]
Can navigate to it, but throws error - should redirect to login page

**Comment by pbinkley** [comment]
e.g. https://era.library.ualberta.ca/users/peter-dot-binkley@ualberta-dot-ca gives error; but it works in dev, e.g. https://hydranorthdev.library.ualberta.ca/users/myself@ualberta-dot-ca

**Comment by pbinkley** [comment]
@leahvanderjagt will specify the desired behavior
We notice that the link to the depositor's files returns all ERA items.

**Comment by leahvanderjagt** [comment]
@pbinkley, I'm wondering why you said this should redirect to login page?
I'd be prone to have this page default to 'contributions' tab and list the
deposited items under contributed files in reverse date created order.


On Wed, Mar 30, 2016 at 2:04 PM, Peter Binkley <notifications@github.com>
wrote:

> @leahvanderjagt <https://github.com/leahvanderjagt> will specify the
> desired behavior
> We notice that the link to the depositor's files returns all ERA items.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/179#issuecomment-203610332>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pbinkley** [comment]
Decision: we're ok with this profile page being displayed to non-logged-in users. But we need to:
- [ ] fix the bug in the "Deposited Files" link, which retrieves all ERA content even though the query includes ```depositor="peter.binkley%40ualberta.ca"```
- [ ] make the "Activity" tab open by default

**Comment by pgwillia** [comment]
![screenshot from 2016-09-28 12-39-10](https://cloud.githubusercontent.com/assets/1220762/18927492/7b01f4de-8579-11e6-87ee-df0755dd6b9e.png)
![screenshot from 2016-09-28 12-40-29](https://cloud.githubusercontent.com/assets/1220762/18927495/7b136336-8579-11e6-98e7-67a1e6df5eb3.png)
![screenshot from 2016-09-28 12-42-02](https://cloud.githubusercontent.com/assets/1220762/18927493/7b127ae8-8579-11e6-89ba-1a83dafbf244.png)
![screenshot from 2016-09-28 12-42-44](https://cloud.githubusercontent.com/assets/1220762/18927494/7b132af6-8579-11e6-8d5b-6dfa8c539054.png)
