### ISSUE TITLE
Browse solution

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#181]
Enable browse for users: blank search with facets? More refined than that?

**Comment by pgwillia** [comment]
- [ ] link 
![image](https://cloud.githubusercontent.com/assets/1220762/7546724/68281e90-f59e-11e4-86be-22cee91985a7.png)
- [ ]  link 
![image](https://cloud.githubusercontent.com/assets/1220762/7546738/7a2c471a-f59e-11e4-9bab-4f845c0c12c9.png)
