### ISSUE TITLE
Thumbnails not generated for multimedia files

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#182]
PDFs, possibly others
on production: tottenham.library.ualberta.ca

**Comment by pgwillia** [comment]
From the [fixtures](https://github.com/ualbertalib/HydraNorth/tree/seed/spec/fixtures) that come with Sufia the following create broken thumbnails
* sample_mpeg4.mp4 
* countdown.avi

and 1.5mb-avatar.jpg would not upload.

**Comment by pbinkley** [comment]
So: we need to figure out why the tools that resque is using to create thumbnails from multimedia files are failing without causing the default thumbnail to be used.

**Comment by criedlberger** [comment]
In order for video and audio files to have proper thumbnails the following line must be uncommented in config/initializers/sufia.rb.

config.enable_ffmpeg = true

**Comment by criedlberger** [comment]
Closed with pull request #261
