### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#184]
DMP uses syslogger gem - works well - but need to discuss with Neil

**Comment by pgwillia** [comment]
6.5G Jun  8 17:16 production.log
12G Jun  8 13:09 production.log

In a production environment, we might have to address this problem by changing the log level
[from @henryzhang87]

**Comment by weiweishi** [comment]
@henryzhang87 do you think it's necessary if we move to syslogger?

**Comment by pbinkley** [comment]
obsolete
