### ISSUE TITLE
Front-end Performance Testing

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#186]
Natasha suggests SmushIt, Speed Test, etc.: remote sites that retrieve your page
Google Developer tools (though SEO isn't needed for soft launch)

**Comment by pgwillia** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=era.library.ualberta.ca&tab=desktop
![screenshot from 2016-02-10 13-14-13](https://cloud.githubusercontent.com/assets/1220762/12960378/3631d824-cff8-11e5-8444-7107723c1725.png)

**Comment by pbinkley** [comment]
Well, at least they like our server response time. I tried turning on compression in my dev environment using [this suggestion](http://stackoverflow.com/a/34435255), and it works for everything including downloads.  We would presumably want to get some caching of the compressed output going. So maybe this is better handled at the Apache level. But the savings are big, so worth pursuing.

**Comment by pbinkley** [comment]
Replaced by #982 and #983
