### ISSUE TITLE
OWASP 2.18: User enumeration

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#189]
Is it enough to force users to enter a name? 
DMP model: on log in, can't save profile without entering name.
Confirm that emails are not discoverable for users with names entered (i.e. that we've fixed the problem of being able to harvest all email addresses).

**Comment by weiweishi** [comment]
Some tips about customizing devise for forcing username:
http://stackoverflow.com/questions/12807576/require-username-at-registration

**Comment by pbinkley** [comment]
Currently a facet query on creator_sim reveals 27 email addresses appearing in the creator field (and therefore being displayed on public pages. There are 16,155 distinct creator strings. Dissertants aren't yet indexed in creator, but presumably there are no thesis authors with emails but no names.

```select?q=*%3A*&rows=0&wt=json&indent=true&facet=true&facet.field=creator_sim&facet.limit=1000000```
