### ISSUE TITLE
OWASP 3.2: Session invalidation on logout

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#190]
Penn State handles this, but it's not in Sufia

**Comment by pgwillia** [comment]
@piyapongch and @henryzhang87:
Might be that we're/sufia's not calling devise signout appropriately (using HTTP delete).

Scholarsphere has this:
https://github.com/psu-stewardship/scholarsphere/commit/715a48d748d8cd029d629094758448ee108418c5
```
  # Login/logout route to destroy session
  get 'logout' => 'sessions#destroy', as: :destroy_user_session
  get 'login' => 'sessions#new', as: :new_user_session
```
```
class SessionsController < ApplicationController
  def destroy
    # make any local additions here (e.g. expiring local sessions, etc.)
    redirect_to Sufia::Engine.config.logout_url
  end
end
```

**Comment by pgwillia** [comment]
@weiweishi  [DMP](https://github.com/ualbertalib/DMPonline_v4/blob/master/config/initializers/devise.rb#L242) is doing this correctly

**Comment by pgwillia** [comment]
HydraNorth is also doing this correctly.
