### ISSUE TITLE
OWASP 3.3: Session timeout after inactivity

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#191]
(related to 3.2)

**Comment by pgwillia** [comment]
@piyapongch and @henryzhang87:
Might be that we're/sufia's not invalidating sessions.

**Comment by pbinkley** [comment]
Use 30 minute session timeout, as in current ERA.

**Comment by pgwillia** [comment]
Public users sessions are not timed-out and can be reused.
