### ISSUE TITLE
Enable Dropbox/Drive deposit

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#193]
Investigate how much work it would be to turn this on - may need new Google account for Admin to manage the ownership (use the one we use for Google Analytics?)
This would be a nice feature to turn on, as an example of new functionality beyond current ERA.

**Comment by pbinkley** [comment]
Use google account we use for GA, if suitable, or set up a new one

**Comment by weiweishi** [comment]
GA's main account is ualib.peel@gmail.com. I think we should have a new one. Has anyone submitted a helpdesk ticket to create a new email address? What do you think as an appropriate name? ual.lib@ualberta.ca? ual.lib.di?

**Comment by pbinkley** [comment]
I'm thinking a DIT-specific address would be better, so as not to clash
with any future services that arise in other areas. And I wonder whether
there's any restriction on a ualberta.ca GMail account that might prevent
it serving this purpose. How about we experiment with our github@ualberta.ca
account first, and then replace it with something like ual.dit@ualberta.ca
for production? I can share github@ualberta.ca with you, I think.

Peter

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
Weiwei has requested a gmail account be created. We will pursue this if it comes through.

**Comment by pgwillia** [comment]
Drive: Google provides some intermediate screens during authentication with our information.  
![image](https://cloud.githubusercontent.com/assets/1220762/7662627/fa0ca7a4-fb1b-11e4-9b24-e7ebf5b7437b.png)
![image](https://cloud.githubusercontent.com/assets/1220762/7660474/9a5857ae-fb07-11e4-9cb6-bc73fdccf2c1.png)

**Comment by pgwillia** [comment]
We need to provide Dropbox with a icon/logo in exchange for a production key. Do we have one?

**Comment by pgwillia** [comment]
If user revokes permissions from either Drive or Dropbox they need to logout and log back in before they are able to re-enable access.

**Comment by pbinkley** [comment]
We should use the university logo that the library uses. Do they give any
guidelines on size? And on their use of the logo? We should check with
Kenton and make sure our use is consistent with the rest of the library's
online presence.


Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pgwillia** [comment]
https://www.dropbox.com/developers/reference/branding

**Comment by pbinkley** [comment]
The decision is to drop Dropbox for now, since IST discourages its use at U of A.

**Comment by gsharder** [comment]
Sure, I'm fine with putting dropbox integration on the product backlog.
However, is GDrive still an option? That would be a nice touch.

On Wed, May 20, 2015 at 2:06 PM, Peter Binkley <notifications@github.com>
wrote:

> The decision is to drop Dropbox for now, since IST discourages its use at
> U of A.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/193#issuecomment-104019963>
> .
>



-- 
Geoff Harder
Associate University Librarian
Information Resources and Digital Initiatives

*University of Alberta Libraries*


*2-10H Cameron Library, University of AlbertaEdmonton, AB, Canada T6G 2J8
 780.492.7914  *
*geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca> *
*library.ualberta.ca <http://library.ualberta.ca>*

**Comment by pbinkley** [comment]
Yes, Google Drive will be there - I'll merge Tricia's PR to enable it
shortly.

**Comment by pgwillia** [comment]
Peter, I added a test to ensure that the OAuth callback url I've configured in Google Developer Console exists.  This is another configuration management problem that I've solved with a change to the playbook.  Henry will apply it when he's reviewed it.

**Comment by pbinkley** [comment]
OK, I won't merge on Github until that's done.

**Comment by pgwillia** [comment]
The test can be merged anytime. Just want to make sure others know that the enabling Google Drive change is happening in other channels.
