### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#198]
Test against tottenham.library.ualberta.ca - this is the production environment
Use jmeter

Areas to test
- upload files
  - see related issue: #31 on file size limit
- download files
- search
- Google bot - wget to spider the site
- login 
- editing metadata
- revision of file (upload new version)
- adding to collections / removing from collections
- effect of batch ingest on user access
- social stuff: sharing, following, etc.

Profiling 
- are there RoR tools we should use? - @pbinkley will ask on list

Benchmark data
- Henry will post

**Comment by pgwillia** [comment]
To simulate spiders: https://gist.github.com/pgwillia/97fb2931254c02057418

**Comment by henryzhang87** [comment]
apache benchmark data:

testing case 1:  against newport

 ab -k -n 5000 -c 5 -e c5n50k_newport.csv http://newport.library.ualberta.ca/

Percentage served,Time in ms
0,60.017
1,64.838
2,66.454
3,67.510
4,68.414
5,69.216
6,69.891
7,70.456
8,70.967
9,71.454
10,71.944
11,72.448
12,72.949
13,73.415
14,73.838
15,74.203
16,74.556
17,74.890
18,75.274
19,75.644
20,76.074
21,76.330
22,76.644
23,76.984
24,77.368
25,77.735
26,78.030
27,78.395
28,78.684
29,78.973
30,79.266
31,79.635
32,79.880
33,80.243
34,80.662
35,80.974
36,81.347
37,81.634
38,81.964
39,82.304
40,82.560
41,82.918
42,83.276
43,83.545
44,83.861
45,84.251
46,84.551
47,84.921
48,85.293
49,85.608
50,85.928
51,86.262
52,86.684
53,87.149
54,87.490
55,87.886
56,88.181
57,88.485
58,88.897
59,89.200
60,89.593
61,90.038
62,90.411
63,90.840
64,91.246
65,91.619
66,92.187
67,92.465
68,92.939
69,93.390
70,93.940
71,94.386
72,95.070
73,95.688
74,96.293
75,96.928
76,97.470
77,98.046
78,98.667
79,99.249
80,99.809
81,100.572
82,101.462
83,102.362
84,103.301
85,104.351
86,105.652
87,106.870
88,108.590
89,110.090
90,111.696
91,114.145
92,116.181
93,118.029
94,120.505
95,124.493
96,129.401
97,136.049
98,144.527
99,177.695

**Comment by henryzhang87** [comment]
testing case 2: against leyton

ab -k -n 5000 -c 5 -e c5n50k_leyton.csv http://leyton.library.ualberta.ca/

Percentage served,Time in ms
0,57.931
1,64.096
2,65.543
3,66.450
4,67.056
5,67.783
6,68.332
7,68.762
8,69.214
9,69.558
10,69.933
11,70.234
12,70.509
13,70.839
14,71.143
15,71.381
16,71.653
17,71.911
18,72.192
19,72.449
20,72.651
21,72.873
22,73.106
23,73.356
24,73.645
25,73.883
26,74.135
27,74.367
28,74.554
29,74.781
30,74.971
31,75.199
32,75.411
33,75.615
34,75.887
35,76.144
36,76.349
37,76.572
38,76.823
39,77.051
40,77.277
41,77.445
42,77.665
43,77.867
44,78.079
45,78.271
46,78.585
47,78.789
48,79.079
49,79.365
50,79.573
51,79.828
52,80.028
53,80.258
54,80.566
55,80.768
56,80.992
57,81.303
58,81.571
59,81.848
60,82.066
61,82.369
62,82.675
63,82.953
64,83.238
65,83.567
66,83.883
67,84.176
68,84.652
69,84.931
70,85.267
71,85.649
72,86.054
73,86.455
74,86.905
75,87.348
76,87.717
77,88.148
78,88.687
79,89.203
80,89.869
81,90.471
82,91.117
83,92.336
84,93.477
85,94.604
86,95.744
87,97.349
88,99.192
89,101.159
90,104.281
91,106.236
92,108.225
93,110.633
94,114.718
95,119.560
96,134.777
97,230.303
98,308.167
99,337.483

**Comment by henryzhang87** [comment]
testing case 3: through haproxy with http access
 ab -k -n 5000 -c 5 -e c5n50k_http.csv http://hydranorth.library.ualberta.ca/
0,0.897
1,1.107
2,1.153
3,1.181
4,1.202
5,1.220
6,1.236
7,1.251
8,1.263
9,1.276
10,1.287
11,1.299
12,1.309
13,1.318
14,1.326
15,1.335
16,1.343
17,1.350
18,1.358
19,1.366
20,1.373
21,1.380
22,1.387
23,1.394
24,1.400
25,1.407
26,1.413
27,1.419
28,1.425
29,1.431
30,1.437
31,1.443
32,1.448
33,1.454
34,1.459
35,1.465
36,1.471
37,1.476
38,1.482
39,1.488
40,1.494
41,1.500
42,1.506
43,1.511
44,1.517
45,1.522
46,1.528
47,1.534
48,1.540
49,1.546
50,1.552
51,1.558
52,1.564
53,1.570
54,1.577
55,1.583
56,1.590
57,1.597
58,1.604
59,1.611
60,1.618
61,1.626
62,1.634
63,1.641
64,1.650
65,1.657
66,1.666
67,1.675
68,1.684
69,1.693
70,1.703
71,1.714
72,1.724
73,1.734
74,1.745
75,1.757
76,1.769
77,1.781
78,1.794
79,1.807
80,1.821
81,1.834
82,1.848
83,1.863
84,1.879
85,1.896
86,1.913
87,1.932
88,1.951
89,1.972
90,1.993
91,2.018
92,2.048
93,2.083
94,2.121
95,2.177
96,2.256
97,2.377
98,2.588
99,2.927

**Comment by henryzhang87** [comment]
testing case 4: haproxy with https

0,413.777
1,502.572
2,515.771
3,524.912
4,531.644
5,536.861
6,541.047
7,544.445
8,547.671
9,550.800
10,553.313
11,555.904
12,558.312
13,560.661
14,562.781
15,564.646
16,566.547
17,568.219
18,570.012
19,571.646
20,573.476
21,575.059
22,576.638
23,578.238
24,579.747
25,581.201
26,582.567
27,583.942
28,585.325
29,586.705
30,587.963
31,589.324
32,590.676
33,591.987
34,593.338
35,594.682
36,595.939
37,597.248
38,598.531
39,599.844
40,601.141
41,602.418
42,603.764
43,605.004
44,606.203
45,607.425
46,608.642
47,609.994
48,611.265
49,612.418
50,613.698
51,615.027
52,616.319
53,617.502
54,618.722
55,620.157
56,621.579
57,622.810
58,624.316
59,625.669
60,626.992
61,628.239
62,629.566
63,630.996
64,632.421
65,633.861
66,635.353
67,636.937
68,638.697
69,640.348
70,642.149
71,643.849
72,645.666
73,647.445
74,649.191
75,651.125
76,653.063
77,655.087
78,657.045
79,659.311
80,661.889
81,664.591
82,667.331
83,670.284
84,673.374
85,676.563
86,680.015
87,684.092
88,688.842
89,694.120
90,699.665
91,706.933
92,715.249
93,726.113
94,741.520
95,763.947
96,799.194
97,885.136
98,1058.061
99,1305.399

**Comment by pbinkley** [comment]
This is great. Let's think about where and how to store this benchmark data
in a standard way so that we can use it for future comparisons as the
platform evolves.

Peter

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by piyapongch** [comment]
I have created hydranorth-load-testing project on GitHub (
https://github.com/ualbertalib/hydranorth-load-testing). You can put
scripts, source code and document for load testing in this project.

Piyapong.

**Comment by pgwillia** [comment]
@weiweishi or someone with access to Google Analytics.  It would be useful to have typical session activity and extreme session activity, concurrent users, browsers/OS breakdown, and performance values from current ERA to use as inputs/targets for load/performance testing. Could you provide a report like this?

These metrics specific gathered from the following scenarios would be fantastic:
* ~~Thesis deposit~~ Batch ingest and searching around deadlines
* teaching
* course use
* media attention
* systematic downloader / google bot

**Comment by piyapongch** [comment]
2015.05.13: Test Results for Upload 10 Users 1 Loop

#Samples | Failed  | Max (ms) | Min (ms) | Ave (ms) | Throuhput (#/m) | KB/s
------------------- | -------- | ------------ | ----------- | ------------ | --------------------- | --------
23 | 1 | 114578 | 7920 | 33650 | 1.8 | 0.04

JMeter Results: \\libroot\ITS_Share\Hydra North\hydranorth-load-testing\apache-jmeter\test-results\2015.05.13 - Upload 10 Users 1 Loop

**Comment by piyapongch** [comment]
**2015.05.13: Test Results for Upload 10 Users 5 Loops**
* testing only on oldham.library.ualberta.ca

#Samples | Failed  | Max (ms) | Min (ms) | Ave (ms) | Throuhput (#/m) | KB/s
------------------- | -------- | ------------ | ----------- | ------------ | --------------------- | --------
1150| 183 | 358424 | 14 | 102583 | 5.7 | 0.08

*All failed are internal server error because of not enough space on tmp directory.

JMeter Results: [2015.05.13 - Upload 10 Users 5 Loops](https://github.com/ualbertalib/hydranorth-load-testing/tree/master/apache-jmeter/test-results/2015.05.13%20-%20Upload%2010%20Users%201%20Loop)

**Comment by piyapongch** [comment]
Need to create a new user story for Jenkins CI server integration.
