### ISSUE TITLE
RSOLR error when opening collection detail page

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#201]
Now there were about 130 items in the collection, it shows the following error message when opening the collection description page:

It seems that the query includes all the member ids within the collection, which makes the request too big to process. It's a potential bug upstream. 

(can't do a screen capture right now but will do one later). 

RSolr::Error::Http in Collections#show
Showing /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/sufia-6.0.0/app/views/collections/_show_descriptions.html.erb where line #3 raised:

RSolr::Error::Http - 413 Request Entity Too Large
Error: Error: Request Entity Too Large: head

URI: http://localhost:8983/solr/development/select?wt=ruby&rows=200&q=_query_%3A%22%7B%21raw+f%3Did%7Dp8418n60j%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n61t%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n623%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n63c%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n64n%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n65x%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n67g%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n68r%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n691%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n70s%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n712%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n72b%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n74w%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n755%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n76f%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n77q%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n780%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n798%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n819%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n82k%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n83v%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n844%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n85d%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n86p%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n887%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n89h%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n908%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n91j%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n92t%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n933%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n94c%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n95n%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n96x%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n976%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n98g%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418n99r%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p009%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p01k%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p02v%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p034%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p04d%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p05p%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p06z%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p077%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p08h%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p09s%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p10j%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p11t%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p123%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p13c%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p14n%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p15x%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p166%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p17g%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p18r%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p191%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p20s%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p212%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p22b%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p24w%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p255%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p26f%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p27q%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p280%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p298%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p301%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p319%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p32k%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p33v%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p344%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p35d%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p36p%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p37z%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p387%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p39h%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p408%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p41j%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p42t%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p433%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p44c%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p45n%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p46x%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p476%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p48g%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p49r%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p50h%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p51s%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p522%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p53b%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p54m%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p55w%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p565%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p57f%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p58q%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p60r%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p611%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p629%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p63k%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p64v%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p654%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p66d%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p67p%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p68z%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p697%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p700%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p718%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p72j%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p73t%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p743%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p75c%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p76n%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p77x%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p786%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p79g%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p807%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p81h%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p82s%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p832%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p84b%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p85m%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p86w%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p875%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p88f%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p89q%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p90g%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p91r%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p921%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p939%22+OR+_query_%3A%22%7B%21raw+f%3Did%7Dp8418p94k%22&qt=standard

Backtrace: /var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in `execute'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive'
(eval):2:in `get'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/solr_service.rb:107:in `query'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/associations/has_and_belongs_to_many_association.rb:55:in `block in find_target'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/associations/has_and_belongs_to_many_association.rb:53:in `step'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/associations/has_and_belongs_to_many_association.rb:53:in `find_target'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/associations/collection_association.rb:250:in `load_target'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/associations/collection_proxy.rb:50:in `load_target'
/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/active-fedora-9.0.6/lib/active_fedora/associations/collection_proxy.rb:846:in `to_ary'
Extracted source (around line #3):
1
2
3
4
5
6
          
  <h2 class="sr-only">Descriptions</h2>
  <dl class="dl-horizontal metadata-collections">
    <% present_terms(@presenter, @presenter.terms_with_values - [:title, :description]) do |r, term| %>
        <dt><%= r.label(term) %></dt>
        <dd><%= r.value(term) %></dd>
    <% end %>

Trace of template inclusion: app/views/collections/show.html.erb

Rails.root: /var/www/sites/hydranorth

Application Trace | Framework Trace | Full Trace
app/models/collection.rb:30:in `bytes'
app/presenters/hydranorth/collection_presenter.rb:31:in `size'
app/presenters/hydranorth/collection_presenter.rb:22:in `[]'
app/presenters/hydranorth/collection_presenter.rb:16:in `block in terms_with_values'
app/presenters/hydranorth/collection_presenter.rb:16:in `select'
app/presenters/hydranorth/collection_presenter.rb:16:in `terms_with_values'
app/views/collections/show.html.erb:13:in `_app_views_collections_show_html_erb___84984366823848998_70308788679120'
Request

Parameters:

**Comment by weiweishi** [comment]
Changed pagesize from default 200 to 70.

**Comment by pgwillia** [comment]
Can we close this?

**Comment by weiweishi** [comment]
fixed with #233
