### ISSUE TITLE
Error when accessing the collection list page on Plano

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#202]
Page:
http://plano.library.ualberta.ca/dashboard/collections
![image](https://cloud.githubusercontent.com/assets/2047614/7175106/33f0e594-e3ce-11e4-8d9b-768dade99320.png)

**Comment by pgwillia** [comment]
Looks like it's trying to sort on 'date_modified_dtsi' which is missing on 
 "docs": [
      {
        "title_tesim": [
          "Theses"
        ]
      },
      {
        "title_tesim": [
          "Photographs"
        ]
      },
      {
        "title_tesim": [
          "Communities"
        ]
      },
      {
        "title_tesim": [
          "Canadian Circumpolar Institute"
        ]
      }
    ]

One of the collections did get this value 
{
     "title_tesim": [
        "Circumpolar Digital Image Collection"
      ]
}

I'm wondering if the collections without the data modified were created before sufia 6.0.0 was deployed on plano?  If so then maybe we should wipe plano clean and start again.

**Comment by pgwillia** [comment]
Change between hydra-collections 4.0.0 and v5.0.0? https://github.com/projecthydra/hydra-collections/commit/61f887f6ac47e1c34489a60fb1a935a5c706534d

**Comment by weiweishi** [comment]
Same issue on http://plano.library.ualberta.ca/dashboard/files

**Comment by pgwillia** [comment]
_form_for_select_collection.html.erb is responsible for creating the list of collections modal dialog that is shown when the user adds files/collections to a collection.

**Comment by pgwillia** [comment]
Can we close this?

**Comment by criedlberger** [comment]
Looks like this is fixed on plano.
