### ISSUE TITLE
Permanent ID generation at point of deposit

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#207]
As a researcher, I want to know the permanent id /url before I finalize the document, so that I can include it in the document (e.g. PDF).
(From conversation with Amanda, 2015-04-21)

**Comment by pbinkley** [comment]
Can't do this directly in Sufia (since it requires a file upload), but it could be done by uploading a draft, getting the ARK, and then replacing the draft with the finished article with the ARK included. @sfbetz is this good enough? If so, please go ahead and close this.

**Comment by sfbetz** [comment]
Good enough from my perspective.
