### ISSUE TITLE
Import download stats from old ERA

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#210]
As a user, I want to see a continuous timeline of download and access of my items that have migrated from old ERA, with no difference between old ERA and new ERA activities.

(From conversation with Amanda, 2015-04-21)

**Comment by pbinkley** [comment]
In download table in old ERA we have these columns: `id`, `pid`, `collection_pids`, `downloaded_date`, `user_id`,  `ds_id`, `ip`, `user_agent`, so we can generate downloads per date at the item and collection levels.

**Comment by pgwillia** [comment]
https://support.google.com/analytics/answer/3191589?hl=en

**Comment by pbinkley** [comment]
Implemented with #529
