### ISSUE TITLE
Mediated deposit for user without an ERA account

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#211]
As admin, I want to be able to deposit an item whose author has no ERA account, without creating confusion about roles of depositor, creator and owner.
Some users may not want an ERA account at all, e.g. co-authors from other institutions, deceased authors, etc.
(From conversation with Amanda, 2015-04-21)

**Comment by pbinkley** [comment]
Dummy accounts, dummy emails?

**Comment by sfbetz** [comment]
This functionality exists. I don't think it requires further discussion unless we reignite the author profiles. Closing for now.
