### ISSUE TITLE
Deleting Collection on Plano results in Error

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#215]
When I select collection(s) to delete on dashboard/collections page, and click on delete selected button
![image](https://cloud.githubusercontent.com/assets/2047614/7284653/636100ec-e8fc-11e4-9841-cc0c21286632.png)
I get:
![image](https://cloud.githubusercontent.com/assets/2047614/7284685/9be2be74-e8fc-11e4-871c-4c88e2193464.png)

**Comment by criedlberger** [comment]
Looks like we need the routes added to the config file.
