### ISSUE TITLE
Sign up error on plano

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/HydraNorth#216]
I have tried to sign up, but I got an error message.

ArgumentError in Devise::Registrations#create
Showing /usr/lib64/ruby/gems/2.1.0/gems/devise-3.4.1/app/views/devise/mailer/confirmation_instructions.html.erb where line #5 raised:

Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
Extracted source (around line #5):
  <p>You can confirm your account email through the link below:</p>
  
  <p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>

**Comment by pgwillia** [comment]
This typically is a symptom of the devise mailer configuration not being present.  It is supplied by configuration management.

**Comment by pgwillia** [comment]
I added this by hand:

```
#devise config
  config.action_mailer.default_url_options = { :host => 'plano.library.ualberta.ca' }
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = { :address => "localhost", :port => 25 }

  ActionMailer::Base.default :from => 'hydranorth@ualberta.ca'
  ActionMailer::Base.delivery_method = :smtp
  ActionMailer::Base.smtp_settings = { :address => "localhost", :port => 25 }
```

Sign up works for now.  I'm guessing that @weiweishi might have changed branches and not considered the changes made by ansible for configuration.  I'll close for now.  We can reopen again if this is really a problem with deployment.

**Comment by weiweishi** [comment]
Yes. Sorry. Keep having issue when committing changes to the configuration
files. Will try to pay closer attention. Thanks Tricia.
