### ISSUE TITLE
CanvasJS Error on secondary pages

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#218]
Many of the tests are generating a warning because of a javascript error on the page that is unrelated to the functionality in the test.

CanvasJS Error: Chart Container with id "chartContainer" was not found

**Comment by nnunn** [comment]
I've seen this and planned to fix it ASAP.

Natasha

**Comment by weiweishi** [comment]
fixed with pull request https://github.com/ualbertalib/HydraNorth/pull/220

**Comment by pgwillia** [comment]
It would be good to remove https://github.com/ualbertalib/HydraNorth/blob/master/spec/spec_helper.rb#L133 and see if the tests pass.

**Comment by weiweishi** [comment]
Without the fix, tests failed with this line
https://github.com/ualbertalib/HydraNorth/blob/master/spec/spec_helper.rb#L133
in
place.
All tests succeeded with the fix no matter if {js_errors: false, timeout:
180} is removed from
https://github.com/ualbertalib/HydraNorth/blob/master/spec/spec_helper.rb#L133
.

Weiwei
