### ISSUE TITLE
8.2 Link CC licenses to CC site

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#22]
as a user, I want CC licenses in the item display page to be linked to their descriptions in the CC site, so that I understand the license terms (note: Sufia pulls up a static description of the license - we could add the link there) (contributable?) size:small priority:medium

**Comment by pbinkley** [comment]
This should be simpler once we finish #84 (do view tests with Selenium)

**Comment by criedlberger** [comment]
Link CC licenses to CC site #59
