### ISSUE TITLE
css missing from pages over https

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#223]
@nnunn did you see this before?  Do you remember the fix?

**Comment by pgwillia** [comment]
https://hydranorth.library.ualberta.ca/

**Comment by nnunn** [comment]
Do you know why the cert is broken? I can't even load the page unless I
ignore the cert error.

**Comment by pgwillia** [comment]
@henryzhang87 can correct me but I think it was self signed it to save a few extra days on the one that was purchased. Browsers don't think much of self-signed certificates.

**Comment by nnunn** [comment]
Ok - I can get to the css once I accept the cert.

https://hydranorth.library.ualberta.ca/assets/application-700865227b2c86374a2fdfa5c9ec19b0.css

I think the page just does not want to load the css because of the broken
cert.

**Comment by henryzhang87** [comment]
True. Browsers complains about self-signed certificates.

The certificate needs to use the right domain name. When it comes to
production, we would like to use era.library.ualberta.ca as the official
hostname.
At this moment, era.library.ualberta.ca is in use.

I will try to use physical name tottenham.library.ualberta.ca to create
certificate, and give an alias era.library.ualberta.ca to tottenham when it
is in production.
To see if that works.

**Comment by henryzhang87** [comment]
I used a wildcard certificate issued by GlobalSign to us, and concatenated
certificate, key, and root certificate in  a single file with PEM format.

Hope that fixes the problem

**Comment by pbinkley** [comment]
Looks good from here. @nnunn , if the new wildcard cert works for you, go ahead and close the issue.

**Comment by pgwillia** [comment]
I'm seeing missing images.

**Comment by pbinkley** [comment]
Hmm ... I wasn't a few minutes ago but now I am...

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by nnunn** [comment]
hmmm - I'm not sure why the css images aren't showing up. I can't browse to
them either. I'll dig into this a bit.

**Comment by nnunn** [comment]
I've added a fix for this and created a pull request.
