### ISSUE TITLE
Clean up sessions - specifically public users

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#226]
```ab -k -n 5000 -c 5 -e c5n50k_hydranorth.csv http://hydranorth.local/``` creates ~5000 rows in the sessions table that appear to persist indefinitely. Expected behaviour is that this table gets cleaned on occasion.

**Comment by pgwillia** [comment]
This has the same behaviour as DMP

**Comment by pgwillia** [comment]
```rake db:sessions:clear``` will purge all sessions.

**Comment by weiweishi** [comment]
Some helpful tips here: http://stackoverflow.com/questions/10088619/how-to-clear-rails-sessions-table

**Comment by pbinkley** [comment]
Current state: Henry can do it from the server side, but would prefer to have it done at the application side to prevent side effects. Current session expiry is 24 hours, with expiry checked every hour. The only problem is when load testing is running.

So:
- on production, change session expiry to 1 hour like current ERA
- on test, set expiry very low to prevent large build-up of sessions during load testing.

**Comment by pbinkley** [comment]
Sam and Natasha are looking at the same issue: ualbertalib/discovery#319 . It would be good to employ a consistent solution, to make life easier for the sysadmins.
