### ISSUE TITLE
Backlog and Critical Path Discussion

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#227]
## Soft Launch (May 28)
(See [Current](https://github.com/ualbertalib/HydraNorth/milestones/Current) and [Soft Launch](https://github.com/ualbertalib/HydraNorth/milestones/Soft%20Launch) milestones )
- Bug fixes
- Migration
- Load and stress testing, tuning
- Security: automated testing
- UI Design

## Post Soft Launch
(see [Future](https://github.com/ualbertalib/HydraNorth/milestones/Block:%20Future) and [Research Data](https://github.com/ualbertalib/HydraNorth/milestones/Block:%20Research%20Data) milestones)
- PCDM (following Hydra sprint work)
  - Item-level modelling; fixes to migration
  - Collection-level modelling
- OpenStack Swift integration
- Migration 
  - CCID authentication (SAML)
  - Theses (merging the two collections)
  - Other work emerging from the remaining collections
- Security: completion of OWASP Gold level #189 #192 #194 #222 
- Identifiers: ARK and EZ-ID integration
- Usability testing (after arrival of Projects Librarian)
- Bling
  - Dropbox/Google Drive integration #193 
  - Local GeoNames db: vocab caching #152 
- Audit Trail / Provenance (following Fedora 4 work) #49 #54 
- Research Data
  - Large Dark Datasets #68 
  - Dataverse to HydraNorth metadata import #67 
- Import usage stats from old ERA to display along with Google Analytics stats in HydraNorth #210
- ERA functionality
  - Batch export of citations #209 
  - Batch export of content #208 
  - Permanent ID generation at point of deposit #207 
  - Mediated deposit for user without account #211 
  - Tracking of admin users #212 
- OAI service #38 
- Infrastructure
  - #45 #46 #47 #48 
- UI Design for new features and in response to usability testing

## Production launch
- Redirections of ERA urls #113 
- Shutdown of old ERA functionality
- Change of domain

**Comment by pgwillia** [comment]
Here are my notes and thoughts.

Priorities
---
AW 
1. Mediated Deposit
2. OAI
∞. Batch export #208 content, #209 citations
SF
1. Content Migration
GH
1. Roadmap
2. Usability Testing
∞. Dark Archives

Critical Path
---
External Dependencies:
* PCDM (May 4-15) => collections, multipart works 
* Fedora 4 audit trails (April Phase 1 & 2 complete -- no fixity checks) => audits
* FGSR/Alfresco workflows => retiring old ERA

Internal Dependencies
* usability testing => batch export, citations, browsing, collections, design, navigation
* SAML authentication => migration of CCID protected content
* migration of content => OAI, Theses, UX

Sprint to Launch (brainstorming)
---
Sprint 16 (April 27-May 8)
* Bug fixes & Content Migration prep

Sprint 17 (May 11-22) - May 18 (Victoria Day)
* Deployment to Production and Content Migration
* Analytics
* Usability testing plan (i)

Sprint 18 (May 25-June 5)
* Demo to staff
* Usability testing and analysis (i)  -- depends on plan
* Mediated Deposit
* Content Migration (ERA?) -- depends on prep work

Sprint 19 (June 8 - 19)
* High Priority Usability stories (i) -- depends on testing/analysis
* SAML authentication
* Security (i)
* Content Migration (Dataverse?) -- depends on prep work

Sprint 20 (June 22 - July 3) - July 1 (Canada Day)
* Usability testing plan (ii) -- depends on migrated content/ux enhancements
* High Priority Usability stories (i) -- depends on previous sprint work
* PCDM/upgrades -- depends on PCDM completion and other community activity
* Identifiers -- depends on plan/requirements definition
* Content Migration (CCID?) -- depends on SAML authentication

Sprint 21 (July 6 - 17)
* Usability testing and analysis (ii) -- depends on plan
* audit/admin reporting -- depends on Fedora 4 audit work & defining requirements
* Deposit from Cloud
* Content Migration (ERA with identifiers?) -- depends on identifiers

Sprint 22 (July 20 - 31)
* High Priority Usability stories (ii) -- depends on testing/analysis
* OAI -- depends on content migration & identifiers
* OpenStack Swift
* Content Migration (Research Data?) -- depends on prep work

Sprint 23 (August 3 - 14) - August 3 (Heritage Day)
* Usability testing plan (iii) -- depends on migrated content/ux enhancements
* High Priority Usability stories (ii) -- depends on previous sprint work
* Security (ii) -- depends on Security (i) 
* Testing Backup/Recovery -- depends on content migrations and openstack

Sprint 24 (August 17 - 28)
* Usability testing and analysis (iii) -- depends on plan
* High Priority Usability stories (ii) -- depends on previous sprint work
* Communications Plan -- depends on progress and launch date (maybe earlier?!)

Sprint 25 (August 31 - September 11) - September 7 (Labour Day)
* High Priority Usability stories (iii) -- depends on previous sprint
* Prep work for retiring old ERA
* Launch?
