### ISSUE TITLE
Maximum size of content on ingest is 200MB

### ISSUE THREAD

**Issue by criedlberger** [ualbertalib/HydraNorth#253]
Need to increase the maximum size especially when users start uploading multimedia files

**Comment by pbinkley** [comment]
We'll set it to 1GB; anything larger will be handled by batch ingest

**Comment by pgwillia** [comment]
From   /etc/httpd/logs/error_log

[ 2015-05-11 11:17:29.5107 6336/7f1fab2e27e0 apache2/Hooks.cpp:732 ]: Unexpected error in mod_passenger: An error occured while buffering HTTP upload data to a temporary file in /tmp/passenger.1.0.13637/generation-1/buffered_uploads. Disk directory doesn't have enough disk space, so please make sure that it has enough disk space for buffering file uploads, or set the 'PassengerUploadBufferDir' directive to a directory that has enough disk space.
  Backtrace:
     in 'boost::shared_ptr<Passenger::BufferedUpload> Hooks::receiveRequestBody(request_rec*)' (Hooks.cpp:1190)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:546)

/tmp only has 961M total.  Could be why larger uploads fail if this is where uploads are buffered.

Directory can be configured https://github.com/ualbertalib/HydraNorth/blob/master/config/initializers/sufia.rb#L123-L124

**Comment by weiweishi** [comment]
Here is how PennState does it:
https://github.com/psu-stewardship/scholarsphere/blob/master/app/assets/javascripts/scholarsphere_fileupload.js
