### ISSUE TITLE
Usability testing

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#256]
At least informal usability testing with a small number of users. To be done by the Projects Librarian if the position is filled in a timely way. If possible and when time permits, a more formal usability process.

**Comment by pbinkley** [comment]
Identify user communities - structured conversations to develop user stories
Targets: 
- faculty
- students
- librarians
Work towards Sept. launch, but continue beyond that

**Comment by sfbetz** [comment]
I've completed two rounds of user testing with 11 participants. Testing materials and findings are in the Hydra User testing folder here: https://drive.google.com/folderview?id=0BwXbqVc9w_ukfkRiWXZSOUh0ZXVYODYyWFZJRzN5RjU1Tkx0bnR3ZEQ1YlVSV3ZWOEM0VkU&usp=sharing

We can consider
