### ISSUE TITLE
User migration on era-test

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#280]
User test failed on one of the era-test servers, with the following (sample) error message. Seems like it has problem access mysql?

FAILED: User 25459 migration at 2622!
closed MySQL connection
["/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:83:in `escape'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/mysql2_adapter.rb:83:in `quote_string'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/quoting.rb:21:in `quote'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:266:in `quote'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:591:in `quote'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:558:in `quoted'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:22:in `visit'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:515:in `visit_Arel_Nodes_Equality'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:22:in `visit'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:496:in `block in visit_Arel_Nodes_And'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:496:in `map'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:496:in `visit_Arel_Nodes_And'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:22:in `visit'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:204:in `block in visit_Arel_Nodes_SelectCore'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:203:in `each'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:203:in `each_with_index'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:203:in `visit_Arel_Nodes_SelectCore'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/mysql.rb:41:in `visit_Arel_Nodes_SelectCore'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:163:in `block in visit_Arel_Nodes_SelectStatement'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:163:in `each'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/to_sql.rb:163:in `visit_Arel_Nodes_SelectStatement'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/mysql.rb:36:in `visit_Arel_Nodes_SelectStatement'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:22:in `visit'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/visitor.rb:5:in `accept'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/arel-5.0.1.20140414130214/lib/arel/visitors/bind_visitor.rb:11:in `accept'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/querying.rb:39:in `find_by_sql'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation.rb:611:in `exec_queries'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation.rb:493:in `load'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation.rb:238:in `to_a'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/finder_methods.rb:460:in `find_take'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/finder_methods.rb:98:in `take'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/finder_methods.rb:81:in `find_by'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/querying.rb:7:in `find_by'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/dynamic_matchers.rb:70:in `find_by_email'", "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/hydra-access-controls-9.1.2/lib/hydra/user.rb:26:in `find_by_user_key'", "/var/www/sites/hydranorth/lib/tasks/user_migration.rake:41:in `block (2 levels) in migrate_users'", "/var/www/sites/hydranorth/lib/tasks/user_migration.rake:23:in `each_line'", "/var/www/sites/hydranorth/lib/tasks/user_migration.rake:23:in `block in migrate_users'", "/var/www/sites/hydranorth/lib/tasks/user_migration.rake:21:in `open'", "/var/www/sites/hydranorth/lib/tasks/user_migration.rake:21:in `migrate_users'", "/var/www/sites/hydranorth/lib/tasks/user_migration.rake:10:in `block (2 levels) in <top (required)>'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'", "/usr/lib64/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'", "/usr/lib64/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'", "/usr/bin/rake:33:in `<main>'"]

**Comment by weiweishi** [comment]
@henryzhang87, do you have a sense why this would happen?

**Comment by henryzhang87** [comment]
which server this happened on? tried to find the error message on both keith and oldham,
but found some similar error messages about MySQL


[root@oldham log]# cat test.log | grep MySQL
Mysql2::Error: Lost connection to MySQL server during query: COMMIT
Mysql2::Error: MySQL server has gone away: ROLLBACK
Mysql2::Error: Lost connection to MySQL server during query: COMMIT
Mysql2::Error: MySQL server has gone away: ROLLBACK
Mysql2::Error: closed MySQL connection: ROLLBACK
Mysql2::Error: Lost connection to MySQL server during query: COMMIT
Mysql2::Error: MySQL server has gone away: ROLLBACK
Mysql2::Error: Lost connection to MySQL server during query: SELECT  `users`.* FROM `users`  WHERE `users`.`email` = 'ehtesham@ualberta.ca' LIMIT 1
Mysql2::Error: MySQL server has gone away: SELECT  `users`.* FROM `users`  WHERE `users`.`email` = 'arhindle@ualberta.ca' LIMIT 1
Mysql2::Error: Lost connection to MySQL server during query: COMMIT
Mysql2::Error: MySQL server has gone away: ROLLBACK

**Comment by weiweishi** [comment]
It was ran on both Keith (last week) and Oldham (last night). I didn't
record the error message from last Friday's run on Keith so I can't tell if
they are exactly the same.
