### ISSUE TITLE
License files in ERA and free-text rights in Hydranorth

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#282]
A question for @awakaruk,  @sfarnel and the product owner,  and potentially more work following @criedlberger 's work on #21. 

Many items migrated from ERA to Hydranorth has either free text license and/or license files, the discussion we had in the past didn't seem to reach a mutual agreement on:

1. Do we continue to offer the option of free-text rights statement for new deposit in Hydranorth? And do we continue to offer the option of uploading customized license files?

2. How are we going to handle the license text for migrated items?
Option 1: if the answer to the first question is yes, we can also use the "Rights" field to handle the non-standard license text for migrated items. 
Option 2: if the decision is to not offer free-text rights statement for new deposit, we will still use the Rights field to handle the text. 
  * This option will require additional development work as it adds the complexity of handling the migrated items and new items differently on the record display page. 

3. How are we going to handle the license files?
Option 1: extract the text from the file and added to the free-text rights statement - however the text in the file could be lengthy and not particular user friendly on the record page. 
Option 2. Ingest the file as a separate datastream. More development work will be involved in this option, and we may not be able to have it ready for the soft launch. 

All of these options involve some level of development. Although we should not make our decisions based on the soft-launch deadline, we will have to have a plan for the items we migrated:
Option 1 - excluding items that has free text or license file from migration in the soft launch - until we have our selected option developed. 
Option 2 - try to develop with an easy option (adding free text rights statement, and extract text from the file) for the soft-launch while keeping in mind that it will need revisit after the launch.

**Comment by gsharder** [comment]
I would like to request that Amanda explore licensing options with Adrian
from the copyright office and that she put forward a sensible
recommendation, which we can then discuss and make a firm decision about.

Geoffrey Harder
Associate University Librarian
University of Alberta

Sent from mobile device

On May 20, 2015, at 10:18 AM, Weiwei Shi <notifications@github.com> wrote:

A question for @awakaruk <https://github.com/awakaruk>, @sfarnel
<https://github.com/sfarnel> and the product owner, and potentially more
work following @criedlberger <https://github.com/criedlberger> 's work on
#21 <https://github.com/ualbertalib/HydraNorth/issues/21>.

Many items migrated from ERA to Hydranorth has either free text license
and/or license files, the discussion we had in the past didn't seem to
reach a mutual agreement on:
1. Do we continue to offer the option of free-text rights statement for new
deposit in Hydranorth? And do we continue to offer the option of uploading
customized license files?
2. How are we going to handle the license text for migrated items?
Option 1: if the answer to the first question is yes, we can also use the
"Rights" field to handle the non-standard license text for migrated items.
Option 2: if the decision is to not offer free-text rights statement for
new deposit, we will still use the Rights field to handle the text.

   - This option will require additional development work as it adds the
   complexity of handling the migrated items and new items differently on the
   record display page.
      1. How are we going to handle the license files? Option 1: extract
      the text from the file and added to the free-text rights statement -
      however the text in the file could be lengthy and not particular user
      friendly on the record page. Option 2. Ingest the file as a separate
      datastream. More development work will be involved in this option, and we
      may not be able to have it ready for the soft launch.

All of these options involve some level of development. Although we should
not make our decisions based on the soft-launch deadline, we will have to
have a plan for the items we migrated:
Option 1 - excluding items that has free text or license file from
migration in the soft launch - until we have our selected option developed.
Option 2 - try to develop with an easy option (adding free text rights
statement, and extract text from the file) for the soft-launch while
keeping in mind that it will need revisit after the launch.

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/282>.

**Comment by awakaruk** [comment]
I am in the process of setting up a meeting with Adrian. Will let you know
as soon as I have a recommendation.

Amanda

*Amanda Wakaruk <https://sites.google.com/a/ualberta.ca/wakaruk/>*, MLIS,
MES
Acting Digital Repository <http://era.library.ualberta.ca> Services
Librarian
Government Information Librarian
<http://guides.library.ualberta.ca/govtinfo>
University of Alberta
amanda.wakaruk@ualberta.ca

**Comment by awakaruk** [comment]
The migration strategy described above sounds good to me. That is, migrating existing freetext and uploaded rights statements into the Rights field in new ERA.

Here are the revisions to this section. While this work should be completed before the start of structured user testing (likely late June or July) it is not expected before Thursday's preview session:

- We are not going to offer depositors the option of uploading a file to provide license information.

- Change the title of this form element to: "Select terms of use" (instead of the existing "Choose a license")

- Modify the pull-down options as follows: 
--- remove the option "All Rights Reserved" 
--- add the option "I am required to use/link to a publisher's license." and have this selection produce a free-text field where the depositor can enter a statement
--- add the option "I am not sure which license to choose."  and have this selection open the question mark/information pop-up text block

- Modify the text in the question mark/information pop-up box as follows:
--- remove information about the "All Rights Reserved" option
--- add a phrase at the bottom, "For help with selecting a terms of use license, see http://creativecommons.org/choose/ or contact the Digital Repository Services Librarian at erahelp@ualberta.ca

**Comment by pbinkley** [comment]
Developers: please use Amanda's comment as the spec of work required.

**Comment by pbinkley** [comment]
This is the one we need @nnunn to look at, in consultation with @criedlberger

**Comment by pbinkley** [comment]
@nnunn will look at this after Discovery project, probably in August.
