### ISSUE TITLE
dcterms namespace missing in some foxml

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#287]
@weiweishi , I don't know if you know about this: some batch-loaded items in old ERA lack the dcterms namespace declaration (it's defined in one element, but not in its siblings which also need it). E.g. uuid:ad91461b-33e1-4b87-a728-c1cd00cc04cb . Fedora doesn't mind this for some reason but other XML processes trip on it and declare the file invalid. The solution is to add the declaration to the root foxml:digitalObject element: xmlns:dcterms
="http://purl.org/dc/terms/" . It would be good to fix this in the migration. I think it would be easiest to add the dcterms declaration to every foxml file you extract from old ERA; it does no harm, and it saves having to determine whether it's needed.

**Comment by weiweishi** [comment]
I think this issue has already been addressed with @anayram 's transformation. Could you please confirm @sfarnel @anayram? Thanks!

**Comment by weiweishi** [comment]
Or do you mean to modify the original foxml that will be saved as a datastream in hydranorth?

**Comment by anayram** [comment]
Part of this issue has been addressed (in the transformed files used for migration) by adding the namespace declaration to the specific DCQ datastream (also all `dc:*` have been updated to `dcterms:*`). I can add the declaration into the root `foxml:digitalObject` element as well.

**Comment by pbinkley** [comment]
Yes, I meant to modify the original foxml before storing it in hydranorth,
so that what we save in hydranorth will be valid. When we use it again it
will probably be with external XML tools so we want it to validate.

Peter Binkley
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by anayram** [comment]
I have added the dcterms namespace to root elements in the transformed foxml (used for migration) just in case it is also needed at some point down the line.

**Comment by anayram** [comment]
Found a related problem with existing FOXML files that are missing the dcterms namespace:
there is a discrepancy between `foxml:datastream` where `@ID=DCQ` and `foxml:datastreamVersion` `@ID=DC.0~`.

I will correct this in the transformed metadata foxml for migration.

**Comment by pbinkley** [comment]
Fixed in FOXML transformation; but still needs to be incorporated into migration so that the stored original FOXML has the namespace. These files also have a problem with datastream ids (id of versions doesn't match id of datastream). Mariana has a list of these. They need manual checking, with Amanda involved.

**Comment by anayram** [comment]
@weiweishi I have added the following to the metadata stylesheet:
```xslt
    <xsl:template match="//foxml:datastream[@ID='DCQ']//foxml:datastreamVersion/@ID[contains(.,'DC.')]">
        <xsl:attribute name="ID">
            <xsl:value-of select="concat('DCQ', substring-after( ., 'DC'))"/>
        </xsl:attribute>
    </xsl:template>```

**Comment by anayram** [comment]
Fixed in both transformed and preserved foxml items.
