### ISSUE TITLE
Changes to the interface from demo

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#294]
- [x] facet: creator -> author
- sort: 
 - [x] date sort change to date_created / label "date oldest first" "date newest first"
 - [x] date uploaded - newest/oldest items
- advanced search form: (see wireframe) **assume that anything removed admin can still access in another way**
 - [x] contributor/creator for author
 - [x] tag should be removed
 - [x] rights-> license  
 - [x] date created -> date
 - [x] spatial
 - [x] resource types -> item type
 - [x] resource type to put down
 - [x] publisher deleted
 - [x] search tips last two duplicated. 
- [ ] after thesis added, the search interface, and facet/communities display/organization revisit after soft launch

**Comment by pgwillia** [comment]
Visit http://plano.library.ualberta.ca/catalog?utf8=%E2%9C%93&q= in Firefox Browser and click on "Item Type"
![image](https://cloud.githubusercontent.com/assets/1220762/7776892/e2fa4c1e-007b-11e5-98ff-9691f9207514.png)
Expected that "Publish" would not be broken
