### ISSUE TITLE
DAMS agreement on deposit form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#299]
Have to have uofa DAMS agreement link to the actual agreement

**Comment by awakaruk** [comment]
Please change the title of the existing deposit form link to "University of Alberta ERA Deposit Agreement" and have it open as a pop-up window to the text found in this document (this change is required in two places on the deposit form): https://docs.google.com/a/ualberta.ca/document/d/1d-tRADOGJqThzXV4eHoDr1AIB8p4OoWaju1BjOF3w0Y/edit?usp=sharing

**Comment by pgwillia** [comment]
closed by #341

**Comment by weiweishi** [comment]
The title of the link has not been changed.
