### ISSUE TITLE
Google form for feedback for soft launch

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#307]

**Comment by pbinkley** [comment]
I've started a form at https://docs.google.com/a/ualberta.ca/forms/d/1ZXZ2-TUVtsX06m3Ffw1K0Lv0kgLw6bghWqTHx8D1-q4/edit . The dev team, Amanda and Geoff have permissions to edit it. It should be easy to finalize the content of the form and incorporate the url in the site.
