### ISSUE TITLE
9.2 File Size Limits

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#31]
Need to check file size limits and adjust if necessary priority:high size:small 

Done: 
- [ ] We know how to (and have documented how to) set and enforce limits for deposits in HydraNorth; 
- [ ] we set the limit to 512mb (current ERA); 
- [ ] we have an appropriate place to store this documentation

**Comment by pgwillia** [comment]
@weiweishi do you remember what's left for this issue?

**Comment by weiweishi** [comment]
I just need to document my findings here. I will try to write something
tonight so we can have it closed.

**Comment by weiweishi** [comment]
Tested with file size up to 1GB. No file size limit in the application. Uploading large file sets from browser can be a problem as it would time out sometimes. Cloud upload may be a solution to the problem -- need to investigate once we have a user story on cloud upload (Google Drive etc. ) It is always possible to batch upload from the backend.
