### ISSUE TITLE
Advanced Search form changes

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#322]
Amanda's screenshot: https://drive.google.com/open?id=0Bx9c8G8_FeK5b2NxUEtWQzhtN2kxNlRNVGtOZ295VWV5djRN&authuser=0

- [x] Delete fields: Publisher, Location, Tag, Depositor, Rights
- [x] Combine Contributor and Creator fields, relabel as Author
- [x] Subject field should include spatial subject / location
- [x] Implement drop-downs for Language and Resource Type fields (based on Solr facets)
- [x] change labels: Contributor/Creator -> Author; Date Created -> Date; Resource Type -> Item Type
- [x] Sort options: "Relevance" [default], "Date (oldest first)", "Date (newest first)" [both based on date_created], "New items" [sort on date_uploaded, newest first]
- [x] Remove duplicate sentence from end of Search Tips

**Comment by weiweishi** [comment]
closed with #325
