### ISSUE TITLE
Browse results: sort by "New items first" when relevance is irrelevant

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#323]
In single-value browse queries (e.g. items in this collection or items with a given publication date), sorting by relevance makes no sense, since every item has the same score. In these cases, the default sort should be "New items first" (i.e. sort by date_uploaded, descending).

**Comment by pgwillia** [comment]
https://cwiki.apache.org/confluence/display/solr/Common+Query+Parameters#CommonQueryParameters-ThesortParameter
>Multiple sort orderings can be separated by a comma, using this syntax: sort=<field name>+<direction>,<field name>+<direction>],...
When more than one sort criteria is provided, the second entry will only be used if the first entry results in a tie. If there is a third entry, it will only be used if the first AND second entries are tied. This pattern continues with further entries.

HydraNorth sort is:
"sort"=>"score desc, date_uploaded_dtsi desc"

Currently **date_uploaded** breaks the tie.
