### ISSUE TITLE
UX usability - the warning message on the front page

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#331]
On the front page, the warning message to advise user to login when they click on the "Share your Research" button is down in the middle below era images, and it's not at all obvious ( I though nothing happened on the page even when I anticipated the message). Could it be moved up?

![image](https://cloud.githubusercontent.com/assets/2047614/7801174/a165d480-02dd-11e5-975d-2b3070531b68.png)

**Comment by weiweishi** [comment]
@nnunn I saw you closed the issue. Was this addressed? Or you don't think it's possible or feasible?

**Comment by nnunn** [comment]
I moved the warning messages up to the top.
