### ISSUE TITLE
refactor migration script

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#337]
Lots of repetition and 300 line methods.

**Comment by sfbetz** [comment]
@pbinkley @weiweishi is this resolved? If not, does in need to happen in current ERA? Or is it work for near-term Sufia or work for future?

**Comment by pbinkley** [comment]
I think this should be closed. We'll need a different migration script for
HydraNorth1 to HydraNorth2, and anything we use this for will be small jobs
at this point.
