### ISSUE TITLE
9.5 Users cannot deposit into thesis collection

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#34]
As admin, I want users to be prevented from depositing into the thesis collection: only admin can deposit sprint:9 size:small

Done: 
- [ ] no registered user has the option on the item menu (or anywhere else where they would otherwise be able to) to put their deposit into the thesis collection; 
- [ ] this option can be applied to other collections by the admin user. 
- [ ] The admin user can add items to theses.

**Comment by pgwillia** [comment]
In db/seeds.rb
```
theses = Collection.new(title: "Thesis").tap do |c|
  c.apply_depositor_metadata(admin.user_key)
end
theses.save!
```

This is a pre-requisite for #25 and follows #32.  Leaving to work on #32.
