### ISSUE TITLE
9.6 Packaging and Deployment

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#35]
As sysadmin, I want to be able to deploy from an ansible playbook, with a tagged release of HydraNorth and access to all necessary resources in RPMs sprint:9

Done: 
- [x] we have a release process for HydraNorth (tagged etc.); 
- [x] all the dependencies are packaged as RPMs; 
- [x] rebuild Plano with nothing compiled from source on it; 
- [x] the RPMs are deployed by the Ansible playbook and tested on new test system

**Comment by pgwillia** [comment]
Tag today. Ask Henry what the version number would be.

**Comment by pbinkley** [comment]
Henry will look into using the same SolrCloud as Blacklight, and report back if there are impediments.

**Comment by pgwillia** [comment]
Can we close this?
