### ISSUE TITLE
Advanced search form item type dropdown list doesn't include special report types

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#351]

**Comment by weiweishi** [comment]
Thanks @sfarnel. Should've thought about it!

@criedlberger . the completed list with all item types is at:
https://github.com/ualbertalib/HydraNorth/blob/master/config/initializers/sufia.rb#L56-L72

use config.admin_resource_types instead of config.resource_types will solve the problem.

**Comment by pgwillia** [comment]
Closed by #363
