### ISSUE TITLE
excessive active mysql connections on production and test servers

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/HydraNorth#357]
On production mysql:

<pre>
[root@mysql-master-PROD ~]$ mysqladmin processlist | grep newport
| 4124149 | hydranorth       | newport.library.ualberta.ca:52206    | hydranorthprod              | Sleep       | 26   |                                                                |                  |
| 4136467 | hydranorth       | newport.library.ualberta.ca:59156    | hydranorthprod              | Sleep       | 3    |                                                                |                  |
| 4153647 | hydranorth       | newport.library.ualberta.ca:32904    | hydranorthprod              | Sleep       | 112  |                                                                |                  |
| 4153648 | hydranorth       | newport.library.ualberta.ca:32905    | hydranorthprod              | Sleep       | 113  |                                                                |                  |
| 4155589 | hydranorth       | newport.library.ualberta.ca:32984    | hydranorthprod              | Sleep       | 325  |                                                                |                  |
[root@mysql-master-PROD ~]$ mysqladmin processlist | grep leyton
| 4078040 | hydranorth       | leyton.library.ualberta.ca:52896     | hydranorthprod              | Sleep       | 6    |                                                                |                  |
| 4134273 | hydranorth       | leyton.library.ualberta.ca:39083     | hydranorthprod              | Sleep       | 432  |                                                                |                  |
| 4153649 | hydranorth       | leyton.library.ualberta.ca:56665     | hydranorthprod              | Sleep       | 335  |                                                                |                  |
| 4153651 | hydranorth       | leyton.library.ualberta.ca:56668     | hydranorthprod              | Sleep       | 122  |                                                                |                  |
| 4153653 | hydranorth       | leyton.library.ualberta.ca:56677     | hydranorthprod              | Sleep       | 122  |                                                                |                  |
| 4156050 | hydranorth       | leyton.library.ualberta.ca:44072     | hydranorthprod              | Sleep       | 122  |                                                                |                  |
| 4156100 | hydranorth       | leyton.library.ualberta.ca:44296     | hydranorthprod              | Sleep       | 12   |                                                                |                  |

</pre>

On test mysql-test: 

<pre>
[root@mysql-master-TEST ~]$ mysqladmin processlist | grep keith | wc -l
71
[root@mysql-master-TEST ~]$ mysqladmin processlist | grep oldham | wc -l
57
[root@mysql-master-TEST ~]$ mysqladmin processlist | grep keith | wc -l
69

</pre>

**Comment by pbinkley** [comment]
@henryzhang87 is this still an issue?

**Comment by henryzhang87** [comment]
fixed
