### ISSUE TITLE
redirect to homepage after successfully create a new collection/file on production 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#364]
This behavior only happens on the production. 

However I did notice that my capybara test on plano seem to do the redirect too although it doesn't have the behavior on the user interface. Something weird with routes possibly?

**Comment by criedlberger** [comment]
Henry has made a change to re-route all http requests to https

The change was made on haproxy nodes.


#frontend hydranorth
#    bind 129.128.216.4:80
#    mode http
#    #redirect location https://tottenham.library.ualberta.ca/
#    redirect location https://hydranorth.library.ualberta.ca/

frontend hydranorth-ssl
     bind 129.128.216.4:80
     bind 129.128.216.4:443 ssl crt /etc/ssl/certs/tottenham.pem no-sslv3 no-tlsv10 no-tlsv11 ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:AES128:AES256:RC4-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK
     mode tcp
     reqadd X-Forwarded-Proto:\ https if { ssl_fc }
     option forwardfor
     default_backend hydranorth-backend
