### ISSUE TITLE
Metadata - Technical metadata for new ERA

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#424]
As the metadata team, we would like to ensure that we are capturing and appropriately recording technical metadata to ensure that objects in new ERA will be meaningfully preservable into the future.
- [ ] update data dictionary and data model to capture and record technical metadata to support preservation
- review current work by Hydra Technical Metadata Subgroup

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#114
