### ISSUE TITLE
ERA_User: Profile

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#43]
As a user, I want to have the same control over my profile information in Hydra North as I have in ERA, so that the transition is seamless size:large priority:high
    - but evaluate in terms of CASRAI - potential migration implications - would like report of data fields in current ERA users, to evaluate how clean it is etc.

**Comment by pbinkley** [comment]
Still needed (?): the evaluation of CASRAI

**Comment by sfarnel** [comment]
Early assessment and draft 'map' to CASRAI completed (and slightly revised based on recent CASRAI dictionary changes) can be found [here](https://docs.google.com/a/ualberta.ca/document/d/1dsJHganUY2EEO1Sf_yUKjbtfZstz-dtdg0O1mGTPbFA/edit?usp=sharing).
