### ISSUE TITLE
Migration of the license for era items

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#430]
- [ ] Extract text from the license files into the rights field. 
- [ ] create a datastream to preserve the rights files

**Comment by pbinkley** [comment]
@weiweishi the only part left to do here is to update the items with truncated licenses #780 - so can we close this as a duplicate?

**Comment by weiweishi** [comment]
Yes, I think so, and that task should be combined with other metadata clean
up tasks. Do we have tickets for the outstanding rake tasks that need to be
run.


*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
