### ISSUE TITLE
Migration of the ccid-protected items

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#431]
- [ ] update the migration task to handle the ccid protected information in the datastream. 

as part of #421

**Comment by sfarnel** [comment]
related to #479

**Comment by weiweishi** [comment]
depends on #582

**Comment by mbarnett** [comment]
@pbinkley this should be part of the current sprint, I believe?

**Comment by pbinkley** [comment]
Good point. Moving it now.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by mbarnett** [comment]
Good, because I have a solution half-finished already ;)

**Comment by pbinkley** [comment]
Great: we do our best work when tickets start out half done. Funny, that.

**Comment by weiweishi** [comment]
files are not downloaded successfully through the public interface. Looking for a solution right now.
