### ISSUE TITLE
Metadata - inclusion of additional vocabs/ontologies into Hydra North via rdf-vocab gem

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#432]
As the metadata team we would like to have be able to make use of vocabularies/ontologies not currently in the rdf-vocab gem to ensure our metadata enable the functionality to address user stories.
- investigate process of inclusion of additional vocabs/ontologies in rdf-vocab gem
- investigate impact on Hydra North as a whole
- determine workflows (who, when, how) around adding additional vocabs/ontologies

See #103, #370, #425, #426

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#111
