### ISSUE TITLE
Jenkins CI integration for load testing

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#440]
Wrapping up Piyapong's work on load testing by making it run on Jenkins.

- [ ] test against era-test

Based on biweekly deployment of new tagged release: build new release package, deploy on test, run load tests, deploy on production.

**Comment by piyapongch** [comment]
The Load Testing has been set up on Cardiff. It tests against era-test using Cardiff as a test machine and triggers by HydraNorth build. The test has been set to run 20 concurrent users for 10 minutes.
