### ISSUE TITLE
Migrating Dataverse Users to Hydranorth

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#449]
Each object deposited into Hydranorth requires a depositor/owner. Question for the research data stakeholders:

Option 1: Migrating Dataverse users to hydranorth, so that each object belongs to the appropriate original depositor, and they could share their objects through Hydranorth as well. But there's possibility that they may edit the metadata in Hydranorth so it would be inconsistent in two systems. 

Options 2: use a single admin user as the depositor in Hydranorth for Dataverse objects, for easy management, and avoiding users to edit their objects in Hydranorth. 

Which option is preferred? @wyman10

**Comment by johnhuck** [comment]
Adding my view, I think that we should choose the option that is least confusing (or potentially confusing) to users. I think that might be option 2. Especially since there is no data attached to the Dataverse objects in HydraNorth (only metadata).

We should test to see if users can perform other routine Hydra functions with the Dataverse "metadata objects," like adding them to collections, for instance, so HydraNorth users could group their data together with their publications.

**Comment by sfarnel** [comment]
I would agree that option #2 would seem the least confusing for users.

On Mon, Jul 6, 2015 at 2:28 PM, johnhuck <notifications@github.com> wrote:

> Adding my view, I think that we should choose the option that is least
> confusing (or potentially confusing) to users. I think that might be option
> 2. Especially since there is no data attached to the Dataverse objects in
> HydraNorth (only metadata).
>
> We should test to see if users can perform other routine Hydra functions
> with the Dataverse "metadata objects," like adding them to collections, for
> instance, so HydraNorth users could group their data together with their
> publications.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/449#issuecomment-118988245>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by wyman10** [comment]
Option #2 - we want to keep all of DV users in DV and harvest their metadata once a study is released.

**Comment by pbinkley** [comment]
Answered: use option 2, which is what the migration process currently does.
