### ISSUE TITLE
Upgrade to Sufia 6.2

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#453]
Failures:

- [ ]  1) delete admin see batch delete
     Failure/Error: expect(page).to have_content( "Batch delete complete")
       expected to find text "Batch delete complete" in "click for notifications. notify Select to access admin@example.com dashboard select for additional menu options upload my profile transfer requests log out education & research archive ERA home browse search share your research contact Search ERA click for notifications. notify Select to access admin@example.com dashboard select for additional menu options upload my profile transfer requests log out Search ERA Advanced Search Browse collections, subjects, or item types × Select something first Upload Create Collection Toggle facets Filter your files Item Type stuff1 Author little_file.txt_creator1 Listing Navigation Bar You are currently listing your files . You have 1 files My Files My Collections My Highlights Files Shared with Me All Files × Add to collection You do not have access to any existing collections. You may create a new collection. Close Add to Collection Files listing Listing of items you have deposited in ERA Select all files to be added to a collection or edited Select to access selection options Select None Select Current Page Title Date Created Visibility Action Check to add to a collection or edit list Display all details of little_file.txt Display summary details of little_file.txt Open Access Press to Select an action Single-Use Link to File Edit File Download File Delete File Highlight File on Profile Transfer Ownership of File File Name: /files/hq37vq368 File Format: JPG Creator: little_file.txt_creator Edit Access: Users: admin@example.com Quick Links Login Browse Search Share Your Research Policies Content Policy Mediated Deposit Metadata Policy Get Help How to Deposit? FAQ Contact Us © University of Alberta Libraries | University of Alberta, Edmonton, AB, Canada T6G 2R3 | Web Site Privacy Policy"
     # ./spec/features/admin_delete_spec.rb:30:in `block (3 levels) in <top (required)>'

- [ ]   2) catalog searching should have relevancy with newest
     Failure/Error: within('#search-form-header') do
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching css "#search-form-header"
     # ./spec/features/catalog_search_spec.rb:105:in `search'
     # ./spec/features/catalog_search_spec.rb:45:in `block (2 levels) in <top (required)>'

- [ ]  3) catalog searching p finds {P,S}
     Failure/Error: within('#search-form-header') do
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching css "#search-form-header"
     # ./spec/features/catalog_search_spec.rb:105:in `search'
     # ./spec/features/catalog_search_spec.rb:51:in `block (2 levels) in <top (required)>'

- [ ]  4) catalog searching NOT p finds {Q,R}
     Failure/Error: within('#search-form-header') do
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching css "#search-form-header"
     # ./spec/features/catalog_search_spec.rb:105:in `search'
     # ./spec/features/catalog_search_spec.rb:60:in `block (2 levels) in <top (required)>'

- [ ]  5) catalog searching p AND q finds {S}
     Failure/Error: within('#search-form-header') do
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching css "#search-form-header"
     # ./spec/features/catalog_search_spec.rb:105:in `search'
     # ./spec/features/catalog_search_spec.rb:69:in `block (2 levels) in <top (required)>'

- [ ]  6) catalog searching p OR q finds {P,Q,S}
     Failure/Error: within('#search-form-header') do
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching css "#search-form-header"
     # ./spec/features/catalog_search_spec.rb:105:in `search'
     # ./spec/features/catalog_search_spec.rb:78:in `block (2 levels) in <top (required)>'

- [ ]  7) catalog searching NOT(p AND q) finds {P,Q,R}
     Failure/Error: within('#search-form-header') do
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching css "#search-form-header"
     # ./spec/features/catalog_search_spec.rb:105:in `search'
     # ./spec/features/catalog_search_spec.rb:87:in `block (2 levels) in <top (required)>'

- [ ]  8) catalog searching NOT(p OR q) finds {R}
     Failure/Error: within('#search-form-header') do
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching css "#search-form-header"
     # ./spec/features/catalog_search_spec.rb:105:in `search'
     # ./spec/features/catalog_search_spec.rb:96:in `block (2 levels) in <top (required)>'

- [ ]  9) coauthor abby shares work @ included
     Failure/Error: select2(uid, from: "User (without the @ualberta.ca part)", search: true)
     Capybara::ElementNotFound:
       Unable to find css ".select2-container"
     # ./spec/features/coauthor_spec.rb:65:in `block in new_user_skel'
     # ./spec/features/coauthor_spec.rb:64:in `new_user_skel'
     # ./spec/features/coauthor_spec.rb:33:in `block (3 levels) in <top (required)>'

- [ ]  10) coauthor abby shares work @ not included
      Failure/Error: select2(uid, from: "User (without the @ualberta.ca part)", search: true)
      Capybara::ElementNotFound:
        Unable to find css ".select2-container"
      # ./spec/features/coauthor_spec.rb:65:in `block in new_user_skel'
      # ./spec/features/coauthor_spec.rb:64:in `new_user_skel'
      # ./spec/features/coauthor_spec.rb:37:in `block (3 levels) in <top (required)>'

- [ ]  11) coauthor abby shares work but not a user
      Failure/Error: expect(page).to have_content( "No matches found" )
        expected to find text "No matches found" in "click for notifications. notify Select to access archivist1@example.com dashboard select for additional menu options upload my profile transfer requests log out education & research archive ERA home browse search share your research contact Search ERA click for notifications. notify Select to access archivist1@example.com dashboard select for additional menu options upload my profile transfer requests log out Search ERA Advanced Search Browse collections, subjects, or item types My DashboardMy FilesBrowse View Edit little_file.txt Descriptions Versions Permissions Descriptions * indicates required fields * Title * Author or Creator Additional Contributors * Subject/Keyword * Type of Item Book Book Chapter Conference/Workshop Poster Conference/Workshop Presentation Dataset Image Journal Article (Draft-Submitted) Journal Article (Published) Learning Object Report Research Material Review * Language English French Spanish Chinese German Italian Russian Ukrainian Japanese No linguistic content Other Is this item about a place? Is this item about a time? Description Date Created Choose a license Attribution 4.0 International Attribution-ShareAlike 4.0 International Attribution-NonCommercial 4.0 International Attribution-NoDerivs 4.0 International Attribution-NonCommercial-NoDerivs 4.0 International Attribution-NonCommercial-ShareAlike 4.0 International Public Domain Mark 1.0 CC0 1.0 Universal I am required to use/link to a publisher's license ERA License Descriptions Creative Commons licenses can take the following combinations, which is what a depositor sees on the page where metadata (descriptions) are entered. Via the drop-down menu, the depositor may select any of the following licenses (these are all described at \"About the Licenses\" on the Creative Commons site): Attribution 4.0 International With this license you allow others to \"distribute, remix, tweak, and build\" on your deposited content - including for commercial purposes - provided they attribute you as the original creator.(Link to Attribution 4.0 International) Attribution-ShareAlike 4.0 International With this license you allow others to \"remix, tweak, and build\" on your deposited content, including for commercial uses, provided they attribute you as the original creator AND incorporate the same level of licensing for the newly resulting creation. \"All new works based on yours will carry the same license, so any derivatives will also allow commercial use.\"(Link to Attribution-ShareAlike 4.0 International) Attribution-NonCommercial 4.0 International With this license you allow others to \"remix, tweak, and build\" on your content in non-commercial ways. While they must credit you as the original creator and while the remixed, tweaked, or expanded upon content must remain non-commercial, they do not have to apply identical license terms on the new content.(Link to Attribution-NonCommercial 4.0 International) Attribution-NoDerivs 4.0 International With this license you share your work with others and allow them to download your work, provided they attribute you as the creator and refrain from changing the content in any way(Link to Attribution-NoDerivs 4.0 International) Attribution-NonCommercial-NoDerivs 4.0 International With this license you share your work with others and allow them to download your work, provided they attribute you as the creator and refrain from changing the content in any way and from using it for commercial means.(Link to Attribution-NonCommercial-NoDerivs 4.0 International) Attribution-NonCommercial-ShareAlike 4.0 International With this license you allow others to \"remix, tweak, and build\" on your content in non-commercial ways, provided they attribute you as the original creator AND incorporate the same level of licensing for the newly resulting creation. \"All new works based on yours will carry the same license, so any derivatives will also allow commercial use.(Link to Attribution-NonCommercial-ShareAlike 4.0 International) Public Domain Mark 1.0 When content is in the public domain, it has no known copyright owner.(Link to Public Domain Mark 1.0 CC0 1.0 Universal With this license you are waiving your rights as copyright owner to the content you upload. This means your content may be distributed and reused without attribution, without restriction. CC0 is a license that one applies to one's own work; rarely does one apply it to another's work, unless one has the appropriate rights to do so.(Link to CC0 1.0 Universal) Please note: Another license option that is listed is \"All rights reserved.\" With this license you - as the copyright holder - reserve all rights held under copyright law, such as for distribution and creation of derivative works. This means that no one can use your content in a work - such as a presentation or article - or create derivatives from it without your permission. Close Rights Citation for previous publication Source Link to related item Permissions Permissions are not saved until the \"Save\" button is pressed at the bottom of the page. Close this alert × Visibility - who should have the ability to read and download Open Access Visible to the world. University of Alberta Visible to all University of Alberta users. Embargo Restricted to Private University of Alberta until then Open Access University of Alberta Private Visible to users/groups specified below, if any. Share With (optional) Enter User (one at a time) Use the add button to give access to one User at a time (it will be added to the list below). Select the user, by name or User. Then select the access level you wish to grant and click on Add this User to complete adding the permission. User (without the @ualberta.ca part) Access type to grant Choose Access View/Download Edit Add this User Use the add button to give access to one group at a time (it will be added to the list below). Group Select a group Access type to grant Choose Access View/Download Edit Add this group Person/Group Access Level Depositor (archivist1@example.com) Edit Save Versions Upload New Version Upload a new version of this file from your computer. Upload New Version Restore Previous Version You must click \"Save Revision\" to revert a previous version of this file Save Revision Quick Links Login Browse Search Share Your Research Policies Content Policy Mediated Deposit Metadata Policy Get Help How to Deposit? FAQ Contact Us © University of Alberta Libraries | University of Alberta, Edmonton, AB, Canada T6G 2R3 | Web Site Privacy Policy"
      # ./spec/features/coauthor_spec.rb:45:in `block (3 levels) in <top (required)>'

- [ ]  12) coauthor abby shares work barbara can edit and feature
      Failure/Error: select2(uid, from: "User (without the @ualberta.ca part)", search: true)
      Capybara::ElementNotFound:
        Unable to find css ".select2-container"
      # ./spec/features/coauthor_spec.rb:65:in `block in new_user_skel'
      # ./spec/features/coauthor_spec.rb:64:in `new_user_skel'
      # ./spec/features/coauthor_spec.rb:49:in `block (3 levels) in <top (required)>'

- [ ]  13) collection delete collection should delete a collection
      Failure/Error: visit '/dashboard/collections'
      NoMethodError:
        undefined method `show_only_files_deposited_by_current_user' for #<MySearchBuilder:0x00000005f06e50>
      # ./app/controllers/concerns/hydranorth/my_controller_behavior.rb:17:in `index'
      # ./app/controllers/my/collections_controller.rb:11:in `index'
      # ./spec/features/collection/collection_spec.rb:30:in `block (3 levels) in <top (required)>'

- [ ]  14) collection show collection as admin should show a theses collection
      Failure/Error: visit '/dashboard/collections'
      NoMethodError:
        undefined method `show_only_files_deposited_by_current_user' for #<MySearchBuilder:0x00000002ab11c8>
      # ./app/controllers/concerns/hydranorth/my_controller_behavior.rb:17:in `index'
      # ./app/controllers/my/collections_controller.rb:11:in `index'
      # ./spec/features/collection/collection_spec.rb:48:in `block (3 levels) in <top (required)>'

- [ ]  15) collection show collection as admin should allow me to nest collections
      Failure/Error: visit '/dashboard/collections'
      NoMethodError:
        undefined method `show_only_files_deposited_by_current_user' for #<MySearchBuilder:0x0000000c79cb18>
      # ./app/controllers/concerns/hydranorth/my_controller_behavior.rb:17:in `index'
      # ./app/controllers/my/collections_controller.rb:11:in `index'
      # ./spec/features/collection/collection_spec.rb:48:in `block (3 levels) in <top (required)>'

- [ ]  16) collection show collection as user should not show a theses collection
      Failure/Error: visit '/dashboard/collections'
      NoMethodError:
        undefined method `show_only_files_deposited_by_current_user' for #<MySearchBuilder:0x000000111cee70>
      # ./app/controllers/concerns/hydranorth/my_controller_behavior.rb:17:in `index'
      # ./app/controllers/my/collections_controller.rb:11:in `index'
      # ./spec/features/collection/collection_spec.rb:74:in `block (3 levels) in <top (required)>'

- [ ]  17) collection paginate collections should page
      Failure/Error: visit '/dashboard/collections'
      NoMethodError:
        undefined method `show_only_files_deposited_by_current_user' for #<MySearchBuilder:0x000000110e8448>
      # ./app/controllers/concerns/hydranorth/my_controller_behavior.rb:17:in `index'
      # ./app/controllers/my/collections_controller.rb:11:in `index'
      # ./spec/features/collection/collection_spec.rb:95:in `block (3 levels) in <top (required)>'

- [ ]  18) collection delete items from collection should add and delete item from collection
      Failure/Error: click_button "Update Collection"
      ActiveFedora::ObjectNotFoundError:
        ActiveFedora::ObjectNotFoundError
      # ./spec/features/collection/collection_spec.rb:134:in `block (3 levels) in <top (required)>'

- [ ]  19) collection create collection should have a multivalue creator field
      Failure/Error: expect(page).to have_selector("div.collection_creator .input-append button.add")
        expected to find css "div.collection_creator .input-append button.add" but there were no matches
      # ./spec/features/collection/collection_spec.rb:183:in `block (3 levels) in <top (required)>'

- [ ]  20) Rights check if rights does not exist should not have field "generic_file_rights"
      Failure/Error: it { expect(page).to_not have_field('generic_file_rights') }
        expected not to find field "generic_file_rights", found 1 match: ""
      # ./spec/features/edit_rights_spec.rb:33:in `block (3 levels) in <top (required)>'

- [ ]  21) lock_user admin can lock user
      Failure/Error: visit "/users/#{unlocked_user.to_param}/edit"
      ActionView::Template::Error:
        undefined method `zotero_userid' for #<User:0x000000115f7fb0>
      # ./app/views/users/_edit_secondary.html.erb:2:in `_app_views_users__edit_secondary_html_erb__307963389381862185_144683300'
      # ./spec/features/lock_user_spec.rb:28:in `block (3 levels) in <top (required)>'

- [ ]  22) lock_user admin can unlock user
      Failure/Error: visit "/users/#{locked_user.to_param}/edit"
      ActionView::Template::Error:
        undefined method `zotero_userid' for #<User:0x0000000ce6bed0>
      # ./app/views/users/_edit_secondary.html.erb:2:in `_app_views_users__edit_secondary_html_erb__307963389381862185_144683300'
      # ./spec/features/lock_user_spec.rb:37:in `block (3 levels) in <top (required)>'

- [ ]  23) lock_user non-admin cannot lock or unlock user
      Failure/Error: visit "/users/#{user.to_param}/edit"
      ActionView::Template::Error:
        undefined method `zotero_userid' for #<User:0x0000000db70e00>
      # ./app/views/users/_edit_secondary.html.erb:2:in `_app_views_users__edit_secondary_html_erb__307963389381862185_144683300'
      # ./spec/features/lock_user_spec.rb:53:in `block (3 levels) in <top (required)>'

- [ ]  24) search search results should not have depositor info
      Failure/Error: click_button("Search ERA")
      Capybara::Ambiguous:
        Ambiguous match, found 2 elements matching button "Search ERA"
      # ./spec/features/search_spec.rb:33:in `block (2 levels) in <top (required)>'

- [ ]  25) session should assign new session after login
      Failure/Error: fill_in "search-field-header", with: "Toothbrush"
      Capybara::Ambiguous:
        Ambiguous match, found 2 elements matching field "search-field-header"
      # ./spec/features/session_spec.rb:8:in `block (2 levels) in <top (required)>'

- [ ]  26) Migration rake tasks migration:eraitem item should be migrated
      Failure/Error: Rake::Task["migration:eraitem"].invoke('spec/fixtures/migration/test-metadata/standard-metadata')
      NameError:
        uninitialized constant Sufia::IdService
      # ./lib/tasks/migration.rake:197:in `migrate_object'
      # ./lib/tasks/migration.rake:99:in `block (2 levels) in <top (required)>'
      # ./spec/tasks/migration_rake_spec.rb:12:in `block (3 levels) in <top (required)>'

Finished in 7 minutes 4 seconds (files took 10.54 seconds to load)
175 examples, 26 failures

**Comment by pbinkley** [comment]
6.2 was released last week, and Chris reports that it solves some of the problems in the 6.1 upgrade, so this story will be a 6.2 upgrade.

**Comment by pbinkley** [comment]
I'm ready to merge, but someone else should have a look at my final change: https://github.com/ualbertalib/HydraNorth/blob/sufia6.1-pre-rebase/spec/features/my/all_spec.rb#L53 - added "js: true" to run the js that creates the form that is being tested. @pgwillia or @weiweishi I'd be grateful if you could have a look. I'm squashing now in a separate branch.

That form starts out as 

```
 <label>Filter By User:</label>
      <input type="hidden" name="filter" id="filter" />
```

And is dynamically rewritten as:

```
label>Filter By User:</label>
      <div id="s2id_filter" class="select2-container"><a href="javascript:void(0)" class="select2-choice select2-default" tabindex="-1">   <span id="select2-chosen-1" class="select2-chosen">Search for a user</span><abbr class="select2-search-choice-close"></abbr>   <span class="select2-arrow" role="presentation"><b role="presentation"></b></span></a><label for="s2id_autogen1" class="select2-offscreen"></label><input id="s2id_autogen1" aria-labelledby="select2-chosen-1" class="select2-focusser select2-offscreen" aria-haspopup="true" role="button" type="text"><div class="select2-drop select2-display-none select2-with-searchbox">   <div class="select2-search">       <label for="s2id_autogen1_search" class="select2-offscreen"></label>       <input placeholder="" id="s2id_autogen1_search" aria-owns="select2-results-1" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="select2-input" role="combobox" aria-expanded="true" aria-autocomplete="list" type="text">   </div>   <ul id="select2-results-1" class="select2-results" role="listbox">   </ul></div></div><input style="display: none;" title="" tabindex="-1" name="filter" id="filter" type="hidden">
```

**Comment by pbinkley** [comment]
Sorry, forgot, there are a few more tests to update after rebasing on current master. I'll ask again when I've got them all done.

**Comment by pbinkley** [comment]
OK, branch sufia6.1-rebase is rebased on current master and has tests and test metadata (for dataverse) updated. Please have a look at the last two commits 04fce29 and 229ba37 and let me know if you find anything that needs fixing before merging. I'll go ahead and squash in a different branch.

**Comment by pgwillia** [comment]
app/controllers/my/collections_controller.rb can be removed completely, I think.

spec/features/edit_rights_spec.rb seems to have changed in behaviour completely. Is this right?

**Comment by pbinkley** [comment]
Regarding spec/features/edit_rights_spec.rb ; it was created in 2beb007 as we separated license and rights fields in migrated ERA items, and changed in 7d495e2 as Chris worked through necessary changes to the generic_file metadata form after the Sufia 6.2 upgrade. I'll confirm with the stakeholders that the current behavior is correct.

**Comment by pbinkley** [comment]
Stakeholder approves the current behaviour. I've deleted app/controllers/my/collections_controller.rb and will merge the squashed branch.
