### ISSUE TITLE
SAML Scenario 1: Sign in, doesn't have user account, can use SAML credentials to login

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#459]
Broken out from #428

Scenario 1: Sign in, doesn't have user account, can use SAML credentials to login
- [x] Given user has valid CCID/password
- [x] And user visits /users/sign_in
- [x] When they click on "Sign in with Shibboleth"
- [x] And enter their SAML credentials
- [x] Then an ERA account should be created
- [x] And that user should be signed in
- [x] And that user should be redirected to /dashboard

**Comment by pbinkley** [comment]
Duplicate of #457

**Comment by pgwillia** [comment]
Not duplicate of #457.  Similar but different work.
