### ISSUE TITLE
SAML 5: User has existing user account different than SAML response, link account but unconfirmed

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#460]
Story: SAML #428 
As a University of Alberta user with a valid CCID, I want to use these credentials to login to ERA so that I don't have to remember a separate username/password.

Scenario 5: Sign in, SAML email not found, can use SAML credentials to login

- [x] Given the user enters their SAML credentials
- [x]  And the email address returned by the SAML response doesn't exist in the system
- [x]  When the user is prompted if they have an existing account
- [x]  And they respond with the email from an active account
- [x]  Then a email for account confirmation should be sent and not confirmed
- [x]  And the user should not be able to use the credentials

**Comment by weiweishi** [comment]
Noticed that:
[ ] Then a email for account confirmation should be sent and not confirmed

It's re-sending the confirmation email. Just a thought: Wondering if from a usability point of view, this confirmation email can be worded differently to avoid confusion. Maybe a separate mail template in Devise? Need input from @sfbetz. Will create a new ticket if that's preferred.

**Comment by sfbetz** [comment]
Not sure I understand the scenario and outcome - Sorry - someone might need to give me a face to face on this one next week!

**Comment by weiweishi** [comment]
@sbetz. Yes, let's do a demo together on the new SAML function and discuss
this.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
