### ISSUE TITLE
ERA_Monitoring: Advisories

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#47]
As admin, I want to be able to place system advisories (to appear on every page) to inform users of expected or current outages, so that users are not frustrated by system outages

**Comment by sfbetz** [comment]
Functionality referenced in User stories for admin epic #833 
 
**As an administrator I want to be able to easily communicate with users so I can keep them updated on changes to ERA.** 

-post banner messages on the home page.
-ability to add notifications to the dashboard.
-push highlighted collections / researchers to the front page
