### ISSUE TITLE
"Select folder" button missing in FireFox

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#487]
![select folder missing in ff](https://cloud.githubusercontent.com/assets/12801010/8559063/4544c6f6-24c6-11e5-8391-5185cf82b042.png)
Firefox

![select folder in chrome](https://cloud.githubusercontent.com/assets/12801010/8559064/48bb0b24-24c6-11e5-8af8-6f8145df6f14.png)
Chrome

**Comment by pbinkley** [comment]
It turns out this is deliberate, in ```app/views/generic_files/upload/_form_fields.html.erb```. Presumably the folder upload function depends on Chrome in some way. I haven't dug into it further yet.

```
<% ua = request.env['HTTP_USER_AGENT'] %>
<% if !!(ua =~ /Chrome/) %>
    <span class="btn btn-primary fileinput-button">
        <i class="glyphicon glyphicon-plus"  aria-hidden="true"></i>
        <span aria-hidden="true">Select folder...</span>
        <input type="file" name="files[]" directory webkitdirectory mozdirectory />
    </span>
<% end %>
```

**Comment by sfbetz** [comment]
Performing as expected. Not a bug
