### ISSUE TITLE
Error message clicking on "files shared with me" tab

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#488]
Clicking here:
![files shared with me](https://cloud.githubusercontent.com/assets/12801010/8559144/d7a24852-24c6-11e5-9eb7-5f1e0c8cc49e.png)

Does this:
![shared with me tab](https://cloud.githubusercontent.com/assets/12801010/8559151/e2ec901e-24c6-11e5-9c10-36b330ace7c4.png)

**Comment by sfbetz** [comment]
Still presenting - error now "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

**Comment by sfarnel** [comment]
Strange. On my desktop, in Chrome, when logged in either with ccid or with
another non-UA account I don't seem to get an error. But if I log in as
admin I get an error. Maybe too many files?

On Thu, Oct 22, 2015 at 12:52 PM, Sonya Betz <notifications@github.com>
wrote:

> Still presenting - error now "We're sorry, but something went wrong. If
> you are the application owner check the logs for more information."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/488#issuecomment-150321303>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfbetz** [comment]
fixed - no longer a problem.
