### ISSUE TITLE
Error message clicking on "edit selected" 

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#489]
Selected all files and clicked here:

![edit selected](https://cloud.githubusercontent.com/assets/12801010/8559208/8704dabc-24c7-11e5-87d4-f40b92782170.png)

Error message:

![my files - edit selected](https://cloud.githubusercontent.com/assets/12801010/8559205/7fb3beae-24c7-11e5-9629-5779ed793a20.png)

**Comment by pbinkley** [comment]
Duplicate of #783
