### ISSUE TITLE
Dataverse to HydraNorth (Sept. launch) -- Part 2

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#491]
This issue gathers together the loose ends from #67 that need to be resolved before September launch.
It is part of epic story #69.

Questions to be answered by John:

- [x] Metadata team needs to reach final decision about how to handle qualifiers for elements derived from dc:coverage.
- [x] Metadata team needs to decide whether to include or exclude dc:coverage "geographic unit" (it will be excluded)
- [x] Decision needed to decide whether to remove html markup from selected dcterms:description elements or leave as-is.
- [x] request a fresh export of oai_dc data.
- [x] respond to question in #450 to provide information about alternate dates that could be used for submission and modification dates.
- [x] handling of multi-value rights fields in migration and display:
(The second rights element, which corresponds to a contact information field in DDI, will be excluded.)

**Comment by johnhuck** [comment]
New information about html tags in content: Dataverse explicitly allows html formatted content in certain fields, and description is one of them.

**Comment by johnhuck** [comment]
Answering first checkbox: qualifiers will be excluded. As a result, some dc elements will be excluded from the and alternate predicates will be found for others.

Provisionally:
Time Period Covered --> use dcterms:temporal
Date of Collection --> exclude
Country/Nation --> use http://dbpedia.org/ontology/Country
Geographic Coverage --> use dcterms:spatial
Geographic Bounding --> use http://www.rdaregistry.info/Elements/u/#P60109 (coordinatesOfCartographicContent)
Geographic Unit --> exclude
rights --> exclude 2nd rights statement (contact information)

**Comment by sfarnel** [comment]
John, for the geographic bounding, is there anything that can be taken
from, say, the Geoblacklight work in terms of a more geo-focused predicate
than the one from RDA?

On Thu, Jul 16, 2015 at 1:20 AM, johnhuck <notifications@github.com> wrote:

> Answering first checkbox: qualifiers will be excluded. As a result, some
> dc elements will be excluded from the and alternate predicates will be
> found for others.
>
> Provisionally:
> Time Period Covered --> use dcterms:temporal
> Date of Collection --> exclude
> Country/Nation --> use http://dbpedia.org/ontology/Country
> Geographic Coverage --> use dcterms:spatial
> Geographic Bounding --> use http://www.rdaregistry.info/Elements/u/#P60109
> (coordinatesOfCartographicContent)
> Geographic Unit --> exclude
> rights --> exclude 2nd rights statement (contact information)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/491#issuecomment-121856493>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by johnhuck** [comment]
@sfarnel, I don't think that Geoblacklight has developed any vocabularies, but that's a good suggestion, and I will investigate.

**Comment by sfarnel** [comment]
I recall from the article in code4lib that they mentioned using GML and
others and wondered if there were options there?

On Thu, Jul 16, 2015 at 8:51 AM, johnhuck <notifications@github.com> wrote:

> @sfarnel <https://github.com/sfarnel>, I don't think that Geoblacklight
> has developed any vocabularies, but that's a good suggestion, and I will
> investigate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/491#issuecomment-121979399>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by johnhuck** [comment]
html markup will be stripped out by a pre-ingest script.

**Comment by weiweishi** [comment]
http://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-strip_tags ?
