### ISSUE TITLE
Dataverse to HydraNorth: dcterms:publisher display

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#492]
dcterms:publisher is not being displayed in plano
- example: http://plano.library.ualberta.ca/files/bv73ht029#.VZ2RaPlVhBc
(publisher: Population Research Laboratory)

Plan: 
- [x] add publisher field back into GenericFile, as it was in Sufia
- [x] add remote_resource attribute to GenericFile, and populate it in dataverse migration task: remote_resource='dataverse' - this allows us to identify imported dataverse items without depending on resource_type or membership in Dataverse collection
- [x] suppress publisher field in GenericFile editing form if remote_resource=='dataverse'

**Comment by pbinkley** [comment]
Publisher isn't yet part of the GenericFile model or the HydraNorth data dictionary. Is there any discussion needed before we add it? @sfarnel , @awakaruk ?

**Comment by johnhuck** [comment]
I think I flagged the need to add this term when communicating with Weiwei, but neglected to add it to the data dictionary, which I have now down. And @sfarnel and I have discussed the need to add it.

**Comment by awakaruk** [comment]
Thanks! Sharon and I also touched base about this. More work to come
post-launch for the content entered in this field.

*Amanda Wakaruk <https://sites.google.com/a/ualberta.ca/wakaruk/>*, MLIS,
MES
Acting Digital Repository <http://era.library.ualberta.ca> Services
Librarian
University of Alberta Libraries
amanda.wakaruk@ualberta.ca

**Comment by pbinkley** [comment]
A question: Sufia adds schema.org tagging, and for the publisher field it
uses Organization:

<span itemprop="publisher" itemscope itemtype="
http://schema.org/Organization">

Is this ok for the content of publisher fields in Dataverse?

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by wyman10** [comment]
There does not seem to be a Publisher field in DV. There is however a Producer field. Can we link Producer to Organization?

**Comment by pbinkley** [comment]
Yes, sorry, I think that's what John's extraction script is doing: the
record arrives at HydraNorth's door with a DC publisher field. So I just
want to confirm that the contents of the DV source field are always
suitable to be presented as a schema.org Organization.

Peter

**Comment by sfarnel** [comment]
Just wanting to chime in here to say that we do have schema.org
implementation on our radar for post-launch and so we will be looking at
this.

But these two questions, i.e., properties for items and embedded microdata
for SEO are two different questions that should not be co-mingled. We will
have to look at all of our item types from different sources and suss out
the appropriate representation in schema.org as a whole rather than
property by property for only one data source.

On Tue, Jul 14, 2015 at 4:30 PM, Peter Binkley <notifications@github.com>
wrote:

> Yes, sorry, I think that's what John's extraction script is doing: the
> record arrives at HydraNorth's door with a DC publisher field. So I just
> want to confirm that the contents of the DV source field are always
> suitable to be presented as a schema.org Organization.
>
> Peter
>
>
> On 14 July 2015 at 16:18, wyman10 <notifications@github.com> wrote:
>
> > There does not seem to be a Publisher field in DV. There is however a
> > Producer field. Can we link Producer to Organization?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/492#issuecomment-121409010
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/492#issuecomment-121412489>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by johnhuck** [comment]
@wyman10 : publisher is a dublin core term that is present in the oai_dc output that we are importing into Hydranorth. Dataverse fields have been mapped to available dublin core and the source of the value is some other field in Dataverse. It may be producer, in fact, but I have to check.

**Comment by johnhuck** [comment]
@pbinkley I think I need to know more about how schema.org is used in Sufia to answer the question. As @sfarnel suggests, I think it's probably something to focus on down the way.
