### ISSUE TITLE
Dataverse to HydraNorth pt. 2: automation

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#493]
We need an automated process to update previously migrated Dataverse items and to detect and migrate new items.
- [ ] mechanism to detect new and changed items (OAI?)
- [ ] process to refresh HydraNorth items derived from Dataverse with updated metadata from Dataverse. Refactor our migration process

For further thought: other Dataverse users are feeding items into SHARE via OAI: question of authoritative single source.

**Comment by pbinkley** [comment]
Piyapong reports that our current Dataverse instance has an OAI server, which we haven't turned on. An alternative for detecting new items would be to pull from EZID's OAI server, since our DOI-minting process notifies it when we create new items. It's not clear, though, whether it would be able to report changed items.

**Comment by gsharder** [comment]
Dataverse version 3 may have OAI, but note that the service appears to have
been dropped from Dataverse version 4  - see:
https://groups.google.com/forum/#!topic/dataverse-community/TOhe1IuuosQ

On Thu, Jul 9, 2015 at 10:31 AM, Peter Binkley <notifications@github.com>
wrote:

> Piyapong reports that our current Dataverse instance has an OAI server,
> which we haven't turned on. An alternative for detecting new items would be
> to pull from EZID's OAI server, since our DOI-minting process notifies it
> when we create new items. It's not clear, though, whether it would be able
> to report changed items.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/493#issuecomment-120059970>
> .
>



-- 
Geoff Harder
Associate University Librarian
Information Resources and Digital Initiatives






*University of Alberta Libraries2-10H Cameron Library, University of
AlbertaEdmonton, AB, Canada T6G 2J8  780.492.7914
 geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
library.ualberta.ca <http://library.ualberta.ca>*

**Comment by sfarnel** [comment]
definitely worth watching. have read a little about ResourceSync in the
context of Archivematica development but don't know too much.

On Fri, Jul 10, 2015 at 9:00 AM, gsharder <notifications@github.com> wrote:

> Dataverse version 3 may have OAI, but note that the service appears to have
> been dropped from Dataverse version 4 - see:
> https://groups.google.com/forum/#!topic/dataverse-community/TOhe1IuuosQ
>
> On Thu, Jul 9, 2015 at 10:31 AM, Peter Binkley <notifications@github.com>
> wrote:
>
> > Piyapong reports that our current Dataverse instance has an OAI server,
> > which we haven't turned on. An alternative for detecting new items would
> be
> > to pull from EZID's OAI server, since our DOI-minting process notifies it
> > when we create new items. It's not clear, though, whether it would be
> able
> > to report changed items.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/493#issuecomment-120059970
> >
> > .
> >
>
>
>
> --
> Geoff Harder
> Associate University Librarian
> Information Resources and Digital Initiatives
>
>
>
>
>
>
> *University of Alberta Libraries2-10H Cameron Library, University of
> AlbertaEdmonton, AB, Canada T6G 2J8 780.492.7914
> geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
> library.ualberta.ca <http://library.ualberta.ca>*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/493#issuecomment-120430000>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
ResourceSync looks promising - it has a cleaner separation of notification
and harvesting than OAI. It looks like the Dataverse folks recognize the
need for something like this, so we can expect that 4 will eventually have
it. If it isn't there at launch, the worst that can happen to us is that
our HydraNorth metadata falls behind changes to Dataverse metadata, and we
can remedy that by manually-triggered updates.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
Note: Dataverse hopes to offer final 3-to-4 migration scripts in October. We won't attempt upgrade until these are ready.
