### ISSUE TITLE
Dataverse to HydraNorth: download link

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#494]
- [ ] Download link takes user to a dead end. Can the Dataverse DOI URI be substituted? Otherwise, can the link be deactivated?
Note: DOI is stored in identifier field. We would only want it to be used as the download link for items in the Dataverse collection.

**Comment by pgwillia** [comment]
![image](https://cloud.githubusercontent.com/assets/1220762/10144832/f2f389ca-65dc-11e5-8cc5-ab8572d37ba4.png)
