### ISSUE TITLE
Selecting embargo causes files to hang up while processing

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#495]
During deposit, if user selects embargo options in permissions, files won't process:
![embargo](https://cloud.githubusercontent.com/assets/12801010/8607866/43f1566e-2653-11e5-9e79-ed50d6e0b83f.png)

![embargo bug](https://cloud.githubusercontent.com/assets/12801010/8607880/52bb242c-2653-11e5-9a5c-c732c8b848db.png)

Metadata entered during initial deposit won't save, but can be saved and edited after.

**Comment by pgwillia** [comment]
This is related to the [hydra-tech] Setting Embargoes in Sufia discussion from this week.

**Comment by sfbetz** [comment]
Tested and can confirm this bug is fixed.
