### ISSUE TITLE
Batch Edit Form: Priority 3

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#499]
As a repository administrator, I want to ensure that users complete fields in the deposit form correctly so that items have good metadata. 

As a depositor, I want easy to understand feedback built into the deposit form so I can fill in fields correctly.

User testing indicated that users had some confusion about filling in fields correctly - clarifying language in the form, and in the pop-up help boxes should resolve this issue. 

- [x] Turn off auto-populating title and author fields
- [ ] Add additional box for subject / keyword field to invite multiple entries
- [ ] Add easy-to-see text above selected fields to guide users in formatting their entries *
- [x] Edit language in selected pop-up help boxes to provide additional clarification where necessary *
- [x] Delete selected pop-up boxes that do not provide additional clarity *
- [x] Bring up Description and Date Created fields above the "Show Additional Fields" button
- [ ] Make "Show Additional Fields" button more visible (contrast colour)

* Recommended language for pop-up help box changes here: https://docs.google.com/document/d/1Scbt3DiwYHl3wAw0zM_Ae4_YPEGRoqXhKKlvspDQzYc/edit?usp=sharing

**Comment by sfbetz** [comment]
I think this was supposed to be in Sprint 22? @pbinkley

**Comment by criedlberger** [comment]
Created branch batch_edit_form

**Comment by pbinkley** [comment]
Moved leftover work to #546
