### ISSUE TITLE
Layout of Bulk Permissions in Deposit Form: Priority 4

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#501]
As  a depositor, I want easy-to-understand visibility settings so I can be confident that I'm sharing my items appropriately.

In user testing, participants were unsure of which options they were selecting.

- [x] separate the options (Open access, University of Alberta, Embargo, Private) and place each on its own line
- [x] update language in "Visibility" and "Share With" help pop-ups for additional clarity (see https://docs.google.com/document/d/1Scbt3DiwYHl3wAw0zM_Ae4_YPEGRoqXhKKlvspDQzYc/edit?usp=sharing)
- [x] add a calendar select tool to the Embargo date field to ensure correct formatting of date OR provide example date format above field.

**Comment by pbinkley** [comment]
I tied the datepicker js, but it needs some thought. I moved that into #533 and just went with sample date string for now.

**Comment by pbinkley** [comment]
Handling of embargo date approved by Amanda and Sonya.

**Comment by pgwillia** [comment]
@sfbetz does the order matter in the Visibility help box? Your document has "Embargo" then "University of Alberta" while the interface has "University of Alberta" then "Embargo.

**Comment by pgwillia** [comment]
@sfbetz also the 'Share With' language is marked as needing work. Is this still the case?

**Comment by sfbetz** [comment]
Order should be the same in the help box as it is on the form itself - I think I messed up in my document.

Share with: if groups are being used then the language is fine as is. If there are no groups being created and managed, then the information about sharing with groups can be deleted.

**Comment by pbinkley** [comment]
I think I silently amended Sonya's order to match the order of the form -
Tricia, are you looking at Sonya's document or the code?

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pgwillia** [comment]
@pbinkley both.  Checking that the PR matches the requirements.

@sfbetz right now there are public, registered and admin groups.  Most users will not see a group listed here. We've talked about adding groups for other purposes, but this has not yet been implemented.
