### ISSUE TITLE
Term discrepancy between data dictionary and submission form

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#503]
Small terminology inconsistency:

[HydraNorth data dictionary](https://docs.google.com/spreadsheets/d/1hSd6kf4ABm-m8VtYNyqfJGtiZG7bLJQ3fWRbF_nVoIw/edit#gid=1015613040) has:
* Conference/workshop Poster
* Conference/workshop Presentation

ERA HydraNorth Submission form has:
* Conference/Workshop Poster
* Conference/Workshop Presentation

Any option is ok as long as term strings are consistent (in the meantime we move toward using data type URIs). If we keep the first option, the submission form needs adjusting. If we keep the second, the FOXML DCQ transform can update all objects' metadata before migration.

**Comment by weiweishi** [comment]
A very small but needed change before the launch. @criedlberger do you want to fix this?
