### ISSUE TITLE
Layout and language of upload form: Priority 2

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#504]
As a depositor, I want to understand if the options presented on the deposit form are relevant to my situation, so I can make the right decisions about uploading my items.

Participants found the "Uploading special reports?" language on the upload form confusing - weren't sure if this language applied to them.

Participant who opened the DAMS agreement got lost in orphaned new window.

Possible solutions:
- [x] reposition the Special reports options below the DAMS agreement, or provide other ways to reduce visibility when not necessary
- [x] keep DAMS agreement visible ( keep on page with expandable text / or open new window with "I agree" box on that page / or open in same page with easy option to return using back button or breadcrumbs)

**Comment by sfbetz** [comment]
Created mock-up here: https://docs.google.com/document/d/1lkab2EP8i3STGCpM5dVk31_xBaaWzWsm1lyC6no8ef0/edit?usp=sharing

**Comment by pbinkley** [comment]
The way the mockup handles the special reports changes the logic of the form and will require a little work. The yes/no pairs of buttons presumably need to be linked, so that you can't click both yes buttons.
