### ISSUE TITLE
Navigation to user tools and dashboard: Priority 1

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#508]
As a user I want to easily navigate ERA so I can find the tools I frequently use, such as viewing and editing my files, uploading content, and creating collections.

During user testing we found that participants had significant difficulty finding and returning to their dashboard. Users clicked on "home" and "share my research" or the drop-down arrows next to their profile name, but could not return to the dashboard. Navigation elements are inconsistent and not accessible from all pages. When users could find helping elements, like breadcrumbs, they used them frequently.

**Comment by pbinkley** [comment]
For Aug. 1, we will:
- do relabelling: "Dashboard"
- add breadcrumbs to pages that lack them, based on the structure of the site
- add "My Dashboard" to header
Sonya will lead process of determining the actual changes needed, in consultation with Amanda.

**Comment by sfbetz** [comment]
Suggestions for easy changes to improve nav:
 1. 
Changes to log-in button in top RH corner:
[ ] Add "my dashboard" link to drop down menu
[ ] make name and drop down arrow all one entity, and only open drop down on click (no longer link name to dashboard)

![login link](https://cloud.githubusercontent.com/assets/12801010/8839001/afab9d7a-308e-11e5-8858-59748a8d45a0.png)

**Comment by sfbetz** [comment]
Easy change 2.
Change "Share your research" link on homepage and in header to link to dashboard instead of to upload.

**Comment by sfbetz** [comment]
Easy change 3:

Move View files icon in dashboard to more visible location. Rename "view my files." (while we're at it, rename "view collections" to "my collections")
![move view files](https://cloud.githubusercontent.com/assets/12801010/8839250/f118a850-3090-11e5-8239-126f89273ea6.png)

**Comment by sfbetz** [comment]
Breadcrumbs:

I think this is a logical structure for breadcrumbs, but you could use some brainstorming on this one when someone is ready to tackle it with me...

Home
>Browse
>Search
>My Dashboard
    >>Upload
        >>>Describe your item
    >>View my files
        >>>My files
        >>>Files shared with me
        >>>My highlights
        >>>Transfer of ownership
    >>My collections
    >>Create collections
>My Profile
    >>Edit my profile (includes authorize proxy?)
    >>View users (? I don't know)

**Comment by sfbetz** [comment]
On dashboard:
-move upload icon to the right and compress 4 red icons above that block
-move profile above "your statistics"

**Comment by pgwillia** [comment]
easy fix 1,2,3 merged with #538 

unfinished: breadcrumbs and moving profile.

**Comment by pbinkley** [comment]
Leftover work moved to #540
