### ISSUE TITLE
"Update generic file" button 

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#509]
As a user I want page elements to naming conventions that are consistent with my expectations, so I can easily navigate the site.

Users found the language for the save button in the edit file confusing - currently it's called "Update Generic file" - recommend changing to "Save" or "Update"

**Comment by pbinkley** [comment]
Closed by #871

**Comment by sfbetz** [comment]
This is still showing on the item edit screen?

![screen shot 2016-01-08 at 9 43 25 am](https://cloud.githubusercontent.com/assets/12801010/12203457/534e2c8a-b5ec-11e5-95df-1a3982b5bd81.png)

**Comment by pbinkley** [comment]
Argh, I messed up the merge: this was fixed by dc1ab55, but then I overwrote the change with a merge from master in 12e236d before merging #871. I'll restore the fix.
