### ISSUE TITLE
"Start upload" button

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#514]
As a user, I want upload behaviour of ERA to be consistent with my experience in other online environments so that I know what to expect.

Some users were a little bit confused by the upload button. Once they added files, they waited for upload to start automatically. When it didn't they investigated and clicked on "start upload." All users were able to upload content easily.

**Comment by nnunn** [comment]
I have simplified the upload process, which I think fixes this issue.
