### ISSUE TITLE
Type of Item field

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#516]
As a user, I want the "type of Item" field to behave consistently with my expectations, so I can be confident that I've correctly entered information.

Users expected the Type of Item field to behave like the Language field. All users were able to complete this field correctly, however, they were unsure if they had done so. 

Note: this field can have multiple selections (unlike language), so we may not want to change it. Instead, may want to add clarification that more than one option may be selected by using control - click.

**Comment by sfarnel** [comment]
It should be the case that type of item is required but single value, as
with language. I will check this on Monday when I'm on campus.

On Wed, Jul 15, 2015 at 4:50 PM, Sonya Betz <notifications@github.com>
wrote:

> As a user, I want the "type of Item" field to behave consistently with my
> expectations, so I can be confident that I've correctly entered information.
>
> Users expected the Type of Item field to behave like the Language field.
> All users were able to complete this field correctly, however, they were
> unsure if they had done so.
>
> Note: this field can have multiple selections (unlike language), so we may
> not want to change it. Instead, may want to add clarification that more
> than one option may be selected by using control - click.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/516>.
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
On the current form users can select multiple item types when they should only be able to select one.

**Comment by weiweishi** [comment]
@criedlberger again, small bug fix but is needed for the launch.

**Comment by weiweishi** [comment]
fixed by #600
