### ISSUE TITLE
Single author displayed in author / creator field

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#517]
As a user, I want to see all authors / creators for a work displayed in the search results page so that I can easily find articles that have been co-authored when I conduct an author search.

When they conduct a search using an author's name as keyword, users have to click into the detailed view to see if an article has been co-authored.

Suggest displaying all authors in results.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#119
