### ISSUE TITLE
ERA migration - complete for fall launch

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#521]
Migrate all ERA communities, collections and items for fall launch.

ualbertalib/metadata-transforms#36

We want to do a full fresh migration, but this is likely to take too long - so we will do an incremental remigration of items that have changed. Perhaps lock old ERA at end of work on D-1, do the final incremental migration overnight, and bring up HydraNorth in the morning.

**Comment by sfarnel** [comment]
For final migration, we will migrate:

- all active, open items (including theses)
- all active embargoed items (except theses)
- all active, ccid protected items
- all inactive items (including inactive ccid protected items) except theses
- all dark items

For final migration, we will not migrate:

- deleted items
- inactive theses (which prevents migrating any theses in process or embargoed)

@pbinkley @weiweishi @sfbetz - does this capture everything accurately?

**Comment by pbinkley** [comment]
That agrees with my understanding.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by sfbetz** [comment]
Yes. Sounds good to me.

**Comment by sfarnel** [comment]
Super; thanks all!

On Mon, Aug 24, 2015 at 4:19 PM, Sonya Betz <notifications@github.com>
wrote:

> Yes. Sounds good to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/521#issuecomment-134398150>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
Clarification (in discussion with @anayram @sfarnel @weiweishi @sfbetz @pbinkley)
inactive items: we will migrate no inactive theses, and all other inactive items. They will include embargoed items and other items (mostly saved). We will apply embargo permissions if an embargo is set, otherwise we will simply make it private (like a dark items). We will the detect the inactive status by inspecting the state of the foxml record.

**Comment by anayram** [comment]
Done. All files for ERA migration are available from:
Digital_Init shared drive
Hydra_DAMS\ERA\ERA_migration\FOXML_transformed\complete_remigration\era_final_migration
+++
Total ERA files: ~42498

Excluded from October 1st migration:
35 system files (service definitions, deployments, models, etc.)
16525 legacy theses (will be migrated later)
1101 inactive theses (2009-present)
189 deleted files
32 malformed XML files (to be migrated later)

Total files to be migrated for launch: ~24755

Files to be migrated on or after Oct 6:
16525 legacy theses
32 malformed xml files
any files updated in ERA after September 10.

**Comment by pbinkley** [comment]
With the migration underway and the first real-world benchmarks, it looks
like we should be able to migrate the legacy theses before launch, if the
files are ready. Are the transformed foxml files for these available? I see
that digital_init:Hydra_DAMS/ERA/ERA_migration/FOXML_transformed/complete_remigration/legacy_theses
is empty at the moment.

Thanks,

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by anayram** [comment]
Legacy theses' ERA foxml is ready (you can find it under folder
PSL/psl_15/era_transformed_data if I recall correctly), but it hasn't yet
been merged with the enhanced metadata (in folder new_data).  There is a
merge stylesheet almost ready in the ualbertalib/metadata-transforms repo.
The only thing left to add to the stylesheet is to grab handles and
proquest identifiers from foxml and preserve them in the enhanced
foxml records.

On Friday, 2 October 2015, Peter Binkley <notifications@github.com> wrote:

> With the migration underway and the first real-world benchmarks, it looks
> like we should be able to migrate the legacy theses before launch, if the
> files are ready. Are the transformed foxml files for these available? I see
> that
> digital_init:Hydra_DAMS/ERA/ERA_migration/FOXML_transformed/complete_remigration/legacy_theses
> is empty at the moment.
>
> Thanks,
>
> Peter
>
> Peter Binkley, Ph.D., MLIS
> Digital Initiatives Technology Librarian
> Information Technology Services
> peter.binkley@ualberta.ca
> <javascript:_e(%7B%7D,'cvml','peter.binkley@ualberta.ca');>
>
> 2-10K Cameron Library
> University of Alberta
> Edmonton, Alberta
> Canada T6G 2J8
>
> phone 780-492-3743
> fax 780-492-9243
>
> On 1 October 2015 at 14:00, Mariana Paredes-Olea <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Done. All files for ERA migration are available from:
> > Digital_Init shared drive
> >
> >
> Hydra_DAMS\ERA\ERA_migration\FOXML_transformed\complete_remigration\era_final_migration
> > +++
> > Total ERA files: ~42498
> >
> > Excluded from October 1st migration:
> > 35 system files (service definitions, deployments, models, etc.)
> > 16525 legacy theses (will be migrated later)
> > 1101 inactive theses (2009-present)
> > 189 deleted files
> > 32 malformed XML files (to be migrated later)
> >
> > Total files to be migrated for launch: ~24755
> >
> > Files to be migrated on or after Oct 6:
> > 16525 legacy theses
> > 32 malformed xml files
> > any files updated in ERA after September 10.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/521#issuecomment-144831955
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/521#issuecomment-145139044>
> .
>


-- 
--
Mariana
