### ISSUE TITLE
Relations of researchers to communties

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#525]
To be specced out by @awakaruk and @sfbetz - what is needed within HydraNorth to enable researchers to see/present themselves as members of a community?

**Comment by sfarnel** [comment]
I think what may be meant here is what's reflected in ualbertalib/HydraNorth#92, i.e., users associate a deposited item with a 'community' and/or 'collection'

**Comment by sfbetz** [comment]
Yes - that looks like it, thanks. I browsed through the issues, but missed this. Is every item in ERA assigned to a collection and community?

**Comment by sfarnel** [comment]
In current ERA, every item must belong to at least one community, but can
belong to more. Items can also belong to one or more collection, but it is
not required.

On Tue, Jul 21, 2015 at 8:22 AM, Sonya Betz <notifications@github.com>
wrote:

> Yes - that looks like it, thanks. I browsed through the issues, but missed
> this. Is every item in ERA assigned to a collection and community?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/525#issuecomment-123332005>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
Dupe of #92
