### ISSUE TITLE
Service Migration: handles

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#528]
ERA and DSpace handles must be updated to resolve to new location.

**Comment by weiweishi** [comment]
closed with PR #651

**Comment by weiweishi** [comment]
@pbinkley Does it mean we need to update the handle servers with the new location?

**Comment by pbinkley** [comment]
Yes - currently the handle server resolves to the old ERA url and then
HydraNorth redirects to the new url. We ought to have the handle resolve
directly to the new url. This isn't urgent, since it's working for users
now, but we ought to clean it up. We can do this after all issues from the
migration audit are resolved, since they might affect a handful of items
that need updates for their handles.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243
