### ISSUE TITLE
Import download stats from old ERA to Google Analytics for HydraNorth

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#529]
Download data must be migrated from MySQL table into Google Analytics, so that it can drive the analytics display for migrated items.

- [Migration](https://support.google.com/analytics/answer/3191589?hl=en)

Are there other implications for GA of our re-using the era.library domain that we should consider? 

We could filter by bots (since the db contains the user agent) but this has communication implications (since download numbers will drop).

We know that import is easy; export from mysql should only be difficult if we do the bot filtering.

We will not attempt to migrate old ERA's Google Analytics data to match new ERA urls.

- [ ] test bot filtering
- [ ] determine the effect on download numbers of bot filtering, decide whether to implement
- [ ] determine whether information about the service change needs to be incorporated into the analytics display (e.g. "Data before Sept. 2015 was collected by a different method")
- [ ] import the data at migration time

**Comment by pbinkley** [comment]
The data from old ERA is in the ```download``` table of the ```era``` db. Rows look like this:

```
# id, pid, collection_pids, downloaded_date, user_id, ds_id, ip, user_agent
'141012', 'uuid:a7f11b6e-3140-47b8-a50e-9a60cd25eb54', 'uuid:39331f1f-769d-4c2a-a103-416c285d01fc,uuid:7af76c0f-61d6-4ebc-a2aa-79c125480269', '2011-09-07 12:52:21', '0', 'DS1', '<ip address>', 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)'
```
Note that user_agent is null before 2011-09-07. Starting 2013-08-26 we have another table, ```download_notcounted```, containing downloads by harvesting scripts.

**Comment by pbinkley** [comment]
See also #210

**Comment by pbinkley** [comment]
Note that sufia reports page views and downloads, but our legacy data only only covers downloads (and that's all that old ERA presented to users). The main requirement is to display the downloads going back as far as the old ERA data goes. We'll display page views starting from the HydraNorth migration, with explanatory wording to be supplied by @sfbetz once we have a chance to see how it looks.

**Comment by sfbetz** [comment]
And a few items to test with (from concerned users):

https://era.library.ualberta.ca/files/kd17ct370#.Vi6reBCrSL4
https://era.library.ualberta.ca/files/6108vb631#.Vi6rwxCrSL4
https://era.library.ualberta.ca/files/pv63g0413#.Vi6sOxCrSL4

**Comment by pbinkley** [comment]
On further investigation, it turns out that we cannot import old download events into Google Analytics. Drat. We will therefore tackle the problem this way:
- [ ] generate a total download count from old ERA, associated with the item uuid. This count is now static: no more downloads from old ERA will be counted. (The only ones that will happen now will be associated with thesis processing)
- [ ] map that to the item identifier in HydraNorth
- [ ] display it with the Sufia analytics graph, with wording such as "Downloads before October 2015: 213"
We'll give the display more attention. Options include:
- [ ] make sure the graph begins with October 2015, i.e. doesn't start with a long flat line
- [ ] present a combined count (sum of old ERA and new ERA downloads)

**Comment by pbinkley** [comment]
- [ ]  add the dates with 0 downloads to the legacy data, so that the graph will go down to zero
- [ ] add start date  to production config, so that the new GA data starts on that date
- [ ] extract old page views data from GA, map to new ids, use to populate the views line of the graph

**Comment by criedlberger** [comment]
@sfbetz, when you have a chance can you provide the wording changes.

**Comment by pbinkley** [comment]
That looks good. There's a typo in the Pageviews definition: "visitors have
viewed of an item page". And I would say "Pageviews is the number of
times", but I'm not sure I can defend it grammatically. But I can call my
wife the grammar nazi if anyone disagrees with me. How about this: in this
context, "Pageviews" is the label for the line (singular) on the graph; if
we mean individual viewing events (plural), we'd have to say "Pageviews are
times when visitors have viewed..." Maybe that "of" in the definition is
evidence that you changed from one approach to the other?

Peter



Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by sfbetz** [comment]
Yep. I had exactly the same debate in my head. Sigh. How about:

*A pageview is counted each time a visitor views an item page in ERA. Pageviews  may include multiple views by a single visitor. Pageviews were not collected prior to Sept 2011.

**A download is counted each time a visitor clicks the download link. For more information about ERA analytics, please contact erahelp@ualberta.ca.

**Comment by pbinkley** [comment]
I like it. Nice and clear, and concise.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by gsharder** [comment]
I agree. Good work.

On Wed, Nov 18, 2015 at 3:29 PM, Peter Binkley <notifications@github.com>
wrote:

> I like it. Nice and clear, and concise.
>
> Peter
>
> Peter Binkley, Ph.D., MLIS
> Digital Initiatives Technology Librarian
> Information Technology Services
> peter.binkley@ualberta.ca
>
> 2-10K Cameron Library
> University of Alberta
> Edmonton, Alberta
> Canada T6G 2J8
>
> phone 780-492-3743
> fax 780-492-9243
>
> On 18 November 2015 at 15:10, Sonya Betz <notifications@github.com> wrote:
>
> > Yep. I had exactly the same debate in my head. Sigh. How about:
> >
> > *A pageview is counted each time a visitor views an item page in ERA.
> > Pageviews may include multiple views by a single visitor. Pageviews were
> > not collected prior to Sept 2011.
> >
> > **A download is counted each time a visitor clicks the download link. For
> > more information about ERA analytics, please contact erahelp@ualberta.ca
> .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/529#issuecomment-157880869
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/529#issuecomment-157885564>
> .
>



-- 
Geoff Harder
Associate University Librarian
Information Resources and Digital Initiatives

University of Alberta Libraries
2-10H Cameron Library, University of Alberta
Edmonton, AB, Canada T6G 2J8
780.492.7914

*geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
library.ualberta.ca <http://library.ualberta.ca>*

**Comment by weiweishi** [comment]
:+1:
