### ISSUE TITLE
Migration: purge deleted items from old ERA that are not to be migrated

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#530]
There are many old test items that should be purged so they don't create issues in the migration. @sfarnel and @awakaruk have discussed them.

A number of items need to be fixed before they can be dealt with. @anayram has prepared lists.

- [x] items with ill-formed XML (needs to be fixed at foxml level)
- [x] items with double-nested XML (need to be fixed at datastream level)
- [x] items with mismatched datastream version attributes (need to be fixed at foxml level)

**Comment by anayram** [comment]
Fixed both in transformed foxml and preserved version of migrated items. (See https://github.com/ualbertalib/metadata/blob/master/stylesheets/ERA_DCQ_migration.xsl)
