### ISSUE TITLE
Add datepicker to embargo date field

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#533]
Add jquery-ui datepicker to embargo date field in permissions section of generic-file editing form. Split off from #501 
- [ ] put jquery-ui-datepicker.js in vendor/javascripts/assets/jquery-ui-1.9.2
- [ ] add script:

```
 $(function() {
    $( "#embargo_release_date" ).datepicker(
       {"dateFormat": "yy-mm-dd"} );
  });
```

Note: need to make form select Embargo option when date field is changed.

**Comment by sfbetz** [comment]
Datepicker fetaure has been built into in Sufia 7.2
