### ISSUE TITLE
Add 'Bounding Box' field to metadata display

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#543]
This is an example of a record with a bounding box value.

https://plano.library.ualberta.ca/files/bv73j1005#.VbvcOMBVhBc

**Comment by johnhuck** [comment]
Bounding box was metadata I imagined we would want to display, but that was before we launched and got to play with the system. I'm going to go out on a limb now (a very short one) and suggest that ERA users are not going to find a text-string of coordinate values all that useful for discovery.

The feature that would make that metadata useful is something like a map for searching, which is a much larger piece.

I'll maintain the coordinates in the metadata so they'll be there for future uses, but otherwise would recommend not attempting to display this field.

@sfbetz, if you agree I would invite you to close this ticket. thanks.

**Comment by sfarnel** [comment]
this will be more useful in future once we start to incorporate Peel maps.

On Tue, Feb 23, 2016 at 11:14 AM, johnhuck <notifications@github.com> wrote:

> Bounding box was metadata I imagined we would want to display, but that
> was before we launched and got to play with the system. I'm going to go out
> on a limb now (a very short one) and suggest that ERA users are not going
> to find a text-string of coordinate values all that useful for discovery.
>
> The feature that would make that metadata useful is something like a map
> for searching, which is a much larger piece.
>
> I'll maintain the coordinates in the metadata so they'll be there for
> future uses, but otherwise would recommend not attempting to display this
> field.
>
> @sfbetz <https://github.com/sfbetz>, if you agree I would invite you to
> close this ticket. thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/543#issuecomment-187824895>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by gsharder** [comment]
In addition to Peel maps, another use case might be users who wish to do
some geo-based data analysis using our record set(s). I agree though with
John that display of the coordinates is at this point a low priority.

Geoffrey Harder
Associate University Librarian
University of Alberta

Sent from mobile device

On Feb 23, 2016, at 12:11 PM, Sharon Farnel <notifications@github.com>
wrote:

this will be more useful in future once we start to incorporate Peel maps.

On Tue, Feb 23, 2016 at 11:14 AM, johnhuck <notifications@github.com> wrote:

> Bounding box was metadata I imagined we would want to display, but that
> was before we launched and got to play with the system. I'm going to go
out
> on a limb now (a very short one) and suggest that ERA users are not going
> to find a text-string of coordinate values all that useful for discovery.
>
> The feature that would make that metadata useful is something like a map
> for searching, which is a much larger piece.
>
> I'll maintain the coordinates in the metadata so they'll be there for
> future uses, but otherwise would recommend not attempting to display this
> field.
>
> @sfbetz <https://github.com/sfbetz>, if you agree I would invite you to
> close this ticket. thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/ualbertalib/HydraNorth/issues/543#issuecomment-187824895>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/543#issuecomment-187845694>
.
