### ISSUE TITLE
'Open Access' label on Dataverse items

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#545]
This label appears on many (all?) items imported from Dataverse. If, for normal Hydra items, this label is displaying a status chosen by depositors, I'm not sure it should be applied by default to Dataverse items. Is the label being displayed for some other reason?

There are probably broader questions about harmonizing these types of designations between the two systems to look at farther down the road.

**Comment by weiweishi** [comment]
We have to assign an access level to the objects as it's not only a
required field, but drives the access control for the objects. What types
of access control do Dataverse items have? Is it possible to map them in
the metadata if they are different from one another?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by wyman10** [comment]
The access to the files is controlled via the permissions tab were a user can select from a drop down list if a file is public or restricted. All one can do in the metadata section is note terms of use. Today at the sprint review I really liked how an ERA depositor could select various access options. In dataverse on the other hand it is limited at the file level to public or restricted. This allows a user to restrict some files and leave others public (readme).

**Comment by johnhuck** [comment]
Thanks, Weiwei. Taking a closer look at the Hydra Permissions options, I see that open access in Hydra means anyone can read and download. We only get metadata for studies that have been released, so the 'read' portion of open access fits. And as Larry says, the ability to download will vary from file to file within the same study, whereas our metadata corresponds to the study as a whole. So maybe we can let this sleeping dog lie undisturbed.

The reason I brought it up was because I noticed other items in the soft-launch Era that did not have the Open Access label (or any label like that), so I thought it was perhaps optional.

**Comment by johnhuck** [comment]
For reference, here's an example of a study with a file that's restricted:

http://dx.doi.org/10.7939/DVN/10039 

In the DDI, each file is captured in an &lt;otherMat> element, and it's possible that the restricted status is reflected in a note in that element: 
&lt;notes type="LOCKSS:CRAWLING" level="file" subject="LOCKSS Permission">restricted&lt;/notes>

So looking down the road, it may be possible to improve the situation by, for instance, changing the label for any study that contains only restricted files. But this status may change over time if new files are added, and restricted in Dataverse doesn't exactly equate with the available Hydra permissions: e.g, it's not exactly private, because a user can request access.

@weiweishi , I'll let you decide whether we can close this. Thanks for answering the question.
