### ISSUE TITLE
Service Migration: Thesis deposit interface

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#550]
Old ERA becomes simply a thesis deposit and workflow engine.

 Review with Anna after the 10th.

- [ ] change domain name from era.library to thesisdeposit.library...
- [x] remove Home, Browse, Communities and Researchers tabs, and search box
- [x] deposit will point to thesis submission form
- [x] Get Help points to new FAQ
- [x] New wording for Contact Us page
- [x] My Account: keep: My Saved Items, My Pending Items, My Information, Change Password - we think that approved thesis will show up under My Items, but this needs confirmation 
[edit] confirmed with Anna - approved theses show up under "My Items" so we should keep that item in the menu.
- [x] Review email templates: @piyapongch will send to @sfbetz - will flag any changes
- [x] Footer: Remove Policies column, remove search and browse under quicklinks column
- [x] robots.txt: block all spiders; remove Google sitemap
- [ ] Remove Google Analytics
- [ ] Link to thesis deposit interface from HydraNorth (add issue there)
- [x] Make sure that non-thesis items do not appear in My Items (delete from Solr if necessary)
- [ ] Handles created when items come out of embargo
- [ ] Daily migration of new user accounts to HydraNorth (new ERA)
- [ ] Determine how to delay notification email when an item comes out of embargo, so that a user does not receive a notification with a handle that doesn't work yet (because the item hasn't been migrated yet) - send notification from Hydra based on import event? - this would be reusable for Alfresco imports.

**Comment by awakaruk** [comment]
- add notice and redirect from Hydra ERA page to thesis deposit page: "Need to deposit your thesis?"
- review email templates within erahelp@ualberta.ca (Anna Bombak) 
- inform FGSR of changes @sfbetz / Anna Bombak

**Comment by sfbetz** [comment]
I've reviewed email templates - I have some questions and comments in Google doc here: https://docs.google.com/document/d/1uZm_hq0VIx5q5cAL0P0DQKP91RcS_FiY4np25DxJ2hs/edit?usp=sharing

Needs review with Anna Bomback

**Comment by sfbetz** [comment]
Question:
What url makes more sense?
thesisdeposit.library.ualberta.ca OR thesissubmission.library.ualberta.ca (I'm partial to the former)

**Comment by sfarnel** [comment]
+1 on thesisdeposit.library.ualberta.ca

On Mon, Aug 10, 2015 at 11:49 AM, Sonya Betz <notifications@github.com>
wrote:

> Question:
> What url makes more sense?
> thesisdeposit.library.ualberta.ca OR thesissubmission.library.ualberta.ca
> (I'm partial to the former)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-129547002>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by awakaruk** [comment]
Ditto - prefer the first url.

Amanda

**Comment by sfbetz** [comment]
Suggested visuals for changes we discussed (already reviewed with Anna B). 

Menu:

![thesis deposit menu](https://cloud.githubusercontent.com/assets/12801010/9179492/2f4cc4d0-3f5a-11e5-87ad-dc00258a164e.png)

Footer:

![era footer](https://cloud.githubusercontent.com/assets/12801010/9179516/679ae86c-3f5a-11e5-843a-a0b117a18f8f.png)

My ERA page:

![my era](https://cloud.githubusercontent.com/assets/12801010/9179519/6f21fa9e-3f5a-11e5-81f8-441deab491aa.png)

Get Help page:

![era help page](https://cloud.githubusercontent.com/assets/12801010/9179533/8c390c80-3f5a-11e5-852a-b9065f69d578.png)

**Comment by piyapongch** [comment]
Can you give me the links that you want to put in the footer (names and URLs)?

**Comment by piyapongch** [comment]
ERA Modifications
* Public Interface
  * [x] Add wording, Thesis Submission to logo image.
  * [x] Remove my cart from my era menu bar.
  * [x] Remove Browse, Communities, Researchers and Contact Us from navigator bar.
  * [x] Move Get Help to man section of navigator bar and point to Contact Us page.
  * [x] Change Contact Us page header to Get Help.
  * [x] Remove Policies and Get Help columns from page footer.
  * [x] Remove Browse and Search from page footer.
  * [x] Change Deposit link on page footer to Deposit a Thesis and pointing to thesis submission form.
  * [x] Change Get Help to Contact Us page.
  * [ ] Modify University of Alberta links on page footer.
  * [ ] Change wording on home page.
* My ERA
  * [ ] Remove My Subscriptions, My Favourites and My Public Profile from My ERA page and popup menu.
  * [ ] Remove add to cart and share button from view item page.
  * [ ] Remove non-thesis items from My Items page.
* Scheduler
  * [ ] Remove email from embargoed item publisher process.
* Configurations
  * [ ] Remove webbots
  * [ ] Remove Google Analytics.
  * [ ] Modify email templates
  * [ ] Change domain name.

**Comment by piyapongch** [comment]
I need the home page on ERA because many pages refer to it. If we remove it, those page will be broken. We can change the wording on the home page and not showing number of items.

**Comment by piyapongch** [comment]
I think I will remove an email from embargoed publishing process when the embargo expired. The email can be include in daily migration process after it has been migrated to HydraNorth. The process should also modified the handle pointing to the item on HydraNorth instead.

**Comment by sfbetz** [comment]
We can remove the entire U of A footer section. Most of the links are broken and not pointing to useful services. Thanks!

**Comment by sfbetz** [comment]
Here is the language for the new Get Help page (formerly Contact Us)

https://docs.google.com/document/d/1ek5Ot4K4Bt3gG0bzdKIF6A59odXwoNEchV_VxykNUlI/edit

**Comment by piyapongch** [comment]
I think we should have a link back to HydraNorth home page for user to return back to main public interface. The link might be on the navigator bar.

**Comment by piyapongch** [comment]
Configuration Changes
* /exposrt/digital/era/conf/applicaiton.properties
  * http.server.url		= https://thesissubmission.library.ualberta.ca   // new domain name
  * https.server.url 	= https://thesissubmission.library.ualberta.ca   // new domain name
  * subscription.enabled 	= false   // turn of subscription email
  * google.analytics.id	= UA-26026113-1	// new id for thesis submission stats

**Comment by piyapongch** [comment]
I will leave search box for admin user. I think this should be useful for admin and metadata team to find and investigate a problem on thesis and old items.

**Comment by piyapongch** [comment]
Admin user still can navigate to browse, community and researcher pages by URL.

**Comment by piyapongch** [comment]
I have created a new contact us page for Get Help tab. I have added a comment on Google Docs.

**Comment by piyapongch** [comment]
I have deploy the ERA thesis submission application on Walsall. You can try it at http://walsall.library.ualberta.ca. Let me know if you have any problem, question or comment. I also need a new Google Analytics ID for ERA thesis submission application. 

Peter: Can you register and give the ID to me to update on Walsall?

**Comment by pbinkley** [comment]
Thanks, Piyapong. The GA id will be UA-26026113-2 . It applies to the
domain https://thesisdeposit.library.ualberta.ca, but you can add it now
and it will start collecting data when we deploy it in production.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by piyapongch** [comment]
I have update the ID on Walsall. It will be collecting data when we migrate to new domain.

**Comment by sfbetz** [comment]
-Language on registration page /public/register needs to be updated:

Register to use ERA: Thesis Deposit
[delete: Registration will allow you to use ...]

-All links in body (below anchor links) of Get Help page public/home/contactUS are pointing to self public/home/contactUS#

**Comment by sfbetz** [comment]
Hokay,

New homepage
![home](https://cloud.githubusercontent.com/assets/12801010/9508891/3fd2d29e-4c17-11e5-96eb-896bcd41f256.png)

Language for the content:
col 1:

Before depositing your thesis, please review the Faculty of Graduate Studies and Research  <a href="https://uofa.ualberta.ca/graduate-studies/current-students/academic-requirements/thesis-requirement-and-preparation">Thesis Requirement and Preparation</a>  information.

Register [/public/register] to create an account and start your deposit.

For more information about thesis policies and procedures, please contact FGSR. [https://uofa.ualberta.ca/graduate-studies/about/contact-us]

For technical assistance with your deposit please contact erahelp@ualberta.ca / 780.492.4359

**Comment by sfbetz** [comment]
New language for registration page
![registration](https://cloud.githubusercontent.com/assets/12801010/9508991/19757d8a-4c18-11e5-9075-9aadecd3a83d.png)

**Comment by sfbetz** [comment]
New language for login
![login](https://cloud.githubusercontent.com/assets/12801010/9509011/4d4efde8-4c18-11e5-9317-d69ee6a90082.png)

**Comment by piyapongch** [comment]
There are many places using ERA and/or Education and Research Archive: email subject headings, email templates, contact as page and some description wordings. Do we want to replace those? I have share share some of those on Google Drive. Please review and let me know.

**Comment by piyapongch** [comment]
Putting home page behind login is a much more complicated than I have expected, but I can be done. I will need some time to figure it out and test the application to make sure that is working properly.

**Comment by pbinkley** [comment]
We want to change the name of the application to Thesis Deposit, so this
should replace ERA wherever it occurs. The only exception would be in new
wording informing users that their theses will move to new ERA when they
come out of embargo. I'm not sure whether Sonya has asked to have wording
like this added to the deposit form or elsewhere.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
Let's take the very shortest route to a solution. I'd be happy with just
adding a 'Log In" tab to the yellow bar. Since work on putting the home
page behind login is already done, let's test it and put it to bed as
quickly as possible.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by gsharder** [comment]
I agree with Peter's suggestion. Let's keep the time investment to a bare
minimum and go with a Log In tab.

On Thu, Aug 27, 2015 at 11:53 AM, Peter Binkley <notifications@github.com>
wrote:

> Let's take the very shortest route to a solution. I'd be happy with just
> adding a 'Log In" tab to the yellow bar. Since work on putting the home
> page behind login is already done, let's test it and put it to bed as
> quickly as possible.
>
> Peter Binkley, Ph.D., MLIS
> Digital Initiatives Technology Librarian
> Information Technology Services
> peter.binkley@ualberta.ca
>
> 2-10K Cameron Library
> University of Alberta
> Edmonton, Alberta
> Canada T6G 2J8
>
> phone 780-492-3743
> fax 780-492-9243
>
> On 27 August 2015 at 11:42, Piyapong Charoenwattana <
> notifications@github.com> wrote:
>
> > Putting home page behind login is a much more complicated than I have
> > expected, but I can be done. I will need some time to figure it out and
> > test the application to make sure that is working properly.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-135503668
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-135506325>
> .
>



-- 
Geoff Harder
Associate University Librarian
Information Resources and Digital Initiatives






*University of Alberta Libraries2-10H Cameron Library, University of
AlbertaEdmonton, AB, Canada T6G 2J8  780.492.7914
 geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
library.ualberta.ca <http://library.ualberta.ca>*

**Comment by piyapongch** [comment]
I updated the era-test server on last Friday. Please try it.

**Comment by sfarnel** [comment]
In email depositor receives when thesis needs revision, text should mention
'my account' rather than 'myERA'.

[image: Inline image 1]

On Mon, Aug 31, 2015 at 9:35 AM, Piyapong Charoenwattana <
notifications@github.com> wrote:

> I updated the era-test server on last Friday. Please try it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-136408408>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
Message on successful thesis submission still has link to old help pages in
Libguides and therefore throws 404 error; needs to be updated.

[image: Inline image 1]

On Mon, Aug 31, 2015 at 12:52 PM, Sharon Farnel <sharon.farnel@ualberta.ca>
wrote:

> In email depositor receives when thesis needs revision, text should
> mention 'my account' rather than 'myERA'.
>
> [image: Inline image 1]
>
> On Mon, Aug 31, 2015 at 9:35 AM, Piyapong Charoenwattana <
> notifications@github.com> wrote:
>
>> I updated the era-test server on last Friday. Please try it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-136408408>
>> .
>>
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
When thesis is archived, message does not include handle for item, but the
email confirmation does.

[image: Inline image 1]

[image: Inline image 2]



On Mon, Aug 31, 2015 at 12:54 PM, Sharon Farnel <sharon.farnel@ualberta.ca>
wrote:

> Message on successful thesis submission still has link to old help pages
> in Libguides and therefore throws 404 error; needs to be updated.
>
> [image: Inline image 1]
>
> On Mon, Aug 31, 2015 at 12:52 PM, Sharon Farnel <sharon.farnel@ualberta.ca
> > wrote:
>
>> In email depositor receives when thesis needs revision, text should
>> mention 'my account' rather than 'myERA'.
>>
>> [image: Inline image 1]
>>
>> On Mon, Aug 31, 2015 at 9:35 AM, Piyapong Charoenwattana <
>> notifications@github.com> wrote:
>>
>>> I updated the era-test server on last Friday. Please try it.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-136408408>
>>> .
>>>
>>
>>
>>
>> --
>> Sharon Farnel
>> Metadata Coordinator
>> University of Alberta Libraries
>> sharon.farnel@ualberta.ca
>> 780-492-3685
>>
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
When logged in as a reviewer, clicking on Restricted Access Items under My
Account shows zero results. Reviewers need to be able to see embargoed
theses.

[image: Inline image 1]

On Mon, Aug 31, 2015 at 12:56 PM, Sharon Farnel <sharon.farnel@ualberta.ca>
wrote:

> When thesis is archived, message does not include handle for item, but the
> email confirmation does.
>
> [image: Inline image 1]
>
> [image: Inline image 2]
>
>
>
> On Mon, Aug 31, 2015 at 12:54 PM, Sharon Farnel <sharon.farnel@ualberta.ca
> > wrote:
>
>> Message on successful thesis submission still has link to old help pages
>> in Libguides and therefore throws 404 error; needs to be updated.
>>
>> [image: Inline image 1]
>>
>> On Mon, Aug 31, 2015 at 12:52 PM, Sharon Farnel <
>> sharon.farnel@ualberta.ca> wrote:
>>
>>> In email depositor receives when thesis needs revision, text should
>>> mention 'my account' rather than 'myERA'.
>>>
>>> [image: Inline image 1]
>>>
>>> On Mon, Aug 31, 2015 at 9:35 AM, Piyapong Charoenwattana <
>>> notifications@github.com> wrote:
>>>
>>>> I updated the era-test server on last Friday. Please try it.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-136408408>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> Sharon Farnel
>>> Metadata Coordinator
>>> University of Alberta Libraries
>>> sharon.farnel@ualberta.ca
>>> 780-492-3685
>>>
>>
>>
>>
>> --
>> Sharon Farnel
>> Metadata Coordinator
>> University of Alberta Libraries
>> sharon.farnel@ualberta.ca
>> 780-492-3685
>>
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfbetz** [comment]
@piyapongch  - can you share text for all email templates via google drive? I can review all at once and make sure we get everything.

**Comment by sfbetz** [comment]
@sfarnel currently reviewers can't see theses once they've been approved and are under embargo.  Admin has to go in at request of FGSR to remove additional files, etc.

**Comment by sfarnel** [comment]
ah, ok; no worries then!

Sent from my iPhone

On Aug 31, 2015, at 3:13 PM, Sonya Betz <notifications@github.com> wrote:

@sfarnel <https://github.com/sfarnel> currently reviewers can't see theses
once they've been approved and are under embargo. Admin has to go in at
request of FGSR to remove additional files, etc.

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-136502584>
.

**Comment by sfarnel** [comment]
maybe then remive that option from under 'my account'?

Sent from my iPhone

On Aug 31, 2015, at 3:40 PM, Sharon Farnel <sbalazs@ualberta.ca> wrote:

ah, ok; no worries then!

Sent from my iPhone

On Aug 31, 2015, at 3:13 PM, Sonya Betz <notifications@github.com> wrote:

@sfarnel <https://github.com/sfarnel> currently reviewers can't see theses
once they've been approved and are under embargo. Admin has to go in at
request of FGSR to remove additional files, etc.

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-136502584>
.

**Comment by sfbetz** [comment]
Makes sense to me!

**Comment by pbinkley** [comment]
This should be low priority, though, since only FGSR staff are affected,
and they're familiar with the workflow in old ERA.

**Comment by sfarnel** [comment]
that seems reasonable

Sent from my iPhone

On Aug 31, 2015, at 4:39 PM, Peter Binkley <notifications@github.com> wrote:

This should be low priority, though, since only FGSR staff are affected,
and they're familiar with the workflow in old ERA.



On 31 August 2015 at 16:05, Sonya Betz <notifications@github.com> wrote:

> Makes sense to me!
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-136513802>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/550#issuecomment-136519466>
.

**Comment by sfbetz** [comment]
All email templates and subjects have been reviewed and updated. See https://drive.google.com/open?id=0B86QgxUJ28ueMXZ2aVQ5aUNpclE

**Comment by sfbetz** [comment]
Front page requires correction in rh column. Pointing users to Thesis Deposit for *submitted* theses - but should point users to ERA, where theses are archived. Language in column should read:

Looking for a thesis that has already been submitted?

Visit era.library.ualberta.ca for theses and dissertations by graduate students of the University of Alberta. Theses will be released each year on June 15 for Spring Convocation and November 15 for Fall Convocation.

**Comment by piyapongch** [comment]
I have updated email templates and deployed on Walsall.

**Comment by sfbetz** [comment]
Thanks @piyapongch . Can you confirm also that the following work has been done based on above comments?
[ ] Front page requires correction in rh column. Pointing users to Thesis Deposit for submitted theses - but should point users to ERA, where theses are archived. 
[ ] Message on successful thesis submission still has link to old help pages in Libguides and therefore throws 404 error; needs to be updated to new Help / FAQ / contact us page

**Comment by piyapongch** [comment]
I have updated those item and re-deployed the latest version on Wallsal. You can check them when you have a change. 

The server will be updated back to production version when I finish fixing broken links.

**Comment by pbinkley** [comment]
Since Sonya will be away next week, and the changes that we need to her to check are so small, I think we should close this story. If Sonya discovers any problems we can open bugs to deal with them.
