### ISSUE TITLE
Create Links to Thesis Submission Form

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/HydraNorth#558]
* [ ] Create a link on home page pointing to new thesis submission form, https://${domain.name}/submit/thesis.
* [ ] Create a link on main navigator bar.

**Comment by sfbetz** [comment]
We haven't any comments from users on being unable to find Thesis Deposit tool - I think our help info and FGSR's guide is directing users sufficiently and that this link is not necessary.  Closing.
