### ISSUE TITLE
Refactoring view/presenter logic

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#567]
There's a lot of logic that appears to have crept into the views. Over time, this can become a major source of technical debt, as the view begins to take on more and more responsibilities that should be centralized in presenters and controllers. In general, view logic can be considered a code smell -- the more you see of it, the smellier the view is.

A motivating example is found in app/views/records/show_fields/_license.html.erb

``` ruby
<% unless record.license.nil? %>
  <% if Sufia.config.cc_licenses.has_key?(record.license) %>
    <%=link_to_field('license',record.license, Sufia.config.cc_licenses_reverse[record.license])%> <%= iconify_auto_link(record.license,false) if linkable?(record.license)%><br />
  <% else %>
    <%=link_to_field('license',record.license, record.license)%><br />
  <% end %>
<% end %>
```

ideally, we'd like to bring this logic back into the presenter (which in this case is the record object above) with something like this untested pseudo-code:

``` ruby
.....
def license
  return unless license.nil?
  if Sufia.config.cc_licenses.has_key?(license)
    capture do
      concat link_to_field('license',license, Sufia.config.cc_licenses_reverse[license])
      concat(iconify_auto_link(license,false)) if linkable?(license)
    end
  else
    link_to_field('license',license, license)
  end
end
```

and reduce the view to simply:

``` ruby
<%= record.license %>
```

The only complicating factor here is that any of the records/\* partials are shared between several different presenters, each of which would have to implement its own copy of the license logic. To further clean this up, we would need to introduce a BasePresenter-type object from which GenericFilePresenter, ThesisPresenter, etc would have to inherit to share this logic.

**Comment by weiweishi** [comment]
Great point. Batch upload form also contains a tons of smelly logics, and
would require some thinking to move the logic elsewhere.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
