### ISSUE TITLE
OAI service

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#570]
define and implement refinements needed for our OAI service
- depends on Fedora 4.2 upgrade #293 
- requires follow-up with Piyapong on remaining work needed for Fedora 4.2
- requires ability to reassemble an ETDMS record from our current RDF #105 and possibly other metadata work

See @piyapongch 's Google Doc (link in comment below)

**Comment by piyapongch** [comment]
Here is the Fedora4 OAI Provider note, https://docs.google.com/document/d/1uRwIGY0Duoo4dyz6Xk6Rq0t19XdRkZ0DLPW-v4Oi9Vk/edit?usp=sharing. Please scroll to OAI-PMH Provider section. The notes based on Fedora 4.1.

**Comment by sfarnel** [comment]
F4 oai-provider out of the box supports oai_dc but we can add additional formats via oai.xml, which we will need for theses (which have to be etdms). We can work backwards from examples and the schema and referencing LAC harvest documentation (http://www.bac-lac.gc.ca/eng/services/theses/Pages/harvesting.aspx).

**Comment by pbinkley** [comment]
Broken into subissues
