### ISSUE TITLE
Collection page sometimes does not display all contained items

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#586]
E.g. in current plano: http://plano.library.ualberta.ca/collections/th83kz412 says "total items: 5", but only displays one. Not sure if this is a migration problem or a display problem.
![ccicollection](https://cloud.githubusercontent.com/assets/272816/9646222/ca666818-518e-11e5-8f7f-2d9c5f6877b3.png)

**Comment by mbarnett** [comment]
It appears that at least one issue playing into this is that the "Total Items" count is absolute and irrespective of the current user's permissions. ie) if a collection contains a "private" item, that item is included in the count even though no one other than the owner can see it.

I'm investigating possible ways of making the presenter aware of the user's visibility.

**Comment by pbinkley** [comment]
This would be a nice feature to contribute back to Sufia if it can be done
without adding much to the work - now's not the time to take on extra, so
the contribution might have to be post-launch refactoring.

**Comment by mbarnett** [comment]
Good point; worth keeping in mind as I figure out what the solution should look like for the time being, anyways.
