### ISSUE TITLE
Description field in migrated items contains escapes

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#590]
e.g. in current plano: http://plano.library.ualberta.ca/files/v118rd73x#.VehlrbMy3mE

![escapes](https://cloud.githubusercontent.com/assets/272816/9662679/baaf9216-521d-11e5-8d76-6ca64a05b543.png)

**Comment by pbinkley** [comment]
@weiweishi , the backslash before a double-quote in the description field is inserted by the first gsub in this line: https://github.com/ualbertalib/HydraNorth/blob/master/lib/tasks/migration.rake#L239 . I've tried removing it, and I don't encounter any problems. Other fields that sometimes contain double-quotes, such as title, don't have this gsub. Do you recall a reason why this gsub needs to be there for the description field? If not, I'll remove it.

**Comment by weiweishi** [comment]
I think it was put into place as when the text contains double-quotes, it
would treat the double-quotes as the string terminator, and possibly break
this
<https://github.com/ualbertalib/HydraNorth/blob/master/lib/tasks/migration.rake#L490>?
There ought to be a better way to deal with single-quotes and double-quotes
in strings.



*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pbinkley** [comment]
It looks to me like we're safe without it: rake is escaping the double-quotes for us. I've tried this:

```<dcterms:description>This is the "description". This follows the last double-quote.</dcterms:description>```

and it comes out as this:

``` "description"=>["This is the \"description\". This follows the last double-quote."],```

So I think I'll go ahead and remove it.

**Comment by pbinkley** [comment]
Done
