### ISSUE TITLE
Fix malformed XML in some batch-ingested FOXML in old ERA

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#595]
After Henry gives us a fresh dump of the complete ERA FOXML, we'll have to fix the items that Mariana has identified (see lists in https://drive.google.com/drive/folders/0Bx9c8G8_FeK5OTNwN3FDZERpYTg ). Rather than attempt to reinsert them into Fedora (with the risk that something will go wrong and cause downtime before the thesis deadline), we'll simply use the fixed FOXML in the migration. The migration script will have to be adjusted to reflect this (i.e. to avoid fetching the current FOXML from ERA, or to handle the error message that it will get if it tries).

**Comment by pbinkley** [comment]
Migration script needs to catch up with this.

**Comment by pbinkley** [comment]
Closed by #645

**Comment by pgwillia** [comment]
Reopened by #646
