### ISSUE TITLE
Wrong Twitter handle in twitter:card metadata

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#605]
Embedded metadata includes:

```
<!-- Twitter card metadata -->
  <meta name="twitter:card" content="product">
  <meta name="twitter:site" content="@HydraSphere"/>
  <meta name="twitter:creator" content="@HydraSphere"/>
```

We should suppress this, or create a twitter account for ERA to use here ( @sfbetz ?)

(Tested on plano)

**Comment by sfbetz** [comment]
I think it would be good to use the libraries' twitter handle here - I
think the library communications people are moving towards a more unified
approach to social media management (and it means we don't need somebody to
manage a dead twitter account). I can broach with communications committee?

On Mon, Sep 14, 2015 at 5:15 PM, Peter Binkley <notifications@github.com>
wrote:

> Embedded metadata includes:
>
> 
>   <meta name="twitter:card" content="product">
>   <meta name="twitter:site" content="@HydraSphere"/>
>   <meta name="twitter:creator" content="@HydraSphere"/>
>
> We should suppress this, or create a twitter account for ERA to use here (
> @sfbetz <https://github.com/sfbetz> ?)
>
> (Tested on plano)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/605>.
>



-- 
Sonya Betz
Digital Initiatives Projects Librarian
Acting Digital Repository <http://era.library.ualberta.ca/> Services
Librarian



*University of Alberta Libraries2-10U Cameron Library, University of
AlbertaEdmonton, AB, Canada T6G 2J8  *
*sonya.betz@ualberta.ca <sfbetz@ualberta.ca> *
*780-492-1718*

**Comment by pbinkley** [comment]
The twitter handle drives [Twitter Analytics](https://dev.twitter.com/cards/analytics), which will be interesting. If you include your twitter handle in your profile, it should be inserted along with ours, in the ```twitter:creator``` field, which presumably allows user to track their items' usage on Twitter as well.
