### ISSUE TITLE
description in migrated items contain garbled characters

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#606]
![image](https://cloud.githubusercontent.com/assets/2047614/9882828/ea12c86e-5b93-11e5-90fc-3a46cba7665c.png)

**Comment by pbinkley** [comment]
This specific item is displaying correctly in HydraNorth: https://hydranorth.library.ualberta.ca/collections/44558t91d . We'll reopen if we find another instance but I think the character set issue has been resolved.
