### ISSUE TITLE
force user to update their profile after they create account/login

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#607]
To avoid showing email address on the interface, users should be forced to update their first and last name on the profile page after they create a new account, or login into the system with incomplete name information. 
Proposed:
- [ ] for new user, they will be redirected to edit_profile page first, and filled out their names before proceeding. 
- [ ] for migrated users, if they don't have first/last name in the record, they will be redirect to edit_profile page to provide information after their first login in Hydranorth 

related #189

**Comment by sfbetz** [comment]
Does this require a re-indexing job to remove email from objects and replace with user names?
- [ ] users who created an account in hydranorth after migration (post launch) should also be forced to update their first and last name on next login
