### ISSUE TITLE
Computing Science Technical Report ID not showing on full item page

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#608]
TRxx-xx is an individual property for the Comp Sci tech reports and should display on the full item page. E.g., TR06-20 (http://hdl.handle.net/10402/era.26958 in old ERA) in production (https://hydranorth.library.ualberta.ca/files/mk61sm09q#.VflxlkZSn9U):

![image](https://cloud.githubusercontent.com/assets/4697932/9906518/d197cd48-5c47-11e5-974f-9368097effc6.png)

The metadata is in the transformed FOXML:

**<ualterms:trid xsi:type="string">TR06-20</ualterms:trid>**

**Comment by sfarnel** [comment]
same in test

**Comment by sfarnel** [comment]
still seems to be the case in production; e.g.: https://hydranorth.library.ualberta.ca/files/7d278t092#.Vhh1ZqLwMiE

**Comment by weiweishi** [comment]
Hmm. I will create a rake task to delete all the items in this collection
after the migration, and verify the migration script to ensure they are
handled correctly.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
Seems that it's the namespace that has caused the issue. will further
investigate.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
Sorry, I was wrong. The information is migrated, but not presented on the
record page. I am going to create a new issue for it.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
new issue opened #713 and will be fixed with a rake task to update all resource types to Computing Science Technical Report/Structural Engineering Report.
