### ISSUE TITLE
Structural Engineering Report ID not showing in full item page

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#609]
SERxx is an individual property for the Structural Engineering reports and should display on the full item page. E.g., SER283 (http://hdl.handle.net/10402/era.17211 in old ERA) in production (https://hydranorth.library.ualberta.ca/files/mk61sx135#.Vfl4yUZSn9U):

![image](https://cloud.githubusercontent.com/assets/4697932/9907115/c50563a8-5c4a-11e5-8f81-0249a6a33abb.png)

The metadata is in the transformed FOXML:

**<ualterms:ser xsi:type="string">SER283</ualterms:ser>**

**Comment by pbinkley** [comment]
This may be an error in previous migrations which has been fixed in since these items were migrated. I'll have a look at the current status.

**Comment by sfarnel** [comment]
same in test

**Comment by sfarnel** [comment]
seems to be happening in production still; e.g. https://hydranorth.library.ualberta.ca/files/jq085j97c#.Vhh0GaLwMiE

**Comment by sfarnel** [comment]
Addressed with #713 
Closing
