### ISSUE TITLE
Link to related item not displaying on item page

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#610]
Content of link to related item (dcterms:relation) not displaying. E.g., old ERA (http://hdl.handle.net/10402/era.38628), production (https://hydranorth.library.ualberta.ca/files/mk61s1894#.VfmdMVXBzRY), test (http://keith.library.ualberta.ca/files/ft84cs39b#.VfmdDFXBzRY)

**Comment by weiweishi** [comment]
The information is not migrated over. need to be fixed as part of #715

**Comment by sfarnel** [comment]
Assuming same issue with #707 ?

On Tue, Oct 13, 2015 at 4:44 PM, Weiwei Shi <notifications@github.com>
wrote:

> The information is not migrated over. need to be fixed as part of #715
> <https://github.com/ualbertalib/HydraNorth/issues/715>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/610#issuecomment-147874728>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
Will be addressed in #715 
Closing
