### ISSUE TITLE
type of item not saving properly

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#621]
related to #516. Now the form is sending string instead of array for resource_type, data model/actor etc need to be modified to reflect the change.

**Comment by pgwillia** [comment]
I'm confused by the intention of this issue.  Issue #516 seems to ask for a language like selection of one resource type per item.  @mbarnett's solution seems to revert some of the changes made in #600 so that the resource type is multi-valued. @weiweishi could you clarify?

**Comment by mbarnett** [comment]
Re-reading all of that, I suspect have implemented backwards, bring the new form into line with the edit form instead of the edit into line with the new

**Comment by weiweishi** [comment]
The resource type should not be a multi-value property. And intention of this ticket is to correct the validation etc to make the deposit form, and the saving process accepts a single value string instead of an array. @pgwillia @mbarnett

**Comment by mbarnett** [comment]
Got it, will reimplement accordingly

**Comment by mbarnett** [comment]
There's an immense amount of code (and tests) in Hydranorth and Sufia that assumes that resource_type is an array and can be treated accordingly.

I think I might be able to create a hacky workaround in the Item forms to make this work for the time being, but if we want to fully convert the resource_type property into a single string and not an array, it's going to be a much bigger job.

**Comment by pbinkley** [comment]
We may want multiple item types in the next phase, when we start dealing with richer metadata and multiple domains, so it makes sense to me to implement this as a constraint on the form rather than a change to the model for now.

**Comment by sfarnel** [comment]
this seems a reasonable path at this point

On Tue, Sep 29, 2015 at 5:16 PM, Peter Binkley <notifications@github.com>
wrote:

> We may want multiple item types in the next phase, when we start dealing
> with richer metadata and multiple domains, so it makes sense to me to
> implement this as a constraint on the form rather than a change to the
> model for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/621#issuecomment-144218094>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
