### ISSUE TITLE
Plan sequence of migration for efficiency

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#626]
We must migrate all of current ERA content (except for recently deposited theses) between Oct. 1 and Oct. 5. We will want the migration work to run around the clock.

**Comment by johnhuck** [comment]
In order to have transformed Dataverse metadata ready for ingest alongside the migrating ERA content, an export of Dataverse metadata needs to be scheduled, perhaps on or around Oct. 1 or 2nd. I believe this will involve Piyapong and Henry's time.
