### ISSUE TITLE
Running a full RSpec permanently consumes approximately 5% of the vagrant's /var partition

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#631]
I haven't fully hunted this down yet, but the /var on our vagrants is 2 gigs in size, and every time I run rspec or rake spec I end up with about 100 megs less on the partition than before. After a number of runs of the test suite, the partition will reach 100% of capacity, at which point many things seem to go haywire.

My initial assumption is that the migration spec is downloading a lot of files and leaving them lying around afterwards, but more investigation is needed.

**Comment by mbarnett** [comment]
As far as I can tell, this comes down to binary data imported during the tests accumulating and not being deleted.

```
[root@hydranorthdev hydranorth]# du -hsx * | sort -rh | head -20
1.2G    jetty
6.9M    log
6.6M    app
4.6M    tmp
2.3M    spec
1.9M    lib
216K    config
184K    db
128K    fedora_conf
56K     spec-views
44K     solr_conf
40K     test
32K     test-metadata.zip
24K     bin
20K     public
20K     Gemfile.lock
16K     vendor
8.0K    README.md
4.0K    resque.sh
4.0K    README.rdoc
```
```
[root@hydranorthdev jetty]# du -hsx * | sort -rh | head -20
1.1G    fcrepo4-data
75M     webapps
51M     solr
51M     logs
2.1M    lib
92K     velocity.log
76K     LICENSE.txt
48K     start.jar
28K     NOTICE.txt
16K     etc
16K     contexts
12K     velocity.log.1
12K     resources
8.0K    CONTRIBUTING.md
4.0K    VERSION
4.0K    start.ini
4.0K    README.md
4.0K    jettywrapper.log
```
```
[root@hydranorthdev fcrepo4-data]# du -hsx * | sort -rh | head -20
995M    fcrepo.binary.directory
52M     fcrepo.ispn.repo.cache
2.6M    fcrepo.activemq.directory
32K     com.arjuna.ats.arjuna.objectstore.objectStoreDir
12K     com.arjuna.ats.arjuna.common.ObjectStoreEnvironmentBean.default.objectStoreDir
```

Almost half of the partition is consumed by the fcrepo.binary.directory after approximately one week of development usage.

Running:
```ruby
ActiveFedora::Base.delete_all
```
does not cause any noticeable drop in the amount of data consumed. The ```cleanup_jetty``` method also makes no difference, as it relies on the ```delete_all``` method internally.

Running:
```ruby
require 'active_fedora/cleaner'

ActiveFedora::Cleaner.clean!
```
similarly does not remove this stale binary data.

**Comment by weiweishi** [comment]
delete_all is turning fedora objects into tombstones, but I don't think if
they are actually removed. That's probably why the fcrepo4-data doesn't get
smaller.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mbarnett** [comment]
Tricia pointed me in the direction of ```rake jetty:clean``` which got my filesystem out of being 100% full, at least

**Comment by pbinkley** [comment]
Not happening any morre
