### ISSUE TITLE
Front page and footer edits

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#642]
Update footer and "What is ERA?" sections as per screenshot:

![hydrafooter](https://cloud.githubusercontent.com/assets/12801010/10204699/7d84cfce-677a-11e5-8ded-0ba82bea5eb5.png)

Language for "What is ERA?" is:
---------------------
ERA (Education and Research Archive) is the name for University of Alberta's Digital Asset Management strategy, being developed and supported by the University of Alberta Libraries [link to https://www.library.ualberta.ca/]. For more on the technology behind ERA see Technology and Partnerships [link to /about].

ERA's open access content includes the intellectual output of the University and promotes global opportunities for research discovery as well as for archival preservation. ERA also provides an easy and convenient solution for faculty who must deposit their research in an open access repository to meet funding agency requirements.

-----------------------------

Changes to images to come

**Comment by pgwillia** [comment]
The contact form refers to the FAQ. What should this say instead?

![image](https://cloud.githubusercontent.com/assets/1220762/10205211/26bd0c58-677d-11e5-9908-fbfd4c75bd69.png)

**Comment by sfbetz** [comment]
It can say "See _About ERA_ [link to http://www.library.ualberta.ca/research-support/era/] for more information."

**Comment by sfbetz** [comment]
![2015-09-30_14-10-49](https://cloud.githubusercontent.com/assets/12801010/10206091/62baa36e-6782-11e5-9fe4-104651bd0fc4.png)

For these images, image on left can stay. Description for image is accurate, but link should point to collection URL. Current handle for collection in ERA ishttp://hdl.handle.net/10402/era.14579

Image on left should be deleted and replaced with squiggly purple image from big header. Description can read:

Highlighted collection
-------
Department of Biological Sciences

The Department of Biological Sciences currently has over 70 professors, 20 adjunct professors and 20 professors emeritus, along with a graduate student population of nearly 300 and 70 departmental support staff. 

Go to collection [link to http://hdl.handle.net/10402/era.25395]

replace image on right with this one:
![2015-09-30_14-32-19](https://cloud.githubusercontent.com/assets/12801010/10206123/8e934644-6782-11e5-9ecd-ff6f1abde0e4.png)

**Comment by sfbetz** [comment]
@nnunn is removing the squiggly purple image and the birch trees image from the large header. She probably can supply this image to @pgwillia ?

**Comment by sfbetz** [comment]
And finally, remove "Beta" from above logo.

**Comment by weiweishi** [comment]
@nnunn has made some of the changes for the research profile. The page
needs to be changed is:
https://github.com/ualbertalib/HydraNorth/blob/master/app/views/layouts/homepage.html.erb
and the image path is in era.custom.css.scss

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfbetz** [comment]
Name of the purple squiggles image is slide8.jpg and it is in the assets/image folder.

**Comment by pgwillia** [comment]
![image](https://cloud.githubusercontent.com/assets/1220762/10206851/54ea8f70-6786-11e5-921d-3c1300d6303e.png)
![image](https://cloud.githubusercontent.com/assets/1220762/10206843/4cc4ec78-6786-11e5-8a8a-1e8044fb11f8.png)
