### ISSUE TITLE
Failing specs in master branch

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#649]
Failures:

- [x] 1) Hydranorth::GenericFile::Actor#update_metadata should update year_created based on date_created
     Failure/Error: actor.update_metadata({date_created:'2012/01/01'}, 'open')
     NoMethodError:
       undefined method `empty?' for nil:NilClass
     # ./app/actors/hydranorth/generic_file/actor.rb:21:in `update_metadata'
     # ./spec/actors/hydranorth/generic_files/actor_spec.rb:14:in `block (3 levels) in <top (required)>'

- [x]  2) coauthor abby shares work @ included
     Failure/Error: click_link "Permissions"
     Capybara::ElementNotFound:
       Unable to find link "Permissions"
     # ./spec/features/coauthor_spec.rb:73:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:34:in `block (3 levels) in <top (required)>'

- [x]  3) coauthor abby shares work @ not included
     Failure/Error: click_link "Permissions"
     Capybara::ElementNotFound:
       Unable to find link "Permissions"
     # ./spec/features/coauthor_spec.rb:73:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:38:in `block (3 levels) in <top (required)>'

- [x]  4) coauthor abby shares work barbara can edit and feature
     Failure/Error: click_link "Permissions"
     Capybara::ElementNotFound:
       Unable to find link "Permissions"
     # ./spec/features/coauthor_spec.rb:73:in `share_work_with'
     # ./spec/features/coauthor_spec.rb:50:in `block (3 levels) in <top (required)>'

- [x]  5) Hydranorth::Forms::GenericFileEditForm#terms should return a list
     Failure/Error: expect(subject.terms).to eq([:title, :creator, :contributor, :subject, :resource_type, :language, :identifier, :spatial, :temporal, :description, :date_created, :license, :rights, :is_version_of, :source, :related_url ])

       expected: [:title, :creator, :contributor, :subject, :resource_type, :language, :identifier, :spatial, :temporal, :description, :date_created, :license, :rights, :is_version_of, :source, :related_url]
            got: [:title, :creator, :contributor, :subject, :resource_type, :language, :identifier, :spatial, :temporal, :description, :date_created, :license, :rights, :is_version_of, :source, :related_url, :belongsToCommunity, :hasCollectionId]

       (compared using ==)

       Diff:
       @@ -13,5 +13,7 @@
         :rights,
         :is_version_of,
         :source,
       - :related_url]
       + :related_url,
       + :belongsToCommunity,
       + :hasCollectionId]
     # ./spec/forms/generic_file_edit_form_spec.rb:8:in `block (3 levels) in <top (required)>'

**Comment by pbinkley** [comment]
This will give us a chance to hone our git bisect skills!

**Comment by criedlberger** [comment]
Need to add code to delete all Collections after test is complete for the migration rake spec task

**Comment by weiweishi** [comment]
I added it in the PR #646.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
