### ISSUE TITLE
9.3.f Admin can put any file in a collection

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#65]
size:medium priority:high

Part of #32

**Comment by pgwillia** [comment]
Suggested approach: create another tab just for administrators, something like 'All Files' which has the same functionality to add files to a collection as the user that owns the file.

Suggested approach: add the ability to edit directly from the search results.

Suggested approach: add to file view the same options that the user has for adding to collections.

Leah says pick the easiest.

Gap analysis between Sufia and ERA.

**Comment by pbinkley** [comment]
Closed by #100
