### ISSUE TITLE
Strange message on new collections form page

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/HydraNorth#652]
@weiweishi and @pgwillia On the Create new collection form there is a strange message - see image. I can't figure out where this is coming from or what it means. Thoughts?

![coll](https://cloud.githubusercontent.com/assets/495318/10251591/174afd98-68ef-11e5-9356-8fb21ddad8e3.jpg)

**Comment by weiweishi** [comment]
Think maybe this relates to that the collection#new shares the same method
in batch_edit_controller, which requires user to select a group of objects
first. I can look into this.


*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfbetz** [comment]
Fixed
