### ISSUE TITLE
email from hydranorth

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#655]
@henryzhang87  I'd like to test an upload on hydranorth production (which I'm hitting as era.library.ualberta.ca). I can't log in with my CCID until SAML is working, so I tried to create an account with my home email address. I get a page saying that a confirmation email has been sent, but I haven't received it (after more than an hour - and yes, I checked my spam folder). I've just tried again, accessing hydranorth.library.ualberta.ca, and the message hasn't come through. Is there anything we need to do to the server configuration to get outgoing email working?

**Comment by pgwillia** [comment]
@mbarnett and @piyapongch both commented recently that email wasn't working on their dev environments either.  I recall this working at some point but now see that it isn't working there for me either. Wonder if a gem update might have changed how email is configured? I'm not seeing anything in the sendmail logs or queues on my hydranorthdev indicating that Hydranorth is sending any email.

**Comment by pbinkley** [comment]
Oog. This is important. I'll move this issue to the current sprint.

**Comment by pbinkley** [comment]
Tricia's looking into this in her dev environment, but @henryzhang87 if you can have a look at production that would be good. We don't want to launch without the ability to send confirmation emails.

**Comment by mbarnett** [comment]
@pgwillia By default, in Rails 4, ```config.action_mailer.perform_deliveries``` is false in Development mode, so that's probably why we don't send email locally (which is generally a good thing because you don't want to spam real users with dev emails).

In production mode it *should* be true, but it might help to set it explicitly

**Comment by pgwillia** [comment]
I confirmed that I was getting emails from the current dev configuration of HydraNorth September 15th.

**Comment by pgwillia** [comment]
Still receiving emails today to dittest@ualberta.ca but oddly not my own address.

**Comment by mbarnett** [comment]
Pull request is up
