### ISSUE TITLE
Gallery and slideshow views are available but don't work

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#656]
I'm not sure whether they are supposed to work at this point so this may be future work. But the options are there on the search results, without icons:

![bug-1](https://cloud.githubusercontent.com/assets/272816/10259289/be4c2a0c-6923-11e5-8ad2-833e1e4ba136.png)

Gallery view:

![bug-2](https://cloud.githubusercontent.com/assets/272816/10259292/c8b74ada-6923-11e5-8a49-97e2b5dfc43b.png)

Slideshow view:

![bug-3](https://cloud.githubusercontent.com/assets/272816/10259294/d0f7e9d4-6923-11e5-9ef1-85775e75d536.png)

(Note that these shots were taken before any characterization had run, so no items had thumbnails.)

**Comment by pgwillia** [comment]
Do we want to 
a) remove these options
b) fix them so that the gallery and slideshow views have icons and the features look finished

**Comment by pbinkley** [comment]
I meant to tag this for @sfbetz attention and decision. We should certainly try to fix this for Friday's release.

**Comment by sfbetz** [comment]
From my perspective the gallery and slideshow options don't add much value to the end user except for photo and image collections. My vote would be to remove those icons for now, and work on theming them nicely when we start the work on migrating peel and steele.

**Comment by pbinkley** [comment]
That makes sense to me. Let's go with Tricia's option a. It will require a
new release, so at this point we won't fix it in production before Friday.

Peter

**Comment by gsharder** [comment]
Agreed.

On Mon, Oct 5, 2015 at 9:59 AM, Peter Binkley <notifications@github.com>
wrote:

> That makes sense to me. Let's go with Tricia's option a. It will require a
> new release, so at this point we won't fix it in production before Friday.
>
> Peter
>
>
>
> On 5 October 2015 at 09:30, Sonya Betz <notifications@github.com> wrote:
>
> > From my perspective the gallery and slideshow options don't add much
> value
> > to the end user except for photo and image collections. My vote would be
> to
> > remove those icons for now, and work on theming them nicely when we start
> > the work on migrating peel and steele.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/656#issuecomment-145570583
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/656#issuecomment-145581019>
> .
>



-- 
Geoff Harder
Associate University Librarian
Information Resources and Digital Initiatives

University of Alberta Libraries
2-10H Cameron Library, University of Alberta
Edmonton, AB, Canada T6G 2J8
780.492.7914

*geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
library.ualberta.ca <http://library.ualberta.ca>*

**Comment by johnhuck** [comment]
I think this bug is still present in 1.2.0.

**Comment by pgwillia** [comment]
correct. this bug is still presetn in 1.2.0
