### ISSUE TITLE
Updated content for footer

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#657]
I've completed some content to live in the footer:

I'd like to replace the "Policies" Section with an "About" section with three pages:
About Era [should replace the current /about page] 
Policies
Technology and Partnerships 

In the Get Help section there should be two pages:
Contact Us [I've thought this through and think it might be better to provide direct contact info and not force a form fill-in here - Sorry @pgwillia for the flip flop!]
How to Deposit

Content for all of these pages can be found in DIT>Hydra>UI and Web Content > new footer content

**note that most of these pages have internal links to other pages - I didn't link in the text because had no urls!

https://drive.google.com/folderview?id=0BwXbqVc9w_ukdHE5alZoSF80X3c&usp=sharing

![2015-10-02_16-36-03](https://cloud.githubusercontent.com/assets/12801010/10259326/1b12bba2-6924-11e5-9f54-b99be44a1aa8.png)

**Comment by pbinkley** [comment]
I've added this to the current sprint, so we'll try to get it done for next Friday's deployment.

**Comment by pgwillia** [comment]
@criedlberger I just pushed a 657_footer_contact branch.  Feel free to cherry-pick my commit into your work.

@nnunn is there a nice and easy way to make https://github.com/ualbertalib/HydraNorth/blob/657_footer_contact/app/views/contact_form/new.html.erb#L3 bolded? Also any feedback on structure of content is appreciated.

**Comment by pbinkley** [comment]
Closed by #748
