### ISSUE TITLE
dynamically update stats number on the homepage

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#664]
Current the stats on the homepage is a hardcoded number:
![image](https://cloud.githubusercontent.com/assets/2047614/10268491/866b76b0-6a77-11e5-8c6e-f005bfe0b334.png)
Need to make it change dynamically with the actual content in the repo.

**Comment by pbinkley** [comment]
The chart values are currently hard-coded at https://github.com/ualbertalib/HydraNorth/blob/master/app/assets/javascripts/custom.js#L78-L96 . We need a solr query that facets on item type for all accessible items (including ccid-protected but not private), in a json format suitable for this chart, which can be fetched by an xhr.

**Comment by pbinkley** [comment]
Solr query: ```/select?q=active_fedora_model_ssi%3A%22GenericFile%22&rows=0&wt=json&indent=true&facet=true&facet.field=resource_type_sim```
