### ISSUE TITLE
thesis with no collection

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#668]
https://hydranorth.library.ualberta.ca/files/qr46r1242#.VhKT2UZSn9U

this thesis is listed as not being part of a collection although it is part of the theses & dissertations 2009 to present collection

old ERA: https://era.library.ualberta.ca/public/view/item/uuid:5071be6c-15ec-4a60-9f4b-47ee7fc0ceca/

data is in the transformed foxml

**Comment by anayram** [comment]
Looks like many items in the Theses and dissertations 2009 to present collection do not show collection (only community FGSR) in item page. This is after release v1.2.0

More examples:
https://hydranorth.library.ualberta.ca/files/jq085m893
https://hydranorth.library.ualberta.ca/files/4m90dv490

This item, however, does show the right community and collection
https://hydranorth.library.ualberta.ca/files/q811kk95h

**Comment by anayram** [comment]
Maybe this is a rake task to be run?

**Comment by pbinkley** [comment]
Yes this is part of the cleanup rake tasks we'll be running this weekend.
We'll also be moving all of the theses into a single collection.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
Yes, that is one of the rake task to be run.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
To be addressed in #715 
Closing
