### ISSUE TITLE
Author Order between Dataverse and HydraNorth

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#674]
This appears to be an issue again in the latest import after being apparently resolved in a previous issue.

https://github.com/ualbertalib/HydraNorth/issues/555

Current example:
https://hydranorth.library.ualberta.ca/files/f4752g834#.VhL_NSpViko

Incidentally, if the same remedy can be applied to Subject order that might not be a bad thing.

**Comment by johnhuck** [comment]
New link to example: https://era.library.ualberta.ca/files/f4752g834#.VrJlN2SrQy5

**Comment by pbinkley** [comment]
This was fixed by https://github.com/ualbertalib/HydraNorth/commit/d80e5a4e820d74a569f04125be5cbc356343943b originally

**Comment by pbinkley** [comment]
Closed by #1043
