### ISSUE TITLE
Change search "start over" link

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#677]
When starting new search users expect "start over" to bring them to new search (blank search box), not a list of all search results.  

![screen shot 2015-10-05 at 5 51 30 pm](https://cloud.githubusercontent.com/assets/12801010/10296833/cc304bc2-6b89-11e5-82e4-5c5137925642.png)

**Comment by pbinkley** [comment]
Link to /advanced instead of /catalog
