### ISSUE TITLE
Large dark datasets

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#68]
As a data librarian, I want to be able to ingest large datasets into the DAMS for dark preservation, so that we can handle the genomics data set.

Part of epic #69

**Comment by weiweishi** [comment]
@pbinkley If the dataset is ingested directly into Openstack Swift, does this ticket belong here?

**Comment by pbinkley** [comment]
I think the principle that Fedora knows all and is the authoritative source of information about our digital assets applies, so even if a dataset goes directly into Swift, we want at least a stub in Fedora that points to it (even if Fedora can't actually retrieve it due to security requirements).

**Comment by pbinkley** [comment]
@umarqasim , where does this stand in your priorities? Is there more Archivematica work to be done before we accept large datasets?

**Comment by pbinkley** [comment]
Possible phases:

- phase 1: simple ingest into Swift
- phase 2: stub records in Hydra for Swift items
- phase 3...n: full Archivematica processing, technical metadata handling, access via Avalon/Dataverse, etc. etc.

**Comment by pbinkley** [comment]
Note: @sfarnel prepared a metadata template

**Comment by sfbetz** [comment]
Superseded by discussions around big data. Closing.
