### ISSUE TITLE
inactive items migrating as public rather than private or embargoed

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#683]
as part of the investigation of issue #666 discovered that inactive items are migrating as public rather than private or embargoed, as agreed upon in discussion (see #521).

e.g.:

https://hydranorth.library.ualberta.ca/files/b2773w37q#.VhPduUZSn9U

**Comment by sfbetz** [comment]
Embargoed items also migrating as public: 

https://hydranorth.library.ualberta.ca/files/r494vk66f#.VhPwUdbi8z8 (embargoed to Nov 1, 2015)

**Comment by pbinkley** [comment]
I'm getting a 404 for that item. Hmm...

**Comment by pbinkley** [comment]
No, wait, now it's showing.

**Comment by sfarnel** [comment]
i'm getting hit and miss access to Hydranorth

On Tue, Oct 6, 2015 at 10:10 AM, Peter Binkley <notifications@github.com>
wrote:

> No, wait, now it's showing.
>
>
>
> On 6 October 2015 at 10:09, Peter Binkley <peter.binkley@ualberta.ca>
> wrote:
>
> > I'm getting a 404 for that item. Hmm...
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/683#issuecomment-145914678>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfbetz** [comment]
I was getting 404s for a lot of things: clicking on login link, logging into dashboard, item searches... Multiple clicks seemed to resolve this

**Comment by sfbetz** [comment]
Dark items seem to *not* be migrating as public. Or haven't migrated yet. I can't log in as DITtest so can't check as an admin.

**Comment by sfbetz** [comment]
And got this screen when I logged out: 
![screen shot 2015-10-06 at 10 13 06 am](https://cloud.githubusercontent.com/assets/12801010/10314599/e18accca-6c12-11e5-8f6a-848d18c26543.png)

**Comment by sfbetz** [comment]
Licensed resources also coming across as public:
https://hydranorth.library.ualberta.ca/files/nk322d830#.VhP1thNVhBc

**Comment by sfarnel** [comment]
so, embargoed and inactive/private items should not have metadata display at all.

ccid protected items should have metadata display but prompt for ccid when you try to download.

**Comment by sfbetz** [comment]
I was able to download with no CCID. And item record displays green "Open Access" icon.

**Comment by sfarnel** [comment]
@anayram will generate the following lists of uuids from the migration package:

- inactive, not embargoed
- inactive, embargoed
- ccid protected
- dark

and will then check for overlaps between the lists.

**Comment by sfarnel** [comment]
spot-checked several embargoed/ccid-protected items and rels-ext remained intact after transformation. just wanted to be sure that process hadn't changed anything.

**Comment by weiweishi** [comment]
I noticed that some of the items are both embargoed and ccid-protected, and
that have caused some of the issue with the embargo bug - it overwrites the
ccid-protected visibility with an incorrect embargo visibility.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mbarnett** [comment]
The issue with CCID-protected & embargoed items is caused by

https://github.com/ualbertalib/HydraNorth/blob/master/lib/tasks/migration.rake#L417

since there are multiple isPartOf nodes, the result of the .text() call is the concatenated text of both nodes, ```"info:fedora/ir:CCID_AUTHinfo:fedora/ir:EMBARGOED"```, which isn't what the code is expecting

**Comment by weiweishi** [comment]
And it is hard to determine which "isPartOf" should take precedence. We will generate a report on items that have more than one "isPartOf" and probably ask @sfarnel and @sfbetz  to look through those items.

**Comment by sfarnel** [comment]
embargoed is more restrictive than ccid-auth (i.e. metadata and object
visible to owner only) and so should take precedence based on policy.
started a doc
<https://docs.google.com/document/d/13T9QnCWw4Bqcpw7-9uKvHR-y1OGOA6CV4bpCpaI7Ixc/edit?usp=sharing>
to capture scenarios in one place.

On Tue, Oct 6, 2015 at 4:51 PM, Weiwei Shi <notifications@github.com> wrote:

> And it is hard to determine which "isPartOf" should take precedence. We
> will generate a report on items that have more than one "isPartOf" and
> probably ask @sfarnel <https://github.com/sfarnel> and @sfbetz
> <https://github.com/sfbetz> to look through those items.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/683#issuecomment-146026644>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
Subsumed by #697
