### ISSUE TITLE
'no liguistic content' being added to metadata during migration

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#684]
in investigating issue #666 discovered that language info 'no liguistic content' is being added somewhere in the migration process as it is not in the transformed foxml.

e.g. 

https://hydranorth.library.ualberta.ca/files/2227mp69j#.VhPkEEZSn9U

uuid:065fe22c-b78d-4a29-8c10-43b0ee84b5f6

**Comment by mbarnett** [comment]
It looks like the migration task does the following:
when dcterms:language is "zxx", the language is set to "No Linguistic Content"
when dcterms:language is blank, the language is set to the typo "No Liguistic Content"

Is the correct behaviour here to correct the typo, or to migrate it blank?

**Comment by pbinkley** [comment]
Argh. We need to fix the typo. We'll have to script this (lower priority
than other current fixes).

**Comment by sfarnel** [comment]
good to fix the typo. although good to know too that normally items will
have a language as it is required. these only came empty in the
'stub'/inactive items that were migrated.

On Tue, Oct 6, 2015 at 12:13 PM, Peter Binkley <notifications@github.com>
wrote:

> Argh. We need to fix the typo. We'll have to script this (lower priority
> than other current fixes).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/684#issuecomment-145951095>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
There seem to be only 21 items, so perhaps we can just fix them by hand.

**Comment by mbarnett** [comment]
That would probably be faster than creating a separate script to reprocess the typo, yeah

**Comment by weiweishi** [comment]
and let's also have it fixed on the migration.rake

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
most of these will be inactive things and can be tidied prior to next
migration. any others we will definitely fix manually!

On Tue, Oct 6, 2015 at 3:01 PM, Weiwei Shi <notifications@github.com> wrote:

> and let's also have it fixed on the migration.rake
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Tue, Oct 6, 2015 at 3:00 PM, Matthew Barnett <notifications@github.com>
> wrote:
>
> > That would probably be faster than creating a separate script to
> reprocess
> > the typo, yeah
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/684#issuecomment-145999212
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/684#issuecomment-145999648>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by mbarnett** [comment]
I've opened a pull request on Sprint 27 to correct the typo in migration.rake
