### ISSUE TITLE
404 pages aren't rendering correct template

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#685]
May be related to differences in viewpath handling between development and production Rails modes, as it looks like it is working on plano:

https://plano.library.ualberta.ca/public/view/item/uuid:17305a7a-276b-4575-bbff-b9c9cb80e073/

**Comment by weiweishi** [comment]
[image: Inline image 1]

A screenshot on production after this controller is added.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mbarnett** [comment]
I cannot recreate this locally, running Rails & Passenger in Production mode. Is it possible that Apache on the production server is configured to intercept 404 status codes? It might explain why we're seeing a generic Apache error page there, but I do not have access to check via ssh.

**Comment by mbarnett** [comment]
Best guess here is that one of either ```PassengerErrorOverride on``` or ```ProxyErrorOverride on``` is enabled somewhere in the Apache config, but without access to the production setup it is seemingly impossible to track this down further.

Other possible culprits might be the HAProxy config or mod_security.

**Comment by pbinkley** [comment]
OK, let's put this on hold until all the other fires are out, and then you
and Henry can sit down with access to production and figure out what goes
where.

**Comment by weiweishi** [comment]
PassengerErrorOverride on is turned on

Should we try to turn it off on production?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
tried to turn this off and it works:
https://hydranorth.library.ualberta.ca/public/view/item/uuid:17305a7a-276b-4575-bbff-b9c9cb80e073/

I will let Henry know about the change.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
Checked with @mbarnett and verified with simple tests. Turning this option
off for now.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pbinkley** [comment]
Only if we can do it without slowing down the other fixes.

**Comment by pbinkley** [comment]
Sorry, I'm way behind. congrats, and thanks!

**Comment by mbarnett** [comment]
I assume we can close this now. Reopen if there's something that still needs to be addressed.
