### ISSUE TITLE
Progress window won't stay closed after upload

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#687]
If I deposit an item, I get the progress window ("Thank you for adding your research to ERA!"), which continually refreshes. It says I can close it at any time, but if I do it pops up again. It appears even if I log into my dashboard in a different browser. It should go away and stays away if I click the close link.

Progress window introduced by #511

**Comment by nnunn** [comment]
I will fix this, this afternoon. I thought I had it fixed, but apparently not.

**Comment by nnunn** [comment]
I have a fix for this bug. Should I do a pull request onto master or onto the Sprint 27 branch?

**Comment by weiweishi** [comment]
Thanks @nnunn. Please PR to Sprint 27 branch.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pbinkley** [comment]
Do it into the Sprint 27 branch. We'll merge that branch into master for
Friday's deployment.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by pbinkley** [comment]
closed by Natasha's PR
