### ISSUE TITLE
Operational: near-death experience with paging space

### ISSUE THREAD

**Issue by nmacgreg** [ualbertalib/HydraNorth#689]
Nagios warned: "Swap Usage" for leyton, currently at 13% free.
This is not actively a problem, but indicates that there was a problem in the recent past.   This system has 10Gb of memory & 2Gb of swap, and *almost* used all of it.
This problem started at 11:34am with an initial soft warning in Nagios, when 28% was free.
Datapoints:
* 28% at 11:34
* 20% at 11:40
* 20% at 11:43
* 20% at 11:46
-and-
* 13% at 12:30

**Comment by nmacgreg** [comment]
Again, this isn't a problem right now -- the system isn't actively paging... vmstat says no swap-blocks in or out.  But it indicates *something* used a lot of virtual memory.

This entry from syslog says it was (surprise!) a ruby process: 
Oct  6 12:38:52 leyton kernel: Out of memory: Kill process 1137 (ruby) score 50 or sacrifice child
Oct  6 12:38:52 leyton kernel: Killed process 1137, UID 48, (ruby) total-vm:1042700kB, anon-rss:613268kB, file-rss:4kB
This is the kernel's out-of-memory killer ("the oom-killer") desperately trying not to crash, searching for a user-space program that was using a lot of memory.

**Comment by nmacgreg** [comment]
We spotted that there were some ffmpeg processes still running, stale-dated from yesterday.  Somebody left these running?
    ffmpeg -i /tmp/content-120151005-1513-1ydaaph.mp4 -s 320x240 -vcodec libvpx -acodec libvorbis -g 30 -b:v 345k -ac 2 -ab 96k -ar 44100 /tmp/sufia20151005-1513-u0bix.webm
Henry has rebooted this machine.

**Comment by weiweishi** [comment]
they can be killed. There were some failed thumbnail generating from resque
log. I wonder if any of that processes was hanging. Need to review the
resque log  for information. but that explains why the
characterization/derivative jobs were finished (or as it appears with
Resque.info) before the memory warning happened.



*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by nmacgreg** [comment]
Henry added 2Gb more memory to this machine.  It's been running for 1.5 hours, and memory utilization is low.  We're not fully in Production yet, so, "stay tuned".   I bothered to put this in at all, because I saw that this system had been struggling with memory utilization for much of the midnight-to-4am period; I drained swap (asked it to stop using the device, then added it again), before lunch today, to rectify the Nagios report... but then the problem came back.   We didn't get to root cause, so I'll leave this open for a day, in case of repeats.

**Comment by pbinkley** [comment]
The load will pick up again when we resume migration and start running the
characterization and derivative jobs again (the latter uses ffmpeg to
generate thumbnails). Hopefully later today.

**Comment by weiweishi** [comment]
We can use newport for all the background migration work. Is there a way to
increase the memory there?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by nmacgreg** [comment]
Hmm, we didn't get to root cause, and we're delaying the launch.  I'm going to close this issue.  It might be better to handle operational issues in OTRS, anyway, and use GH issues when the root cause is determined to be a problem requiring a software fix.
