### ISSUE TITLE
Metadata for research data

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#69]
Research data must be discoverable in HydraNorth. For parts of this epic, see:
- [x] #67
- [ ] #68
- [x] #70 

Out of scope for this story: deposit, preservation.

Move parts of this epic to the appropriate sprint milestones as we begin to work on them.

**Comment by pbinkley** [comment]
This may turn out to be too difficult to achieve without adding new models, but let's have a look and see if it can be done in this sprint.
Out of scope: direct deposit of items without datastreams
In scope: 
- batch ingest of Dataverse items
- provide link back to Dataverse
- adjust display page for missing/new elements

**Comment by sfarnel** [comment]
Earlier discussion had concluded that we would allow the deposit of datasets into Hydra (ERA). If this is to be changed then the form will need to be adjusted accordingly and any datasets currently in ERA assessed for handling.

**Comment by johnhuck** [comment]
Sent a first draft of transformed oai_dc metadata sample to Weiwei on June 19th. The transformed metadata:
-updates the namespaces of the dc: elements to dcterms:
-maps values in dc:date to dcterms:created
-maps values in dc:coverage to either dcterms:spatial or dcterms:temporal.
-excludes dc:description elements that contain a formatted citation

Questions that remain:
-Should the introductory phrases that prefaced (and identified) the content in dc:coverage elements be retained for clarity or dropped.
-Should dcterms:publisher be added to the Hydra Data Dictionary.
-what is the ideal root XML element to use with the Hydra import script: the original element from the source metadata (<oai_dc:dc>)? <metadata>? <record>?
-should <dcterms:spatial>Geographic Unit: [...]</dcterms:spatial> be retained or dropped? Examples of values in this field are "Province" and "Census subdivision"

**Comment by weiweishi** [comment]
remaining working may or may not be relevant #68
