### ISSUE TITLE
Stats from Google Analytics Failure

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#694]
@pbinkley (or someone with access to the Google Analytics UI) The part that was missing for the stats "ensure that the OAuth client email has the proper access within your Google Analyics account. To do so, go to the Admin tab for your Google Analytics account. Click on User Management, in the Account column, and add "Read & Analyze" permissions for the OAuth client email address." https://github.com/projecthydra/sufia#analytics-and-usage-statistics.  See @pgwillia email for the secrets.

**Comment by pbinkley** [comment]
done, for hydranorth and for era.
