### ISSUE TITLE
review permissions scenarios in migration

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#697]
Sharon's matrix for scenarios: https://docs.google.com/document/d/13T9QnCWw4Bqcpw7-9uKvHR-y1OGOA6CV4bpCpaI7Ixc/edit

Review migration.rake against these scenarios and fix any gaps. Notes on problems noticed during the Oct. 1 migration are gathered in #683 (which this issue replaces).

**Comment by pbinkley** [comment]
From our conversation this morning: could we use Mariana's lists of old ERA items in various categories (dark, CCID-protected, etc.), and use them to audit every migrated item when the migration is finished to ensure that its HydraNorth permissions are set appropriately for the category it is supposed to be in? This is would closely mimic the tests for the revised migration rake task, but would be applied to all items in HydraNorth.

**Comment by anayram** [comment]
This document contains full lists of specific foxml cases as well as access cases related to ERA migration:
https://docs.google.com/spreadsheets/d/1Bc-UY2Bi9nsokbLV0Po21hWL3Q8I7bDgFpEuA39G1TY/edit#gid=1776212738

**Comment by anayram** [comment]
See sheets:
HN_access_cases
HN_access_transition_cases
special_cases

**Comment by anayram** [comment]
Notes:
* In the spreadsheet, the relevant sheets are HN_access_cases and HN_access_transition_cases
* The sheet titled special_cases includes items that we may want to review individually
* Headers contain information on conditions used to filter items
* Text files are named after each access case to be tested, please let me know if I missed any. I did not create a list for 'Authenticated Access' given that there are no cases of this in old ERA.

Lists are also available as text files located at:
Digital_Init:
Hydra_DAMS\ERA\ERA_migration\FOXML_transformed\complete_remigration\pid_lists\access_testing

**Comment by anayram** [comment]
Lists will be completed after launch with partial dump to transition date.

**Comment by pbinkley** [comment]
Handled by the audit process
