### ISSUE TITLE
Links to licenses

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#699]
Links to license terms in item record does not link to license text - links instead to blank search.
![screen shot 2015-10-06 at 2 51 32 pm](https://cloud.githubusercontent.com/assets/12801010/10348718/faab257a-6cf7-11e5-8662-ecd5d29558ad.png)

Ideally this field would display the text of the license instead of a link.

**Comment by weiweishi** [comment]
Should we remove the license field from the view, if there are customized
rights statement?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfbetz** [comment]
I think all the licenses link to a blank search right now (not sure it's
blank, but definitely not accurate), even the default CC licenses. I think
they're supposed to link to other items with the same license.

As far as custom licenses: I see now that the text of the license is
appearing below the license field in the Rights Statement field. Sorry, I
didn't notice that.

* In an ideal, beyond bug-fixing, world, the customized rights statement
would display just the text in the record of the license field (or rights
field) and there would be no link.  Links to standard CC licenses would
link to an explanation of what they are (so a CC BY NC-ND license would
open a new page that links here
https://creativecommons.org/licenses/by-nc-nd/2.0/).

*in time sensitive let's just fix the bug world, we can fix the links so
they only link to a search of other items with the same license, and (if
it's easy to do) remove the field for license when there are custom Rights
Statement assigned.



On Wed, Oct 7, 2015 at 2:58 PM, Weiwei Shi <notifications@github.com> wrote:

> Should we remove the license field from the view, if there are customized
> rights statement?
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Wed, Oct 7, 2015 at 1:34 PM, Sonya Betz <notifications@github.com>
> wrote:
>
> > Links to license terms in item record does not link to license text -
> > links instead to blank search.
> > [image: screen shot 2015-10-06 at 2 51 32 pm]
> > <
> https://cloud.githubusercontent.com/assets/12801010/10348718/faab257a-6cf7-11e5-8662-ecd5d29558ad.png
> >
> >
> > Ideally this field would display the text of the license instead of a
> link.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ualbertalib/HydraNorth/issues/699>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/699#issuecomment-146326441>
> .
>



-- 
Sonya Betz
Digital Initiatives Projects Librarian
Acting Digital Repository <http://era.library.ualberta.ca/> Services
Librarian



*University of Alberta Libraries2-10U Cameron Library, University of
AlbertaEdmonton, AB, Canada T6G 2J8  *
*sonya.betz@ualberta.ca <sfbetz@ualberta.ca> *
*780-492-1718*

**Comment by weiweishi** [comment]
I think this:
* In an ideal, beyond bug-fixing, world, the customized rights statement
would display just the text in the record of the license field (or rights
field) and there would be no link. Links to standard CC licenses would
link to an explanation of what they are (so a CC BY NC-ND license would
open a new page that links here
can be easily achievable (as it simply involves removing code, not adding
code).

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
Not sure if this needs to be bumped up in priority?

**Comment by sfarnel** [comment]
this is true of newly created items as well (item i created as embargoed for testing)

![licandrights](https://cloud.githubusercontent.com/assets/4697932/10529332/34d61b7a-735a-11e5-9c58-adcf2cb84c80.jpg)
