### ISSUE TITLE
'embargo then UA access' option on deposit form

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#701]
The item deposit form should include the option to make an item UA Access after an embargo lapses:

![embargo_then_ua](https://cloud.githubusercontent.com/assets/4697932/10372627/ef2920f4-6da5-11e5-87f5-4fde6bf517f7.jpg)

**Comment by sfbetz** [comment]
Is that the same as Authenticated Access? Or does Authenticated access mean authenticated to ERA?

**Comment by sfarnel** [comment]
authenticated access is authenticated to/registered with ERA; UA is ccid
and password.

On Fri, Oct 9, 2015 at 10:12 AM, Sonya Betz <notifications@github.com>
wrote:

> Is that the same as Authenticated Access? Or does Authenticated access
> mean authenticated to ERA?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/701#issuecomment-146913886>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
