### ISSUE TITLE
item deposited without hitting save

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#702]
Was just in grabbing a screen shot of of the deposit form, so was past the file upload and agree to terms step, and at the add metadata step. Grabbed the shot then backed out of the form, confirming the 'leave this page' warning. Interestingly, my 'deposit' was listed in my activity and my item is there (private) with no metadata, even though I didn't hit save. (Don't think this is desired functionality?)

**Comment by pbinkley** [comment]
I think the workflow sequence means that by not clicking save you're saying "don't save the metadata", not "don't save the object". Sufia's file-centric workflow creates the item when you upload the file, and treats adding the metadata as a follow-on step, like generating a thumbnail. (This is why you sometimes have to wait to see the metadata on a newly-uploaded item). 
So we could keep the current workflow but improve the info on the form, or we could adjust the workflow so that not saving the metadata triggers the deletion of the object (with maybe an option to warn the user that that's what's going to happen). Did anything about this come up in user testing? @sfbetz

**Comment by sfarnel** [comment]
just for curiosity checked to see what would happen if i made the item open
but added no metadata and then backed out, but it saved it as private
still. so that was good.

On Thu, Oct 8, 2015 at 10:34 AM, Peter Binkley <notifications@github.com>
wrote:

> I think the workflow sequence means that by not clicking save you're
> saying "don't save the metadata", not "don't save the object". Sufia's
> file-centric workflow creates the item when you upload the file, and treats
> adding the metadata as a follow-on step, like generating a thumbnail. (This
> is why you sometimes have to wait to see the metadata on a newly-uploaded
> item).
> So we could keep the current workflow but improve the info on the form, or
> we could adjust the workflow so that not saving the metadata triggers the
> deletion of the object (with maybe an option to warn the user that that's
> what's going to happen). Did anything about this come up in user testing?
> @sfbetz <https://github.com/sfbetz>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/702#issuecomment-146607820>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
That's good. I think the transition from private to published is triggered by the attaching of the metadata, so that makes sense.

**Comment by sfbetz** [comment]
This did come up in user testing. There was concern about not having any way to "stop" the process once an upload is completed and led to some of my concern around our draft content withdrawal policy. I don't think items should be committed to ERA until the last step, and the user has completed the metadata and actively selected "save" (or submit or whatever we've called that button). There's already a warning if you try to navigate away from the page without saving metadata.

This can happen after launch though!

**Comment by pbinkley** [comment]
So our options are:
- automate the deletion of incompletely-submitted files
- allow user to delete them (whereas we do not allow deletion of completed files)

**Comment by pbinkley** [comment]
Sufia 7 will have metadata-first approach.
