### ISSUE TITLE
HTML Markup being displayed in  dataverse metadata and collection pages

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#704]
Looks like we're still seeing HTML markup in some of the fields coming over from dataverse. Referenced in closed issue #491 but I don't think it was resolved.

See: https://hydranorth.library.ualberta.ca/files/3n203z16t#.Vhf9gBNViko

**Comment by anayram** [comment]
Collection pages also display HTML in description fields:

https://hydranorth.library.ualberta.ca/collections/44558v315

**Comment by pbinkley** [comment]
So we have html formatting coming over from Dataverse and also embedded in some ERA collection descriptions. We need a strategic decision about whether to allow this, and if so, how to enable it, but if not, how to strip it without messing up formatting too much.

**Comment by pbinkley** [comment]
In solving this we could look at the LateX problem as well #945

**Comment by pbinkley** [comment]
Display description and abstracts fields for collections or items as html. Use ruby's html-safe to be sure the html is well-formed and contains no nasty tags.

**Comment by pbinkley** [comment]
We already have [rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer) installed. Minispike: inserting ```sanitize``` before ```@presenter.description``` in (app/views/collections/show.html l.10)[https://github.com/ualbertalib/HydraNorth/blob/cb7992eac7e0dda501dae4a41b11405cc941ad5a/app/views/collections/show.html.erb#L10] causes the html to be rendered rather than escaped.  This uses the default [whitelist sanitizer](https://github.com/flavorjones/loofah/blob/master/lib/loofah/html5/whitelist.rb).

**Comment by pbinkley** [comment]
We've added HTML sanitizing to Collections description in #1160 . Let's add it to the appropriate fields in GenericFile: description, isVersionOf, abstract (confirm with @leahvanderjagt whether there are others)

**Comment by leahvanderjagt** [comment]
To the best of my memory, I think those are all the fields.

On Wed, Jun 1, 2016 at 1:57 PM, Peter Binkley <notifications@github.com>
wrote:

> We've added HTML sanitizing to Collections description in #1160
> <https://github.com/ualbertalib/HydraNorth/pull/1160> . Let's add it to
> the appropriate fields in GenericFile: description, isVersionOf, abstract
> (confirm with @leahvanderjagt <https://github.com/leahvanderjagt> whether
> there are others)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/704#issuecomment-223106624>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFieXLAkiBzCHzdAZXF7hsmnqrN2RBGrks5qHeRFgaJpZM4GMRn4>
> .
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by johnhuck** [comment]
HTML is allowed in many fields in Dataverse (I think the DDI standard allows for this). If this sanitizing needs to be applied field by field, I should probably check which fields in the Dataverse metadata we're using might have it.

**Comment by johnhuck** [comment]
OK, the only one to worry about for Dataverse metadata is Description (dcterms:description). I mapped 'Description' and 'Kind of data' (which both allow it) into one dcterms:description element. Everything else where it is allowed we aren't mapping to anything.

**Comment by pgwillia** [comment]
@pbinkley @weiweishi when was the last time we did a dataverse import?

**Comment by johnhuck** [comment]
@pgwillia, earlier in March or April.

**Comment by johnhuck** [comment]
I'm checking back the versions of the metadata I worked with to see where the escaping occurs. I can see it's in the final version of the xml I handed off for ingest. Since we are working with XML, the characters need to escaped somehow, but perhaps enclosing CDATA brackets could be used instead.

**Comment by weiweishi** [comment]
We will handle it at ingest/migration step, as well as at the time the text
is rendered on to the UI in the application. I will create a separate
ticket for it.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pbinkley** [comment]
Subsumed by #1203
