### ISSUE TITLE
link to related item metadata not displaying 

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#706]
e.g.: 
https://hydranorth.library.ualberta.ca/files/pg15bd981#.VhbulUZSn9U

https://hydranorth.library.ualberta.ca/files/q524jp15b#.Vhb0OUZSn9U

**Comment by pbinkley** [comment]
Also part of #715

**Comment by sfarnel** [comment]
Will be addressed in #715 
Closing
