### ISSUE TITLE
Field mapping issues in migration.rake

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#709]
- [x] looks for [```dcterms:dateaccepted```](https://github.com/ualbertalib/HydraNorth/blob/master/lib/tasks/migration.rake#L260), but DCQ in theses has ```dcterms:dateAccepted```
- [x] likewise for ```dcterms:isVersionOf``` and ```dcterms:dateSubmitted```
(I wonder if the ```isVersionOf``` is responsible for #706 )

**Comment by pbinkley** [comment]
I assume we should be following this as the authority for dcterms: http://dublincore.org/documents/dcmi-terms/

**Comment by sfarnel** [comment]
following email conversation with @pbinkley, @weiweishi, @anayram, will
tweak migration script for legacy theses to accept camel case and determine
if/how to revise/update archived foxml for other items

On Fri, Oct 9, 2015 at 4:58 PM, Peter Binkley <notifications@github.com>
wrote:

> I assume we should be following this as the authority for dcterms:
> http://dublincore.org/documents/dcmi-terms/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/709#issuecomment-147006844>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pgwillia** [comment]
The example thesis foxml contains dateaccepted.  What's the best source for a second example with dateAccepted.  This would allow me to ensure that dateaccepted and dateAccepted are both accepted.

**Comment by anayram** [comment]
Here are two legacy theses used to test migration
uuid:000a0761-b7c2-4591-8a2a-f9e96cafd2b3
uuid:000d8d10-2195-4076-a5c1-69696e479a5b

They should have dateAccepted.

On Wed, Oct 14, 2015 at 2:19 PM, pgwillia <notifications@github.com> wrote:

> The example thesis foxml contains dateaccepted. What's the best source for
> a second example with dateAccepted. This would allow me to ensure that
> dateaccepted and dateAccepted are both accepted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/709#issuecomment-148183451>
> .
>



-- 
Mariana Paredes-Olea
paredeso@ualberta.ca
780-492-7075

**Comment by sfarnel** [comment]
Example attached; thanks @pgwillia

On Wed, Oct 14, 2015 at 2:19 PM, pgwillia <notifications@github.com> wrote:

> The example thesis foxml contains dateaccepted. What's the best source for
> a second example with dateAccepted. This would allow me to ensure that
> dateaccepted and dateAccepted are both accepted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/709#issuecomment-148183451>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
grr .. github won't take xml. will send to you directly
