### ISSUE TITLE
ccid items migrating as open access

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#710]
https://hydranorth.library.ualberta.ca/files/3197xm13h#.VhiHWqLwMiE

(https://era.library.ualberta.ca/public/view/item/uuid:04b19808-e70a-4277-8a7c-55054ecc131d/)

* this may have been migrated prior to the migration pause

**Comment by weiweishi** [comment]
I think we should write a verification script, and pair programming with
someone from the metadata team to check all the items that are migrated, to
make sure the metadata comes over correctly. Let try to work out something
next week.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
And Sharon, I've removed the ccid associated with the eraadmi@ualberta.ca
account (it was Leah's), and have set it as admin so you should be able to
login to check items.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
Great; thanks Weiwei.

On Fri, Oct 9, 2015 at 11:21 PM, Weiwei Shi <notifications@github.com>
wrote:

> And Sharon, I've removed the ccid associated with the eraadmi@ualberta.ca
> account (it was Leah's), and have set it as admin so you should be able to
> login to check items.
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Fri, Oct 9, 2015 at 10:09 PM, Weiwei Shi <weiwei.shi@ualberta.ca>
> wrote:
>
> > I think we should write a verification script, and pair programming with
> > someone from the metadata team to check all the items that are migrated,
> to
> > make sure the metadata comes over correctly. Let try to work out
> something
> > next week.
> >
> > *Weiwei Shi*
> >
> > Digital Initiative Applications Librarian
> > University of Alberta Libraries
> > 2-10L Cameron Library
> > Edmonton, Alberta, Canada T6G 2J8
> > Phone:(780)492-7802
> > Fax: (780)248-1209
> > Email: weiwei.shi@ualberta.ca
> >
> > On Fri, Oct 9, 2015 at 9:44 PM, Sharon Farnel <notifications@github.com>
> > wrote:
> >
> >> https://hydranorth.library.ualberta.ca/files/3197xm13h#.VhiHWqLwMiE
> >>
> >> (
> >>
> https://era.library.ualberta.ca/public/view/item/uuid:04b19808-e70a-4277-8a7c-55054ecc131d/
> >> )
> >>
> >> - this may have been migrated prior to the migration pause
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/ualbertalib/HydraNorth/issues/710>.
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/710#issuecomment-147040743>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
further update. when logged in as admin I can see in my files a long list
of ccid-protected items, e.g., Hill Times, Parliament Now, etc.

e.g.: https://hydranorth.library.ualberta.ca/files/dn39x224x

visibility shows as UofA. when I click on an item I get an error:

"We're sorry, but something went wrong. If you are the application owner
check the logs for more information."

The metadata for these items isn't showing up in searches or browses by
type.

If I go to the site and paste the url into the browser when not signed in,
it says

"Not authorized to show generic file. Contact administrator for assistance."

If I then log in with my ccid I get the same error mentioned above:

"We're sorry, but something went wrong. If you are the application owner
check the logs for more information."

On Sat, Oct 10, 2015 at 5:54 PM, Sharon Farnel <sharon.farnel@ualberta.ca>
wrote:

> Great; thanks Weiwei.
>
> On Fri, Oct 9, 2015 at 11:21 PM, Weiwei Shi <notifications@github.com>
> wrote:
>
>> And Sharon, I've removed the ccid associated with the eraadmi@ualberta.ca
>> account (it was Leah's), and have set it as admin so you should be able to
>> login to check items.
>>
>> *Weiwei Shi*
>>
>> Digital Initiative Applications Librarian
>> University of Alberta Libraries
>> 2-10L Cameron Library
>> Edmonton, Alberta, Canada T6G 2J8
>> Phone:(780)492-7802
>> Fax: (780)248-1209
>> Email: weiwei.shi@ualberta.ca
>>
>> On Fri, Oct 9, 2015 at 10:09 PM, Weiwei Shi <weiwei.shi@ualberta.ca>
>> wrote:
>>
>> > I think we should write a verification script, and pair programming with
>> > someone from the metadata team to check all the items that are
>> migrated, to
>> > make sure the metadata comes over correctly. Let try to work out
>> something
>> > next week.
>> >
>> > *Weiwei Shi*
>> >
>> > Digital Initiative Applications Librarian
>> > University of Alberta Libraries
>> > 2-10L Cameron Library
>> > Edmonton, Alberta, Canada T6G 2J8
>> > Phone:(780)492-7802
>> > Fax: (780)248-1209
>> > Email: weiwei.shi@ualberta.ca
>> >
>> > On Fri, Oct 9, 2015 at 9:44 PM, Sharon Farnel <notifications@github.com
>> >
>> > wrote:
>> >
>> >> https://hydranorth.library.ualberta.ca/files/3197xm13h#.VhiHWqLwMiE
>> >>
>> >> (
>> >>
>> https://era.library.ualberta.ca/public/view/item/uuid:04b19808-e70a-4277-8a7c-55054ecc131d/
>> >> )
>> >>
>> >> - this may have been migrated prior to the migration pause
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >> <https://github.com/ualbertalib/HydraNorth/issues/710>.
>> >>
>> >
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ualbertalib/HydraNorth/issues/710#issuecomment-147040743>
>> .
>>
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
If I do a keyword search for apples when not logged in I get 18 results.
When I do  the same search when logged in with my ccid I get an additional
item - https://hydranorth.library.ualberta.ca/files/8s45q881f#.Vhmz2RNViko
- which is ccid-protected. It's labelled as UofA Access.

If I take that url and paste it into a browser when not logged in, I get
prompted to log in. If I log in then I get to the item screen.

On Sat, Oct 10, 2015 at 6:31 PM, Sharon Farnel <sharon.farnel@ualberta.ca>
wrote:

> further update. when logged in as admin I can see in my files a long list
> of ccid-protected items, e.g., Hill Times, Parliament Now, etc.
>
> e.g.: https://hydranorth.library.ualberta.ca/files/dn39x224x
>
> visibility shows as UofA. when I click on an item I get an error:
>
> "We're sorry, but something went wrong. If you are the application owner
> check the logs for more information."
>
> The metadata for these items isn't showing up in searches or browses by
> type.
>
> If I go to the site and paste the url into the browser when not signed in,
> it says
>
> "Not authorized to show generic file. Contact administrator for
> assistance."
>
> If I then log in with my ccid I get the same error mentioned above:
>
> "We're sorry, but something went wrong. If you are the application owner
> check the logs for more information."
>
> On Sat, Oct 10, 2015 at 5:54 PM, Sharon Farnel <sharon.farnel@ualberta.ca>
> wrote:
>
>> Great; thanks Weiwei.
>>
>> On Fri, Oct 9, 2015 at 11:21 PM, Weiwei Shi <notifications@github.com>
>> wrote:
>>
>>> And Sharon, I've removed the ccid associated with the
>>> eraadmi@ualberta.ca
>>> account (it was Leah's), and have set it as admin so you should be able
>>> to
>>> login to check items.
>>>
>>> *Weiwei Shi*
>>>
>>> Digital Initiative Applications Librarian
>>> University of Alberta Libraries
>>> 2-10L Cameron Library
>>> Edmonton, Alberta, Canada T6G 2J8
>>> Phone:(780)492-7802
>>> Fax: (780)248-1209
>>> Email: weiwei.shi@ualberta.ca
>>>
>>> On Fri, Oct 9, 2015 at 10:09 PM, Weiwei Shi <weiwei.shi@ualberta.ca>
>>> wrote:
>>>
>>> > I think we should write a verification script, and pair programming
>>> with
>>> > someone from the metadata team to check all the items that are
>>> migrated, to
>>> > make sure the metadata comes over correctly. Let try to work out
>>> something
>>> > next week.
>>> >
>>> > *Weiwei Shi*
>>> >
>>> > Digital Initiative Applications Librarian
>>> > University of Alberta Libraries
>>> > 2-10L Cameron Library
>>> > Edmonton, Alberta, Canada T6G 2J8
>>> > Phone:(780)492-7802
>>> > Fax: (780)248-1209
>>> > Email: weiwei.shi@ualberta.ca
>>> >
>>> > On Fri, Oct 9, 2015 at 9:44 PM, Sharon Farnel <
>>> notifications@github.com>
>>> > wrote:
>>> >
>>> >> https://hydranorth.library.ualberta.ca/files/3197xm13h#.VhiHWqLwMiE
>>> >>
>>> >> (
>>> >>
>>> https://era.library.ualberta.ca/public/view/item/uuid:04b19808-e70a-4277-8a7c-55054ecc131d/
>>> >> )
>>> >>
>>> >> - this may have been migrated prior to the migration pause
>>> >>
>>> >> —
>>> >> Reply to this email directly or view it on GitHub
>>> >> <https://github.com/ualbertalib/HydraNorth/issues/710>.
>>> >>
>>> >
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ualbertalib/HydraNorth/issues/710#issuecomment-147040743>
>>> .
>>>
>>
>>
>>
>> --
>> Sharon Farnel
>> Metadata Coordinator
>> University of Alberta Libraries
>> sharon.farnel@ualberta.ca
>> 780-492-3685
>>
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
So the behavior needs to be modified - public should be able to view items
but not download. Going to capture this in a ticket.

Still investigating the first one

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
Thanks Weiwei. The ccid-protected visibility covered in
https://github.com/ualbertalib/HydraNorth/issues/582

Closing the issue (bug) that had era admin linked to ccid; attaching your
comment in this email chain.

On Sat, Oct 10, 2015 at 8:47 PM, Weiwei Shi <notifications@github.com>
wrote:

> So the behavior needs to be modified - public should be able to view items
> but not download. Going to capture this in a ticket.
>
> Still investigating the first one
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Sat, Oct 10, 2015 at 7:05 PM, Sharon Farnel <notifications@github.com>
>
> wrote:
>
> > If I do a keyword search for apples when not logged in I get 18 results.
> > When I do the same search when logged in with my ccid I get an additional
> > item -
> https://hydranorth.library.ualberta.ca/files/8s45q881f#.Vhmz2RNViko
> > - which is ccid-protected. It's labelled as UofA Access.
> >
> > If I take that url and paste it into a browser when not logged in, I get
> > prompted to log in. If I log in then I get to the item screen.
> >
> > On Sat, Oct 10, 2015 at 6:31 PM, Sharon Farnel <
> sharon.farnel@ualberta.ca>
> >
> > wrote:
> >
> > > further update. when logged in as admin I can see in my files a long
> list
> > > of ccid-protected items, e.g., Hill Times, Parliament Now, etc.
> > >
> > > e.g.: https://hydranorth.library.ualberta.ca/files/dn39x224x
> > >
> > > visibility shows as UofA. when I click on an item I get an error:
> > >
> > > "We're sorry, but something went wrong. If you are the application
> owner
> > > check the logs for more information."
> > >
> > > The metadata for these items isn't showing up in searches or browses by
> > > type.
> > >
> > > If I go to the site and paste the url into the browser when not signed
> > in,
> > > it says
> > >
> > > "Not authorized to show generic file. Contact administrator for
> > > assistance."
> > >
> > > If I then log in with my ccid I get the same error mentioned above:
> > >
> > > "We're sorry, but something went wrong. If you are the application
> owner
> > > check the logs for more information."
> > >
> > > On Sat, Oct 10, 2015 at 5:54 PM, Sharon Farnel <
> > sharon.farnel@ualberta.ca>
> > > wrote:
> > >
> > >> Great; thanks Weiwei.
> > >>
> > >> On Fri, Oct 9, 2015 at 11:21 PM, Weiwei Shi <notifications@github.com
> >
> > >> wrote:
> > >>
> > >>> And Sharon, I've removed the ccid associated with the
> > >>> eraadmi@ualberta.ca
> > >>> account (it was Leah's), and have set it as admin so you should be
> able
> > >>> to
> > >>> login to check items.
> > >>>
> > >>> *Weiwei Shi*
> > >>>
> > >>> Digital Initiative Applications Librarian
> > >>> University of Alberta Libraries
> > >>> 2-10L Cameron Library
> > >>> Edmonton, Alberta, Canada T6G 2J8
> > >>> Phone:(780)492-7802
> > >>> Fax: (780)248-1209
> > >>> Email: weiwei.shi@ualberta.ca
> > >>>
> > >>> On Fri, Oct 9, 2015 at 10:09 PM, Weiwei Shi <weiwei.shi@ualberta.ca>
> > >>> wrote:
> > >>>
> > >>> > I think we should write a verification script, and pair programming
> > >>> with
> > >>> > someone from the metadata team to check all the items that are
> > >>> migrated, to
> > >>> > make sure the metadata comes over correctly. Let try to work out
> > >>> something
> > >>> > next week.
> > >>> >
> > >>> > *Weiwei Shi*
> > >>> >
> > >>> > Digital Initiative Applications Librarian
> > >>> > University of Alberta Libraries
> > >>> > 2-10L Cameron Library
> > >>> > Edmonton, Alberta, Canada T6G 2J8
> > >>> > Phone:(780)492-7802
> > >>> > Fax: (780)248-1209
> > >>> > Email: weiwei.shi@ualberta.ca
> > >>> >
> > >>> > On Fri, Oct 9, 2015 at 9:44 PM, Sharon Farnel <
> > >>> notifications@github.com>
> > >>> > wrote:
> > >>> >
> > >>> >>
> https://hydranorth.library.ualberta.ca/files/3197xm13h#.VhiHWqLwMiE
> > >>> >>
> > >>> >> (
> > >>> >>
> > >>>
> >
> https://era.library.ualberta.ca/public/view/item/uuid:04b19808-e70a-4277-8a7c-55054ecc131d/
> > >>> >> )
> > >>> >>
> > >>> >> - this may have been migrated prior to the migration pause
> > >>> >>
> > >>> >> —
> > >>> >> Reply to this email directly or view it on GitHub
> > >>> >> <https://github.com/ualbertalib/HydraNorth/issues/710>.
> > >>> >>
> > >>> >
> > >>> >
> > >>>
> > >>> —
> > >>> Reply to this email directly or view it on GitHub
> > >>> <
> >
> https://github.com/ualbertalib/HydraNorth/issues/710#issuecomment-147040743
> > >
> > >>> .
> > >>>
> > >>
> > >>
> > >>
> > >> --
> > >> Sharon Farnel
> > >> Metadata Coordinator
> > >> University of Alberta Libraries
> > >> sharon.farnel@ualberta.ca
> > >> 780-492-3685
> > >>
> > >
> > >
> > >
> > > --
> > > Sharon Farnel
> > > Metadata Coordinator
> > > University of Alberta Libraries
> > > sharon.farnel@ualberta.ca
> > > 780-492-3685
> > >
> >
> >
> >
> > --
> > Sharon Farnel
> > Metadata Coordinator
> > University of Alberta Libraries
> > sharon.farnel@ualberta.ca
> > 780-492-3685
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/710#issuecomment-147142663
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/710#issuecomment-147149123>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
Log info:
ActionView::Template::Error (Model mismatch. Expected Collection. Got: GenericFile):
     8:         <% @generic_file.belongsToCommunity.each do |c| %>
     9:         <tr class="collection attributes">
    10:           <%= content_tag :td, class: 'attribute title', data: { id: c } do %>
    11:             <% community = Collection.find(c) %>
    12:             <%= link_to community.title, collections.collection_path(community) %>
    13:           <% end %>
    14:         </tr>

Some issue with a particular item:
uuid:ca304e6a-06ab-419d-aa52-1771d3b641ee

The community in the foxml has an uuid:11274e20-0426-4e80-84f4-bef79dbd6633 
However, this is not a collection, it's an object. 
https://era.library.ualberta.ca/public/view/item/uuid:11274e20-0426-4e80-84f4-bef79dbd6633/

We can temporarily disable the community display to allow these items to show properly. And can probably generate a report on all the problematic issues for further investigation.

**Comment by weiweishi** [comment]
The first object did migrate as "Open Access" and it was among the first batches to be migrated. I'm deleting the object and remigrate it again to check if there's any bug with the current version of the migration script. To discover the rest, we will need #715. 

https://hydranorth.library.ualberta.ca/files/3197xm13h#.VhiHWqLwMiE

(https://era.library.ualberta.ca/public/view/item/uuid:04b19808-e70a-4277-8a7c-55054ecc131d/)

**Comment by weiweishi** [comment]
ccid items are migrated fine. However deleted object:
https://era.library.ualberta.ca/public/view/item/uuid:081b0fda-0cfa-4b88-a6a2-90f1424caaa1/
is migrated as open-access. 
Closing this ticket and opening a new one.

**Comment by sfarnel** [comment]
This had been embargoed and ccid protected and so went through as open
access prior to addition of embargo functionality.

On Tue, Oct 13, 2015 at 4:49 PM, Weiwei Shi <notifications@github.com>
wrote:

> The first object did migrate as "Open Access" and it was among the first
> batches to be migrated. I'm deleting the object and remigrate it again to
> check if there's any bug with the current version of the migration script.
> To discover the rest, we will need #715
> <https://github.com/ualbertalib/HydraNorth/issues/715>.
>
> https://hydranorth.library.ualberta.ca/files/3197xm13h#.VhiHWqLwMiE
>
> (
> https://era.library.ualberta.ca/public/view/item/uuid:04b19808-e70a-4277-8a7c-55054ecc131d/
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/710#issuecomment-147875793>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
