### ISSUE TITLE
clicking on 'all files' from admin dashboard shows deposit process screen 

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#711]
when logged in as admin, when I clicked on All files I was taken to the following screen:

![screen shot 2015-10-10 at 6 43 49 pm](https://cloud.githubusercontent.com/assets/4697932/10414095/e5309eca-6f7f-11e5-8032-6b0df840a083.png)

**Comment by pbinkley** [comment]
Presumably will be fixed with #770

**Comment by sfarnel** [comment]
Cannot replicate; fixed by #770 
Closing
