### ISSUE TITLE
Special reports don't use the correct presenter

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#713]
@sfarnel discovered that Computing Science Technical Report and Structural Engineering Report items don't show the special report ids. These items are migrated as "Report" instead of their special types, so it doesn't use the proper presenter accordingly.

**Comment by sfarnel** [comment]
In discussion for soft launch determined to keep these as general type
report (as cstr and trid are more useful locally). @weiweishi noted could
either rake taske to update item type to more specific for controller or
use other method of identifiying these which would be presence of
ualterms:trid or ualterms:ser.

On Sun, Oct 11, 2015 at 1:47 AM, Weiwei Shi <notifications@github.com>
wrote:

> @sfarnel <https://github.com/sfarnel> discovered that Computing Science
> Technical Report and Structural Engineering Report items don't show the
> special report ids. These items are migrated as "Report" instead of their
> special types, so it doesn't use the proper presenter accordingly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/713>.
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
searching works for these items as the id is in the description as well as
the identifier field, though for trid is less precise. e.g., search for
SER93 brings up one result while search for TR88-01 brings up more than
1,000.

On Sun, Oct 11, 2015 at 9:39 AM, Sharon Farnel <sharon.farnel@ualberta.ca>
wrote:

> In discussion for soft launch determined to keep these as general type
> report (as cstr and trid are more useful locally). @weiweishi noted could
> either rake taske to update item type to more specific for controller or
> use other method of identifiying these which would be presence of
> ualterms:trid or ualterms:ser.
>
> On Sun, Oct 11, 2015 at 1:47 AM, Weiwei Shi <notifications@github.com>
> wrote:
>
>> @sfarnel <https://github.com/sfarnel> discovered that Computing Science
>> Technical Report and Structural Engineering Report items don't show the
>> special report ids. These items are migrated as "Report" instead of their
>> special types, so it doesn't use the proper presenter accordingly.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ualbertalib/HydraNorth/issues/713>.
>>
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
Thanks @sfarnel for the reminder. We do have a rake task in place to update the resource types in the two collections. rake hydranorth:update_special_itemtype

**Comment by sfarnel** [comment]
super; thanks @weiweishi !

On Mon, Oct 12, 2015 at 5:23 PM, Weiwei Shi <notifications@github.com>
wrote:

> Thanks @sfarnel <https://github.com/sfarnel> for the reminder. We do have
> a rake task in place to update the resource types in the two collections.
> rake hydranorth:update_special_itemtype
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/713#issuecomment-147547583>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
running the rake task to update the resource_type now...

**Comment by sfarnel** [comment]
Looking good:
https://hydranorth.library.ualberta.ca/files/rr171z54m#.Vh2EuUZSn9U

Will continue to check.

On Tue, Oct 13, 2015 at 4:22 PM, Weiwei Shi <notifications@github.com>
wrote:

> running the rake task to update the resource_type now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/713#issuecomment-147870893>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
rake task has finished. Spot checked some, and all seem to be working. Close the ticket now, but reopen the ticket if @sfarnel  you find more.

**Comment by sfarnel** [comment]
Thanks Weiwei. Noticed numbers a little lower than in current ERA but may
have been items that failed to migrate for some reason. Will add to #715

On Tue, Oct 13, 2015 at 4:53 PM, Weiwei Shi <notifications@github.com>
wrote:

> rake task has finished. Spot checked some, and all seem to be working.
> Close the ticket now, but reopen the ticket if @sfarnel
> <https://github.com/sfarnel> you find more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/713#issuecomment-147876388>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
- most seem to be ok but a few not; have included as part of final migration audit (#715) but opening again in case
- e.g., https://hydranorth.library.ualberta.ca/files/5h73px41m not showing ID no though it has community and collection info in the record

**Comment by sfarnel** [comment]
still some reports that aren't showing special identifier even though comm and coll are listed on item. perhaps a simple data update. Can also address as part of #715 

https://hydranorth.library.ualberta.ca/files/kd17cv35n#.ViAlAEZSn9V

**Comment by weiweishi** [comment]
This last item
https://hydranorth.library.ualberta.ca/files/kd17cv35n#.ViAlAEZSn9V has a
data issue. The report type is correct, but the id didn't migrate over.

The other item https://hydranorth.library.ualberta.ca/files/5h73px41m didn't
add to the Collection, so the rake task didn't change its resource type.
Fixed it. But the migration #715 should address any other cases.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
thanks @weiweishi !
