### ISSUE TITLE
metadata for item only in community has both community and collection listed

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#714]
not a major issue, but this item
https://hydranorth.library.ualberta.ca/files/bz60cw70v#.VhqpZqLwMiE (uuid:505d0a18-91fe-4fc1-8d31-2d754d1197ba)
which is an example of an old ERA item that was a member of a community only, not a collection as well, has on its full info page the correct community listed under both 'this file is in the following communities' and 'this file is in the following collections'

**Comment by anayram** [comment]
Here is another example.

https://hydranorth.library.ualberta.ca/files/pg15bd981#.Vh1qcC5VhBc

It is strange that only one of the communities is listed twice (both as collection and community).

**Comment by pbinkley** [comment]
Part of general cleanup of collections.

**Comment by sfarnel** [comment]
Included in #715 
Closing
