### ISSUE TITLE
migration verification scripts

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#715]
We need rake tasks to verify the migration, and generate reports accordingly. 
1. verify that all communities have been migrated, and the number of children collections.
2. verify that all collections have been migrated, and the number of children items;
3. verify that the objects are migrated with correct metadata, visibility, and relationships with collections/communities.

**Comment by sfarnel** [comment]
This can be used to help:
https://docs.google.com/spreadsheets/d/1Bc-UY2Bi9nsokbLV0Po21hWL3Q8I7bDgFpEuA39G1TY/edit?usp=sharing

On Sun, Oct 11, 2015 at 2:27 PM, Weiwei Shi <notifications@github.com>
wrote:

> We need rake tasks to verify the migration, and generate reports
> accordingly.
> 1. verify that all communities have been migrated, and the number of
> children collections.
> 2. verify that all collections have been migrated, and the number of
> children items;
> 3. verify that the objects are migrated with correct metadata, visibility,
> and relationships with collections/communities.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/715>.
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by anayram** [comment]
The spreadsheet referenced above contains list to verify visibility/access settings as specified in #697 

Do you need me to generate lists for the rest of the verifications?
I.e. pid lists for:
communities
collections under a specific community
items under a specific collection

**Comment by sfarnel** [comment]
check for special reports either not migrated or not changed to specific item type
check for deleted items migrated

**Comment by sfarnel** [comment]
see also #610 and #707

**Comment by sfarnel** [comment]
see also #730

**Comment by sfarnel** [comment]
- fix any urls in description fields that migrate incorrectly (see #734)

**Comment by sfarnel** [comment]
As of 7:36 am Oct 19th:

- when not logged in, search all returns 33,496 results
- when logged in as registered user, search all returns 35,065 results
- when logged in as UA user (i.e., with ccid), search all returns 35, 083 results

Given that metadata visibility for open and UA access items is the same; that almost all content currently in Hydranorth is migrated content; that no items were migrated as authenticated user access, we need to better understand these numbers.

**Comment by pbinkley** [comment]
Hmm - we should be able to craft a solr query to identify the items that
make the difference between those numbers.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by sfarnel** [comment]
Sounds great; thanks @pbinkley

On Mon, Oct 19, 2015 at 8:09 AM, Peter Binkley <notifications@github.com>
wrote:

> Hmm - we should be able to craft a solr query to identify the items that
> make the difference between those numbers.
>
> Peter
>
> Peter Binkley, Ph.D., MLIS
> Digital Initiatives Technology Librarian
> Information Technology Services
> peter.binkley@ualberta.ca
>
> 2-10K Cameron Library
> University of Alberta
> Edmonton, Alberta
> Canada T6G 2J8
>
> phone 780-492-3743
> fax 780-492-9243
>
> On 19 October 2015 at 07:51, Sharon Farnel <notifications@github.com>
> wrote:
>
> > As of 7:36 am Oct 19th:
> >
> > - when not logged in, search all returns 33,496 results
> > - when logged in as registered user, search all returns 35,065 results
> > - when logged in as UA user (i.e., with ccid), search all returns 35,
> > 083 results
> >
> > Given that metadata visibility for open and UA access items is the same;
> > that almost all content currently in Hydranorth is migrated content; that
> > no items were migrated as authenticated user access, we need to better
> > understand these numbers.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/715#issuecomment-149218951
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/715#issuecomment-149224122>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
I think we can run a task to compare the returned IDs from solr really quickly. I will do that this morning. 

Weiwei

**Comment by pbinkley** [comment]
From discussion on Oct. 19:
- verify that GenericFile and Collection objects exist for ERA items: report problems
- verify and fix problems:
  - collection.belongsToCommunity
  - collection.member_ids (note: has been removed from thesis collection)
  - GenericFile.belongsToCommunity
  - GenericFile.hasCollecitonID, hasCollection
- verify visibility (CCID, registered, embargo, private, dark) - report problems

**Comment by sfarnel** [comment]
ensure items also display proper collection and community information (e.g., https://hydranorth.library.ualberta.ca/files/qr46r1242#.Vi5AAUarX9V not showing collection).

**Comment by sfarnel** [comment]
ensure source information #707 and linked to related item information #610 #706  migrated and displaying
