### ISSUE TITLE
Fix js refresh bug in #688 / #690

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#716]
The bug that prevents the user from breaking out the reload cycle for the notification screen has been moved to the upload page.

**Comment by nnunn** [comment]
really? hmmm is this up at https://hydranorth.library.ualberta.ca ? Which step of the upload are you seeing this?

**Comment by nnunn** [comment]
Ok I see that it's not up a hydranorth. I am in class right now, but as soon as I am at my dev machine I'll try to track down the issue.

**Comment by nnunn** [comment]
My fix for this bug - pull request "687 javascipt progress window #690" has not been merged into sprint 27 or master. Were you testing this branch and seeing the issue?

**Comment by pgwillia** [comment]
Yes.  I was reviewing the pull request for both of the ux branches and not being able to get past the upload page (files/new) to test the rest of the changes.

**Comment by nnunn** [comment]
Ok - will see what's going on as soon as I'm at my dev machine. Sorry!

**Comment by pbinkley** [comment]
Yes, Tricia was working on the PR but couldn't test other features because
of the bug. She's going to comment out the notification screen so as to be
able to get to the other steps that need testing. We're going to cut a
release at 11:00 today and another tomorrow; I'm hoping the rest of the UX
PR can be merged in time for today's, but we'll see. It will be great if
you can look at this when you get back.

**Comment by nnunn** [comment]
I made a change directly in github that *might* fix the issue. I can't test it because I'm not on my dev machine. Tricia could you see if that worked? (or this can wait, but I thought I would try to get it in before the 11am deadline).

**Comment by pgwillia** [comment]
I'll try it out.

**Comment by nnunn** [comment]
no wait - gah that won't work.

**Comment by nnunn** [comment]
sorry let me see if I can figure it out. I'll keep you posted.

**Comment by pgwillia** [comment]
The problem is that there is a .progress on the upload page as well.

**Comment by nnunn** [comment]
right - I now added "#documents .progress" as the test. Could you see if that works?

**Comment by pgwillia** [comment]
It's looking good so far.

**Comment by nnunn** [comment]
Ok - let me know. I think it should be fixed.

**Comment by pbinkley** [comment]
Fixed in #690
