### ISSUE TITLE
404 not found error when trying to confirm new ERA account

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#718]
I went to new ERA to create a new account. I entered email and password and received the confirmation email.

However, when I click on the link in the confirmation email I get directed back to old ERA with the following error:

![screen shot 2015-10-13 at 10 02 40 am](https://cloud.githubusercontent.com/assets/4697932/10460454/986bfe68-7191-11e5-849e-ee011c06fcc0.png)

**Comment by pbinkley** [comment]
The link works if you manually substitute "hydranorth.library.ualberta.ca" for "era.library.ualberta.ca". So we don't really need to fix this unless it interferes with testing, since it will work for users once we move the domain.
