### ISSUE TITLE
Community pages not showing complete list of associated collections

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#724]
Examples:

Faculty of Pharmacy and Pharmaceutical Sciences
https://hydranorth.library.ualberta.ca/collections/44558r29h
In HydraNorth shows 1 collection out of 2
[See in old ERA](https://era.library.ualberta.ca/public/view/community/uuid:36311147-ee8f-4d3f-969f-17b1f21fb206)

Faculty of Medicine and Dentistry
https://hydranorth.library.ualberta.ca/collections/44558r10s
Shows 3 collections out of 8
[See in old ERA](https://era.library.ualberta.ca/public/view/community/uuid:b496aebe-1e5a-4a23-8492-9bbd382367de)

School of Public Health
Shows 4 out of 7 collections
https://hydranorth.library.ualberta.ca/collections/44558r308
[See in old ERA](https://era.library.ualberta.ca/public/view/community/uuid:85bf5c6e-e252-487a-ab98-8c5b20dfffbf)

**Comment by anayram** [comment]
Collections that are not visible in this page are available, just are not showing on this page.

**Comment by weiweishi** [comment]
I think the maximum number of collections allow to show on the side panel
is set to 3 right now. Can be increased, or remove the limitation all
together.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by johnhuck** [comment]
There is at least one example of a community that should have 16 collections, but only has 6 (i.e., more than 3 are being displayed now).
https://hydranorth.library.ualberta.ca/collections/44558r821
https://era.library.ualberta.ca/public/view/community/uuid:4eb8813a-040f-4a15-a42a-7e6345542b0c

Out of 25 communities that contain collections that I checked, only 5 had all of the collections they were supposed to, so this issue appears to be widespread.

Also noted are several (many?) collections that do not have all the items in them they are supposed to. If this is related at all to the above issue, it may also be widespread. The items can in most cases be found with a title search, but clicking the collection on an individual record returns you to the sparsely populated collection.

Example:
Collection (should have 7 items. 0 are displayed):
https://hydranorth.library.ualberta.ca/collections/44558v269
https://era.library.ualberta.ca/public/view/collection/uuid:6edeb85a-d14d-43b4-a29c-8b2e861bd8b4

Example of item in that collection:
https://hydranorth.library.ualberta.ca/files/rb68xc623#.Vh2M_CpViko

**Comment by weiweishi** [comment]
The collection object in Fedora contains the right number of members (16 in @johnhuck 's first example,   and 6 in the last example) so the error is at the application level - around permission?)

**Comment by weiweishi** [comment]
should we bump this into priority high @sfbetz @pbinkley ?

**Comment by johnhuck** [comment]
I recorded my observations in this spreadsheet. https://docs.google.com/a/ualberta.ca/spreadsheets/d/1dnQoqx415EwVfnPkrjRNXSrf-t7xpdqLqMdpUlZ8xVw/edit?usp=sharing

**Comment by pbinkley** [comment]
It looks like a data problem rather than a code problem, at this point
anyway: we can script a fix to associate collections with their communities
without remigrating.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by sfarnel** [comment]
It's interesting, though, that when you look at the item John gave as an
example, it is showing properly as a member of the collection and
community. So it seems the challenge is in the collection being aware of
who its members are.

On Tue, Oct 13, 2015 at 5:29 PM, Peter Binkley <notifications@github.com>
wrote:

> It looks like a data problem rather than a code problem, at this point
> anyway: we can script a fix to associate collections with their communities
> without remigrating.
>
> Peter Binkley, Ph.D., MLIS
> Digital Initiatives Technology Librarian
> Information Technology Services
> peter.binkley@ualberta.ca
>
> 2-10K Cameron Library
> University of Alberta
> Edmonton, Alberta
> Canada T6G 2J8
>
> phone 780-492-3743
> fax 780-492-9243
>
> On 13 October 2015 at 17:25, johnhuck <notifications@github.com> wrote:
>
> > I recorded my observations in this spreadsheet.
> >
> https://docs.google.com/a/ualberta.ca/spreadsheets/d/1dnQoqx415EwVfnPkrjRNXSrf-t7xpdqLqMdpUlZ8xVw/edit?usp=sharing
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/724#issuecomment-147881979
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/724#issuecomment-147882548>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
And the member ids are actually part of the parent collection. And they are
set to visibility open. So I'm still checking the collection#show method to
understand the access_control_logic.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
didn't read the issue carefully enough, and thought it was something different (not all collections/communities show on the side panel of object record page). This is a duplication of #729, and @mbarnett is working on that.
