### ISSUE TITLE
Email for confirmation instructions coming from HydraNorth

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#726]
We'll need to update email address for account confirmation etc. Right now coming from hydranorth@mailinator.com . Should it come from eraadmi@ualberta.ca?

![confirm email](https://cloud.githubusercontent.com/assets/12801010/10470281/1c607ee2-71c9-11e5-8b0a-59f05c5aa56c.png)

I'm assuming link also will work in prod. Right now the confirmation link is coming from:

http://localhost/users/confirmation?confirmation_token=xWyacBy9Da-89_h5fvK_

I manually updated url in browser to:
http://plano.library.ualberta.ca/users/confirmation?confirmation_token=xWyacBy9Da-89_h5fvK_

And success!

**Comment by pgwillia** [comment]
hydranorth@mailinator.com is just for the default development environment.  Both issues should be fixed in production deployment without any changes required.
