### ISSUE TITLE
deleted objects are migrated as Open Access

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#727]
discovered some deleted items in the final migration package:
https://era.library.ualberta.ca/public/view/item/uuid:081b0fda-0cfa-4b88-a6a2-90f1424caaa1/

It was migrated as an Open Access object. Not sure if there are any other such objects. Should be included as part of #715.

**Comment by sfarnel** [comment]
Yes, there may be a few like this. Definitely must be part of #715

On Tue, Oct 13, 2015 at 5:01 PM, Weiwei Shi <notifications@github.com>
wrote:

> discovered some deleted items in the final migration package:
>
> https://era.library.ualberta.ca/public/view/item/uuid:081b0fda-0cfa-4b88-a6a2-90f1424caaa1/
>
> It was migrated as an Open Access object. Not sure if there are any other
> such objects. Should be included as part of #715
> <https://github.com/ualbertalib/HydraNorth/issues/715>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/727>.
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by anayram** [comment]
This record was deleted on October 8 2015, i.e. after the ERA dump we used for migration (generated on September 10 2015). Below is an audit entry where this deletion is recorded.

I can generate a list of items that were deleted on or after September 10 and pass it along to remove items from HydraNorth.

<audit:record ID="AUDREC5">
<audit:process type="Fedora API-M"/>
<audit:action>modifyObject</audit:action>
<audit:componentID/>
<audit:responsibility>fedoraAdmin</audit:responsibility>
<audit:date>2015-10-08T01:57:08.230Z</audit:date>
<audit:justification>
ERA: Action[/action/item] Username[admin] WorkflowState[Archive] - Modify object state to Delete.
</audit:justification>
</audit:record>

**Comment by sfarnel** [comment]
Another aspect of the final audit; #715

On Wed, Oct 14, 2015 at 9:16 AM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> This record was deleted on October 8 2015, i.e. after the ERA dump we used
> for migration (generated on September 10 2015). Below is an audit entry
> where this deletion is recorded.
>
> I can generate a list of items that were deleted on or after September 10
> and pass it along to remove items from HydraNorth.
>
>
>
> audit:actionmodifyObject/audit:action
> audit:componentID/
> audit:responsibilityfedoraAdmin/audit:responsibility
> audit:date2015-10-08T01:57:08.230Z/audit:date
> audit:justification
> ERA: Action[/action/item] Username[admin] WorkflowState[Archive] - Modify
> object state to Delete.
> /audit:justification
> /audit:record
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/727#issuecomment-148081112>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
Shall we close this issue and just link to it from #715 ?

**Comment by anayram** [comment]
I think so, that would be easier to follow all verifications in one ticket.

I am assuming we will get a new ERA dump as part of the service transition process that can give us any files that changed between Spetember 10 and the final launch date. Is this correct?

**Comment by pbinkley** [comment]
We got one last week, which is now the baseline for Mariana's lists (as I
understand it), but we'll need another one to catch up to our actual
transition date.

**Comment by anayram** [comment]
The lists were generated based on the dump used for migration (September 10 2015) given that this way we can audit access consistently with the package used for migration.

If we can get another partial dump that covers 1) deletions, 2) modifications and 3) new items created *on or after September 10 up to the actual transition date*, that will be enough to catch up with items in old ERA.

**Comment by pbinkley** [comment]
Henry gave us a new full foxml dump on Oct. 8:
/libroot/digital_init/Hydra_DAMS/ERA/ERA_migration/FOXML_dumps/era_foxml_20151008
- so we're only a few days out of date, if we use that. But yes, we'll need
another up-to-date dump to finish with.

Peter

**Comment by anayram** [comment]
Yes, we used the Oct 8 dump to generate another migration package in case re-migration was necessary.

We can use the Oct 8 dump to generate lists of objects modified on or after Sept 10, but there could be conflicts between objects changed between Sept 10 - Oct 8, and objects changed between Oct 8 and the actual transition date.

**Comment by sfarnel** [comment]
All we will really need is a partial dump of anything changed between when ERA was brought back up Oct 6 and when it is shut down on transition day for launch. We can these details to the transition doc specs.

**Comment by anayram** [comment]
Right, those dates work if items between Sept 10 and Oct 6 were re-migrated.

If not, a partial dump between Sept 10 and the actual launch date will
cover everything.


On Wednesday, 14 October 2015, Sharon Farnel <notifications@github.com>
wrote:

> All we will really need is a partial dump of anything changed between when
> ERA was brought back up Oct 6 and when it is shut down on transition day
> for launch. We can these details to the transition doc specs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/727#issuecomment-148144430>
> .
>


-- 
Mariana

**Comment by anayram** [comment]
Here is the complete list of items deleted in old ERA after September 10 2015 (to be deleted from HydraNorth ERA)

uuid:0988f8dc-7ba2-4d97-995e-20c065417846
uuid:23f239ec-f175-4cff-b7b4-69cb0e410473
uuid:27b1dbd6-8a69-4c38-81cc-34cef7be01fd
uuid:2ba328a9-51ee-406d-8045-2adcf1b00307
uuid:2f50a9e3-bb8d-4c91-b59c-94c37edda646
uuid:3fbcf166-79ad-4601-99f4-f0dbde292b94
uuid:59804c08-b5ce-4315-9a13-c608b362d004
uuid:61cd80d0-d61f-4f17-895d-587c378f6cfc
uuid:8f4c8c69-8f76-4abe-b7c4-dd85021e93b8
uuid:a958a40d-d0c3-498f-805c-324931163364
uuid:dc52c1c7-3ae1-41e5-a009-ffa1d55e3f5b
uuid:e3c83a13-5654-4d2b-80e5-ea5c4313bd19
uuid:f7bbe110-6362-4a86-8898-27f299e80631
uuid:fd8bf3f6-8d6d-4475-bfbb-112c48f350a0
uuid:02574f82-ec1a-470c-bdaf-f6f714abbf02
uuid:081b0fda-0cfa-4b88-a6a2-90f1424caaa1
uuid:3bf01c3e-6169-4c99-aba5-2e0af290bdb3
uuid:7223d520-616b-477f-9710-81da4c59c916
uuid:d0418cd8-f760-4c49-9201-5f61b2e5bcaa
uuid:ff5bd34e-9dc5-4940-ab2d-df681a779461

**Comment by pbinkley** [comment]
OK, I've deleted these. Only three were still present in Hydranorth.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
objects were deleted and remigrated.
