### ISSUE TITLE
Authenticated access now showing up as visibility option?

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#728]
We have a new "Authenticated access" option showing up on the permissions section of the deposit form. We only need the three levels: Open, CCID, and Private + embargo

![authenticated access](https://cloud.githubusercontent.com/assets/12801010/10470689/4ca89226-71cc-11e5-99d0-e6bb85e1b1c7.png)

**Comment by mbarnett** [comment]
This would seem to contradict the original CCID ticket, where it was decided we wanted to treat Authenticated and CCID as distinctly different groups: https://github.com/ualbertalib/HydraNorth/issues/582#issuecomment-140478733.

**Comment by sfbetz** [comment]
Ah yes ... I see - I guess I wasn't part of that convo. I think this is going to cause some confusion but will reclassify as definitely not a bug.

**Comment by gsharder** [comment]
I'm not clear on the rationale behind behind the requirement but wondering
if it traces back to discussions around us being an adoptive repository,
i.e. more than just UA people can deposit (Peter had left a comment about
this). Any external depositors should be depositing to fulfill an open
access requirement so no restrictions should be imposed or allowed in that
case.

On Tue, Oct 13, 2015 at 5:12 PM, Sonya Betz <notifications@github.com>
wrote:

> Ah yes ... I see - I guess I wasn't part of that convo. I think this is
> going to cause some confusion but will reclassify as definitely not a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/728#issuecomment-147879620>
> .
>



-- 
Geoff Harder
Associate University Librarian
Information Resources and Digital Initiatives

University of Alberta Libraries
2-10H Cameron Library, University of Alberta
Edmonton, AB, Canada T6G 2J8
780.492.7914

*geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
library.ualberta.ca <http://library.ualberta.ca>*

**Comment by pbinkley** [comment]
I think it arose from the need to map old ERA items that have those
permissions to something in HydraNorth. Without this we need to map them to
CCID-protected (unless open would be ok). Assuming we fix the mapping to
make this an empty category, we could reverse the interface changes,
presumably easily.

**Comment by sfbetz** [comment]
I can understand preventing registered-but-not-CCID-authed users access to CCID protected content, but can't think of a use case where we would need to restrict an item to *only* registered (not CCID) users. But I'm not familiar with why this may have been used in old ERA!

Not a launch killer, IMO.

**Comment by mbarnett** [comment]
@pbinkley it's a bit bigger than just the interface change, IMO. We'd want to rip out all of the institutional visibility code that was added as part of this, since it's all essentially dead code and needless complexity/bug surface area if ccid == authenticated

**Comment by mbarnett** [comment]
> I can understand preventing registered-but-not-CCID-authed users access to CCID protected content, but can't think of a use case where we would need to restrict an item to only registered (not CCID) users. 

Just to clarify, that's not how this works (confusing!):

Setting it to authenticated means it's visible to all logged in users ("I don't have a CCID" and "I have a CCID" alike). Setting it to CCID specifically restricts it to users who log in via "I have a CCID" only.

Presumably the idea in the original ticket was that there might be some classes of things that should be visible to any user with an account (perhaps in a future where we are also servicing other institutions and want any of them to be able to view an item), and some classes of things that should only be visible to users we can map to a specific institution via CCID.

**Comment by sfarnel** [comment]
https://docs.google.com/document/d/13T9QnCWw4Bqcpw7-9uKvHR-y1OGOA6CV4bpCpaI7Ixc/edit?usp=sharing
gathers together visibility/access scenarios for current ERA and what was
understood via #582 for Hydranorth.

As noted there, ERA had only open access, dark and ccid-protected (with the
latter two also enabling an embargo for a time). The difference between
registered users and the general public was only in what they could do
(i.e., deposit, mark favourites, etc.) not what they could see or access.

The concept of a registered user (tho not with UA ccid username/password)
is the basis of enabling things like access within a
group/institute/project not solely associated with UA and underlies the
idea of 'private but shared with these individuals' functionality as these
could be people not associated with UA.

On Tue, Oct 13, 2015 at 6:17 PM, Matthew Barnett <notifications@github.com>
wrote:

> I can understand preventing registered-but-not-CCID-authed users access to
> CCID protected content, but can't think of a use case where we would need
> to restrict an item to only registered (not CCID) users.
>
> Just to clarify, that's not how this works (confusing!):
>
> Setting it to authenticated means it's visible to all logged in users ("I
> don't have a CCID" and "I have a CCID" alike). Setting it to CCID
> specifically restricts it to users who log in via "I have a CCID" only.
>
> Presumably the idea in the original ticket was that there might be some
> classes of things that should be visible to any user with an account
> (perhaps in a future where we are also servicing other institutions and
> want any of them to be able to view an item), and some classes of things
> that should only be visible to users we can map to a specific institution
> via CCID.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/728#issuecomment-147889933>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfbetz** [comment]
Yep! I get how it works (CCID is a subset of registered). My question is, basically, if we allow *anyone* to register and create an account, then having a visibility setting based on registered users isn't really meaningful. If we have no way of distinguishing between institutions, then this doesn't help with any group based visibility controls either. Sharon's example of private but shared makes sense, but again, this isn't dependent on an item having an overarching "authenticated" visibility status, and is really only dependent on the users it's being shared with having an account. I'm cautious about creating an entirely new category of visibility that may give users an inaccurate idea of what it does...

**Comment by sfbetz** [comment]
But, again, I think this can be resolved post-launch!

**Comment by pbinkley** [comment]
Moved to PostProduction milestone to give it a home.

**Comment by sfarnel** [comment]
makes sense. need to discover if there is indeed a user story there :)

On Wed, Oct 14, 2015 at 9:30 AM, Sonya Betz <notifications@github.com>
wrote:

> But, again, I think this can be resolved post-launch!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/728#issuecomment-148086930>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
