### ISSUE TITLE
ERA_Collections: Collection logo

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#73]
As admin I want to be able to upload a logo or thumbnail that will represent the collection

**Comment by pbinkley** [comment]
May already be there.

**Comment by pbinkley** [comment]
Decision 2016-02-01: we like logos for communities, but not collections - so the work is to allow custom logos for communities, and remove display of logo for collections

**Comment by sfbetz** [comment]
Requirement captured in Sufia 7 repo. Won't fix for Sufia 6.
