### ISSUE TITLE
Open access item (migrated) has private label but is behaving like open access

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#730]
https://hydranorth.library.ualberta.ca/files/2801ph22b#.Vh5j60ZSn9U (https://era.library.ualberta.ca/public/view/item/uuid:8a2723a2-f7a3-4234-a7de-d8d6aba0ea35/)

has the red private label but is displaying and is downloadable when not logged in as owner. spot checking implies this is a one-off but worth adding to #715

**Comment by mbarnett** [comment]
Hey @criedlberger do you happen to know or remember anything about this? It looks like you may have touched it at some point in the past.

Tracing this back lands me at this Solr Permissions Document

```
#<Hydra::PermissionsSolrDocument:0x000000052d8ca0 @_source={"id"=>"2801ph22b", "read_access_group_ssim"=>["public"], "edit_access_person_ssim"=>["riedlber@ualberta.ca"]}, @response={"responseHeader"=>{"status"=>0, "QTime"=>70, "params"=>{"qt"=>"permissions", "id"=>"2801ph22b", "wt"=>"ruby", "q"=>"{!raw f=id v=$id}", "echoParams"=>"all", "fl"=>"\n        id,\n        access_ssim,\n        discover_access_group_ssim,discover_access_person_ssim,\n        read_access_group_ssim,read_access_person_ssim,\n        edit_access_group_ssim,edit_access_person_ssim,\n        depositor_ti,\n        embargo_release_date_dtsi\n        inheritable_access_ssim,\n        inheritable_discover_access_group_ssim,inheritable_discover_access_person_ssim,\n        inheritable_read_access_group_ssim,inheritable_read_access_person_ssim,\n        inheritable_edit_access_group_ssim,inheritable_edit_access_person_ssim,\n        inheritable_embargo_release_date_dtsi\n      ", "rows"=>"1", "facet"=>"off"}}, "response"=>{"numFound"=>1, "start"=>0, "maxScore"=>11.053243, "docs"=>[{"id"=>"2801ph22b", "read_access_group_ssim"=>["public"], "edit_access_person_ssim"=>["riedlber@ualberta.ca"]}]}}>
```

It looks like even though it's fedora read_groups are correctly empty:

```ruby
 f = GenericFile.find('2801ph22b')
f.read_groups
=> []
```

the solr index was directly manipulated to add public to the read group?

**Comment by sfarnel** [comment]
This is still a bug

**Comment by sfbetz** [comment]
@weiweishi can you fix in the console by reindexing?

**Comment by sfbetz** [comment]
@leahvanderjagt @sfarnel can we confirm this is a one-off issue?

**Comment by sfarnel** [comment]
Item: https://era.library.ualberta.ca/files/2801ph22b

Seems to be the only one I can find like this in this collection, so assume a one-off problem. In checking discovered another issue with this one (see #1024)

**Comment by pbinkley** [comment]
Possibly related to #593 as well. 

- [ ] discover how many of these there are using "Characterization: not yet characterized" status
- [ ] determine whether they can resolved by using an upgraded FITS, or some other characterization tool, or simply by manual checking and setting of values
- [ ] if possible, fix the automated process (by upgrades etc.) to give better results
- [ ] provide report of uncharacterized items for repair
