### ISSUE TITLE
PR to Sufia for embargo fix

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#732]
Contribute our fix in #708 to the community. The fix is in our Sufia repo: https://github.com/ualbertalib/sufia/commit/4edf55214f7064e8a4aec7290f4f1b30a60571d8

**Comment by pbinkley** [comment]
This should be ready to submit.

**Comment by pgwillia** [comment]
Missed our chance, modern sufia deals with embargoes.
