### ISSUE TITLE
CCID-protected download link fails if you aren't logged in

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#733]
The download link for a CCID-protected file (e.g. https://hydranorth.library.ualberta.ca/downloads/hm50ts561), when accessed by a userwho isn't logged in, causes a redirect to the front page with a "Not authorized" notification. There's no way for the user to log in and get the file they wanted. Since these links may be shared or bookmarked among users with CCIDs, they should always get a user to the file whether they're logged in before-hand or not.

This also affects redirection of old ERA urls: https://era.library.ualberta.ca/public/view/item/uuid:8d7620c2-5ba1-4d76-8482-db13b615811e/DS1/Alumni%20Relations%20Benchmarks,%202013%20Edition.pdf (tested by changing host to hydranorth ). It redirects to the front page, with a "Not authorized" notice. There's no way to log in and navigate to the file you want. The item-level redirect works correctly ( https://era.library.ualberta.ca/public/view/item/uuid:8d7620c2-5ba1-4d76-8482-db13b615811e/): it takes you to the log-in screen, and after you log in you go to the item screen.

**Comment by mbarnett** [comment]
The how-to on fixing this, when we get to it: https://github.com/plataformatec/devise/wiki/How-To%3a-Redirect-to-a-specific-page-when-the-user-can-not-be-authenticated

**Comment by mbarnett** [comment]
I cannot re-create this, locally or in Production. When not logged in, attempting to download a CCID-protected file redirects me to /users/sign_in, and after signing in, the browser downloads the file requested.

**Comment by pbinkley** [comment]
Me neither. I'll close it.
