### ISSUE TITLE
handle link in the description doesn't have the correct url

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#734]
https://hydranorth.library.ualberta.ca/files/c534fp43r#.Vh7Iyi5VhBc

In the description it says:
Please click here for Part 2 and Part 3. 

where the Part2 links to https://hydranorth.library.ualberta.ca/files/%5C%22http://hdl.handle.net/10402/era.39273%5C%22

instead of the true handle link. 

Same with the other link

**Comment by pbinkley** [comment]
There are [39 items](https://hydranorth.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=&author=&title=&description=href&date_created=&allsubject=&language=&resource_type=&sort=score+desc%2C+date_uploaded_dtsi+desc&search_field=advanced&commit=Search) with "href" in the description field  - maybe we can just fix them manually.

**Comment by sfarnel** [comment]
I'll fix now.

On Wed, Oct 14, 2015 at 4:19 PM, Peter Binkley <notifications@github.com>
wrote:

> There are 39 items
> <https://hydranorth.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=&author=&title=&description=href&date_created=&allsubject=&language=&resource_type=&sort=score+desc%2C+date_uploaded_dtsi+desc&search_field=advanced&commit=Search>
> with "href" in the description field - maybe we can just fix them manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/734#issuecomment-148219648>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
fixed (except see below); added final check to post migration audit (#715). Couple of things of note:

- this threw an error: https://hydranorth.library.ualberta.ca/collections/44558r34c/edit

- before leaving the office fixed url in collection (e.g., Ad $ Summary) and was able to. just now tried to update the FGSR url in the Theses and Dissertations to Spring 2009 collection but couldn't as it was requiring a license. This is different than current ERA in that license/rights isn't set at the collection or community level (although access/visibility can be) and I believe new to Hydranorth. In the case of this collection, no option available is applicable as it would have to be a freetext rights area.

**Comment by weiweishi** [comment]
I think we have discussed this in the past, but can't find an issue for it: re: license field on collection. Does collection need to have a required license field? And does it need to be on the collection creation/edit page? @sfarnel @sfbetz

**Comment by sfarnel** [comment]
I recall discussion of this as well, tho haven't been able to pin down
documentation. My thought based on current ERA content and past experience
with ERA is that a license at the collection level could/would be very
useful, but making it required would be problematic. If we go with this in
the future enabling the freeform rights option could/would also be a
helpful option.

On Wed, Oct 14, 2015 at 10:29 PM, Weiwei Shi <notifications@github.com>
wrote:

> I think we have discussed this in the past, but can't find an issue for
> it: re: license field on collection. Does collection need to have a
> required license field? And does it need to be on the collection
> creation/edit page? @sfarnel <https://github.com/sfarnel> @sfbetz
> <https://github.com/sfbetz>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/734#issuecomment-148278009>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
A collection-level license would just mean that that license applies to all
the items in the collection, wouldn't it? There isn't anything at the
collection-level that needs a license. So it would come into play as a
validation mechanism when an item is added to the collection (you can't
come in without the right license). So I think it's unnecessary to require
a license at the collection level, since very few collections would impose
a license on their member items.

Does that make sense?

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by sfbetz** [comment]
@pbinkley makes perfect sense to me. I don't think a collection needs to have a required license field.

**Comment by gsharder** [comment]
I agree too.

On Thu, Oct 15, 2015 at 10:32 AM, Sonya Betz <notifications@github.com>
wrote:

> @pbinkley <https://github.com/pbinkley> makes perfect sense to me. I
> don't think a collection needs to have a required license field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/734#issuecomment-148446589>
> .
>



-- 
Geoff Harder
Associate University Librarian
Information Resources and Digital Initiatives

University of Alberta Libraries
2-10H Cameron Library, University of Alberta
Edmonton, AB, Canada T6G 2J8
780.492.7914

*geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
library.ualberta.ca <http://library.ualberta.ca>*

**Comment by sfarnel** [comment]
makes good sense to me.

On Thu, Oct 15, 2015 at 11:35 AM, gsharder <notifications@github.com> wrote:

> I agree too.
>
> On Thu, Oct 15, 2015 at 10:32 AM, Sonya Betz <notifications@github.com>
> wrote:
>
> > @pbinkley <https://github.com/pbinkley> makes perfect sense to me. I
> > don't think a collection needs to have a required license field.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/734#issuecomment-148446589
> >
> > .
> >
>
>
>
> --
> Geoff Harder
> Associate University Librarian
> Information Resources and Digital Initiatives
>
> University of Alberta Libraries
> 2-10H Cameron Library, University of Alberta
> Edmonton, AB, Canada T6G 2J8
> 780.492.7914
>
> *geoffrey.harder@ualberta.ca <geoffrey.harder@ualberta.ca>
> library.ualberta.ca <http://library.ualberta.ca>*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/734#issuecomment-148467675>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
@sfarnel if you've done the manual fixes to the mangled links, can we close this? The collection license discussion has been dealt with in #789

**Comment by sfarnel** [comment]
still getting an error when trying to edit this collection:

https://hydranorth.library.ualberta.ca/collections/44558r34c/edit

other than that, good to go

**Comment by weiweishi** [comment]
This is the error message for this collection:
ActionView::Template::Error (Missing partial
collections/_collection_action_menu, application/_collection_action_menu,
catalog/_collection_action_menu, catalog/_collection_action_menu with
{:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb,
:builder, :raw, :ruby, :coffee, :jbuilder, :haml]}. Searched in:
  * "/var/www/sites/hydranorth/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/devise-3.5.2/app/views"
  * "/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/sufia-6.2.0/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/mailboxer-0.13.0/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight_advanced_search-5.1.4/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/browse-everything-0.8.2/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/hydra-batch-edit-1.1.1/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/hydra-collections-5.0.3/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-gallery-0.4.0/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/hydra-editor-1.0.4/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/gems/blacklight-5.14.0/app/views"
  *
"/var/www/sites/hydranorth/vendor/ruby/2.1.0/bundler/gems/kaminari-7f7108e12bdd/app/views"
):
    38:
    39:   </td>
    40:   <td class="text-center">
    41:     <%= render partial:'collection_action_menu', locals: { id: id }
%>
    42:    </td>
    43: </tr>
    44: <tr id="detail_<%= id %>"> 
  app/views/my/_index_partials/_list_collections.html.erb:41:in
`_app_views_my__index_partials__list_collections_html_erb__4354519892730247422_69813109434020'
  app/views/my/_index_partials/_default_group.html.erb:20:in `block in
_app_views_my__index_partials__default_group_html_erb___1731854191856352984_69813095679760'
  app/views/my/_index_partials/_default_group.html.erb:15:in `each'
  app/views/my/_index_partials/_default_group.html.erb:15:in
`each_with_index'
  app/views/my/_index_partials/_default_group.html.erb:15:in
`_app_views_my__index_partials__default_group_html_erb___1731854191856352984_69813095679760'


*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
Remaining issue relates to #704.
