### ISSUE TITLE
javascript on batch upload form to select community/collection remove collections

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#735]
On the batch upload form where users select communities/collections, whenever the collection on the second (or any sequential groups) is selected, it will reset all the previous collection selections.

**Comment by weiweishi** [comment]
@sfbetz could you please label this with a priority? Thx!

**Comment by sfbetz** [comment]
Marked as low priority - likelihood of user selecting multiple communities for an item seems low risk.

**Comment by weiweishi** [comment]
This bug is still not fixed:
![screen shot 2016-02-23 at 11 00 34 am](https://cloud.githubusercontent.com/assets/2047614/13261319/c8f4c9c2-da1c-11e5-9dc9-fffd72b866e4.png)

**Comment by sfbetz** [comment]
Also, functionality for multiple collections / communities should be present on edit form as well ... can that be wrapped up in this issue, or make a new one?

**Comment by pbinkley** [comment]
No longer relevant (don't allow multiple collections).
