### ISSUE TITLE
Community and collection fields in item edit display ids instead of names

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#739]
In edit form communities and collections displayed as ids in field. User can't easily edit community. Can we update to same drop-down menu format as in deposit form?
![2015-10-14_16-39-02](https://cloud.githubusercontent.com/assets/12801010/10500118/08d528d0-7293-11e5-9e76-834e808b8679.png)

**Comment by weiweishi** [comment]
And it should be a dropdown menu similarly to the batch upload form instead of text fields.

**Comment by pbinkley** [comment]
This is the broader collection issue: #785 . If it makes sense to resolve that one first, feel free.

**Comment by pbinkley** [comment]
This discussion of Admin Sets and Collections on Hydra-Tech, with links to code in curation concerns, might be useful: https://groups.google.com/forum/#!topic/hydra-tech/-1IIzDP8U7U
