### ISSUE TITLE
Theses need to display dissertant on search results page

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#742]
Theses have no creator field; instead, the author is in the "dissertant" field. This is displayed correctly in the item-level page, e.g. here, where the creator "Smith, Lisa Wynne" comes from the dissertant field:

![dissertant-item](https://cloud.githubusercontent.com/assets/272816/10519412/d24238ae-7322-11e5-9540-ec76deae2ae0.png)

But on the search results page the Creator is empty:

![dissertant-search](https://cloud.githubusercontent.com/assets/272816/10519435/f802010a-7322-11e5-89d9-c41d5d097d81.png)

We need to modify the search results to use creator field if it exists, otherwise use dissertant field if it exists.

**Comment by weiweishi** [comment]
Is the label okay?
![image](https://cloud.githubusercontent.com/assets/2047614/10535419/148c66ee-73a0-11e5-9904-6759aa3a0427.png)

**Comment by sfarnel** [comment]
I think the label can be left as creator as dissertant is simply a more specific type of creator, and creator is very intuitive. There are other cases in the metadata where what we name something for human view is something more general than the specific label of the property.

**Comment by pbinkley** [comment]
I agree, Creator is good for consistency.
