### ISSUE TITLE
Use _ssim instead of _tesim fields to match collection ids

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#745]
See https://github.com/ualbertalib/HydraNorth/issues/729#issuecomment-148469217

Low priority because the probability of error is very low, but should get fixed.

**Comment by pgwillia** [comment]
Fixed in #777

**Comment by pgwillia** [comment]
Sorry, actually only half fixed: https://github.com/ualbertalib/HydraNorth/blob/master/app/models/search_builder.rb#L8
