### ISSUE TITLE
CCID session remains active after user log out

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#753]
I apparently logged out successfully, but was not challenge for CCID / PW when logging in again. @sfarnel also found the same thing. v.1.0.6

**Comment by weiweishi** [comment]
that is a common behavior for any campus application using IST's Shibboleth
authentication. Tested with Gmail last week with @pbinkley, and gmail/apps
behaves the same way.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by johnhuck** [comment]
OK, great. We weren't sure. I'll close the issue then.
