### ISSUE TITLE
Cannot resume editing metadata of incomplete submission

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#754]
I initiated an item submission prior to release v.1.0.6
Logged in after v.1.0.6 was deployed and got the message in screenshot 1.
![image](https://cloud.githubusercontent.com/assets/879749/10527288/ed3b5030-734c-11e5-885a-8e57d6b4135d.png)

Then clicked on 'edit teir metadata' and got a generic error page:

![image](https://cloud.githubusercontent.com/assets/879749/10527391/6880ed9a-734d-11e5-8578-ebacbe64816a.png)

**Comment by pbinkley** [comment]
This may be the result of having a session carry over from the old release
to the new one. If you close you browser and start fresh, can you reproduce
the problem?

**Comment by anayram** [comment]
I tested from a different computer and everything worked fine. Thanks! Closing this ticket.
