### ISSUE TITLE
Menu does not deploy from username button

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#755]
After logging in (v.1.0.6), I encountered erratic behaviour of the drop down menu from the username button. It wouldn't consistently deploy. Clicking the 'login in' link at page bottom reset and resolved this once, but not a second time. I tried this on Chrome on mac and pc and on Firefox on mac.

**Comment by pbinkley** [comment]
Can you reproduce this, @johnhuck , and if so, can you give a screenshot?

**Comment by johnhuck** [comment]
Yes, I can still reproduce this today. it's intermittent. The screenshot won't show much, but I will append one.

**Comment by johnhuck** [comment]
![menu_not_deploying](https://cloud.githubusercontent.com/assets/5233196/10549810/a036e286-7400-11e5-80c8-8820d2191fe2.png)

**Comment by johnhuck** [comment]
In this case, refreshing the page did not resolve it. However, moving to another interface page did. Yesterday moving to another page did not resolve it, but refreshing the page did (if I recall). So it seems to be unpredictable.

**Comment by pgwillia** [comment]
related to #752.  All javascript on the page is affected.
