### ISSUE TITLE
new ccid protected items working, but migrated items not

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#757]
added new item to test ccid protection:

https://hydranorth.library.ualberta.ca/files/6d56zz76b#.ViAQfy5VhBc

shows metadata but prompts for log in when I try to download. awesome!

@sfbetz commented in #717 with suggested minor revision to text to make it very clear you can log in to access.

![ccid](https://cloud.githubusercontent.com/assets/4697932/10527225/9172e632-734c-11e5-8ec0-472cac1588bc.jpg)

migrated ccid items still not showing but may be due to needed data change

**Comment by weiweishi** [comment]
related to #717. and need to run the rake task in #743

**Comment by sfarnel** [comment]
Subsumed under #743 
Closing
