### ISSUE TITLE
deposit form has no add+ buttons for repeatable elements

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#759]
After uploading a file, went back to upload another and on the metadata form the Add+ button for metadata elements seems to have gone:

![singleoption](https://cloud.githubusercontent.com/assets/4697932/10529462/69c52fa0-735b-11e5-97dd-a61496b42da0.jpg)

**Comment by weiweishi** [comment]
It is still on era-test, not sure what version is on era-test? @henryzhang87
![image](https://cloud.githubusercontent.com/assets/2047614/10534345/87fe5ef4-7394-11e5-83a8-eed6054ae371.png)

**Comment by weiweishi** [comment]
Never mind my last question, still seeing the add+ button on hydranorth. Anyone else can verify?
![image](https://cloud.githubusercontent.com/assets/2047614/10534408/6c9aff22-7395-11e5-93af-25169fec484f.png)

**Comment by sfarnel** [comment]
Can no longer replicate so seems to be fixed. Closing.
