### ISSUE TITLE
error when trying to upload comp sci tech report

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#760]
tried twice to upload a comp science tech report and both times got an error on save

![error](https://cloud.githubusercontent.com/assets/4697932/10529744/dc29e1f6-735d-11e5-9d2c-a3184fa1713f.jpg)

first try: https://hydranorth.library.ualberta.ca/batches/tt44pp77n
second try: https://hydranorth.library.ualberta.ca/batches/9c67wp86v

**Comment by sfarnel** [comment]
see also #761

**Comment by sfarnel** [comment]
looking in 'my files' i see the item listed but it only has item type and author as populated from my username (as the author I entered was different).

![screen shot 2015-10-15 at 7 52 07 pm](https://cloud.githubusercontent.com/assets/4697932/10532006/64f4a206-7376-11e5-8c9c-3ab70e808002.png)

**Comment by pbinkley** [comment]
Is this actually a dupe of #761 ?

**Comment by sfarnel** [comment]
put as two separate issues to reflect each type of report, and the fact that the stub record for sers was displaying type as comp sci tech report

**Comment by sfarnel** [comment]
Fixed except remaining issue in #767 
Closing.
