### ISSUE TITLE
error when trying to upload structural engineering report

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#761]
same error as #760 

one try: https://hydranorth.library.ualberta.ca/batches/d217qr411

**Comment by weiweishi** [comment]
to fix this and #760, need to add the following lines in the configuration file: 
config/initializers/sufia.rb

config.cstr_collection_id = "44558v39c"
config.ser_collection_id = "44558s738"

It used to be set with db:seed. Now the collection ids are set, should this happen at the ansible playbook level? @pgwillia @henryzhang87 ?

**Comment by weiweishi** [comment]
verified that this configuration change will fix the two issues

**Comment by pbinkley** [comment]
We will need to make sure this is under control after the deployment of the final release, whether by the playbook or manually.

**Comment by sfarnel** [comment]
Fixed except issue in #767 
Closing
