### ISSUE TITLE
Error when trying to access Google Drive to upload

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#763]
May not be a bug due to con fig changes upcoming? but submitting in any case.

Selected cloud provider then Connect to Google Drive and got the following error:

![screen shot 2015-10-15 at 8 05 52 pm](https://cloud.githubusercontent.com/assets/4697932/10532168/2c4eb32c-7378-11e5-8f97-9820057cb231.png)

**Comment by pgwillia** [comment]
We have http://hydranorth.library.ualberta.ca/browse_everything/connect configured but not http://hydranorth.library.ualberta.ca/connect.  I've added the config.  We will need to update when domain moves.

**Comment by pgwillia** [comment]
I think there maybe a problem with routing. Should be being sent to browse_everything.

**Comment by pgwillia** [comment]
works in development but not test or production -- checking the playbooks for discrepancies.

**Comment by anayram** [comment]
After release v1.2.0: selecting Connect to Google Drive leads first to Google request form permission for HydraNorth to manage files. After clicking on 'Allow' I got the message below.

Tried the usual things: clearing all browsing files, restarting browsers and restarting hydranorth sessions.

![image](https://cloud.githubusercontent.com/assets/879749/10553567/22e1ddea-7419-11e5-978b-522475fd7e4a.png)

**Comment by pgwillia** [comment]
It's still sending us back to http://hydranorth.library.ualberta.ca/connect instead of http://hydranorth.library.ualberta.ca/browse_everything/connect.  I see the same thing. You can force the correct behaviour by editing the url -- but that's not a fix for the problem, only confirmation that if it sent you to the correct place it would be working.

**Comment by sfarnel** [comment]
replicated in production 26 oct 2015

**Comment by pgwillia** [comment]
Think this will be fixed by updating version of browse-everything to 0.8.4.

**Comment by sfarnel** [comment]
Duplicate of #505
