### ISSUE TITLE
was (sort of) able to deposit to thesis collection

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#764]
tested to see if i could deposit an item to a thesis collection (when logged in with ccid).
- the fgsr community and theses collections appear in the community/collections dropdown lists as choices so someone may try this
- took some time but eventually kicked back to dashboard and the file is there but it has minimal metadata, including item type null and the default author. also does not have a community or collection listed
- remove these options from dropdowns?

see #34

**Comment by sfarnel** [comment]
when logged in as a UA user was able to add to the theses collection when this wasn't to be doable except for admin.

![screen shot 2015-10-16 at 7 23 12 pm](https://cloud.githubusercontent.com/assets/4697932/10556242/6c1ae35e-743b-11e5-893e-005043ddefcd.png)

**Comment by sfarnel** [comment]
replicated in production 26 oct 2015

**Comment by sfarnel** [comment]
Although I didn't run into any problems, I was still able to deposit a thesis via the deposit form, which I didn't think was meant to be possible.

**Comment by sfbetz** [comment]
Will be fixed by #1075

**Comment by sfbetz** [comment]
This problem is still appearing - in upload form I'm able to select the FGSR community and the Theses and Dissertations collection as a regular user. As a result, we've had theses deposited here (and users may assume they've met their requirements for graduation).

**Comment by sfbetz** [comment]
Fixed now - see comments on #1075
