### ISSUE TITLE
clicked on add files to collection and got bumped to upload processing screen which spins until stopped

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#765]
Following up on #764 I searched for the theses and dissertations spring 2009 to present collection then clicked on add files which bumped me to the screen that displays when you're uploading files, which spun for quite some time.

![screen shot 2015-10-15 at 8 24 42 pm](https://cloud.githubusercontent.com/assets/4697932/10532396/1bcafdaa-737b-11e5-9abd-5510292bc5bb.png)

Had same issue when trying to add files to ERA General Collection

**Comment by weiweishi** [comment]
and I can't seem to close this window by either click the little X on the top, or the close link..

**Comment by pbinkley** [comment]
Probably same as #770

**Comment by mbarnett** [comment]
Should we consider disabling this for the time being, until we can rework it to not keep popping up in unexpected places?

**Comment by pbinkley** [comment]
​I thought we had this sorted yesterday, but yes, if we can't control it
let's disable it for now.​

**Comment by mbarnett** [comment]
this should now be fixed on hydranorth.library.ualberta.ca
