### ISSUE TITLE
clicking on my files brings up 'item processing message' and won't let me out

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#770]
when i click on my files or on a second or third page it pops up with the 'file processing' message and I can't close it

![spin](https://cloud.githubusercontent.com/assets/4697932/10545651/035607f8-73e7-11e5-99ba-7aebfaf36d0e.jpg)

see also #765 ?

**Comment by mbarnett** [comment]
This should now be fixed on hydranorth.library.ualberta.ca
