### ISSUE TITLE
embargo transition for new items doesn't seem to be working

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#771]
Yesterday I uploaded two items to test embargo.

1. https://hydranorth.library.ualberta.ca/files/q237hv040#.ViET00ZSn9V - was set to private, then UA access, embargo date 2015-10-16. It is showing as private
![embargo1](https://cloud.githubusercontent.com/assets/4697932/10545758/7ea4a1da-73e7-11e5-96a0-0567a0fe20a2.jpg)

2. https://hydranorth.library.ualberta.ca/files/rv042w19g#.ViEVmkZSn9U - was set to private, then open access, embargo date 2015-10-16. It is showing as private
![embargo2](https://cloud.githubusercontent.com/assets/4697932/10545790/a5e876f4-73e7-11e5-8e80-1c6eef301a8b.jpg)

**Comment by pbinkley** [comment]
I wonder if it will happen at midnight tonight (despite the timestamp in the field).

**Comment by sfarnel** [comment]
will check tomorrow!

On Fri, Oct 16, 2015 at 9:51 AM, Peter Binkley <notifications@github.com>
wrote:

> I wonder if it will happen at midnight tonight (despite the timestamp in
> the field).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/771#issuecomment-148752555>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by mbarnett** [comment]
Have we created a periodic job to sweep expired embargos and apply their post-embargo visibility? I don't see anything that's doing what's described here: https://github.com/projecthydra/hydra-head/wiki/Embargos-and-Leases

**Comment by sfarnel** [comment]
will deposit another two items and see how it looks tomorrow

**Comment by pbinkley** [comment]
Hmm, that may be it. We can fix this next week.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
yet another rake task to add to cron job maybe?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mbarnett** [comment]
That's probably the most straightforward solution, yeah.

**Comment by sfarnel** [comment]
on Friday uploaded two more items to test.

1. https://hydranorth.library.ualberta.ca/files/bbr86b356g#.ViJYeaLwMiE - private transition to open, embargo date 2015-10-17
![screen shot 2015-10-17 at 8 19 01 am](https://cloud.githubusercontent.com/assets/4697932/10559185/cc962dda-74a7-11e5-9083-9f0e0332289e.png)

2. https://hydranorth.library.ualberta.ca/files/q811km55r#.ViJaA6LwMiF - private transition to UA, embargo date 2015-10-17
![screen shot 2015-10-17 at 8 23 36 am](https://cloud.githubusercontent.com/assets/4697932/10559217/82fc9e92-74a8-11e5-99f0-0ebb1ebf4840.png)

As with the earlier tests, the radio button has moved from embargo to private, but it is still showing private.
