### ISSUE TITLE
Remove rights statements from Dataverse metadata

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#774]
@weiweishi, pursuant to our conversation this morning, could you please run a rake task to remove all rights statements (all instances of dcterms:rights) for items in the Dataverse Datasets collection (Sonya and Larry agree these can be removed). These items have no license statements that I can see, so I don't believe it's necessary to replace the rights statements with anything else.

Also as we talked about, @sfbetz and I are working on an explanatory statement to insert into the  dcterms:description element of the same set of items and will update this thread with it when it's ready. I am thinking pre-pending it to the beginning of the element content might be best so that it comes before the 'kind of data' statement and the user supplied description. @sfbetz, what do you think?

The pipe character (' | ') is used to separate the 'kind of data' statement from the user supplied description in this element and so the inserted explanatory statement should end with a pipe character as well.

**Comment by sfbetz** [comment]
Hi both - I've shortened the descriptive access statement to the shortest possible variation: 

"This item is a resource in the University of Alberta Libraries' Dataverse Network. Access this item in Dataverse by clicking on the DOI link."

**Comment by johnhuck** [comment]
Thanks, @sfbetz . Looks good to me. So, @weiweishi (just for clarity) with the pipe and trailing space, the statement to insert is: "This item is a resource in the University of Alberta Libraries' Dataverse Network. Access this item in Dataverse by clicking on the DOI link. | "

**Comment by pbinkley** [comment]
- [ ] delete content of rights field
- [ ] prepend "This item is a resource in the University of Alberta Libraries' Dataverse Network. Access this item in Dataverse by clicking on the DOI link. | " to description field
