### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/HydraNorth#778]
Currently the rspec test suite takes upwards of 2 hours to run. Even disabling the slowest test (https://github.com/ualbertalib/HydraNorth/blob/master/db/performance_data.rb), the test suite takes approximately 26 minutes to run.

[Slow tests are an anti-pattern](http://randycoulman.com/blog/2015/07/21/getting-testy-anti-patterns/). This is a big anchor on our overall productivity, as things slow way down any time we need to verify that a change hasn't unintentionally broken something else in the system. 

There are a lot of avenues we can investigate to speed things up:
- [ ] replace the performance test with a mock that simply aims to detect whether the index is performing an N+1 query of files, rather than actually importing 1100+ files into fedora and then timing the render, which is an indirect way of detecting the above, and which takes over an hour.
- [ ] eliminate many of the downloads. At least one spec (possibly redirect_spec, although I haven't checked) downloads a number of files, one of which is over 100MB in size. It should be possible to side load these through ansible, or commit sanitized data to GitHub, rather than curl 20-30 files over the network during each test run. Additionally, many of these downloads seem to be the same file, several times
- [ ] switch to FactoryGirl#build_stubbed wherever possible to avoid hitting the database whenever it can be avoided.
- [ ] take the above even further and [avoid FactoryGirl altogether](https://robots.thoughtbot.com/speed-up-tests-by-selectively-avoiding-factory-girl) where persistence isn't needed
- [ ] consolidate examples. We define many `let()` variables per test. We should attempt to share these across as many tests as possible, to reduce redundant creation of model instances, etc. It may be preferable to simply reset some values on an object after a test so that it can be shared with another test, rather than clean it out of the database and then create a new identical object in the database.
- [ ] reduce as many calls to `cleanup_jetty` as possible, to eliminate expensive calls to Fedora. Running it after each test may be overkill if the test didn't do anything that will impact other tests.
- [ ] mock interactions with Fedora wherever possible, to eliminate expensive calls to Fedora
- [ ] aim to shorten or eliminate any calls to `sleep()`.  [generic_file_new_form_spec](https://github.com/ualbertalib/HydraNorth/blob/master/spec/forms/generic_file_new_form_spec.rb) spends 90 seconds in `sleep`, for instance
- [ ] [defer garbage collection](http://makandracards.com/makandra/950-speed-up-rspec-by-deferring-garbage-collection)
- [ ] [change the password hashing algorithm to something fast purely for non-security related tests](http://keighl.com/post/speed-up-rspec-ditch-bcrypt/)

Here's the output of `bundle exec rspec --profile` to identify some high-value refactorings ( but I don't think these timings are entirely accurate, as the seem to miss the download times, for instance, or any time not spent actively running ruby code):

```
Top 10 slowest examples (314 seconds, 21.9% of total time):
  Ability a user with no roles should not be able to create GenericFile
    78.13 seconds ./spec/models/ability_spec.rb:69
  collection paginate collections should page
    40.1 seconds ./spec/features/collection/collection_spec.rb:143
  Migration rake tasks migration:eraitem - standard item item should be migrated
    37.81 seconds ./spec/tasks/migration_rake_spec.rb:38
  Migration rake tasks migration:update_ccid_visiblity visibility should have been updated
    33.75 seconds ./spec/tasks/migration_rake_spec.rb:469
  Migration rake tasks migration:eraitem - multifile item multifile item should have a zip file
    27.15 seconds ./spec/tasks/migration_rake_spec.rb:80
  CommunitiesController#index responds with success
    23.63 seconds ./spec/controllers/communities_controller_spec.rb:26
  Migration rake tasks era_collection_community migration:era_collection_community collection should be migrated
    19.65 seconds ./spec/tasks/migration_community_collection_spec.rb:53
  Migration rake tasks migration:eraitem - thesis item should have all thesis related metadata field
    19.44 seconds ./spec/tasks/migration_rake_spec.rb:161
  CollectionsController#update a collections members should set collection on members
    17.96 seconds ./spec/controllers/collections_controller_spec.rb:93
  Migration rake tasks migration:eraitem - ccid item item should have institutional visibility
    16.38 seconds ./spec/tasks/migration_rake_spec.rb:293

Top 10 slowest example groups:
  CommunitiesController
    23.63 seconds average (23.63 seconds / 1 example) ./spec/controllers/communities_controller_spec.rb:3
  Migration rake tasks
    18.88 seconds average (226.55 seconds / 12 examples) ./spec/tasks/migration_rake_spec.rb:4
  delete
    17.01 seconds average (68.03 seconds / 4 examples) ./spec/features/admin_delete_spec.rb:3
  Migration rake tasks era_collection_community
    16.07 seconds average (32.13 seconds / 2 examples) ./spec/tasks/migration_community_collection_spec.rb:4
  BatchUpdateJob
    13.98 seconds average (83.89 seconds / 6 examples) ./spec/jobs/batch_update_job_spec.rb:3
  Edit resource form
    11.32 seconds average (22.65 seconds / 2 examples) ./spec/features/resource_types_spec.rb:3
  collection
    11.17 seconds average (156.42 seconds / 14 examples) ./spec/features/collection/collection_spec.rb:3
  GenericFile
    10.73 seconds average (21.46 seconds / 2 examples) ./spec/features/edit_file_spec.rb:3
  myfiles
    9.39 seconds average (28.18 seconds / 3 examples) ./spec/features/my/files_spec.rb:3
  My::AllController
    8.6 seconds average (25.79 seconds / 3 examples) ./spec/controllers/my/all_controller_spec.rb:3
```

**Comment by mbarnett** [comment]
This might also be an opportunity to address #631

**Comment by mbarnett** [comment]
Currently working on the ability_spec.rb tests, if anyone wants to tackle something else.

**Comment by sfbetz** [comment]
@mbarnett @pbinkley @pgwillia @criedlberger @pcharoen @weiweishi 

@leahvanderjagt and I are prioritizing the sprint 38 issues - can you provide a priority for this issue and its inclusion into sprint 39? If it's important it should stay on the list.

**Comment by mbarnett** [comment]
Zero priority for sprint 39. This should kick back into the technical maintenance milestone

**Comment by weiweishi** [comment]
Reopen the issue as there is still room for more improvement, and is a good opportunity for @murny to gain more familiarity to our code base.

**Comment by pbinkley** [comment]
Timeboxed this at one week

**Comment by mbarnett** [comment]
Dumping my notes from HydraConnect's testing session here, not sure if there's anything enormously useful at this point to us:

```
Monday Workshops
Testing Hydra w/ RSpec 




Overview of useful material https://github.com/awead/hydra-rspec-templates
Suggests webmock/vcr for API endpoint stubbing
The room is very pro Travis, some CI, everybody down on Jenkins
Write long feature tests, combining many assertions in one test, visiting multiple pages, rather than atomizing assertions -- pessimal for performance bc of long test setup issues (I think we’re guilty of this)
New rails_helper file for rspec -- use for test files that depend on rails infrastructure (AR et al) otherwise just use spec_helper for faster test boot time. This is only present in newly set up rspec suites
ActiveFedora::Cleaner makes you suire incredibly slow, Adam suggests not running it between tests, only manually cleaning when absolutely necessary (this would be a performance win for us but require some work to get to)
Recommends random order to catch accidental test interdependencies
Many useful examples in that repo, including eg. indexer tests https://github.com/awead/hydra-rspec-templates/tree/master/spec/indexers
Presenters are POROs that present SolrDocs in Hydra-world
View logic should be pushed into them (would help us immensely and give us a speed boost combined with the SolrDoc-only approach) (this is an area we could really benefit from cleaning up & taking advantage of)
It’s about 5C in the lower McKim rooms if anyone else has a session here FYI
Adam recommends any new field added to a Fedora model ALWAYS be indexed into Solr to avoid ever slamming into the issue with Fedora’s slowness, even though this entails changing model, indexer, and SolrDoc class at minimum
Suggest all props be multivalued and dealing with single cardinality at the presenter/view level. Not sure I agree with this given issues we’ve run into with multivalued properties
It’s seriously like a meat-locker in here. Bring a coat.
Suggests running ActiveJobs inline rather than queueing in test mode
Service is a job without the messaging service
```
