### ISSUE TITLE
Dataverse collection not showing its members

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#781]
Probably a data problem. This collection shows no members: https://hydranorth.library.ualberta.ca/collections/wm117p010 . But this item belongs to that collection: https://hydranorth.library.ualberta.ca/files/3n203z16t#.ViF5TJcy3mF

**Comment by mbarnett** [comment]
It looks like dataverse items don't have a hasCollectionId property, so they're not picked up by the new collection search query: https://github.com/ualbertalib/HydraNorth/blob/cdc710196b38601c9d8d8e3107dc9fc88a32d48c/app/models/search_builder.rb#L8

```ruby
 f = GenericFile.find('3n203z16t')
f.to_solr.keys
=> ["system_create_dtsi", "system_modified_dtsi", "active_fedora_model_ssi", "has_model_ssim", :id, "object_profile_ssm", "depositor_ssim", "depositor_tesim", "resource_type_tesim", "resource_type_sim", "title_tesim", "title_sim", "description_tesim", "rights_tesim", "publisher_tesim", "publisher_sim", "date_created_tesim", "date_created_ssi", "date_modified_dtsi", "subject_tesim", "subject_sim", "identifier_tesim", "isPartOf_ssim", "date_uploaded_dtsi", "ingestbatch_tesim", "hasCollection_ssim", "hasCollection_tesim", "date_submitted_dtsim", "label_tesim", "file_format_tesim", "file_format_sim", "all_text_timv", "file_size_is", "read_access_group_ssim", "edit_access_person_ssim"]
```

**Comment by weiweishi** [comment]
@pbinkley could you please make this as part of your dataverse rake task?

**Comment by johnhuck** [comment]
It may be too late for launch, but I am just realizing that since the Dataverse Dataset collection is not part of a community there isn't a way to browse to it from the communities page. I don't know if we want that or not or what the best solution would be.

**Comment by weiweishi** [comment]
is it okay if we label this collection as a community then?

**Comment by johnhuck** [comment]
@sfbetz @sfarnel What do you think? As long as it doesn't cause other problems I think that might be a good solution.

**Comment by sfarnel** [comment]
I would agree

On Fri, Oct 16, 2015 at 4:49 PM, johnhuck <notifications@github.com> wrote:

> @sfbetz <https://github.com/sfbetz> @sfarnel <https://github.com/sfarnel>
> What do you think? As long as it doesn't cause other problems I think that
> might be a good solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/781#issuecomment-148858187>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
Ok - I'm fiddling with it anyway, so I'll make the change.

**Comment by pbinkley** [comment]
dupe of #785

**Comment by pbinkley** [comment]
Rather than promote Dataverse to a community, I think adding a community above it to contain collections of datasets would make sense - I'm not sure if we have others that would qualify now, but we no doubt will in the future, and it would be handy to have them gathered together. @sfbetz @sfarnel @johnhuck  what do you think?

**Comment by johnhuck** [comment]
I think that could start to muddy the waters and confuse the distinction between collections and item types. The item type 'dataset' already allows colocates data.

Also, we can't guarantee that all data collections would be grouped under our central community for data collections:
For instance, one of the other existing communities (e.g., Fac. of Medicine) might decide to create a collection under its community for Faculty of Medicine datasets, and so having a community called 'data collections' would be confusing because it would potentially contain only some of the data collections, but not all.

To me there's a logical equivalence between dataverse and a community of the type we have now (departments, faculties, etc.): both are an entity that is the source of resources in Hydra, similar to the archival concept of a fonds. If we get other data collections it would make sense to set them up in communities that represent where the data has come from.

So I remain in favour of promoting 'Dataverse Datasets' to a community.

**Comment by sfbetz** [comment]
I agree with @johnhuck  - I think we want our communities to reflect some kind of shared identity rather than a shared format type. Does this complicate our understanding of communities as collections of collections in Sufia though? Do all communities need to have one or more collections?

**Comment by sfarnel** [comment]
I would agree with @sfbetz and @johnhuck

On Wed, Oct 21, 2015 at 1:26 PM, Sonya Betz <notifications@github.com>
wrote:

> I agree with @johnhuck <https://github.com/johnhuck> - I think we want
> our communities to reflect some kind of shared identity rather than a
> shared format type. Does this complicate our understanding of communities
> as collections of collections in Sufia though? Do all communities need to
> have one or more collections?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/781#issuecomment-150000896>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by anayram** [comment]
Just a quick thought: can communities have other communities associated?
That would allow for both purposes (aggregating fonds and identifying
Dataverse at the same level as other communities).

On Wed, Oct 21, 2015 at 2:13 PM, Sharon Farnel <notifications@github.com>
wrote:

> I would agree with @sfbetz and @johnhuck
>
> On Wed, Oct 21, 2015 at 1:26 PM, Sonya Betz <notifications@github.com>
> wrote:
>
> > I agree with @johnhuck <https://github.com/johnhuck> - I think we want
> > our communities to reflect some kind of shared identity rather than a
> > shared format type. Does this complicate our understanding of communities
> > as collections of collections in Sufia though? Do all communities need to
> > have one or more collections?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/781#issuecomment-150000896
> >
> > .
> >
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/781#issuecomment-150011850>
> .
>



-- 
Mariana Paredes-Olea
paredeso@ualberta.ca
780-492-7075

**Comment by johnhuck** [comment]
@anayram, I'm not sure if I completely understand your meaning, but my point about fonds was that, once it has been brought into Hydra, the Dataverse "material" as a whole can be thought of as a kind of fonds (an entity producing documents or records), equivalent to a department or faculty, so it's probably best not to aggregate it with any other collections.

**Comment by anayram** [comment]
Thanks, @johnhuck; I was thinking:

1) having a new community that gathers Dataverse and other future communities that fit the concept of  datasets or of fonds, which is what (I think) Peter suggested. But that would maybe require having a page view that can display communities that contain other communities (which I don't think is possible in HydraNorth right now)
and
2) The above would not conflict with keeping Dataverse as a community of its own as well, i.e. it would still appear in the list of communities.

Anyway, these are just quick thoughts; sorry if I am just muddying the waters.

**Comment by johnhuck** [comment]
Thanks, @anayram. I always appreciate exploring all aspects of an idea, so I never mind discussion. If you read my first post, you'll find the reasons that I was suggesting perhaps we should avoid going down the path of trying to aggregate collections of data into one community (in a nutshell): there are bound to be datasets that wind up outside this community in other collections and browsing by item type 'dataset' will currently achieve the same result.

**Comment by anayram** [comment]
Thanks, @johnhuck; It is true that faceting by dataset item type would have the same result.

**Comment by pbinkley** [comment]
Ok, I'll test how to promote the Dataverse collection to a community and
we'll come up with a job that we'll run in the overnight data cleanup queue
when it's ready.

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by weiweishi** [comment]
Dataverse Datasets have already been flagged as a community, and I've run
the clean up job to update each item to associate the community.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
