### ISSUE TITLE
Items from "My Saved" items are showing up OA in Hydranorth

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#782]
I hate to do this, but it looks like incomplete items that are sitting in my saved items in ERA have been migrated as open access items. Should these have been migrated as private items?

Examples: 

https://hydranorth.library.ualberta.ca/files/gh93gz54c#.ViF6VRCrSEI
https://hydranorth.library.ualberta.ca/files/vx021f324#.ViF8phCrSEI
https://hydranorth.library.ualberta.ca/files/wh246t362#.ViF8-RCrSEI

**Comment by mbarnett** [comment]
Possibly related to https://github.com/ualbertalib/HydraNorth/issues/731? @pbinkley

**Comment by weiweishi** [comment]
@mbarnett I think this refers to the Saved items in old ERA which should not have been migrated. 

@sfarnel @anayram how are these items labelled in ERA? inactive?

**Comment by sfbetz** [comment]
These are items that have been saved, but not submitted to ERA. Many of these will be in process, incomplete, or test items. Not sure what other users may have saved!

![screen shot 2015-10-16 at 4 48 34 pm](https://cloud.githubusercontent.com/assets/12801010/10554990/edbe59c4-7425-11e5-8d96-c1fa90dbbd14.png)

**Comment by sfarnel** [comment]
These are marked inactive and should migrate over as private. See
https://docs.google.com/document/d/13T9QnCWw4Bqcpw7-9uKvHR-y1OGOA6CV4bpCpaI7Ixc/edit?usp=sharing

On Fri, Oct 16, 2015 at 4:50 PM, Sonya Betz <notifications@github.com>
wrote:

> These are items that have been saved, but not submitted to ERA. Many of
> these will be in process, incomplete, or test items. Not sure what other
> users may have saved!
>
> [image: screen shot 2015-10-16 at 4 48 34 pm]
> <https://cloud.githubusercontent.com/assets/12801010/10554990/edbe59c4-7425-11e5-8d96-c1fa90dbbd14.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/782#issuecomment-148858236>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfbetz** [comment]
uuid's for some examples:

Saved items (should be private)
uuid:b54d5ccf-e1ae-4da1-93fb-805073adefc6/
uuid:7d945c8e-d60d-4fde-9a57-00ef86e29bc8/

**Comment by weiweishi** [comment]
This is the rels-ext for one of these objects: (uuid:12c1c941-e23c-4d45-ab6e-5bcfaba372a3)
https://hydranorth.library.ualberta.ca/files/gh93gz54c#.ViF6VRCrSEI

    <foxml:datastreamVersion ID="RELS-EXT.37"
                               LABEL="Object Relationships"
                               CREATED="2015-01-07T21:10:58.745Z"
                               MIMETYPE="text/xml"
                               SIZE="2033">
         <foxml:xmlContent>
            <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

               <rdf:Description rdf:about="info:fedora/uuid:12c1c941-e23c-4d45-ab6e-5bcfaba372a3">
	                 <hasModel xmlns="info:fedora/fedora-system:def/model#"
                            rdf:resource="info:fedora/ir:Thesis"/>
	                 <isPartOf xmlns="info:fedora/fedora-system:def/relations-external#"
                            rdf:resource="info:fedora/ir:MANUAL_APPROVAL"/>
	                 <formName xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">thesis</formName>
	                 <submitterId xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">pcharoen</submitterId>
	                 <itemID xmlns="http://www.openarchives.org/OAI/2.0/">oai:era.library.ualberta.ca:uuid:12c1c941-e23c-4d45-ab6e-5bcfaba372a3</itemID>
	                 <userId xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">pcharoen</userId>
	                 <isMemberOf xmlns="info:fedora/fedora-system:def/relations-external#"
                              rdf:resource="info:fedora/uuid:39331f1f-769d-4c2a-a103-416c285d01fc"/>
	                 <isMemberOfCollection xmlns="info:fedora/fedora-system:def/relations-external#"
                                        rdf:resource="info:fedora/uuid:7af76c0f-61d6-4ebc-a2aa-79c125480269"/>
	                 <workflowState xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">Archive</workflowState>
	                 <workflowDate xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#"
                                rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2015-01-07T21:10:57.364Z</workflowDate>
	                 <comments xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">Good Afternoon,

We are unable to approve your e-thesis at this time as we have not received the following supporting documentation:

1) Library Release form
2) Theses Non-Exclusive License Agreement

Both of these documents are required prior to approval of your thesis, and the current templates are available on the Faculty of Graduate Studies and Research website via:
http://www.gradstudies.ualberta.ca/degreesuperv/thesis.aspx

Please re-submit your e-thesis after submitting the requested documents to our office.

Thank you so much,
Graduate Student Services</comments>
               </rdf:Description>

            </rdf:RDF>
         </foxml:xmlContent>

It doesn't seem to be marked as inactive object.

**Comment by pbinkley** [comment]
Sorry, didn't see this till Weiwei mentioned it. After discussion, Weiwei is going to script a task to set these to private, so users will still see their "saved" items in case they are work in progress.

**Comment by sfarnel** [comment]
inactive is not in the rels-ext but in the foxml:property VALUE="Inactive";
see example in google doc (sorry; on phone and foxml not easily accessible
on mobile old ERA)

Sent from my iPhone

On Oct 16, 2015, at 5:07 PM, Weiwei Shi <notifications@github.com> wrote:

This is the rels-ext for one of these objects:
(uuid:12c1c941-e23c-4d45-ab6e-5bcfaba372a3)
https://hydranorth.library.ualberta.ca/files/gh93gz54c#.ViF6VRCrSEI

<foxml:datastreamVersion ID="RELS-EXT.37"
                           LABEL="Object Relationships"
                           CREATED="2015-01-07T21:10:58.745Z"
                           MIMETYPE="text/xml"
                           SIZE="2033">
     <foxml:xmlContent>
        <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

           <rdf:Description
rdf:about="info:fedora/uuid:12c1c941-e23c-4d45-ab6e-5bcfaba372a3">
                 <hasModel xmlns="info:fedora/fedora-system:def/model#"
                        rdf:resource="info:fedora/ir:Thesis"/>
                 <isPartOf
xmlns="info:fedora/fedora-system:def/relations-external#"
                        rdf:resource="info:fedora/ir:MANUAL_APPROVAL"/>
                 <formName
xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">thesis</formName>
                 <submitterId
xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">pcharoen</submitterId>
                 <itemID
xmlns="http://www.openarchives.org/OAI/2.0/">oai:era.library.ualberta.ca:uuid:12c1c941-e23c-4d45-ab6e-5bcfaba372a3</itemID>
                 <userId
xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">pcharoen</userId>
                 <isMemberOf
xmlns="info:fedora/fedora-system:def/relations-external#"

rdf:resource="info:fedora/uuid:39331f1f-769d-4c2a-a103-416c285d01fc"/>
                 <isMemberOfCollection
xmlns="info:fedora/fedora-system:def/relations-external#"

rdf:resource="info:fedora/uuid:7af76c0f-61d6-4ebc-a2aa-79c125480269"/>
                 <workflowState
xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">Archive</workflowState>
                 <workflowDate
xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#"

rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2015-01-07T21:10:57.364Z</workflowDate>
                 <comments
xmlns="http://era.library.ualberta.ca/schema/definitions.xsd#">Good
Afternoon,

We are unable to approve your e-thesis at this time as we have not received
the following supporting documentation:

1) Library Release form
2) Theses Non-Exclusive License Agreement

Both of these documents are required prior to approval of your thesis, and
the current templates are available on the Faculty of Graduate Studies and
Research website via:
http://www.gradstudies.ualberta.ca/degreesuperv/thesis.aspx

Please re-submit your e-thesis after submitting the requested documents to
our office.

Thank you so much,
Graduate Student Services
/rdf:Description

        </rdf:RDF>
     </foxml:xmlContent>

It doesn't seem to be marked as inactive object.

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/782#issuecomment-148862327>
.

**Comment by sfarnel** [comment]
As per permissions scenarios inactive were to be migrated as private (which
is essentially what they are in current ERA)

Sent from my iPhone

On Oct 16, 2015, at 5:21 PM, Peter Binkley <notifications@github.com> wrote:

Sorry, didn't see this till Weiwei mentioned it. After discussion, Weiwei
is going to script a task to set these to private, so users will still see
their "saved" items in case they are work in progress.

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/782#issuecomment-148864120>
.

**Comment by pbinkley** [comment]
Right, Inactive is a low-level Fedora attribute rather than an application
level rels-ext property.

**Comment by weiweishi** [comment]
This particular Item：
 <foxml:property NAME="info:fedora/fedora-system:def/model#state" VALUE="Active"/>

This might be a special case. I will look for others.

**Comment by sfarnel** [comment]
did notice that
https://hydranorth.library.ualberta.ca/files/gh93gz54c#.ViG0aaLwMiF is
active in old ERA and so migrated as open access. deleting from Hydranorth
now

On Fri, Oct 16, 2015 at 8:32 PM, Weiwei Shi <notifications@github.com>
wrote:

> This particular Item：
>
> This might be a special case. I will look for others.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/782#issuecomment-148878799>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
I think we might be okay on this one? Checked all the saved item in ERA, by changing their domain name from era.library.ualberta.ca to hydranorth.library.ualberta.ca, and none of the objects are actually migrated.
Not Found
The item you are looking for is not currently available in ERA. We are migrating our collections and it will take a few days for all the items to appear. Please contact us at erahelp@ualberta.ca if you would like more information about this migration.

 Also checked in rails console and seems to be the case. 

None of the file in current migration package has state value as inactive. Maybe I will use Mariana's inactive list to go through the migrated object again just to confirm.

**Comment by sfarnel** [comment]
@weiweishi sounds like a good plan. will continue to check in to see if
others show up that shouldn't

On Fri, Oct 16, 2015 at 8:48 PM, Weiwei Shi <notifications@github.com>
wrote:

> I think we might be okay on this one? Checked all the saved item in ERA,
> by changing their domain name from era.library.ualberta.ca to
> hydranorth.library.ualberta.ca, and none of the objects are actually
> migrated.
> Not Found
> The item you are looking for is not currently available in ERA. We are
> migrating our collections and it will take a few days for all the items to
> appear. Please contact us at erahelp@ualberta.ca if you would like more
> information about this migration.
>
> Also checked in rails console and seems to be the case.
>
> None of the file in current migration package has state value as inactive.
> Maybe I will use Mariana's inactive list to go through the migrated object
> again just to confirm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/782#issuecomment-148879681>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfbetz** [comment]
Marking as "Sonya it's not a bug."
