### ISSUE TITLE
error when trying to edit multiple files

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#783]
when logged in I navigated to my files and selected several items that I wanted to change permissions on. I checked the boxes next to 6 files and clicked on Edit Selected but got the 'something went wrong" error:

![screen shot 2015-10-16 at 7 29 10 pm](https://cloud.githubusercontent.com/assets/4697932/10556279/4b512ec0-743c-11e5-8503-0bb17e08651d.png)

url: https://hydranorth.library.ualberta.ca/batch_edits/edit?batch_document_ids[]=9k41zf112&batch_document_ids[]=jd472w51z&batch_document_ids[]=w6634442c&batch_document_ids[]=2z10wr83w&batch_document_ids[]=brj430452j&batch_document_ids[]=7w62f838r

**Comment by anayram** [comment]
I think this problem is the same than the one described in #489

On Fri, Oct 16, 2015 at 7:31 PM, Sharon Farnel <notifications@github.com>
wrote:

> when logged in I navigated to my files and selected several items that I
> wanted to change permissions on. I checked the boxes next to 6 files and
> clicked on Edit Selected but got the 'something went wrong" error:
>
> [image: screen shot 2015-10-16 at 7 29 10 pm]
> <https://cloud.githubusercontent.com/assets/4697932/10556279/4b512ec0-743c-11e5-8503-0bb17e08651d.png>
>
> url:
> https://hydranorth.library.ualberta.ca/batch_edits/edit?batch_document_ids[]=9k41zf112&batch_document_ids[]=jd472w51z&batch_document_ids[]=w6634442c&batch_document_ids[]=2z10wr83w&batch_document_ids[]=brj430452j&batch_document_ids[]=7w62f838r
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/783>.
>



-- 
Mariana Paredes-Olea
paredeso@ualberta.ca
780-492-7075

**Comment by pbinkley** [comment]
Fixed on Matt's branch; needs styling by @nnunn .

**Comment by mbarnett** [comment]
Branch: https://github.com/ualbertalib/HydraNorth/tree/783_batch_edit_form_fix

**Comment by pbinkley** [comment]
The multiple-file edit page never got styled. We'll leave this (fall back on single-file editing or for large batches use console).
