### ISSUE TITLE
Labels for ccid-protected items inconsistent

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#786]
Label for ccid-protected items is Open Access on collection browse pages but is then UA Access only on the full item page. May cause confusion.

E.g. Foundation Competition Resources collection, page two of results - https://hydranorth.library.ualberta.ca/collections/44558t31z?page=2

![screen shot 2015-10-17 at 9 04 43 am](https://cloud.githubusercontent.com/assets/4697932/10559447/2e576ab0-74ae-11e5-8f98-52d7f2263015.png)

Each of these items, however, is actually ccid protected which you see reflect in the label on the full item page.

E.g., https://hydranorth.library.ualberta.ca/files/kh04dq22m#.ViJjE6LwMiE
![screen shot 2015-10-17 at 9 06 09 am](https://cloud.githubusercontent.com/assets/4697932/10559458/533fefc8-74ae-11e5-925b-39e4706a2554.png)

So great to see these generally working though!

**Comment by weiweishi** [comment]
The two places use different code:
On collection page:
    <a href="<%= sufia.generic_file_path(document) %>/edit/?tab=permissions" id="permission_<%= id %>" class="visibility-link">
      <% if document.registered? %>
        <span class='label label-info'>Authenticated Access</span>
      <% elsif document.public? %>
        <span class="label label-success" title="Open Access">Open Access</span>
      <% else %>
        <span class="label label-danger" title="Private">Private</span>
      <% end %>
    </a>

On record page it uses:
<h1 class="visibility"><%= @presenter.title.first %> <%= render_visibility_badge %></h1>

hence the inconsistency.

**Comment by sfarnel** [comment]
Still seems to be the case.

**Comment by pbinkley** [comment]
Show item-level permissions always, not collection-level.

**Comment by sfbetz** [comment]
Will be superseded by work in #961 and #962.
