### ISSUE TITLE
Running into regular (and unpredictable) errors

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#788]
This may have to do with migration or the issues with merging the theses collections or other things and so may be temporary but wanted to mention in any case that I am running into a lot of 'we're sorry, something went wrong errors" the last few minutes.

At first it was after I did a search for everything and limited to language Chinese and then tried to access several of the items from the results list.

But now I can't seem to search for a term (just tried searching family) or browse by type review.

**Comment by weiweishi** [comment]
I think Fedora needs a restart with the API calls we made with the attempt
to update/delete the old Theses collection. We'll keep you posted.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

---------- Forwarded message ----------

**Comment by sfarnel** [comment]
Thanks @weiweishi !

**Comment by weiweishi** [comment]
Probably have been fixed with a Fedora restart.

**Comment by sfarnel** [comment]
was better late last night to be sure.

On Sun, Oct 18, 2015 at 12:23 AM, Weiwei Shi <notifications@github.com>
wrote:

> Probably have been fixed with a Fedora restart.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/788#issuecomment-148983056>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
seems ok so closing.
