### ISSUE TITLE
Embargoed items migrating as open access

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#789]
Embargo doesn't seem to be working on some migrated items (see below). 

1. https://hydranorth.library.ualberta.ca/files/2f75r951h#.ViMT3KLwMiE (uuid:5e7167a7-57f1-4b57-a5af-7c54438431f0) - should be embargoed then open

2. https://hydranorth.library.ualberta.ca/files/1n79h543q#.ViMXGKLwMiE (uuid:48bae3de-b140-45b4-a749-ceebcd22601c) - should be embargoed then open

3. uuid:96fe8bac-e16c-44a7-9aec-72731f9108d7 - is embargoed then ccid-protected and doesn't look to have migrated

**Comment by weiweishi** [comment]
We should've removed all embargo items prior to our last launch attempt. I
wonder if these were missing from that batch deletion.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
that's possible. i wasn't sure if the set of embargoed items had started to
be migrated. i'll mark mark these two with the proper permissions.

On Sat, Oct 17, 2015 at 10:01 PM, Weiwei Shi <notifications@github.com>
wrote:

> We should've removed all embargo items prior to our last launch attempt. I
> wonder if these were missing from that batch deletion.
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Sat, Oct 17, 2015 at 9:55 PM, Sharon Farnel <notifications@github.com>
> wrote:
>
> > Embargo doesn't seem to be working on some migrated items (see below).
> >
> > 1.
> >
> > https://hydranorth.library.ualberta.ca/files/2f75r951h#.ViMT3KLwMiE
> > (uuid:5e7167a7-57f1-4b57-a5af-7c54438431f0) - should be embargoed then
> open
> > 2.
> >
> > https://hydranorth.library.ualberta.ca/files/1n79h543q#.ViMXGKLwMiE
> > (uuid:48bae3de-b140-45b4-a749-ceebcd22601c) - should be embargoed then
> open
> > 3.
> >
> > uuid:96fe8bac-e16c-44a7-9aec-72731f9108d7 - is embargoed then
> > ccid-protected and doesn't look to have migrated
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ualbertalib/HydraNorth/issues/789>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/789#issuecomment-148975975>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfarnel** [comment]
Ah, on further digging noticed that the first item has a duplicate item
(uuid:f12e054d-b84f-49c2-bbf5-a774d493a1fa) that is open which is probably
what was migrated; will dig further and sort out.



On Sat, Oct 17, 2015 at 10:06 PM, Sharon Farnel <sharon.farnel@ualberta.ca>
wrote:

> that's possible. i wasn't sure if the set of embargoed items had started
> to be migrated. i'll mark mark these two with the proper permissions.
>
> On Sat, Oct 17, 2015 at 10:01 PM, Weiwei Shi <notifications@github.com>
> wrote:
>
>> We should've removed all embargo items prior to our last launch attempt. I
>> wonder if these were missing from that batch deletion.
>>
>> *Weiwei Shi*
>>
>> Digital Initiative Applications Librarian
>> University of Alberta Libraries
>> 2-10L Cameron Library
>> Edmonton, Alberta, Canada T6G 2J8
>> Phone:(780)492-7802
>> Fax: (780)248-1209
>> Email: weiwei.shi@ualberta.ca
>>
>> On Sat, Oct 17, 2015 at 9:55 PM, Sharon Farnel <notifications@github.com>
>> wrote:
>>
>> > Embargo doesn't seem to be working on some migrated items (see below).
>> >
>> > 1.
>> >
>> > https://hydranorth.library.ualberta.ca/files/2f75r951h#.ViMT3KLwMiE
>> > (uuid:5e7167a7-57f1-4b57-a5af-7c54438431f0) - should be embargoed then
>> open
>> > 2.
>> >
>> > https://hydranorth.library.ualberta.ca/files/1n79h543q#.ViMXGKLwMiE
>> > (uuid:48bae3de-b140-45b4-a749-ceebcd22601c) - should be embargoed then
>> open
>> > 3.
>> >
>> > uuid:96fe8bac-e16c-44a7-9aec-72731f9108d7 - is embargoed then
>> > ccid-protected and doesn't look to have migrated
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/ualbertalib/HydraNorth/issues/789>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ualbertalib/HydraNorth/issues/789#issuecomment-148975975>
>> .
>>
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
If things are going well with legacy theses migration, we should be able to start embargo items right after.

**Comment by pbinkley** [comment]
Can we close this, on the grounds it was an issue of duplication of bibliographic items in old ERA rather than a system problem? @sfarnel @weiweishi

**Comment by sfarnel** [comment]
I think so. Any remaining oddities should be caught by audit.
