### ISSUE TITLE
Collection Creator label always appears, but field isn't required

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#790]
The label appears beside an empty field:

![collecitoncreator](https://github-cloud.s3.amazonaws.com/assets/272816/10566197/502fc19c-759d-11e5-89d5-6858925191a4.png)

Since creator is not always important (especially for official collections), I suggest making the appearance of the label conditional on the field having a value. @sfbetz ?

**Comment by sfbetz** [comment]
Agreed. Makes good sense to me.

**Comment by pbinkley** [comment]
Still relevant.

**Comment by pbinkley** [comment]
Will be fixed in Sufia 7
