### ISSUE TITLE
Trouble logging in?

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#791]
I tried logging in from home while using a vpn.ualberta.ca session (~ 4:15 pm) and ran into this error on a fresh browser session. 
![hydraloginerror2](https://cloud.githubusercontent.com/assets/5233196/10567034/9b12fc26-75b4-11e5-81d6-0bb2a985b2b2.png)

**Comment by sfarnel** [comment]
@pbinkley @weiweishi @henryzhang87 reporting some server issues with CPU which they are working on. I was getting this as well.

**Comment by johnhuck** [comment]
I also ran into this when accessing an item (not logged in). Will assume that it's related to a known server issue.

**Comment by weiweishi** [comment]
I've restarted httpd on leyton. Please let me know if you continue to
experience any problem.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
Seems to be back up and running.

On Sun, Oct 18, 2015 at 6:06 PM, Weiwei Shi <notifications@github.com>
wrote:

> I've restarted httpd on leyton. Please let me know if you continue to
> experience any problem.
>
> Weiwei
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Sun, Oct 18, 2015 at 4:29 PM, johnhuck <notifications@github.com>
> wrote:
>
> > I also ran into this when accessing an item (not logged in). Will assume
> > that it's related to a known server issue.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/791#issuecomment-149056583
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/791#issuecomment-149065892>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
