### ISSUE TITLE
Deposit instructions page needs links

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#797]
There are several "[link]" placeholders on https://era.library.ualberta.ca/deposit @sfbetz

**Comment by sfbetz** [comment]
A few pages in footer content need links. See below for details:

How to Deposit page .../deposit

![screen shot 2015-10-26 at 12 27 59 pm](https://cloud.githubusercontent.com/assets/12801010/10738429/13084852-7bdd-11e5-90d6-720c381b5e0c.png)

-link to policy page: .../policies 
-link to login page: .../users/sign_in

![screen shot 2015-10-26 at 12 31 23 pm](https://cloud.githubusercontent.com/assets/12801010/10738546/852eb51a-7bdd-11e5-8b9d-b17ab42829a3.png)

-link to license chooser: https://creativecommons.org/choose/

About page

-Please update footer link to read "About ERA"

![screen shot 2015-10-26 at 12 34 10 pm](https://cloud.githubusercontent.com/assets/12801010/10738628/e84da00c-7bdd-11e5-9e8b-09d63896a2fd.png)
![screen shot 2015-10-26 at 12 34 46 pm](https://cloud.githubusercontent.com/assets/12801010/10738646/027d7344-7bde-11e5-91fd-59ad6909251f.png)

-link to technologies page: ... /technology
-link to policies page: .../policies
-How to Deposit is listed twice in first and last paragraph - remove unlinked text

Policies page:

-anchor link menu to policies down the page

![screen shot 2015-10-26 at 12 37 44 pm](https://cloud.githubusercontent.com/assets/12801010/10738751/75ee7d8c-7bde-11e5-991f-0b41af290b1c.png)

-link to How to deposit: .../deposit
![screen shot 2015-10-26 at 12 42 33 pm](https://cloud.githubusercontent.com/assets/12801010/10738888/21596448-7bdf-11e5-9119-e6d33694de9b.png)
