### ISSUE TITLE
single use link to file not working?

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/HydraNorth#798]
on my list of files, clicked on single use link to file. on one click it doesn't seem to do anything but if ai click it again it gives me the link and says it's been copied to my clipboard. click ok but when i paste the link into a browser window i get an error:

e.g., https://era.library.ualberta.ca/single_use_link/show/58be80dc24300db5fb226fba473f9d865df00211c4ecefbd9a0892d157120594

![screen shot 2015-10-19 at 3 21 56 pm](https://cloud.githubusercontent.com/assets/4697932/10591762/2939e1f2-7675-11e5-84a3-65c0c54a0061.png)

i confess to not having tried this function previously

**Comment by pbinkley** [comment]
I reproduced this. If I tried the link again after the error, I get "Single
Use Link Expired or Not Found", so evidently the error was also my single
use.
