### ISSUE TITLE
configure analytics

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#8]
Need to configure https://github.com/ualbertalib/HydraNorth/blob/master/config/analytics.yml Likely done in Ansible Playbook.

**Comment by pgwillia** [comment]
Need to configure https://github.com/ualbertalib/HydraNorth/blob/master/config/analytics.yml using Google analytics values. Likely done in Ansible playbook.

**Comment by weiweishi** [comment]
this has already been done.
