### ISSUE TITLE
Untangle admin accounts

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#800]
Accounts that were used for batch loading on old ERA now have large numbers of items associated with them. These should be transfered to the admin account.

**Comment by pbinkley** [comment]
@weiweishi is there anything here that isn't included in the audit work? It has to do with items that appear to belong to Chris' account, since he ran the batch ingests.

**Comment by weiweishi** [comment]
Yes, I think we need to run a job (maybe add to our to-do list for updating
items in Fedora) to change all objects that belongs to Chris to belong to
eraadmi.

However, we may also need to think about the route where the admin users
would land to (as loading dashboard will time out for era admin with 8000+
items, and the situation will only get worse. ) That's a separate issue
though.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
Dealt with in #977
