### ISSUE TITLE
After-launch migration

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#806]
Ready:
- [x] Re-included (360 items that came out of embargo in June plus a couple items added to ERA Oct 19 after 2PM)
- [x] Fixed xml (including originals)

Files available at: digital_init:\Hydra_DAMS\ERA\ERA_migration\after_launch_migration\

To be migrated:
- [x] Inactive (postponed migration, including items in partial dumps)
- [x] Embargoed (postponed migration, including items in partial dumps)
- [x] Error items that the migration logs show 
- [ ] Audit results - items that need to be re-migrated (if any)

**Comment by pbinkley** [comment]
audit work is in issue #886
