### ISSUE TITLE
"University of Alberta licensed resources" community missing

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#810]
We had a community in ERA called something like "University of Alberta Licensed Resources." This was a collection of CCID protected "born-digital" items we subscribe to and make accessible through ERA. It's missing from the Communities list, but individual items seem to be available in ERA as are the individual collections from this community.

See this item (throws an error message): https://era.library.ualberta.ca/files/05741r787

and this collection: https://era.library.ualberta.ca/collections/44558v72d

**Comment by sfarnel** [comment]
I know this was here as the ccid protected materials were a strong focus of
our testing up to and after launch.

On Wed, Oct 21, 2015 at 1:32 PM, Sonya Betz <notifications@github.com>
wrote:

> We had a community in ERA called something like "University of Alberta
> Licensed Resources." This was a collection of CCID protected "born-digital"
> items we subscribe to and make accessible through ERA. It's missing from
> the Communities list, but individual items seem to be available in ERA as
> are the individual collections from this community.
>
> See this item (throws an error message):
> https://era.library.ualberta.ca/files/05741r787
>
> and this collection: https://era.library.ualberta.ca/collections/44558v72d
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/810>.
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by anayram** [comment]
In case it is useful:
the community University of Alberta Libraries Licensed Resources is at:
https://era.library.ualberta.ca/files/2b88qf89d
and when accessed it is displayed as item (not as collection or as
community); i.e. it is probably not identified as community.

I couldn't see it in the communities list either even when logged in as
admin.


On Wed, Oct 21, 2015 at 2:14 PM, Sharon Farnel <notifications@github.com>
wrote:

> I know this was here as the ccid protected materials were a strong focus of
> our testing up to and after launch.
>
> On Wed, Oct 21, 2015 at 1:32 PM, Sonya Betz <notifications@github.com>
> wrote:
>
> > We had a community in ERA called something like "University of Alberta
> > Licensed Resources." This was a collection of CCID protected
> "born-digital"
> > items we subscribe to and make accessible through ERA. It's missing from
> > the Communities list, but individual items seem to be available in ERA as
> > are the individual collections from this community.
> >
> > See this item (throws an error message):
> > https://era.library.ualberta.ca/files/05741r787
> >
> > and this collection:
> https://era.library.ualberta.ca/collections/44558v72d
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ualbertalib/HydraNorth/issues/810>.
> >
>
>
>
> --
> Sharon Farnel
> Metadata Coordinator
> University of Alberta Libraries
> sharon.farnel@ualberta.ca
> 780-492-3685
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/810#issuecomment-150012122>
> .
>



-- 
Mariana Paredes-Olea
paredeso@ualberta.ca
780-492-7075

**Comment by pbinkley** [comment]
Sharon and Weiwei and I have just been looking at this too. The old
community was at 3484zj482 (that's what the CCID-protected items have in
their belongsToCommunity property), and that community returns an ldp:Gone
response when you try to retrieve it, so it has been deleted. The
GenericFile that Mariana found must be a mismigrated version and can be
deleted. I'll check whether anything is linking to it first though.

We're going to remigrate the community, which will give it a new NOID, and
run an overnight job to update every item that links to the old NOID. So by
tomorrow it should be all good, unless the job runs too long, in which case
we'll have to finish tomorrow night.

Peter

Peter Binkley, Ph.D., MLIS
Digital Initiatives Technology Librarian
Information Technology Services
peter.binkley@ualberta.ca

2-10K Cameron Library
University of Alberta
Edmonton, Alberta
Canada T6G 2J8

phone 780-492-3743
fax 780-492-9243

**Comment by sfarnel** [comment]
Thanks Peter, Weiwei and Mariana. We can do some checking tomorrow to see
how the overnight process goes.

On Thu, Oct 22, 2015 at 10:34 AM, Peter Binkley <notifications@github.com>
wrote:

> Sharon and Weiwei and I have just been looking at this too. The old
> community was at 3484zj482 (that's what the CCID-protected items have in
> their belongsToCommunity property), and that community returns an ldp:Gone
> response when you try to retrieve it, so it has been deleted. The
> GenericFile that Mariana found must be a mismigrated version and can be
> deleted. I'll check whether anything is linking to it first though.
>
> We're going to remigrate the community, which will give it a new NOID, and
> run an overnight job to update every item that links to the old NOID. So by
> tomorrow it should be all good, unless the job runs too long, in which case
> we'll have to finish tomorrow night.
>
> Peter
>
> Peter Binkley, Ph.D., MLIS
> Digital Initiatives Technology Librarian
> Information Technology Services
> peter.binkley@ualberta.ca
>
> 2-10K Cameron Library
> University of Alberta
> Edmonton, Alberta
> Canada T6G 2J8
>
> phone 780-492-3743
> fax 780-492-9243
>
> On 22 October 2015 at 10:22, Mariana Paredes-Olea <
> notifications@github.com>
> wrote:
>
> > In case it is useful:
> > the community University of Alberta Libraries Licensed Resources is at:
> > https://era.library.ualberta.ca/files/2b88qf89d
> > and when accessed it is displayed as item (not as collection or as
> > community); i.e. it is probably not identified as community.
> >
> > I couldn't see it in the communities list either even when logged in as
> > admin.
> >
> >
> > On Wed, Oct 21, 2015 at 2:14 PM, Sharon Farnel <notifications@github.com
> >
> > wrote:
> >
> > > I know this was here as the ccid protected materials were a strong
> focus
> > of
> > > our testing up to and after launch.
> > >
> > > On Wed, Oct 21, 2015 at 1:32 PM, Sonya Betz <notifications@github.com>
> > > wrote:
> > >
> > > > We had a community in ERA called something like "University of
> Alberta
> > > > Licensed Resources." This was a collection of CCID protected
> > > "born-digital"
> > > > items we subscribe to and make accessible through ERA. It's missing
> > from
> > > > the Communities list, but individual items seem to be available in
> ERA
> > as
> > > > are the individual collections from this community.
> > > >
> > > > See this item (throws an error message):
> > > > https://era.library.ualberta.ca/files/05741r787
> > > >
> > > > and this collection:
> > > https://era.library.ualberta.ca/collections/44558v72d
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/ualbertalib/HydraNorth/issues/810>.
> > > >
> > >
> > >
> > >
> > > --
> > > Sharon Farnel
> > > Metadata Coordinator
> > > University of Alberta Libraries
> > > sharon.farnel@ualberta.ca
> > > 780-492-3685
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ualbertalib/HydraNorth/issues/810#issuecomment-150012122
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Mariana Paredes-Olea
> > paredeso@ualberta.ca
> > 780-492-7075
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/810#issuecomment-150279094
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/810#issuecomment-150282019>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by sfbetz** [comment]
Thanks all!

**Comment by weiweishi** [comment]
Started the job to update any items that are associated the University of
Alberta Libraries Licensed Resources to have the new community and it
should be finished by tomorrow morning. However, I notice some of these
items were not included in the ua_access batch I updated last week, and
authentication is still required to access metadata. For example:
https://era.library.ualberta.ca/files/t722h9007



*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
https://era.library.ualberta.ca/files/t722h9007 is one of those ones that seems to have ended up with permission setting of UofA and Registered which is causing this.

**Comment by weiweishi** [comment]
yes. but We have run a rake task last weekend with Mariana's ua_access
list: Digital_Init:\Hydra_DAMS\ERA\ERA_migration\FOXML_transformed\complete_
remigration\pid_lists\access_testing\ua_access (see #717)

It seems that the some of the items might be missing from the list and
didn't have their permission setting updated.


*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
Ah, I see that the uuid for that one is included in the open list although
it shouldn't be. I wonder if that is why we are ending up with some of
these odd permission scenarios in migrated items. I'm looking now at
Peter's two lists (ua & open, UA & registered) for patterns.

On Fri, Oct 23, 2015 at 9:12 AM, Weiwei Shi <notifications@github.com>
wrote:

> yes. but We have run a rake task last weekend with Mariana's ua_access
> list:
> Digital_Init:\Hydra_DAMS\ERA\ERA_migration\FOXML_transformed\complete_
> remigration\pid_lists\access_testing\ua_access (see #717)
>
> It seems that the some of the items might be missing from the list and
> didn't have their permission setting updated.
>
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Fri, Oct 23, 2015 at 8:10 AM, Sharon Farnel <notifications@github.com>
> wrote:
>
> > https://era.library.ualberta.ca/files/t722h9007 is one of those ones
> that
> > seems to have ended up with permission setting of UofA and Registered
> which
> > is causing this.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/810#issuecomment-150583138
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/810#issuecomment-150604147>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
I believe this has been fixed with the rake task to associate new UAL licensed resource collection to the member objects.
