### ISSUE TITLE
Searching causing error message

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#812]
I'm experiencing some strange searching behaviour.

From the homepage searching while not authenticated for keyword "Wells" throws up the "We're sorry, but something went wrong." error. 

Searching while not authenticated for "Schrader" and I have no problems.

Same behaviour appears when I'm authenticated as admin.

Could be this search for "Wells" (which is probably a pretty big search) hits a problem item?

**Comment by pbinkley** [comment]
I can search for "the" and get 15,104 results, so it can't be the size of
the result set. My guess is that some item in the first page of hits is
invalid in some way and breaks the page. On the advanced search form it
works in the Author field (and retrieves hits), but fails in the title,
abstract and subject fields. We'll have to get into the logs.

**Comment by sfbetz** [comment]
resolved
