### ISSUE TITLE
Dataverse Community not showing its members

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#814]
Items from Dataverse are now associated with a community called Dataverse Datasets (cf. #781), but the landing page for that community does not list any items.

**Comment by weiweishi** [comment]
I think this:
https://github.com/ualbertalib/HydraNorth/blob/master/app/models/search_builder.rb#L8

has prevented any objects to be displayed on the item level. 

Maybe we should try something like? Anyone see a problem with that?
find items that hasCollectionId not exists AND belongsToCommunity_tesim:#{collection.id}
