### ISSUE TITLE
Add OAI service to production ansible playbook

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#817]
Based on #816 
Part of #570

**Comment by piyapongch** [comment]
I have added the feature to ansible-dev playbook and merge to master branch. I will be working on production when finishing all features.

**Comment by weiweishi** [comment]
@piyapongch will work with @henryzhang87 to incorporate the change to production ansible playbook, after @piyapongch finishes the ETD-MS work.

**Comment by piyapongch** [comment]
I have given Henry steps that he need for OAI Provider deployment. He will continue to add those step to his ansible playbook.

**Comment by piyapongch** [comment]
Henry and I will continue to work on this issue. It should be ready before launch date.

**Comment by pbinkley** [comment]
@henryzhang87 can we close this issue?
