### ISSUE TITLE
Add existing items to OAI sets

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#818]
Old ERA had an OAI set for every collection and community; HydraNorth will do the same. GenericFiles need to be linked to their OAI sets using ```fedoraconfig:isPartOfOAISet ```.

- [ ] create an OAI set for every Collection
- [ ] associate member GenericFile objects with their parent Collections

No doubt our collection-related rake tasks can be adapted for this.
Part of #570 

Implement as part of #739?
Implement as behavior included in GenericFile class?

**Comment by pbinkley** [comment]
Obsolete: sets will be based on existing collections.

**Comment by piyapongch** [comment]
We will not need to add oai set to items. The set support will be implemented using existing Fedora property ualtermid:hasCollectionId.

**Comment by anayram** [comment]
All good. Closing ticket.
