### ISSUE TITLE
Add newly-deposited items to the OAI sets of their collections and communities

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#819]
As a user, I want my newly deposited or ingested items to be added automatically to the OAI sets of their parent collections and communities, so that they may be discovered by partners who harvest those OAI sets. See #818 .

The first priority is the Thesis collection. Since we won't be adding to that collection until the next embargo date, this is slightly lower priority than other OAI tasks.

Part of #570

**Comment by pbinkley** [comment]
Obsolete: sets will be handled by existing collections.

**Comment by piyapongch** [comment]
I will use Fedora property, uatermsid:is_community to create a response for ListSets verb. instead of isPartOfOaiSet. The ualtermsid:is_community property is incorrect. This will be changed when the new namespace uri has been implemented.
