### ISSUE TITLE
Ensure OAI service uses original deposit timestamps

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#820]
It is crucial that the OAI service use the timestamp of an item's original ingest into old ERA, not the timestamp for ingest into HydraNorth (see #574). This should be automatic but it must be tested.

See http://www.openarchives.org/OAI/openarchivesprotocol.html#SelectiveHarvestingandDatestamps
When a request include "from" and "until" parameters, the response must include items whose records "have changed" or "have become available" within that period. The response does not distinguish to two reasons for inclusion. It is therefore sufficient that e.g. an item coming out of embargo have its modification date changed to force its inclusion, even though harvesters wion't have seen it before.

Part of #570

**Comment by piyapongch** [comment]
Right now, it is using object last modified date.

**Comment by piyapongch** [comment]
It is using jcr:lastModified as the timestamp. Can you tell me what field do you want to be the OAI timestamp?

**Comment by piyapongch** [comment]
I am waiting for the audit process to update the last modified date.

**Comment by piyapongch** [comment]
fedora:lastModified is the field to use for datestamp.

**Comment by piyapongch** [comment]
I have changed to use fedora:lastModified property. I think you can close this one.

**Comment by anayram** [comment]
Looks good to me, closing now.

**Comment by anayram** [comment]
notes from conversation with @pbinkley, @weiweishi

The mapping of this date is related to the migration script, but it will be modified before the next unembargo date.

Currently there are two Fedora "last modified dates":
`fedora:lastModified` (currently capturing last uploaded or modified date in current fedora)
and
`dcterms:modified` (last modified date in old fedora)

OAI is using `fedora:lastModified` which is ok but current migrated objects overwrite lastmodifieddate with upload date.

For instance, the following object's `<datestamp>` is coming from fedora:lastModified:
`fedora:lastModified` 2016-04-**19**T16:40:36.621Z
while the last time this item was changed was in old ERA, and this date is captured in:
`dcterms:modified` 2016-04-**05**T19:01:25.317Z
Link:
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t75h73px40b

Will test again after audit changes have been completed.

**Comment by anayram** [comment]
@piyapongch 
Following up discussion in #1074, can we map OAI's datestamp to dcterms:modified instead?
