### ISSUE TITLE
404 Route not found on leyton

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/HydraNorth#828]
Between 4:00AM and 8:25AM on 2015/10/29, there are 1505 messages in production.log saying 
"Route not found".

From application point of view, we are worry about there are broken links among these 404 Route not found messages.  I included the report of these broken links for references. The first column is the number of times it happened in the log, the second columns are the broken links

<pre>
      1 /apple-touch-icon
      1 /apple-touch-icon-120x120-precomposed
      1 /bingsiteauth
      1 /browserconfig
      1 /css/style
      1 /oaiprovider
      1 /public/datastream/get/uuid:07109773-64ab-4f02-8df5-d359a71be383/DS1
      1 /public/datastream/get/uuid:0b19d1f5-399a-42b4-be0c-360010ef6784/DS1/Zapata_Mario_Spring
      1 /public/datastream/get/uuid:0bcbf593-f989-4b1c-bfa1-85ce84875b13/DS1
      1 /public/datastream/get/uuid:0e3e66a2-d5ff-438a-86cf-095b550e646a/DS1
      1 /public/datastream/get/uuid:1541afe8-8c5b-4a71-931a-691c2bc5382e/DS1
      1 /public/datastream/get/uuid:171ddeaf-77ca-477c-8782-6bce87c8bae7/DS1
      1 /public/datastream/get/uuid:1a467d51-225c-4a72-94a3-7b7fb3f69e1b
      1 /public/datastream/get/uuid:1d1a953c-8a04-471a-95db-d9f199cf924a/DS1
      1 /public/datastream/get/uuid:1e144a76-527e-4fcd-9841-a4dda9c2ffb9/DS1
      1 /public/datastream/get/uuid:1eeea50f-8af7-41ce-ad8f-c7c31423d7f6/LICENSE
      1 /public/datastream/get/uuid:21645304-3fb9-47f2-ac52-92d2ac8704c4/DS1
      1 /public/datastream/get/uuid:24ed2eb7-c2b7-45fa-9966-7c2d9d693a8c
      1 /public/datastream/get/uuid:25afddf2-cb0b-454a-a565-fb9bef740dfe/DS1
      1 /public/datastream/get/uuid:2b489777-b8c0-414a-bee5-963580d79aa6/LICENSE
      1 /public/datastream/get/uuid:2ea349c3-81ce-4e5a-bf1a-93d951b66a4f/THUMBNAIL
      1 /public/datastream/get/uuid:2f4558dc-9c38-4e08-991a-18dfdc56a999/DS1
      1 /public/datastream/get/uuid:30d58d75-0481-4be6-bcc5-7523a2ed9725/DS1/Mann_Ajaypal
      1 /public/datastream/get/uuid:312f4884-d43e-4818-8ff1-5e44364a8a6c/DS1/NN01696
      1 /public/datastream/get/uuid:3223c1be-43a3-4597-b66d-63676b5f73d9/LICENSE
      1 /public/datastream/get/uuid:333346d0-3d0b-4758-b122-945a4c4f3d5e/DS1
      1 /public/datastream/get/uuid:356c9fd4-3fcd-4cc0-94b2-013e2bc201f2
      1 /public/datastream/get/uuid:3d766ab5-3700-4c39-8a2a-49ad8a6c991a/DS1
      1 /public/datastream/get/uuid:46af22d7-b772-468d-96ab-e217ab73ccde/DS1
      1 /public/datastream/get/uuid:48ef3130-a813-4693-a536-8931b4f4389b/LICENSE
      1 /public/datastream/get/uuid:4ab4e422-8250-49c5-b462-0034b6e91603/DS1/Kouritzin__microstructure_sumitted_2013
      1 /public/datastream/get/uuid:4b9d20a3-920f-40ee-aca0-06534c6318df/DS1/JOME_47_2010_565
      1 /public/datastream/get/uuid:4c2705ef-2f48-4886-9986-f242f19f1d8d/DS1
      1 /public/datastream/get/uuid:507cb7b7-3adc-4f77-b782-f67c92ee0f57/LICENSE
      1 /public/datastream/get/uuid:518a021e-11b8-4b8b-a140-f79a4e986e24/DS1
      1 /public/datastream/get/uuid:51aeef27-f6ae-44f5-8327-46d6ff1077f5/LICENSE
      1 /public/datastream/get/uuid:53e06e2b-b4fc-4142-9be7-ea4032591920/LICENSE
      1 /public/datastream/get/uuid:545580e2-b81d-4e39-b053-483acc5819a3/LICENSE
      1 /public/datastream/get/uuid:557cfb6a-1799-4f1d-ad67-7e686153261b/LICENSE
      1 /public/datastream/get/uuid:55d1da8e-24f4-4a94-9737-b974063c9a99/DS1
      1 /public/datastream/get/uuid:571917f4-a0a8-4906-8c54-4c4e4656958d/LICENSE
      1 /public/datastream/get/uuid:577dac81-7698-4b68-b12a-5505f2241a2a/LICENSE
      1 /public/datastream/get/uuid:5822bb6f-a9c4-4dbb-b7d1-d3ed8a72ec50/DS1
      1 /public/datastream/get/uuid:588d76cb-acc6-4ff2-938e-ccf54b8b16c9/DS1
      1 /public/datastream/get/uuid:6014183f-1d8b-47a0-a705-0bbeeec2ecd7/DS1
      1 /public/datastream/get/uuid:602c46e9-47a7-43c4-a8a5-ff37c9c679f1/DS1
      1 /public/datastream/get/uuid:621f8981-804d-40de-8c6d-4631e6227067/LICENSE
      1 /public/datastream/get/uuid:6402feb1-2ddf-47b5-ad2f-972d9178fa46/DS1/Ely
      1 /public/datastream/get/uuid:649caaa9-2898-4951-ab5a-afab4d8ec04d/DS1
      1 /public/datastream/get/uuid:657554fc-2772-4a74-8f92-41beb330123f/DS1
      1 /public/datastream/get/uuid:65ae5d12-ba09-457e-8ad5-0f6763a194f8/DS1/MM01546
      1 /public/datastream/get/uuid:68d497e8-ca81-43f4-b9bf-5cb6033c9a5c/DS1
      1 /public/datastream/get/uuid:6b45e014-ae26-450a-a4b7-12a66191191d/LICENSE
      1 /public/datastream/get/uuid:6d97d546-8a30-4103-8e0a-d27f1a900946/DS1
      1 /public/datastream/get/uuid:755b1e17-a517-4306-bc89-2957ebef3657/DS1
      1 /public/datastream/get/uuid:7794beb3-323e-40c9-b754-08ca42aa8f0b/LICENSE
      1 /public/datastream/get/uuid:7b589675-6a17-46bf-aceb-9f6ab99b5340/DS1/CE_137_2005_129
      1 /public/datastream/get/uuid:7d7b128f-c685-4293-ba6d-be7cc04a0b11/LICENSE
      1 /public/datastream/get/uuid:7e183a5e-7883-4688-a4ac-bbb484d09bdc/DS1
      1 /public/datastream/get/uuid:7e22ffc6-aeb9-4525-b173-c05c125329f2/LICENSE
      1 /public/datastream/get/uuid:7e776627-c273-40b9-842c-0939e346bf20/DS1
      1 /public/datastream/get/uuid:7eeda195-a25b-4fee-9b91-c8bec27d6f11/LICENSE
      1 /public/datastream/get/uuid:7fe013b3-7b76-4d81-86c6-899202b135cc/DS1/IJOPS_167_2006_683
      1 /public/datastream/get/uuid:800f988a-f7bf-4ab7-b745-ff9dbc32a1c1/DS1
      1 /public/datastream/get/uuid:806b9f1c-6030-4933-9949-0a70bb9604bf/DS1
      1 /public/datastream/get/uuid:838ffccf-ef2b-4180-bd3e-3a3aec81a0d4/LICENSE
      1 /public/datastream/get/uuid:85ec74b1-9cbe-4cb8-ae26-da72764dd705/LICENSE
      1 /public/datastream/get/uuid:8677cf15-173b-4cdf-ac85-48e2fa4b0634/DS1
      1 /public/datastream/get/uuid:87a68d43-1b29-416e-8d28-a7aa05213274/DS1
      1 /public/datastream/get/uuid:8945bb0f-0bf3-4784-954b-ae1d20b4435f/DS1
      1 /public/datastream/get/uuid:912959ce-8307-4c32-b78d-bea6bf24a5e4
      1 /public/datastream/get/uuid:92247219-4284-4b4f-a756-27031fdce0bf/LICENSE
      1 /public/datastream/get/uuid:997594f6-2b75-4608-90b5-4a487af667d4/DS1/BarbaraBishopThesisFinal3
      1 /public/datastream/get/uuid:9a60f1e9-5ba5-40f8-9547-717010c42958/LICENSE
      1 /public/datastream/get/uuid:9d549778-3685-440a-848b-79bb5143a5c8/LICENSE
      1 /public/datastream/get/uuid:9fa63e42-fb14-4436-8bbf-a4f203607bdb/DS1
      1 /public/datastream/get/uuid:a0103a91-71ab-4142-96fe-d79057a9ddf6/DS1
      1 /public/datastream/get/uuid:a1773e70-372d-428b-8b54-21ace0deb808/DS1/Rey
      1 /public/datastream/get/uuid:a4858795-a1f8-43e2-ac3d-0881320c984a/DS1
      1 /public/datastream/get/uuid:a491b0e5-bf8e-4e91-aa03-82eef6140132/LICENSE
      1 /public/datastream/get/uuid:a8b919d8-4a83-49fa-b7cb-11de9e21e23d/THUMBNAIL
      1 /public/datastream/get/uuid:a8de20e9-a877-4bde-a28d-5c1d0e50da18/LICENSE
      1 /public/datastream/get/uuid:a99051cc-bebe-41bb-a0f4-37a1b61aa90f/LICENSE
      1 /public/datastream/get/uuid:aadd84bb-e853-4e1e-b5ff-c648ffe7e542/THUMBNAIL
      1 /public/datastream/get/uuid:ab3bca1a-d2e8-4089-b86a-a0c6bb8e36d5/DS1
      1 /public/datastream/get/uuid:b3412e78-0ae6-42c8-9419-18defd3d9bc5/DS1
      1 /public/datastream/get/uuid:b9c26eaa-b40b-4e24-80b6-4cb77229773c/DS1
      1 /public/datastream/get/uuid:c06419a1-4be7-4ee9-822d-b0d329a2e2e6/LICENSE
      1 /public/datastream/get/uuid:c0aebcb1-733c-4ba1-bb1d-cda9a2aee5a9
      1 /public/datastream/get/uuid:c418e8ca-1cc5-4a67-93b5-90c547d90e2c/LICENSE
      1 /public/datastream/get/uuid:c4529b3b-4442-40e5-9abd-c22546d64893/LICENSE
      1 /public/datastream/get/uuid:c4f775be-6ef5-458c-b204-f666b914af62/THUMBNAIL
      1 /public/datastream/get/uuid:cc039b2a-f053-44b3-a8d1-4359bc8d1e60/DS1/MM18308
      1 /public/datastream/get/uuid:cd774d88-81f9-476e-897b-69f4965b4725/DS1
      1 /public/datastream/get/uuid:d13d5f93-1bbf-45c4-8fff-612a9757b6ee/THUMBNAIL
      1 /public/datastream/get/uuid:d3230a55-f944-47db-8d51-ae7772415825/LICENSE
      1 /public/datastream/get/uuid:d842bcea-360f-4db4-baaa-077595b920be/LICENSE
      1 /public/datastream/get/uuid:d8e9d26d-d866-4645-8025-acd879802dcc/DS1
      1 /public/datastream/get/uuid:dc9d5ae4-3c58-4119-b415-e290e4e957e4/LICENSE
      1 /public/datastream/get/uuid:df00606d-0d3c-40cc-b539-27b30a9ed206/THUMBNAIL
      1 /public/datastream/get/uuid:dfd55ba4-1e6c-480a-9273-1b74eaa98457/DS1/Arvadia_Pratik_Fall
      1 /public/datastream/get/uuid:e2f135c1-7461-4fea-b423-3c8e74f4bbcd/DS1
      1 /public/datastream/get/uuid:e4428ef8-9f24-4226-87ab-1ce81a682967/DS1
      1 /public/datastream/get/uuid:e7187d14-473e-4ffb-b42e-08eee1db4e8c/DS1
      1 /public/datastream/get/uuid:e72a8c91-ec99-4b5e-82ea-dea165e91529/DS1
      1 /public/datastream/get/uuid:e8fdf9d3-0144-4a6d-bb30-644d3bf6cf27/LICENSE
      1 /public/datastream/get/uuid:ea77ba6a-4749-48e3-b222-bced5581e301/DS1
      1 /public/datastream/get/uuid:eb6d2046-b8e7-4867-b901-e3353c1dc7e1/DS1/Metcalfe_Peter_Fall_2010
      1 /public/datastream/get/uuid:ed9b2f4f-1f86-404f-b1a2-dba9a687a962/DS1/HE
      1 /public/datastream/get/uuid:ee178616-bc72-4546-9b6f-37a47e4b4220/DS1/AppPsych_25_2004_67
      1 /public/datastream/get/uuid:f0791c75-dbb6-48d7-b214-630e9d6671f0/LICENSE
      1 /public/datastream/get/uuid:f088626b-d17d-4c39-adf7-a73da611511c/THUMBNAIL
      1 /public/datastream/get/uuid:f0abcac9-2247-4dd6-ab5f-8e1b44a63982/DS1
      1 /public/datastream/get/uuid:f26ef634-21d2-433d-bcf7-832ac5944e71/DS1
      1 /public/datastream/get/uuid:f578e69e-ce30-4113-8948-af0119fb611c/LICENSE
      1 /public/datastream/get/uuid:f83153e6-6671-460b-9b34-cf743f886161/THUMBNAIL
      1 /public/datastream/get/uuid:f86d3e08-71ff-4c79-8cf8-bb5d975f5457/DS1
      1 /public/datastream/get/uuid:fbdd8f52-a947-4371-998a-e93faa8dd160/DS1
      1 /public/feed/collectionitems/rss_2.0/uuid:8fc622ed-479d-4f48-aa05-1db53c10f2ec
      1 /public/feed/collection/rss_2
      1 /public/feed/item/rss_2
      1 /public/home
      1 /public/researcher
      1 /public/researcher/downloadCv/197
      1 /public/researcher/getPicture/206
      1 /public/researcher/getPicture/230
      1 /public/view/item/uuid:0b11d509-3c27-439f-98b4-9180eb4ecaba/DS1/ME
      1 /public/view/item/uuid:17afef9f-57e7-4761-8be6-aacf3c7845dc/ds1/af3.5.1dec1978
      1 /public/view/item/uuid:1f8003ba-a0ca-47bc-8c42-0dbe5803cc6a/ds1/aoserphy2.5-1979-intensivesurfacewaterqualitystudy
      1 /public/view/item/uuid:402b6e29-ac8f-4b99-8952-7e46da6b1fab/DS1/Javed_Muhammad_B_201501_PhD.pdf
      1 /public/view/item/uuid:53192c41-9c0c-4433-8141-a7ceb8586f52/DS1/AS
      1 /public/view/item/uuid:71c1e174-a3b3-4b8f-9102-8e883c69112d/DS1/AOSERP
      1 /public/view/item/uuid:94f12887-3fe8-41f8-a376-d0c4951d0e0d/DS1/cjps36.1
      1 /rules
      1 /sitemap/sitemap_0.xml
      1 /sitemap/sitemap_1.xml
      2 /public/datastream/get/uuid:7bb613b7-9b30-4f18-b875-f1c0d7c5a296/DS1/D_2004_15_3
      2 /public/datastream/get/uuid:a8b919d8-4a83-49fa-b7cb-11de9e21e23d/DS1/Barret_Weber_Spring
      2 /public/datastream/get/uuid:dac708b1-dd24-4c2e-873f-2a315aa4dc50/DS1/IJOPS_167_2006_649
      2 /public/datastream/get/uuid:fcab1788-96b4-4622-9bab-9e5a015dfb9e/DS1
      2 /public/view/item/uuid:9decac8e-4d43-4c82-886c-dfa747278fb3/DS1/Dr.
      3 /public/datastream/get/uuid:3b1997a3-45e8-4a2b-b601-f7fbe6743a14/DS1
      3 /public/datastream/get/uuid:69f1bc57-dec5-46c7-b3b7-1062a289eb87/DS1/TAFS_119_1990_337
      3 /public/researcher/getPicture/63
      4 /public/search
      5 /public/search/narrow
     20 /public/login
    675 /public/home/message
    705 /public/browse/stats

</pre>

**Comment by pbinkley** [comment]
The important ones (with DS links) are working now. I'll close this; we should do a fresh investigation of the logs after the audit (and again after PCDM).
