### ISSUE TITLE
ERA timing out

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#829]
I'm getting 504 gateway timeout error on the ERA homepage. I'm sure somebody's already working on it, but capturing here as well.

**Comment by weiweishi** [comment]
This was solved with a Fedora restart by @henryzhang87. Some summary from him:

--  haproxy:  the request got to haproxy node very quickly, and haproxy node passed the requests
                 to the application server newport and leyton very quickly as well

-- the application servers.
                           * cpu usage is very little
                            * memory usage is very little
                            * disk I/O is basically  nothing
                             * swap memory is not usage at all
                             * incoming/outgoing network traffic not much

                 No reason to believe that we have computer resource problems on the application servers.

 --  SolrCloud:  
                   * run query from SolrCloud GUI and command line to get all communities, it returned 
                     results in 0.02s. 
                   * run query to get all documents, it returned results instantly.

 --  Fedora Server:

                   - everything points to Fedora server
                   - Just blindly restarted tomcat7 on Fedora server, we got the responsiveness back. 

How to improve availability and performance remains to be an issue.
