### ISSUE TITLE
Some (?) Google Scholar links back to ERA content broken

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#835]
With reference to #435 and #321, some initial testing indicates that links back to ERA for previously indexed material from Google Scholar are failing. Here is one example. I found another similar example too.

Example: https://era.library.ualberta.ca/files/m039k564p#.VjnbCipViko

Title: Rape and Other War Crimes in Chechnya: Is there a Role for the International Criminal Court?

GS search result: https://scholar.google.com/scholar?q=Rape+and+Other+War+Crimes+in+Chechnya%3A+Is+there+a+Role+for+the+International+Criminal+Court%3F&btnG=&hl=en&as_sdt=0%2C5

Sources grouped for this title: 5, including 2 for UofA/ERA (one for landing page, one for pdf?)
UofA links back:
https://era.library.ualberta.ca/public/view/item/uuid:8e28a4a3-2f1c-4d1a-bc92-253f124d979d/DS1/SOI_5_2005_89.pdf
https://era.library.ualberta.ca/public/datastream/get/uuid:8e28a4a3-2f1c-4d1a-bc92-253f124d979d/DS1/SOI_5_2005_89.pdf

.../view/item... --> resolves to the PDF, but
.../datastream/get/... --> does not resolve.

Looking at our Google Scholar guidelines, we may need to address again the question adding .pdf file extension to links to the full text, adding DSI to URLs and possibly the directory structure, as was undertaken for old ERA.
https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#

Another possibility to investigate is the instruction from Google:

"If you need to move your articles to new URLs, set up HTTP 301 redirects from the old location of each article to its new location. Do not redirect article URLs to the homepage - users need to see at least the abstract when they click on your URL in Google results."

https://scholar.google.com/intl/en/scholar/inclusion.html#crawl

**Comment by pbinkley** [comment]
The redirects have been fixed by #831, which will be deployed in Friday's tagged release. Would you care to put the file extension part into a new epic issue for SEO enhancements? We can gather them there and then break them down when we're ready to work on them.

**Comment by johnhuck** [comment]
Thanks, Peter. I'm going to add the issues specific to Google Scholar indexing to #435. If we also intend to do traditional SEO, it seems to me that would be separate.
