### ISSUE TITLE
Index thesis fields into regular fields

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#837]
- [x] We need to index thesis fields (dissertant, abstract) into the equivalent indexes used by non-thesis items. These should also be in the general keyword index, like their non-thesis equivalents.
  - [x] dissertant -> creator
  - [x] abstract -> description
- [x] include NOID, department, supervisor and committee_member in the general keyword index
- [ ] document mappings from metadata fields through to solr fields as defined at various levels (from Blacklight up to HydraNorth) in the data dictionary (link to be provided by @johnhuck)

Original issue (from @sfbetz):

I was searching for this thesis, and could not find it by using the author's name as a keyword in the basic search:
![screen shot 2015-11-04 at 11 42 57 am](https://cloud.githubusercontent.com/assets/12801010/10951549/595bf266-82fb-11e5-88db-eb2e80714562.png)

I check some other examples and can't retrieve theses by author name, not even using the author field in the advanced search. Search for author seems to be working for other item types (eg articles). Is there something happening with the way ERA is handling theses metadata that is preventing this from happening for theses?

**Comment by anayram** [comment]
Could it be that the marcrel:dis field needs to be mapped to the creator
field for search results?

This item is part of the legacy theses. For migration the dc:creator or
dcterms:creator field was mapped to marcrel:dis

On Wed, Nov 4, 2015 at 1:54 PM, Sonya Betz <notifications@github.com> wrote:

> I was searching for this thesis, and could not find it by using the
> author's name:
> [image: screen shot 2015-11-04 at 11 42 57 am]
> <https://cloud.githubusercontent.com/assets/12801010/10951549/595bf266-82fb-11e5-88db-eb2e80714562.png>
>
> Search for author seems to be working for other item types (eg articles).
> Is there something happening with the way ERA is handling theses metadata
> that is preventing this from happening for theses?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/837>.
>



-- 
Mariana Paredes-Olea
paredeso@ualberta.ca
780-492-7075

**Comment by sfarnel** [comment]
I would imagine this is the issue.

On Wed, Nov 4, 2015 at 2:19 PM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> Could it be that the marcrel:dis field needs to be mapped to the creator
> field for search results?
>
> This item is part of the legacy theses. For migration the dc:creator or
> dcterms:creator field was mapped to marcrel:dis
>
> On Wed, Nov 4, 2015 at 1:54 PM, Sonya Betz <notifications@github.com>
> wrote:
>
> > I was searching for this thesis, and could not find it by using the
> > author's name:
> > [image: screen shot 2015-11-04 at 11 42 57 am]
> > <
> https://cloud.githubusercontent.com/assets/12801010/10951549/595bf266-82fb-11e5-88db-eb2e80714562.png
> >
> >
> > Search for author seems to be working for other item types (eg articles).
> > Is there something happening with the way ERA is handling theses metadata
> > that is preventing this from happening for theses?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ualbertalib/HydraNorth/issues/837>.
> >
>
>
>
> --
> Mariana Paredes-Olea
> paredeso@ualberta.ca
> 780-492-7075
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/837#issuecomment-153868671>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by pbinkley** [comment]
I've changed the name of the issue to reflect the implementation that is needed. Are there any other changes to indexing that are needed for the marcrel fields used by the legacy theses? @sfbetz, would you mind testing with that same thesis to see if committee etc. are handled as you expect? We may as well capture them into a single issue if so.

**Comment by sfbetz** [comment]
I would like department to be a searchable field (and it would be SUPER helpful as a facet).
I would like Supervisor and Examining committee to be searchable fields.

I would like description to be searchable as well, but maybe that's a step too far?

**Comment by pbinkley** [comment]
While we're at it let's make the NOID searchable in the general search, so that you can just paste one in the search box to retrieve the file/collection.

**Comment by johnhuck** [comment]
Here is the Hydra North Data Dictionary:

https://docs.google.com/spreadsheets/d/1hSd6kf4ABm-m8VtYNyqfJGtiZG7bLJQ3fWRbF_nVoIw/edit?usp=sharing

**Comment by johnhuck** [comment]
@mbarnett Add a tab for your work and organize however you see fit. The PCDM Object tab is the main sheet that lists the predicates of the metadata elements we are using and what ERA object types they may be applied to. You may also find it useful to refer to the Current Hydranorth Generic File tab, which contains information that Weiwei added.

**Comment by mbarnett** [comment]
Thanks, John

**Comment by pbinkley** [comment]
OK, I know it's late to be asking this, but do we really need dissertant and abstract to be different fields from creator and description? Couldn't we just map creator to dissertant and description to abstract when we're generating ETDMS records? Is there anywhere else where we care about the difference between a dissertant and a creator?

**Comment by sfarnel** [comment]
Thanks Peter. I would argue that we definitely do. An abstract is a more
specific type of description with its own meaning. Dissertant is a more
specific kind of creator, with its own meaning. If we want at any time to
drive functionality with the more specific metadata we need to capture it
now; teasing out the specifics later on becomes very challenging (and
perhaps near impossible). While one could argue that we could work out that
an individual listed as creator when the object type is thesis means that
person must be a dissertant, this is more for human reasoning than for
machine action. If we are able to express these relationships concisely and
with a specific property we should; that's what can enable functionality
and the benefits of linked data. Thinking for example of Eleni's work,
wanting/needing to tease out students supervised versus committee
membership versus authoring papers, depends on the ability to express this
simply and concisely and in a machine readable manner. The ability to
handle such nuances is only going to become more important as we move into
more complex metadata like Peel, Steele, etc.

On Mon, Dec 14, 2015 at 2:27 PM, Peter Binkley <notifications@github.com>
wrote:

> OK, I know it's late to be asking this, but do we really need dissertant
> and abstract to be different fields from creator and description? Couldn't
> we just map creator to dissertant and description to abstract when we're
> generating ETDMS records? Is there anywhere else where we care about the
> difference between a dissertant and a creator?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/837#issuecomment-164565098>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
