### ISSUE TITLE
Embargoed items moving into wrong visibility category

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#838]
This from Sandra Castellarin, who deposits our licensed resources:

Parliament Now, Nov 4 ed - received on Nov 3, uploaded to ERA on Nov 3 with a embargoed visibility setting of private until Nov 4 and then University of Alberta (see image below)

![image](https://cloud.githubusercontent.com/assets/12801010/10955695/f5353fdc-8312-11e5-9b79-10dd7b7815f6.png)

Checked today, status has changed from embargo to private and therefore isn't visible to the UA community.

![image 1](https://cloud.githubusercontent.com/assets/12801010/10955699/fb1a3ac4-8312-11e5-8c64-4418badc4d35.png)

**Comment by weiweishi** [comment]
On the visibility status, it will always show the "current" visibility. So after the embargo is set to private during embargo, it will always appear as private in the form, until the embargo is cleared. 

After our next deployment, we will have a rake task to clear any expired embargoes. @henryzhang87, maybe we can work with you next week to schedule the rake task to run after midnight everyday?

**Comment by sfbetz** [comment]
I think the above item should have cleared embargo and be displaying as U of A instead of private, though? Do they change status at the beginning of the day marked or the end?

**Comment by weiweishi** [comment]
It's because the embargoes don't clear themselves automatically. We will
need to schedule the rake task and run it on the daily basis, probably at
the beginning of the day.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
With old ERA I believe the script that did this ran just after midnight.

Sent from my iPhone

On Nov 4, 2015, at 5:03 PM, Weiwei Shi <notifications@github.com> wrote:

It's because the embargoes don't clear themselves automatically. We will
need to schedule the rake task and run it on the daily basis, probably at
the beginning of the day.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

On Wed, Nov 4, 2015 at 4:51 PM, Sonya Betz <notifications@github.com> wrote:

> I think the above item should have cleared embargo and be displaying as U
> of A instead of private, though? Do they change status at the beginning of
> the day marked or the end?
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-153907749>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-153909741>
.

**Comment by sfbetz** [comment]
Thanks both for the context. Should I change the label to "Sonya, it's not
a bug" :) ?

On Wed, Nov 4, 2015 at 5:15 PM, Sharon Farnel <notifications@github.com>
wrote:

> With old ERA I believe the script that did this ran just after midnight.
>
> Sent from my iPhone
>
> On Nov 4, 2015, at 5:03 PM, Weiwei Shi <notifications@github.com> wrote:
>
> It's because the embargoes don't clear themselves automatically. We will
> need to schedule the rake task and run it on the daily basis, probably at
> the beginning of the day.
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Wed, Nov 4, 2015 at 4:51 PM, Sonya Betz <notifications@github.com>
> wrote:
>
> > I think the above item should have cleared embargo and be displaying as U
> > of A instead of private, though? Do they change status at the beginning
> of
> > the day marked or the end?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-153907749
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <
> https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-153909741
> >
>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-153912588>
> .
>



-- 
Sonya Betz
Digital Initiatives Projects Librarian
Acting Digital Repository <http://era.library.ualberta.ca/> Services
Librarian



*University of Alberta Libraries2-10U Cameron Library, University of
AlbertaEdmonton, AB, Canada T6G 2J8  *
*sonya.betz@ualberta.ca <sfbetz@ualberta.ca> *
*780-492-1718*

**Comment by sfarnel** [comment]
I don't think so. It's the best way to catch the ones that are bugs :)

On Thu, Nov 5, 2015 at 2:04 PM, Sonya Betz <notifications@github.com> wrote:

> Thanks both for the context. Should I change the label to "Sonya, it's not
> a bug" :) ?
>
> On Wed, Nov 4, 2015 at 5:15 PM, Sharon Farnel <notifications@github.com>
> wrote:
>
> > With old ERA I believe the script that did this ran just after midnight.
> >
> > Sent from my iPhone
> >
> > On Nov 4, 2015, at 5:03 PM, Weiwei Shi <notifications@github.com> wrote:
> >
> > It's because the embargoes don't clear themselves automatically. We will
> > need to schedule the rake task and run it on the daily basis, probably at
> > the beginning of the day.
> >
> > *Weiwei Shi*
> >
> > Digital Initiative Applications Librarian
> > University of Alberta Libraries
> > 2-10L Cameron Library
> > Edmonton, Alberta, Canada T6G 2J8
> > Phone:(780)492-7802
> > Fax: (780)248-1209
> > Email: weiwei.shi@ualberta.ca
> >
> > On Wed, Nov 4, 2015 at 4:51 PM, Sonya Betz <notifications@github.com>
> > wrote:
> >
> > > I think the above item should have cleared embargo and be displaying
> as U
> > > of A instead of private, though? Do they change status at the beginning
> > of
> > > the day marked or the end?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-153907749
> > >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> >
> https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-153909741
> > >
> >
> > .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-153912588
> >
> > .
> >
>
>
>
> --
> Sonya Betz
> Digital Initiatives Projects Librarian
> Acting Digital Repository <http://era.library.ualberta.ca/> Services
> Librarian
>
>
>
> *University of Alberta Libraries2-10U Cameron Library, University of
> AlbertaEdmonton, AB, Canada T6G 2J8 *
> *sonya.betz@ualberta.ca <sfbetz@ualberta.ca> *
> *780-492-1718*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/838#issuecomment-154190991>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
No Sonya :). It is a bug - (a fixed but not deployed one is still a bug),
and it's great to be able to track it on Github.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfbetz** [comment]
Daily rake task scheduled - @weiweishi can you confirm? If so this can be closed...

**Comment by pbinkley** [comment]
@henryzhang87 can you confirm that rake task "rake hydranorth:remove_lapsed_embargoes" is running as a nightly cron job in production?

**Comment by pgwillia** [comment]
from @henryzhang87 

> and on bournemouth, we have embargo script
> #Ansible: embargoes
> 1 22 * * * cd /var/www/sites/hydranorth && RAILS_ENV=production bundle exec rake hydranorth:remove_lapsed_embargoes
