### ISSUE TITLE
Browsing by communities and collections

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#840]
Thoughts for improving the UX of communities and collections - needs to be tested on real users before committing to implementation.

-------------------

**Top level Community browse page:** #960

As a user I want to browse communities and collections so I can easily find sets of items produced by organizational entities.

As a collection “owner” (not technically, but organizationally) I want to be able to showcase sets of items from my research group or department so I can demonstrate the body of work being created.

As a researcher, I was my items to be grouped with similar items so that they become more findable for end users, and to emphasize my connection to a department or group.

Functional solution that gets directly to the collections very quickly (but looks too much like DSpace). Note that both collections and communities are clickable from this page.. Could use chevrons instead of + signs for expandable content or do something more visually interesting.

https://ecommons.cornell.edu/community-list 

--------------------------------
**Community page** #961

As a user, I want to be able to see all of a community’s collections so I can easily browse those collections.
As a user, I want to be able to sort a community’s collections by title, number of items, or most recently updated so I can easily find relevant collections.

As a user, I want to be able to search for items within a community so I can easily find items that belong to any of its collections.

As a user, I want to be able to see items with no collections (only a community), so they don’t get lost (? are there any of these?)

As a collection owner, I want to be able to attach some branding to my community to provide some recognition of its identity.

UI ideas here: https://docs.google.com/presentation/d/1INXmuNfTPFGVC9sMAh8iLYzD2FnBCPkAEKCF3Su4Vqk/edit?usp=sharing

-----------------

**Collections page** #962
As a user I want to be able to browse sets of items grouped by collections so I can find related items.

As a user, I want options to sort and refine sets of items, so I can easily find what I’m looking for.

UI ideas here: 
https://docs.google.com/presentation/d/195k-GIB4C2W7KFrqna6XMki8IGxvWaZx_HGBXZSYzh8/edit?usp=sharing

**Comment by pbinkley** [comment]
@sfbetz wants to discuss with @nnunn , hope to have in shape for Sprint 32

**Comment by pbinkley** [comment]
I've put @nnunn's name on this just so others know not to pick it up until her work is done.
