### ISSUE TITLE
Administrator tasks: find and manage all items

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#841]
From epic #833 - hope this helps flesh out this section:

As an administrator, I want to have the ability to find and manage all items, so I can effectively administer ERA’s items:

-search and view all items (including private items not owned by me) 
-edit all items (including items I do not own)
-delete all items
-transfer ownership of all items (including items I do not own)
-share ownership of all items (including items I do not own)

Example scenarios driving these needs: 

User X contacts ERA Help: I need help adding a description (license info, author names, etc) to an item I am uploading. Can you review and help me through the process? Problem: I can't find other users private items in search. I think I can see them in all files tab in dashboard, but it doesn't allow for any searching function.

User Y contacts ERA Help: I accidentally uploaded the wrong file while completing a self deposit. Can you please delete it for me? Problem: No delete function for admin.

User Z, who completes mediated deposit for her department: the other staff member who completes mediated deposit for my dept is on mat leave. Can you transfer her files to me? Problems: I can't transfer ownership from one user to another and I can't see a user's list of files.

**Comment by pbinkley** [comment]
Closed by #867
