### ISSUE TITLE
OAI server should make ETDMS record available only for theses

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#845]
In old ERA, there was no way to restrict the availability of a record type, so ETDMS records were available for all items, even though they make sense only for theses. 

As an OAI harvester, I want to be able to retrieve ETDMS records only for theses, and I want to be able to detect whether an ETDMS record is available (using the ListMetadataFormats verb), so that I can harvest the right record format for my needs.

**Comment by piyapongch** [comment]
Can you give me to the oai_etdms schema?

**Comment by piyapongch** [comment]
This is not possible at this point unless there is an item property for metadata prefixes. Users can request oai_etdms metadataPrefix for a set that they want.

**Comment by anayram** [comment]
@piyapongch looks like we are still getting etdms records for non-thesis objects.

Examples:

http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t7jw827d11n

http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_etdms&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t75h73px40b

**Comment by piyapongch** [comment]
I have done in ListRecords and ListIdentifier. I will add the condition to
GetRecord verb and let you know when it is done.

Piyapong.

**Comment by piyapongch** [comment]
I have added the condition to GetRecord verb and deploy on plano. Try again.

**Comment by anayram** [comment]
Works now, closing ticket.
