### ISSUE TITLE
Google Scholar Indexing (2): Modify directory structure

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#849]
Issue 2 of Epic #435.

With reference to UAL's [Google Scholar Strategy document] (https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#bookmark=id.jd4nolw32z5s).

Modify directory structure so .pdf file is found in same directory as the landing page.

Current structure:
landing page URL: https://era.library.ualberta.ca/files/bsj139193r
file download URL: https://era.library.ualberta.ca/downloads/bsj139193r

cf. https://scholar.google.com/intl/en/scholar/inclusion.html#indexing
-->
H. The '<' meta '>' tags normally apply only to the exact page on which they're provided. If this page shows only the abstract of the paper and you have the full text in a separate file, e.g., in the PDF format, please specify the locations ofall full text versions using citation_pdf_url or DC.identifier tags. The content of the tag is the absolute URL of the PDF file; for security reasons, **it must refer to a file in the same subdirectory as the HTML abstract.**

**Comment by sfbetz** [comment]
complete
