### ISSUE TITLE
Google Scholar Indexing (3): Browse by date

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#850]
Issue 3 of Epic #435.

With reference to UAL's [Google Scholar Strategy document] (https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#bookmark=id.jd4nolw32z5s).

Ensure that ERA content is crawl-able by ensuring that we have a suitable 'browse by date' interface, as recommended in the inclusion guidelines (and perhaps configure exclusions appropriately in the robot.txt file).

https://scholar.google.com/intl/en/scholar/inclusion.html#crawl

B. If your website has thousands of papers or more, the best way to make sure they're all discovered by the search robots is to provide a way to list them by the date of publication or the date of record entry. Other forms of browse interfaces, such as browse by author or by keyword, often generate more URLs than your website can deliver to the search robots in a reasonable amount of time.

C. For websites with more than a hundred thousand papers, we recommend that you create an additional browse interface that lists only the articles added in the last two weeks. This smaller set of webpages can be recrawled more frequently than your entire browse interface, which will facilitate timely coverage of your recent papers by the search robots.

**Comment by weiweishi** [comment]
- [ ] requires a time-based browsable page, maybe link on the front page within the sitemap function. 
- [ ] a sitemap (depending on what do we want to include? it may require a cache for faster constructing the map)
- [ ] libhub version of the site? 
- [ ] schema.org (regular google crawling)

**Comment by pgwillia** [comment]
Sufia has recently uploaded items featured on the front page.  
![screenshot from 2016-03-22 10-52-58](https://cloud.githubusercontent.com/assets/1220762/13960069/696307ec-f01c-11e5-8dda-56da1e6e6448.png)
Using the same logic it should be easy to re-introduce recently uploaded items to Hydranorth.  @leahvanderjagt  do we want this on the front page, somewhere else, or on it's own page?

**Comment by leahvanderjagt** [comment]
If they are all equal in terms of how they would support Google Scholar
indexing then I think it would be good to have it on the front page
somewhere as long as it wouldn't slow down the front page loading. I wasn't
here for the decisions made for how the front page would look (and I really
like the way it looks now) so I'm going to talk to @sbetz about this before
providing further guidance.

On Tue, Mar 22, 2016 at 10:57 AM, pgwillia <notifications@github.com> wrote:

> Sufia has recently uploaded items featured on the front page.
>
> [image: screenshot from 2016-03-22 10-52-58]
> <https://cloud.githubusercontent.com/assets/1220762/13960069/696307ec-f01c-11e5-8dda-56da1e6e6448.png>
> Using the same logic it should be easy to re-introduce recently uploaded
> items to Hydranorth. @leahvanderjagt <https://github.com/leahvanderjagt>
> do we want this on the front page, somewhere else, or on it's own page?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/850#issuecomment-199905136>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by pgwillia** [comment]
Just chatted with @leahvanderjagt.  I'm going to 
* replace the twitter block on the front page with the most recently updated *public* item
* display the thumbnail, title and subjects (within space constraints)
* not affect performance on the front page
* link to a /recent target 
  * will display the most recent *public items* in the last 2 weeks
  * be the destination for Google Scholar to crawl

**Comment by mbarnett** [comment]
As discussed last night, there are a few ways you could keep a lot of logic out of the main view for processing those date ranges. The main one we talked about was mapping over the collection in the controller, and then processing the result in a helper method using something like ```content_tag```. There's a good post about using them here: http://thepugautomatic.com/2013/06/helpers/

I do like the advice at the end of that article to split it out into partials if your helper gets too complex. It sounded like you'd probably want to use one "parent" partial for the whole thing and a separate collection partial that takes care of rendering each item. There's a lot of information out there for structuring collection partials well, but this seems like a good intro: http://blog.8thcolor.com/en/2013/07/partials-abuse-of-them-dont-abuse-them/
