### ISSUE TITLE
Google Scholar Indexing (4): Ensure date of publication is present

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#851]
Issue 4 of Epic #435.

With reference to UAL's [Google Scholar Strategy document](https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#bookmark=id.jd4nolw32z5s).

Ensure ERA items have a date of publication, one of 3 mandatory elements.

https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

C. The publication date tag, e.g., citation_publication_date or DC.issued, must contain the date of publication, i.e., the date that would normally be cited in references to this paper from other papers. Don't use it for the date of entry into the repository - that should go into citation_online_date instead. Provide full dates in the "2010/5/12" format if available; or a year alone otherwise. **This tag is required for inclusion in Google Scholar.**

**Comment by weiweishi** [comment]
publication date issue can be addressed largely as part of #571. 
1000+ items may require more investigation after.

**Comment by pbinkley** [comment]
This will be resolved when we resolve the mapping of publication dates for migrated theses.
