### ISSUE TITLE
Google Scholar Indexing (5): Ensure abstracts are accessible

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#852]
Issue 5 of Epic #435.

With reference to UAL's [Google Scholar Strategy document](https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#bookmark=id.jd4nolw32z5s).

Ensure that ERA item abstracts are being presented appropriately on landing pages.

The abstract is emphasized in the inclusion guidelines, to the point where the landing page is referred to as the HTML abstract.

"Likewise, all PDF files will be processed as if they had no meta tags at all, unless they're linked from the corresponding **HTML abstracts** using citation_pdf_url or DC.identifier tags."
https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

But there does not appear to be a Highwire Press tag for abstract.

The complete list of tags is not easy to find. Highwire is a Stanford service/product, but documentation could not be found on their site. There is a list in this [article from 2011](https://jira.duraspace.org/secure/attachment/13020/Invisible_institutional.pdf), but it differs in several respects from the tags cited in the inclusion instructions (e.g., citation_date vs. citation_publication_date).

So it is unclear to me from reading the guidelines what the appropriate way to present the abstract actually is. Is it enough to simply having the text somewhere in the HTML or does it need to go in some kind of tag?

Finally, not all ERA items have abstracts. Could we extract them from the OCR for some of those items lacking abstracts? Would this have copyright implications?

Example: https://era.library.ualberta.ca/files/bsj139193r#.VkYEPypViko

**Comment by sfarnel** [comment]
I think abstract is something that we can provide when we can provide it,
but a discussion around generating it somehow when we don't is a very big
question with serious implications of various kinds. Good for thought down
the line. Google identifies as minimum author(s), title, year; the more
other you have the more helpful it can be of course but some of the others
can be considered 'bonus' in a way.

On Fri, Nov 13, 2015 at 11:55 AM, johnhuck <notifications@github.com> wrote:

> Issue 5 of Epic #435
> <https://github.com/ualbertalib/HydraNorth/issues/435>.
>
> With reference to UAL's Google Scholar Strategy document
> <https://docs.google.com/document/d/1t8LMGsYEQtkvWOSGHLXJDGJ-8fLVPgumrBqwWHQjkMY/edit#bookmark=id.jd4nolw32z5s>
> .
>
> Ensure that ERA item abstracts are being presented appropriately on
> landing pages.
>
> The abstract is emphasized in the inclusion guidelines, to the point where
> the landing page is referred to as the HTML abstract.
>
> "Likewise, all PDF files will be processed as if they had no meta tags at
> all, unless they're linked from the corresponding *HTML abstracts* using
> citation_pdf_url or DC.identifier tags."
> https://scholar.google.com/intl/en/scholar/inclusion.html#indexing
>
> But there does not appear to be a Highwire Press tag for abstract.
>
> The complete list of tags is not easy to find. Highwire is a Stanford
> service/product, but documentation could not be found on their site. There
> is a list in this article from 2011
> <https://jira.duraspace.org/secure/attachment/13020/Invisible_institutional.pdf>,
> but it differs in several respects from the tags cited in the inclusion
> instructions (e.g., citation_date vs. citation_publication_date).
>
> So it is unclear to me from reading the guidelines what the appropriate
> way to present the abstract actually is. Is it enough to simply having the
> text somewhere in the HTML is enough, or does it need to go in some kind of
> tag?
>
> Finally, not all ERA items have abstracts. Could we extract them from the
> OCR for some of those items lacking abstracts? Would this have copyright
> implications?
>
> Example: https://era.library.ualberta.ca/files/bsj139193r#.VkYEPypViko
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/852>.
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by johnhuck** [comment]
Sorry, I should have been more clear about this: I was thinking of cases where there was an abstract section in the paper but not in the metadata (I saw one example), but I agree it's not a core element and could be fraught with challenges, so best to leave it for now.

**Comment by pbinkley** [comment]
We might look at ways to encourage depositors to paste the abstract into the metadata, at least.
