### ISSUE TITLE
can't get ride of the Not Found error message on Password Reset page

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#853]
Debbie has discovered that on the password reset page, if an "Not Found" error message is thrown, user can't get ride of this error message by refreshing the page, or reentering the correct email. They can only get rid of the message by leaving the page and coming back again. 
![image](https://cloud.githubusercontent.com/assets/2047614/11153179/5d04f1ce-89f4-11e5-858e-d543078e8436.png)

**Comment by pbinkley** [comment]
We want to present the user with the full original form again, so that they can enter a good email if they made a typo the first time.

**Comment by weiweishi** [comment]
This issue can't be reproduced. No longer relevant.
