### ISSUE TITLE
Bug: failure to extract text by Solr leaves batch with status "processing"

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#863]
@sfbetz identified two articles that had remained in the "processing" state for days after they were uploaded: they showed "File is being processed; you may edit when processing has completed" in the item view under Actions, where the "Edit" link should be. It was therefore impossible to edit them. The logs showed that they had failed when Solr attempted to extract their content:

```
E, [2015-11-18T14:03:05.073816 #2199] ERROR -- : Error extracting content from bp2676v527: #<RuntimeError: URL 'http://tottenham.library.ualberta.ca:8080/solr/hydranorth/update/extract?extractOnly=true&wt=json&extractFormat=text' returned code 500>
```
The result was that the batch ended up with status="processing":
```
=> #<Batch id: "b6682x394v", creator: [], title: [], status: ["processing"]>
```
The solution was to change the status manually:
```
batch.update(status: ["Complete"])
```
We want the processing to fail gracefully when Solr has an extract error, leaving the item with no content; and we want to look into why these two PDFs baffled Solr. The two items are b2n49t168w and bp2676v527.

**Comment by pbinkley** [comment]
Should have been fixed by #883 - check after next release

**Comment by pbinkley** [comment]
@sfbetz has a pdf that used to cause this problem during testing - let's try it again.

**Comment by sfbetz** [comment]
I believe this was the PDF we used in round one of user testing: https://drive.google.com/file/d/0BwXbqVc9w_ukaVN3dFFXRy1DSEU/view?usp=sharing

**Comment by pbinkley** [comment]
Thanks, I'll test in a current dev vm.

>

**Comment by pbinkley** [comment]
This pdf does not cause a hang. I'll close the issue until we have a report of a problem item.
