### ISSUE TITLE
Disable full-text indexing

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#875]
Prevent uploaded files from being passed to Solr for content extraction and indexing.

Some items remain in "processing" state, which prevents the user from editing them. The intermediate cause is that the Batch retains status "processing". This is sometimes associated with errors in Solr's attempt to extract content.

See OTRS ticket 2015120210963 for background and examples.

**Comment by pgwillia** [comment]
Might not be finished.  Looks like 
```
Error extracting content from 5t34sj59n: #<RuntimeError: URL 'http://127.0.0.1:8983/solr/development/update/extract?extractOnly=true&wt=json&extractFormat=text' returned code 500>
```
Appearing in my logs
