### ISSUE TITLE
change 'Descriptions' heading on ERA item page?

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/HydraNorth#879]
The section heading on the item display page that sits above the metadata is "Descriptions." Unless there is a specific reason for this, could it be changed to the singular "Description" instead? @sfbetz and @sfarnel both concur that the plural form is odd and perhaps a little confusing.

![descriptions](https://cloud.githubusercontent.com/assets/5233196/11481445/c9cc8d80-975a-11e5-8c82-4e4f74e9d976.jpg)

**Comment by pbinkley** [comment]
Do we need the "Description" heading at all? The title is represented only
by the heading above, so it makes sense to me to have the other metadata
fields flow continuously below it. How about removing "Descriptions" and
the horizontal bar below it, and just leave enough space to look nice under
the large title? (This seems like a survival from the self-deposit
priorities of Sufia, and not well adapted to the environment  of citable
bibliographic metadata that we're running in ERA).

​Peter​

**Comment by weiweishi** [comment]
I agree. and also thinking that the "embargo history" should be added to
somewhere in this section, instead of in the file details section. I think
the "file detail" section should be purely technical metadata of the
characterization of the file, and nothing about the item itself.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfbetz** [comment]
Agreed - I'm in full support of reducing the amount of non-critical
information displayed to the user. Eliminating the "description" header
will make the item record easier to read.

Cheers,
Sonya

On Mon, Nov 30, 2015 at 12:32 PM, Weiwei Shi <notifications@github.com>
wrote:

> I agree. and also thinking that the "embargo history" should be added to
> somewhere in this section, instead of in the file details section. I think
> the "file detail" section should be purely technical metadata of the
> characterization of the file, and nothing about the item itself.
>
> Weiwei
>
> *Weiwei Shi*
>
> Digital Initiative Applications Librarian
> University of Alberta Libraries
> 2-10L Cameron Library
> Edmonton, Alberta, Canada T6G 2J8
> Phone:(780)492-7802
> Fax: (780)248-1209
> Email: weiwei.shi@ualberta.ca
>
> On Mon, Nov 30, 2015 at 12:18 PM, Peter Binkley <notifications@github.com>
> wrote:
>
> > Do we need the "Description" heading at all? The title is represented
> only
> > by the heading above, so it makes sense to me to have the other metadata
> > fields flow continuously below it. How about removing "Descriptions" and
> > the horizontal bar below it, and just leave enough space to look nice
> under
> > the large title? (This seems like a survival from the self-deposit
> > priorities of Sufia, and not well adapted to the environment of citable
> > bibliographic metadata that we're running in ERA).
> >
> > ​Peter​
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/HydraNorth/issues/879#issuecomment-160730434
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/879#issuecomment-160734590>
> .
>



-- 
Sonya Betz
Digital Initiatives Projects Librarian
Acting Digital Repository <http://era.library.ualberta.ca/> Services
Librarian



*University of Alberta Libraries2-10U Cameron Library, University of
AlbertaEdmonton, AB, Canada T6G 2J8  *
*sonya.betz@ualberta.ca <sfbetz@ualberta.ca> *
*780-492-1718*

**Comment by johnhuck** [comment]
If the heading can be eliminated, that's probably a better solution. However, I wonder if the change shouldn't be checked with Natasha to ensure that there isn't an issue with mobile display or whatnot. Also I would defer to her judgement on whether or not to keep the line. On mobile, the scroll sequence of sections is alphabetical: Actions, Communities, Collections, [title] Descriptions, File Details. That's probably why Description is plural, actually: it's following the pattern of the other section titles.

**Comment by pbinkley** [comment]
Decision: remove the heading "Descriptions" from item display.
