### ISSUE TITLE
Collection field in item edit screen not updating to match community

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#887]
Communities are now listed in the item edit screen (yay!), but when you select a community, the collections list doesn't update to match collections that are in that community, and instead lists lots of collections that are not in that community (not sure if it's listing all of them).

![8b7bc811-f017-436c-9b08-7f02bc998d1d](https://cloud.githubusercontent.com/assets/12801010/11638897/92c58828-9ce6-11e5-897e-b6a4f08276ab.png)
.

**Comment by sfbetz** [comment]
We've solved almost all the issues around collections in the forms, BUT, for both edit and upload screens, collections are now not updating to match their communities. This may lead to users adding items in a community, and also inadvertently into a collection that does not belong to that community.

**Comment by pgwillia** [comment]
In production ERA I am seeing the collection drop down refresh -- but after waiting a beat while the last set is still displayed. I'm guessing that this should be non-perceptible to the user? Would clearing the collection selection list while the new set is calculated be acceptable?

**Comment by pgwillia** [comment]
Nevermind.  I can see where this is a problem when editing an item. Working to resolve -- might be a problem between use of presenter and forms.

**Comment by pbinkley** [comment]
It wasn't in the original issue, but it should have been, and I hope it's a quick fix: could we get the collections sorted alphabetically by title at https://github.com/ualbertalib/HydraNorth/blob/887_filter_collections/app/views/generic_files/_filtered_collections.html.erb#L2 ?

**Comment by pgwillia** [comment]
Minor set back.  The Collection object is using building a Solr query for Collection.where(...).order(:title) and because title is permitted to be multivalued this isn't possible. I either have to (a) figure out a different way to apply order to the https://github.com/ualbertalib/HydraNorth/blob/887_filter_collections/app/controllers/generic_files_controller.rb#L17 or (b) change and enforce the sortable type on titles.

**Comment by sfbetz** [comment]
I don't think item title should be multivalue?

**Comment by sfbetz** [comment]
See bug #949

**Comment by weiweishi** [comment]
Title are stored as multivalue as this is what Sufia allowed. We allow only
single value on the form but the backend data structure is still a
multivalue array.

Tricia:
@mbarnett did this:
https://github.com/ualbertalib/HydraNorth/blob/794c9c51852f676d71ac18ff1eb18562b7b87edf/app/controllers/concerns/hydranorth/collections/selects_collections.rb#L51-L52

Do you think this would be any help to your issue?

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mbarnett** [comment]
Yeah, you'll have to sort that in Ruby. Sorting in the Solr query was an exercise in frustration when I tried it.

**Comment by pgwillia** [comment]
Sorting by title implemented in hydra-collections v7.0.0, we're using v5.0.3

**Comment by pbinkley** [comment]
I'd say take the shortest cut possible - we know we'll be revisiting
collections in depth in pcdm,  so let's not build an elaborate solution
here. Can we just sort in the   .each loop?
