### ISSUE TITLE
Selecting more than 10 items to display at once breaks the "sort" function

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#888]
Selecting more than 10 items / page to display in the sort option breaks the display and no items show. Here I've selected 20 items per page, and none show (although the pagination at the bottom seems to be correct?). Same happens when I choose 50 or 100. 10 works fine.

![screen shot 2015-12-09 at 12 07 44 pm](https://cloud.githubusercontent.com/assets/12801010/11696174/4288d92e-9e70-11e5-974a-190c713bc612.png)

**Comment by pbinkley** [comment]
Fixed.
