### ISSUE TITLE
Aggregate statistics in dashboard not updating

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#889]
I don't think the stats in the dashboard are updating. According to this, admin has 0 views and 0 downloads - which is definitely not the case.
![screen shot 2015-12-09 at 12 30 54 pm](https://cloud.githubusercontent.com/assets/12801010/11696326/eac38bac-9e70-11e5-91c9-0b721206ac06.png)

**Comment by pbinkley** [comment]
Decision: remove the aggregated stats from the display ("which have been viewed / downloaded"). We'll restore this in Sufia 7.
