### ISSUE TITLE
Description and collection not sticky on upload

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#902]
When uploading a new file, description and collection field aren't sticking.

**Comment by pbinkley** [comment]
Here's an instance from testing on plano:
```
Processing by BatchController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"bQJNJ3LkUysFYBQnyE37FyvUPiuYsblgY2Q6LCLuWikXLFKAJn2wlj60kbULQAaoyjla7z4SdkA7ok68UlfOeg==", "title"=>{"sq87bv37k"=>["test"]}, "extra_description_count"=>"1", "generic_file"=>{"resource_type"=>["Image"], "language"=>"Ukrainian", "creator"=>["test"], "subject"=>["test"], "license"=>"http://creativecommons.org/publicdomain/mark/1.0/", "rights"=>"", "description"=>"test", "date_created"=>"", "contributor"=>[""], "spatial"=>[""], "temporal"=>[""], "is_version_of"=>"", "source"=>"", "related_url"=>"", "belongsToCommunity"=>["cc08hf89x"], "hasCollectionId"=>[""]}, "visibility_during_embargo"=>"restricted", "embargo_release_date"=>"", "visibility_after_embargo"=>"open", "visibility"=>"restricted", "new_user_name_skel"=>"", "new_user_permission_skel"=>"none", "update_permission"=>"", "id"=>"f7623d47q"}
```
(note the ```"description"=>"test"``` parameter). This leads to:

```
Unpermitted parameter: description
```

**Comment by sfbetz** [comment]
Collection actually seems to be sticking,  it's just not displaying in the edit field - for example, I uploaded several new videos to a community and collection, and they're all properly displaying under the collection. However, if I edit one of them, collection does not display, and the error described in #901 occurs.

Example: these videos all uploaded into the correct collection, but when editing the individual items, I can't see the collection in the form:

https://era.library.ualberta.ca/collections/44558v45h

**Comment by weiweishi** [comment]
confirmed that on the editing page when collection information is not presented:
![screenshot - 16-01-11 - 04 29 17 pm](https://cloud.githubusercontent.com/assets/2047614/12249946/6bf1cc92-b880-11e5-92d7-ccf2d05a94c9.png)
The collection information will be erased upon saving. 
And dashboard/files page will throw error messages as the list depending on proper collection information. So the fix should take care: 
- [ ]  retain collection information on the editing page
- [ ]  remove the dependency on the collection information on the file list page (or use community information and collection information instead, and failed elegantly if no collection information is presented. )

**Comment by weiweishi** [comment]
This should be fixed with PR #921

**Comment by sfbetz** [comment]
Does this fix include the "unsticky" description field as well or should we create a new issue to capture that?

**Comment by weiweishi** [comment]
ah! No it doesn't. The issue for unsticky description field still exists.
I'll create a new issue for that, and I assume that's high priority.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mbarnett** [comment]
Description issue is definitely unrelated to the collection issue. I'll start looking into it.

**Comment by weiweishi** [comment]
New issue created at #922.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
