### ISSUE TITLE
Collection refactoring

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#909]
As admin, I want the ability to nest collections into communities so I can easily organize official collections and communities. 

-when I create a new collection, I want to be able to choose a community to add it to.
-from an existing community, I want to be able to add collections to the community
-from an existing collection, I want to be able to add that collection to a community
-from the dashboard, "my communities and collections" I want to be able to select a collection and add it to a community.

@weiweishi do you have documentation as to how we are doing this without using the interface?

**Comment by pgwillia** [comment]
#686 shows this is a regression. It used to work...

**Comment by weiweishi** [comment]
Additional bugs that are related to this issue. 
- [ ] Adding a collection to the community from the community page (by clicking on Add Collections) It gives user a list that is not complete. It may related to the upper limit of search result returned similar to:
https://github.com/ualbertalib/HydraNorth/blob/master/app/models/collection_search_builder.rb#L5
![screenshot - 16-01-14 - 01 37 12 pm](https://cloud.githubusercontent.com/assets/2047614/12336847/de4db586-bac3-11e5-960d-bda1afcb79e3.png)

- [ ] When add a collection/file from the search result page 
![screenshot from 2016-01-14 13 41 36](https://cloud.githubusercontent.com/assets/2047614/12336956/838e4d44-bac4-11e5-90e1-ec0c594691f7.png)
It gives this message instead. 
![screenshot - 16-01-14 - 01 42 26 pm](https://cloud.githubusercontent.com/assets/2047614/12336980/99b82392-bac4-11e5-990e-833f0eb24bdc.png)

**Comment by pbinkley** [comment]
We think that fixing those two bugs will finish the issue, but we don't know for sure until we can  see what happens next.

**Comment by pbinkley** [comment]
subsumed by #1205
