### ISSUE TITLE
Error message when editing item, creating collection

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#910]
I'm getting the "we're sorry something went wrong" error trying to do basic editing and creating tasks in ERA. 

e.g. I tried to edit visibility of this item from open to private:

https://era.library.ualberta.ca/files/qf85nf11m#.VorEkJMrKEI

Same error message occurs when creating a collection, trying to delete an item, etc.

**Comment by sfbetz** [comment]
I think this one is resolved with work @weiweishi did earlier this week. I can successfully edit items with no error. Error only comes if I try to view a community that contains items I edited and then saved with no collection id (#913). I think this can be closed?

**Comment by weiweishi** [comment]
@sfbetz @pbinkley Can we close this one now?
