### ISSUE TITLE
Dataverse items not found in ERA

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#912]
Clicking on Dataverse items leads to item not found:

DV collection:
https://era.library.ualberta.ca/collections/wm117p010

Sample item:
https://era.library.ualberta.ca/files/3n203z16t

**Comment by weiweishi** [comment]
Did some investigation, and found that the issue is caused by not having hasCollection and hasCollectionId in the record. If the information is presented, then there's no issue to access the item:
https://era.library.ualberta.ca/files/3n203z16t

**Comment by weiweishi** [comment]
Found the issue is the "hasCollectionId" and hasCollection array are both [""] instead of a real empty array. Tried on several object on bournemouth and it has fixed the issue. Will try to see if I can find other objects beyond dataverse ones through Solr that are having the same issue.

**Comment by weiweishi** [comment]
All objects have been updated.
