### ISSUE TITLE
Error depositing Computing Science technical report

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#917]
I've created a new account associated with our email address and tried to deposit a new technical report into "Community: Department of Computing Science, Collection: Technical Reports". 
![describe1 2016-01-11 at 2 55 25 pm](https://cloud.githubusercontent.com/assets/1220762/12270044/70c960a4-b911-11e5-861b-cff8815dab85.png)
![describe2 2016-01-11 at 2 56 11 pm](https://cloud.githubusercontent.com/assets/1220762/12270047/72652a38-b911-11e5-943d-227090bf917a.png)
![describe3 2016-01-11 at 2 56 40 pm](https://cloud.githubusercontent.com/assets/1220762/12270052/73d095a6-b911-11e5-9868-843c35c6029f.png)

I was able to upload the item no problem, but the form threw an error when I tried to save the metadata on the "Describe your item" page. I would guess I made the submission around 2:45pm today (11 Jan 2016).
![error 2016-01-11 at 2 54 33 pm](https://cloud.githubusercontent.com/assets/1220762/12270016/4bef4e9c-b911-11e5-89e9-5ed4d454b730.png)

On old ERA I believe our CS ERA account may have had special permission to add to this collection - I had to navigate to the collection and use a deposit link on that page in order to upload tech reports (couldn't use the general "deposit" link). I'm not sure if this is part of the issue. 

Thanks,
Vanessa

**Comment by pgwillia** [comment]
![screenshot from 2016-01-12 10-29-53](https://cloud.githubusercontent.com/assets/1220762/12271275/7f11f1ac-b917-11e5-8cb1-5a9350b88e74.png)

**Comment by pgwillia** [comment]
```
I, [2016-01-11T14:46:23.521970 #5704]  INFO -- : Started POST "/batches/mg74qp75p" for 129.128.216.11 at 2016-01-11 14:46:23 -0700
I, [2016-01-11T14:46:23.524802 #5704]  INFO -- : Processing by BatchController#update as HTML
I, [2016-01-11T14:46:23.524942 #5704]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"fQy7LOkaG7CjelOxfmPOgpQXi25dlpZ/EpD11M7Xzu9Co33nO8GWAa8ZUW90aopesKACh3t+QMUzdP1P2cLPhw==", "title"=>{"b4m90dv54v"=>["Bidirectional Search That Is Guaranteed to Meet in the Middle: Extended Version"]}, "trid"=>{"b4m90dv54v"=>"TR15-01"}, "extra_description_count"=>"1", "generic_file"=>{"language"=>"English", "creator"=>["Holte, Robert C."], "subject"=>["heuristic search, bidirectional search"], "license"=>"http://creativecommons.org/licenses/by-nc-nd/4.0/", "rights"=>"", "description"=>"", "date_created"=>"2015", "contributor"=>[""], "spatial"=>[""], "temporal"=>[""], "is_version_of"=>"", "source"=>"", "related_url"=>"", "belongsToCommunity"=>["44558r201"], "hasCollectionId"=>["44558v39c"]}, "visibility"=>"open", "visibility_during_embargo"=>"restricted", "embargo_release_date"=>"", "visibility_after_embargo"=>"open", "new_user_name_skel"=>"", "new_user_permission_skel"=>"none", "update_permission"=>"", "id"=>"mg74qp75p"}
I, [2016-01-11T14:46:24.905354 #5612]  INFO -- : Started GET "/users/notifications_number" for 129.128.216.11 at 2016-01-11 14:46:24 -0700
I, [2016-01-11T14:46:24.907790 #5612]  INFO -- : Processing by UsersController#notifications_number as JS
I, [2016-01-11T14:46:24.925376 #5612]  INFO -- :   Rendered vendor/ruby/2.1.0/gems/sufia-6.2.0/app/views/users/_notify_number.html.erb (0.1ms)
I, [2016-01-11T14:46:24.925546 #5612]  INFO -- :   Rendered vendor/ruby/2.1.0/gems/sufia-6.2.0/app/views/users/notifications_number.js.erb (0.5ms)
I, [2016-01-11T14:46:24.925897 #5612]  INFO -- : Completed 200 OK in 18ms (Views: 1.5ms | ActiveRecord: 3.4ms)
I, [2016-01-11T14:46:25.211349 #5704]  INFO -- : Completed 500 Internal Server Error in 1686ms (ActiveRecord: 3.6ms)
F, [2016-01-11T14:46:25.212611 #5704] FATAL -- : 
NoMethodError (undefined method `cstr_collection_id' for #<Rails::Engine::Configuration:0x00000003ccb2a0>):
  app/controllers/concerns/hydranorth/batch_controller_behavior.rb:35:in `update'
```

**Comment by weiweishi** [comment]
I thought this is handled by the ansible playbook at the point of
deployment? Maybe worth checking with @henryzhang?

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by pgwillia** [comment]
Side effect of commits b4f6c5e600460e and 34a3fd5c which alter and remove tokens used to find and replace during deployment.
