### ISSUE TITLE
User can add their files to any collection

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#92]
User can add their files to any collection in the collection of collections (ERA collection) except for the thesis collection.
- [ ] add to deposit workflow: as I deposit my item, I can choose communities and collections to add them to (note: collection is not required)
- [ ] require the depositor to select a community when depositing: no item without a community

Implementation:
- [x] ensure that non-closed collections (i.e not theses or dataverse) are available in the workflow and item edit for users to add items to 
- [ ] a dropdown with all the communities; when you select one, you get a dropdown with the collections that belong to that community
- [ ] use solr "belongsToCommunity" property (added by #569) to enforce constraint that item must have a community

**Comment by pbinkley** [comment]
Also exclude Dataverse collection - any others?

**Comment by sfarnel** [comment]
perhaps consider also UAL licensed resources and sub-collections

On Wed, Jul 22, 2015 at 1:12 PM, Peter Binkley <notifications@github.com>
wrote:

> Also exclude Dataverse collection - any others?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/92#issuecomment-123830698>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by weiweishi** [comment]
Checked in current Hydranorth. Regular users don't seem to have access to collections that they don't own. They will see the following error message:
You do not have access to any existing collections. You may create a new collection.

**Comment by weiweishi** [comment]
Add to Collections on the batch upload form will be available in Sufia with:
https://github.com/projecthydra/sufia/pull/1307
It has to wait until hydra-collections 5.3 is ready.

**Comment by weiweishi** [comment]
@pgwillia I've figured out part of this - to allow registered users to edit collections that are not part of the admin set. I'll create a branch with my changes - and if you don't have time to put into this, I'll work with @mbarnett on it next week. 
 [ ] ensure that non-closed collections (i.e not theses or dataverse) are available in the workflow and item edit for users to add items to

**Comment by weiweishi** [comment]
My work is in the branch 92-add-files-to-any-collection in case anyone is interested.

**Comment by weiweishi** [comment]
@pbinkley @sfbetz @sfarnel 
Does it make sense to add the "Upload to Collection" to the first upload screen where users agree to the Terms and select files. That way we can probably get rid of the Special Collection options. This is how the latest PR in sufia works: projecthydra/sufia#1307.

**Comment by sfbetz** [comment]
This sounds like an okay option - but I think we have to be careful to make sure we're not really confusing the content on that screen. We'll need to have upload to community and then upload to collection that displays the collections in that community. We should make sure that we see the latest design work that @nnunn  has done with the deposit form to make sure we're not really cluttering up that first screen.  My preference would be to have this as a step that follows the agreement and upload step, but I don't want to create a huge amount of custom work if this functionality is coming down the pipe in the near future.

**Comment by weiweishi** [comment]
Okay. I will keep the communities/collection selection on the metadata page
for now then, and we can review that later.

Thanks!



*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
Details about the implementation of this story:
- [ ] Users can add to any collections except for admin collections (thesis and dataverse collection for now)
- [ ] Users will have to add at least one community to their deposit. Collection is optional
- [ ] If users have chosen to upload CSTR or SER then they will given the option but not required
- [ ] Dropdown menu to allow users to select a community and the collection dropdown will be populated based on their selection of the community. 
- [ ] User can add multiple group of communities/collections, but only the community in the first group is mandatory. 
- [ ] User will see the community/collection the object belongs to on the left side of the record page.

**Comment by weiweishi** [comment]
More:
- [ ] disable users to add collections to collections
- [ ] only allow users to add files to collections
- [ ] disable to add to collection button on the My Collection page
