### ISSUE TITLE
description entered on the upload form doesn't stick

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/HydraNorth#922]
The description entered on the upload form doesn't save properly, while other metadata fields are saved. Editing form seems to be fine. 
![screenshot - 16-01-14 - 11 05 52 am](https://cloud.githubusercontent.com/assets/2047614/12332989/d167ca24-baae-11e5-8659-6669eb96a920.png)

**Comment by mbarnett** [comment]
Pull request is up.
