### ISSUE TITLE
ARK: display to user

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#925]
On item page, show the ARK with wording to inform user that this is a permalink, like wording for handles in old ERA. @sfbetz will advise on placement and wording. We expect to use a local resolver, so the form will be https://era.library.ualberta.ca/id/ark:... Part of completion of #571.

**Comment by sfbetz** [comment]
Let's place ARKs here:
![ark location](https://cloud.githubusercontent.com/assets/12801010/12569188/c108205a-c389-11e5-8b36-191a7e64eb41.png)

I think it makes sense for it to be co-located with sharing and citation functionality. Language for other repos seems to be either "permanent URI" or "permanent URL"  - going with latter.

**Comment by pbinkley** [comment]
Closed by #973
