### ISSUE TITLE
Search results in different column

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#926]
![screenshot from 2016-01-15 16-25-12](https://cloud.githubusercontent.com/assets/1220762/12368035/a09d97c4-bba4-11e5-9d48-a9763d010069.png)
Is anyone else seeing this in development master?

**Comment by pbinkley** [comment]
I'm not seeing that on plano (which has current master) or on my local dev
vm (likewise). In both cases the results appear in the center column as
usual. Could you have some damaged item, maybe, that's throwing an artifact
into the html?

**Comment by pbinkley** [comment]
Intermittent in dev machines; Anna has seen in production in dashboard

**Comment by pgwillia** [comment]
Seeing it right now on my dev machine after recreating scenarios for a number of issues: 

[catalog.txt](https://github.com/ualbertalib/HydraNorth/files/143105/catalog.txt)

**Comment by pbinkley** [comment]
I still can't reproduce it, even with a result set similar to yours (several collections followed by some items). Presumably it's a css problem, where div#documents (which contains the table of results) is butting against div.batch-info (which contains the sort, show and refresh controls, including some modal boxes to handle operations on selected items), when it should drop below it. If it can be reproduced, maybe try adding ```div#documents {clear:left}``` to the css and see what happens?

**Comment by pgwillia** [comment]
I'm logged in as the admin (dittest@ualberta.ca). {clear:left} to the css does fix it.
