### ISSUE TITLE
Test failing on Jenkins

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#947]
Failures:

- [ ]  1) Advanced search Check keyword search finds uuid
     Got 0 failures and 2 other errors:
```
     1.1) Failure/Error: id = doc["id"]
          NoMethodError:
            undefined method `[]' for nil:NilClass
          # ./spec/features/advanced_search_spec.rb:31:in `block (3 levels) in <top (required)>'

     1.2) Failure/Error: @file.delete
          NoMethodError:
            undefined method `delete' for nil:NilClass
          # ./spec/features/advanced_search_spec.rb:36:in `block (3 levels) in <top (required)>'
```
- [x]  2) generic file new new item fields should not allow multiple resource_type selections, but assign to an array
```
     Failure/Error: expect(page).to have_xpath('//select[@name="generic_file[resource_type][]" and not(@multiple)]')
       expected to find xpath "//select[@name=\"generic_file[resource_type][]\" and not(@multiple)]" but there were no matches
     # ./spec/forms/generic_file_new_form_spec.rb:39:in `block (3 levels) in <top (required)>'
```
- [x]  3) generic file new request CSTR item should have CSTR field
     Failure/Error: expect(page).to have_field('generic_file_trid')
       expected to find field "generic_file_trid" but there were no matches
     # ./spec/forms/generic_file_new_form_spec.rb:55:in `block (3 levels) in <top (required)>'

- [x]  4) generic file new check form fields Title and creator is blank
```
     Failure/Error: within("form#new_generic_file") do
     Capybara::ElementNotFound:
       Unable to find css "form#new_generic_file"
     # ./spec/forms/generic_file_new_form_spec.rb:72:in `block (3 levels) in <top (required)>'
```
- [x]  5) CreateDerivativesJob thumbnail generation with a video (.avi) file generates a thumbnail on job run
```
     Failure/Error: subject.run
     RuntimeError:
       Unable to execute command "ffmpeg  -i "/tmp/content-120160129-10561-t82gwk" -s 320x240 -vcodec libx264 -acodec libfdk_aac -g 30 -b:v 345k -ac 2 -ab 96k -ar 44100 /tmp/sufia20160129-10561-5ot0xt.mp4"
       ffmpeg version 0.8.17-4:0.8.17-0ubuntu0.12.04.1, Copyright (c) 2000-2014 the Libav developers
         built on Mar 16 2015 13:26:50 with gcc 4.6.3
       The ffmpeg program is only provided for script compatibility and will be removed
       in a future release. It has been deprecated in the Libav project to allow for
       incompatible command line syntax improvements in its replacement called avconv
       (see Changelog for details). Please use avconv instead.
       Input #0, avi, from '/tmp/content-120160129-10561-t82gwk':
         Duration: 00:00:14.10, start: 0.000000, bitrate: 410 kb/s
           Stream #0.0: Video: msvideo1, rgb555le, 356x264, 10 fps, 10 tbr, 10 tbn, 10 tbc
           Stream #0.1: Audio: pcm_u8, 11025 Hz, 1 channels, u8, 88 kb/s
       Unknown encoder 'libfdk_aac'
     # ./spec/jobs/create_derivatives_job_spec.rb:31:in `block (4 levels) in <top (required)>'
```
- [x]  6) GenericFile#append_metadata with fulltext disabled (by default) should not call extract_content
```
     Failure/Error: @myfile.characterize
     RuntimeError:
       Unable to execute command "fits -i "/tmp/content-1.pdf20160129-10561-1mwm2bc.pdf""
       sh: 1: fits: not found
     # ./spec/models/generic_file_spec.rb:82:in `block (3 levels) in <top (required)>'
```
- [x]  7) GenericFile#append_metadata with fulltext enabled should call extract_content
```     
Failure/Error: @myfile.characterize
     RuntimeError:
       Unable to execute command "fits -i "/tmp/content-1.pdf20160129-10561-11wrxzb.pdf""
       sh: 1: fits: not found
     # ./spec/models/generic_file_spec.rb:82:in `block (3 levels) in <top (required)>'
```
- [x]  8) Migration rake tasks migration:eraitem - standard item item should be migrated
     Got 0 failures and 2 other errors:
```
     8.1) Failure/Error: id = doc["id"]
          NoMethodError:
            undefined method `[]' for nil:NilClass
          # ./spec/tasks/migration_rake_spec.rb:31:in `block (3 levels) in <top (required)>'

     8.2) Failure/Error: @file.delete
          NoMethodError:
            undefined method `delete' for nil:NilClass
          # ./spec/tasks/migration_rake_spec.rb:36:in `block (3 levels) in <top (required)>'
```
- [x]  9) Migration rake tasks migration:eraitem - multifile item multifile item should have a zip file
     Got 0 failures and 2 other errors:
```
     9.1) Failure/Error: id = doc["id"]
          NoMethodError:
            undefined method `[]' for nil:NilClass
          # ./spec/tasks/migration_rake_spec.rb:74:in `block (3 levels) in <top (required)>'

     9.2) Failure/Error: @file.delete
          NoMethodError:
            undefined method `delete' for nil:NilClass
          # ./spec/tasks/migration_rake_spec.rb:79:in `block (3 levels) in <top (required)>'
```
- [x]  10) Migration rake tasks migration:eraitem - item with a license file item should have the license file content as rights statement
      Got 0 failures and 2 other errors:
```
      10.1) Failure/Error: id = doc["id"]
            NoMethodError:
              undefined method `[]' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:112:in `block (3 levels) in <top (required)>'

      10.2) Failure/Error: @file.delete
            NoMethodError:
              undefined method `delete' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:117:in `block (3 levels) in <top (required)>'
```
- [x] 11) Migration rake tasks migration:eraitem - thesis item should have all thesis related metadata field
      Got 0 failures and 2 other errors:
```
      11.1) Failure/Error: id = doc["id"]
            NoMethodError:
              undefined method `[]' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:155:in `block (3 levels) in <top (required)>'

      11.2) Failure/Error: @file.delete
            NoMethodError:
              undefined method `delete' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:161:in `block (3 levels) in <top (required)>'
```
- [x]  12) Migration rake tasks migration:eraitem - legacy thesis item should have all thesis related metadata field
      Got 0 failures and 2 other errors:
```
      12.1) Failure/Error: id = doc["id"]
            NoMethodError:
              undefined method `[]' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:211:in `block (3 levels) in <top (required)>'

      12.2) Failure/Error: @file.delete
            NoMethodError:
              undefined method `delete' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:217:in `block (3 levels) in <top (required)>'
```
- [x]  13) Migration rake tasks migration:eraitem - dark item item should have private visibility
      Got 0 failures and 2 other errors:
```
      13.1) Failure/Error: id = doc["id"]
            NoMethodError:
              undefined method `[]' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:250:in `block (3 levels) in <top (required)>'

      13.2) Failure/Error: @file.delete
            NoMethodError:
              undefined method `delete' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:255:in `block (3 levels) in <top (required)>'
```
- [x]  14) Migration rake tasks migration:eraitem - ccid item item should have institutional visibility
      Got 0 failures and 2 other errors:
```
      14.1) Failure/Error: id = doc["id"]
            NoMethodError:
              undefined method `[]' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:286:in `block (3 levels) in <top (required)>'

      14.2) Failure/Error: @file.delete
            NoMethodError:
              undefined method `delete' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:292:in `block (3 levels) in <top (required)>'
```
- [x] 15) Migration rake tasks migration:eraitem - inactive item item should have private visibility
      Got 0 failures and 2 other errors:
```
      15.1) Failure/Error: id = doc["id"]
            NoMethodError:
              undefined method `[]' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:326:in `block (3 levels) in <top (required)>'

      15.2) Failure/Error: @file.delete
            NoMethodError:
              undefined method `delete' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:332:in `block (3 levels) in <top (required)>'
```
- [x] 16) Migration rake tasks migration:eraitem - embargoed item then open access item should have private visibility
      Got 0 failures and 2 other errors:
```
      16.1) Failure/Error: id = doc["id"]
            NoMethodError:
              undefined method `[]' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:365:in `block (3 levels) in <top (required)>'

      16.2) Failure/Error: @file.delete
            NoMethodError:
              undefined method `delete' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:371:in `block (3 levels) in <top (required)>'
```
- [x] 17) Migration rake tasks migration:eraitem - embargoed item then ccid protected item should have private visibility
      Got 0 failures and 2 other errors:
```
      17.1) Failure/Error: id = doc["id"]
            NoMethodError:
              undefined method `[]' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:406:in `block (3 levels) in <top (required)>'

      17.2) Failure/Error: @file.delete
            NoMethodError:
              undefined method `delete' for nil:NilClass
            # ./spec/tasks/migration_rake_spec.rb:412:in `block (3 levels) in <top (required)>'
```
Finished in 97 minutes 36 seconds (files took 20.11 seconds to load)
365 examples, 17 failures, 2 pending

Failed examples:

rspec ./spec/features/advanced_search_spec.rb:40 # Advanced search Check keyword search finds uuid
rspec ./spec/forms/generic_file_new_form_spec.rb:30 # generic file new new item fields should not allow multiple resource_type selections, but assign to an array
rspec ./spec/forms/generic_file_new_form_spec.rb:47 # generic file new request CSTR item should have CSTR field
rspec ./spec/forms/generic_file_new_form_spec.rb:63 # generic file new check form fields Title and creator is blank
rspec ./spec/jobs/create_derivatives_job_spec.rb:30 # CreateDerivativesJob thumbnail generation with a video (.avi) file generates a thumbnail on job run
rspec ./spec/models/generic_file_spec.rb:87 # GenericFile#append_metadata with fulltext disabled (by default) should not call extract_content
rspec ./spec/models/generic_file_spec.rb:96 # GenericFile#append_metadata with fulltext enabled should call extract_content
rspec ./spec/tasks/migration_rake_spec.rb:41 # Migration rake tasks migration:eraitem - standard item item should be migrated
rspec ./spec/tasks/migration_rake_spec.rb:84 # Migration rake tasks migration:eraitem - multifile item multifile item should have a zip file
rspec ./spec/tasks/migration_rake_spec.rb:122 # Migration rake tasks migration:eraitem - item with a license file item should have the license file content as rights statement
rspec ./spec/tasks/migration_rake_spec.rb:166 # Migration rake tasks migration:eraitem - thesis item should have all thesis related metadata field
rspec ./spec/tasks/migration_rake_spec.rb:222 # Migration rake tasks migration:eraitem - legacy thesis item should have all thesis related metadata field
rspec ./spec/tasks/migration_rake_spec.rb:260 # Migration rake tasks migration:eraitem - dark item item should have private visibility
rspec ./spec/tasks/migration_rake_spec.rb:299 # Migration rake tasks migration:eraitem - ccid item item should have institutional visibility
rspec ./spec/tasks/migration_rake_spec.rb:339 # Migration rake tasks migration:eraitem - inactive item item should have private visibility
rspec ./spec/tasks/migration_rake_spec.rb:378 # Migration rake tasks migration:eraitem - embargoed item then open access item should have private visibility
rspec ./spec/tasks/migration_rake_spec.rb:419 # Migration rake tasks migration:eraitem - embargoed item then ccid protected item should have private visibility

**Comment by pgwillia** [comment]
The remaining failing test is failing because it's dependant on a migration to initialize data for the test. This isn't necessary to test the advanced search functionality. However, replacing the migration with a couple of test objects reveals a bug in the keyword search of uuids where extra items are included in the result set because fedora3uuid is being tokenized. A fix for this test is straightforward, but causes regressions in the dataverse migration and migration rake specs and requires reindexing for a proportion of the existing items.  I propose a pull request for the 16/17 failing ci tests and a new issue for the remaining 1/17. Thoughts?

**Comment by weiweishi** [comment]
I agree on a separate issue for fixing the regressions. And as a matter of
fact, do we still need the migration rake specs now that we won't do any
further migration with the existing script? should we just ignore that
specs, and use other ways to initialize test data that are needed.
Dataverse migration tests are probably still needed, as the migration will
be an ongoing routine job.

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
