### ISSUE TITLE
Title and description allow multiple fields to be added in edit mode

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#949]
This is weird:

We now have an "add" button for title and description in the edit screen - neither should be repeatable. Now this item has two titles :(
![screen shot 2016-02-01 at 2 13 24 pm](https://cloud.githubusercontent.com/assets/12801010/12731612/fd1a2b46-c8ee-11e5-89ac-594ebb51e8ff.png)

**Comment by pbinkley** [comment]
Closed by #1058
