### ISSUE TITLE
OAI: resumptionTokens not returned as element

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#954]
resumptionTokens are returned as an attribute of the request element:

```
  <request verb="ListRecords" metadataPrefix="oai_dc" 
    resumptionToken="TGlzdFJlY29yZHM6b2FpX2RjOjo6OjIw"/>
```

The spec requires them to be returned as an element - e.g.:

```
   <resumptionToken expirationDate="2002-06-01T23:20:00Z" 
      completeListSize="6" 
      cursor="0">xxx45abttyz</resumptionToken>
```

**Comment by piyapongch** [comment]
I have looked at the document, http://www.openarchives.org/OAI/openarchivesprotocol.html#ListIdentifiers.
Here is a sample that is the same as implemented. The token is an request attribute.
<?xml version="1.0" encoding="UTF-8"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/
         http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
  <responseDate>2002-06-01T19:30:00Z</responseDate>
  <request verb="ListIdentifiers"
           resumptionToken="xxx45abttyz">http://an.oa.org/OAI-script</request>
  <ListIdentifiers>
    <header>  
      <identifier>oai:arXiv.org:hep-th/9801020</identifier>
      <datestamp>1999-02-23</datestamp>
      <setSpec>physic:hep</setSpec>
    </header> 
    <header>   
    <identifier>oai:arXiv.org:hep-th/9801060</identifier>
      <datestamp>1999-02-23</datestamp>
      <setSpec>physic:hep</setSpec>
    </header>  
    <resumptionToken completeListSize="6" cursor="4"/>
  </ListIdentifiers>
</OAI-PMH>

**Comment by piyapongch** [comment]
I have added resumptionToken as an element instead of attribute for ListRecords verb.

**Comment by piyapongch** [comment]
I have added resumptionToken as an element in ListIdentifiers verb results. I have also added cursor attribute on resumptionToken element.
