### ISSUE TITLE
OAI: empty and/or repeated elements

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#955]
If possible, remove empty or repeated descriptive metadata elements. In most cases, repetition or empty elements are related to theses mappings.

1. creator - content is repeated when object is thesis - see example 1; field empty when object is non-thesis - see example 2 (empty element seems to be expecting to marcrel:dis in those cases).
2. date - there are always two date elements, one expecting a freetext date, and another one expecting an ISO-formatted date. Empty elements occur whenever one of those dates is not present.
3. description - there are always three elements; I think the repetition is due to mappings to theses-exclusive fields: when populated, the first instance of description contains degree info (bibo:ThesisDegree, see example 1), the second contains non-theses descriptions (dcterms:description, see example 2), and the third captures abstracts in theses (dcterms:abstract see example 1).
4. publisher - In non-theses, this field always contains a '.' perhaps expecting marcrel:dgg (thesis field, see example 1)
5. relation - is always present and is empty when there is no content.

Example 1:
Thesis: https://era.library.ualberta.ca/files/9880vr65c
``` xml
<oai_dc:dc>
<dc:type>Thesis</dc:type>
<dc:creator>Chachula, Kathryn M</dc:creator>
<dc:creator>Chachula, Kathryn M</dc:creator>
<dc:contributor>Myrick, Florence (Faculty of Nursing)</dc:contributor>
<dc:publisher>University of Alberta; Faculty of Nursing</dc:publisher>
<dc:subject>Nurse exit from profession, workload, shiftwork, bullying, student-teacher relationships</dc:subject>
<dc:subject>New nurse graduate</dc:subject>
<dc:subject>Grounded theory</dc:subject>
<dc:date/>
<dc:date>2013-12-09T11:35:48Z</dc:date>
<dc:title>Letting go: How newly-graduated Registered Nurses in western Canada decide to exit the nursing profession</dc:title>
<dc:description>Master of Nursing</dc:description>
<dc:description/>
<dc:description>The Canadian Nurses Association predicts the nursing shortage will rise to an estimated 60,000 Registered Nurses (RNs) by the year 2022. Further compounding this issue is the approximate 14-61% of nursing graduates who will change nursing roles or exit the profession within two years of practice. Using the Glaserian grounded theory method, the purpose of this study was to examine the basic psychosocial process labelled Letting Go involved in how newly-graduated RNs in western Canada arrive at the decision to exit the nursing profession within five years of entry into the workforce through semi-structured interviews. The study findings revealed the following themes: Navigating Constraints of the Healthcare System and Workplace; Negotiating Social Relationships, Hierarchies, and Troublesome Behaviours; Facing Fears, Traumas and Challenges; and Weighing Competing Rewards and Tensions. This study adds to a growing body of knowledge to understand new RN attrition from the profession.</dc:description>
<dc:language>English</dc:language>
<dc:relation/>
<dc:rights>
Permission is hereby granted to the University of Alberta Libraries to reproduce single copies of this thesis and to lend or sell such copies for private, scholarly or scientific research purposes only. The author reserves all other publication and other rights in association with the copyright in the thesis and, except as herein before provided, neither the thesis nor any substantial portion thereof may be printed or otherwise reproduced in any material form whatsoever without the author&apos;s prior written permission.
</dc:rights>
<dc:rights>I am required to use/link to a publisher&apos;s license</dc:rights>
</oai_dc:dc>
```
Example 2:
Non thesis: https://era.library.ualberta.ca/files/9019s2728
This item contains 1 empty creator, 2 empty description elements, and one empty relation.
```xml
<oai_dc:dc>
<dc:type>Report</dc:type>
<dc:creator>Armstrong, Glen W.</dc:creator>
<dc:creator>Novak, Frank</dc:creator>
<dc:creator>Adamowicz, Wiktor</dc:creator>
<dc:creator/>
<dc:subject>timber harvesting</dc:subject>
<dc:subject>sustainable forestry</dc:subject>
<dc:subject>forest management</dc:subject>
<dc:subject>Canada, Alberta</dc:subject>
<dc:date>1995</dc:date>
<dc:date>2013-08-21T11:57:09Z</dc:date>
<dc:title>Environmental and Financial Sustainability of Forest Management Practices</dc:title>
<dc:description/>
<dc:description>One of the guiding themes for forest management policy throughout much of North America is sustained yield. The basic premise behind this theme is that a constant or non-declining flow of services from the forest is socially desirable. Unfortunately, the act of capturing the benefits of this service (timber harvesting) often has detrimental effects on the timber-productive capacity at a forest site. This paper presents a dynamic program that is used to determine the optimal harvest system choice for a timber stand described by average piece size, stand density, a measure of site quality, and stumpage value. The harvest systems are defined by logging costs, reforestation and rehabilitation costs, and the impact of the system on the productivity of the site. An application of the model is presented for lodgepole pine in Alberta. We conclude that at high discount rates, soil conservation is note economically rational. At lower discount rates, some degree of soil conservation is desirable on the more productive sites. At lower discount rates, there also appears to be an incentive for more intensive forest management. Limitations on acceptable harvest practices can have a large impact on optimal rotation age and the volume harvested. There is a large opportunity cost resulting from a requirement for sustainable volume production because of the imapct of harvesting on soil productivity.</dc:description>
<dc:description/>
<dc:language>English</dc:language>
<dc:relation/>
<dc:rights>Creative Commons Attribution-Non-Commercial-No Derivatives 3.0 Unported</dc:rights>
</oai_dc:dc>
```

**Comment by piyapongch** [comment]
I have removed all empty fields. The page size has been changed to 100. The results sort by last modified date. The application has been deploy on plano. I will be working on other issues.

**Comment by anayram** [comment]
Will check results.

**Comment by piyapongch** [comment]
Can you point me to the mapping document? Thanks,

**Comment by anayram** [comment]
No prob, here you go https://docs.google.com/spreadsheets/d/1hSd6kf4ABm-m8VtYNyqfJGtiZG7bLJQ3fWRbF_nVoIw/edit#gid=459268147

**Comment by anayram** [comment]
The ISO date seems to be a date accepted stamp (theses). I think we can do without it but we should check with @sfarnel 

Once a decision is confirmed I'll edit the data dictionary accordingly.

**Comment by piyapongch** [comment]
I have deployed the update on plano. I have re-configured jetty and added more memory to JVM. It seems to help on performance. The response time for 300 records (record set has been changed to 300) around 40 s. It is almost the same as 100 records before changes. Overall response time for harvesting 9323 records (all records on plano) is 22 m. 18 s. I think this is pretty good if comparing to 63 m. 42 s. in last week.

**Comment by piyapongch** [comment]
I have changes the result set to 500 records. The response time is ~45 s. For all items, response time is 14 m. 18 s. It seems to be faster as result set bigger.

**Comment by anayram** [comment]
I just ran the OAI harvester script and got all records in plano (9323) in 13 minutes.

Checking results

**Comment by piyapongch** [comment]
That is great! It is about 84 ms per record. I think we should try 40,000
records.

Piyapong.

**Comment by pbinkley** [comment]
Since Henry cloned production to test, we could try deploying the OAI
server on test Fedora and see how it does with the full set of records on
production-equivalent hardware.

**Comment by sfarnel** [comment]
That would be really great to try out.

On Wed, Feb 17, 2016 at 1:06 PM, Peter Binkley <notifications@github.com>
wrote:

> Since Henry cloned production to test, we could try deploying the OAI
> server on test Fedora and see how it does with the full set of records on
> production-equivalent hardware.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/955#issuecomment-185380585>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by piyapongch** [comment]
I have copied data from plano (9323 items) and put on my workstation. It took about 15 s. to harvest 500 items. That is 30 ms. per record. It is very fast.

**Comment by piyapongch** [comment]
@anayram: For the creator field can we get only form dcterms:creator or marcrel:dis? Do we really deduplicate data from both field?

**Comment by piyapongch** [comment]
@anayram: Is there any condition that I can check to prevent duplicate dcterms:creator? For example, 
if (dcterms:creator exists) then {
  add creator elements
} else {
  add creator elements from marcrel:dis
}
or vise versa

**Comment by piyapongch** [comment]
The deduplication will take some resources that will slow down the server and put some load on it. The process will run on all 500 items at the time. If we can avoid the deduplication process that should help with the server overall performance.

**Comment by anayram** [comment]
Yes, that condition should work well.

Another option is to choose source of creator data based on sets. For example:
if (object is thesis) then {
add creator from marcrel:dis
}
else {
add creator from dcterms:creator
}

**Comment by piyapongch** [comment]
I will add the condition to the source code.

**Comment by piyapongch** [comment]
I have added a Search verb for oai provider development. I am using it to check on oai metadata. Here is a sample url, http://plano.library.ualberta.ca:8983/fedora/rest/oai?verb=Search&property=dcterms:type&value=Thesis&metadataPrefix=oai_dc 

The verb will be removed from production deployment.

**Comment by piyapongch** [comment]
I have fixed all issues about oai_dc metadata and deployed on plano. Please check on sample records for those metadata fields.

Let me know if you found any problem.

**Comment by anayram** [comment]
Thanks @piyapongch; checked samples of field specs and only found two changes:

The field ualterms:specialization is not coming through. Should be mapped to `<dc:description>Specialization: [...] </dc:description>`
For example, the OAI record for the thesis "Characterization and Evaluation of Aged 20Cr32Ni1Nb Stainless Steels" (http://plano.library.ualberta.ca/files/ws859g42z) does not contain a dc:description element with the 'Materials Engineering' specialization.

Regarding mappings into dc:publisher: when no department (vivo:AcademicDepartment) is available, use marcrel:dgg only but remove period in mapping to dc:publisher.
Example: in the same sample record mentioned above, remove period from:
`<dc:publisher>University of Alberta.</dc:publisher>`

**Comment by piyapongch** [comment]
Can you try this url, http://plano.library.ualberta.ca:8983/fedora/rest/oai?verb=GetRecord&identifier=https://era.library.ualberta.ca/oai/dev/ws/85/9g/42/ws859g42z&metadataPrefix=oai_dc?

**Comment by anayram** [comment]
Works, thanks! @piyapongch

**Comment by piyapongch** [comment]
I did not do anything. You might have looked at the old data. You might want to harvest new metadata from plano. 

I am checking on dc:publisher field.

**Comment by anayram** [comment]
Hmm, I was looking at data harvested today around 10:30. But you are right, I just harvested another copy and things are looking good.

**Comment by anayram** [comment]
@piyapongch 

Here is a draft condition for OAI display of marcrel:dgg and/or vivo:AcademicDepartment

* If both marcrel:dgg and vivo:AcademicDepartment are present  
   print: marcrel:dgg "; "  then  
      * if vivo:AcademicDepartment = 1 occurrence, print its value followed by "."  
      * if vivo:AcademicDepartment > 1 occurrence, separate each value with ', '  
* If only marcrel:dgg is present  
   print: "University of Alberta"
* Otherwise, print only marcrel:dgg (no punctuation)

This assumes that all theses will have University of Alberta as degree grantor
@sfarnel do you see any cases where that does not apply?

**Comment by piyapongch** [comment]
I have fixed the dc:publisher field and updated on plano. Please check again and let me know.

**Comment by piyapongch** [comment]
I have also fixed the dc:identifier field.

**Comment by sfarnel** [comment]
This will be true in *almost* all cases. We currently have one thesis - in
the UAL staff collection - which is not from UA:

https://era.library.ualberta.ca/files/9306sz65x

On Wed, Mar 2, 2016 at 12:04 PM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> @piyapongch <https://github.com/piyapongch>
>
> Here is a draft condition for OAI display of marcrel:dgg and/or
> vivo:AcademicDepartment
>
>    - If both marcrel:dgg and vivo:AcademicDepartment are present
>    print: marcrel:dgg "; " then
>    - if vivo:AcademicDepartment = 1 occurrence, print its value followed
>       by "."
>       - if vivo:AcademicDepartment > 1 occurrence, separate each value
>       with ', '
>       - If only marcrel:dgg is present
>    print: "University of Alberta"
>    - Otherwise, print only marcrel:dgg (no punctuation)
>
> This assumes that all theses will have University of Alberta as degree
> grantor
> @sfarnel <https://github.com/sfarnel> do you see any cases where that
> does not apply?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/955#issuecomment-191374982>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by anayram** [comment]
Ok, that is good to know. The conditions I sent above would

* capture theses that have a different publisher than "University of Alberta"
* but would add "University of Alberta" as publisher when no marcrel:dgg is present. So in the case of Denise's thesis, because it has no degree grantor information, it would appear as granted by the University of Alberta.

So we need to remove the condition: "If none of marcrel:dgg and vivo:AcademicDepartment are present
print 'University of Alberta'" 
@sfarnel is that ok with you?

**Comment by sfarnel** [comment]
This should do it.

On Fri, Mar 4, 2016 at 3:29 PM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> Ok, that is good to know. The conditions I sent above would
>
>    - capture theses that have a different publisher than "University of
>    Alberta"
>    - but would add "University of Alberta" as publisher when no
>    marcrel:dgg is present. So in the case of Denise's thesis, because it has
>    no degree grantor information, it would appear as granted by the University
>    of Alberta.
>
> So we need to remove the condition: "If none of marcrel:dgg and
> vivo:AcademicDepartment are present
> print 'University of Alberta'"
> @sfarnel <https://github.com/sfarnel> is that ok with you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/955#issuecomment-192500416>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685

**Comment by anayram** [comment]
@piyapongch can we remove please the condition below?

If none of marcrel:dgg and vivo:AcademicDepartment are present
print "University of Alberta"

**Comment by anayram** [comment]
All fixed. Closing ticket.
