### ISSUE TITLE
ARK: deployment prep

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#957]
For the deployment of the new ARK functionality, we need a couple of pieces:
- [x] register shoulder for production (done). Our production values are:
  - NAAN: 54379
  - Shoulder​: t7
- [ ] fix ansible deployment to use test naan and shoulder in dev environments, and to resolve to hydranorthdev.library.ualberta.ca. The ARK creation code now doesn't error out when it tries to create an ARK that already exists at ezid. So it doesn't matter if different test vms start at the beginning of the NOID minter's sequence and try to use the same ARK: the ARK will be assigned to the item with that NOID whether the ARK previously existed or not, and it will resolve to the local vm when tested on that workstation.

Later, if it becomes a concern, maybe:
- [ ] maybe add an option to turn off ARKs in dev environments, to reduce load on EZID service? If we run a large migration test in dev (e.g. on plano) we'll be creating a lot of useless test arks

**Comment by sfbetz** [comment]
Resolved through DOI work (@pbinkley - reopen if not the case!)
