### ISSUE TITLE
Improve "Browse by Communities" function

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#960]
As a user I want to browse communities and collections so I can easily find sets of items produced by organizational entities.

As a collection “owner” (not technically, but organizationally) I want to be able to showcase sets of items from my research group or department so I can demonstrate the body of work being created.

As a researcher, I was my items to be grouped with similar items so that they become more findable for end users, and to emphasize my connection to a department or group.

Design work completed by @nnunn 

Notes from @nnunn : 

I have pushed the changes for the browse community page to a branch called 840_browsing_communities. I haven't created a pull request since this still requires some developer time to get the code to actually work. The work that needs to be done is in app/views/communities/index.html.erb. I tried to put all the information into the comments on that page. If anything isn't clear, or if it doesn't look like it should, let me know. It should look like this once it's set up -- https://www.ualberta.ca/~nnunn/era-demo/ERA.html

**Comment by sfbetz** [comment]
Part of epic #840

**Comment by pgwillia** [comment]
This functionality is completed, but performance might be an issue.  Is 35 seconds to load this page acceptable? If not, what would be?

**Comment by sfbetz** [comment]
I would think that's too high for most users ... Nielson Norman has long held that 10 seconds is the max response time for just about everything:

**Comment by sfbetz** [comment]
https://www.nngroup.com/articles/response-times-3-important-limits/

**Comment by pgwillia** [comment]
Thanks @sfbetz! I have a goal!

**Comment by sfbetz** [comment]
No problem! For future reference, this is very helpful:
"
0.1 second: Limit for users feeling that they are directly manipulating objects in the UI. For example, this is the limit from the time the user selects a column in a table until that column should highlight or otherwise give feedback that it's selected. Ideally, this would also be the response time for sorting the column — if so, users would feel that they are sorting the table. (As opposed to feeling that they are ordering the computer to do the sorting for them.)

1 second: Limit for users feeling that they are freely navigating the command space without having to unduly wait for the computer. A delay of 0.2–1.0 seconds does mean that users notice the delay and thus feel the computer is "working" on the command, as opposed to having the command be a direct effect of the users' actions. Example: If sorting a table according to the selected column can't be done in 0.1 seconds, it certainly has to be done in 1 second, or users will feel that the UI is sluggish and will lose the sense of "flow" in performing their task. For delays of more than 1 second, indicate to the user that the computer is working on the problem, for example by changing the shape of the cursor.

10 seconds: Limit for users keeping their attention on the task. Anything slower than 10 seconds needs a percent-done indicator as well as a clearly signposted way for the user to interrupt the operation. Assume that users will need to reorient themselves when they return to the UI after a delay of more than 10 seconds. Delays of longer than 10 seconds are only acceptable during natural breaks in the user's work, for example when switching tasks.
"

**Comment by pgwillia** [comment]
So I've got it down to between 5-10 (mean: 7.05 median: 6.8, sample size: 16) seconds to load the page. Is this acceptable?

**Comment by sfbetz** [comment]
Much better. I can live with it (although would be nice to improve in the future!).

**Comment by pgwillia** [comment]
I spoke too soon.  I had been working with a subset of the communities and collections in ERA, as I add more the response time is significantly >10s.

Some other things I didn't initially consider. Do we want only the official collections to be shown?

**Comment by sfbetz** [comment]
We only want official collections to appear. We do not want to see personal collections on that page.

**Comment by pgwillia** [comment]
Using group_by with one Solr call results in an average page load time of 5.36 seconds (sample size 16).
