### ISSUE TITLE
Redesign Community landing page

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#961]
As a user, I want to be able to see all of a community’s collections so I can easily browse those collections.

As a user, I want to be able to sort a community’s collections by title, number of items, or most recently updated so I can easily find relevant collections.

As a user, I want to be able to search for items within a community so I can easily find items that belong to any of its collections.

As a user, I want to be able to see items with no collections (only a community), so they don’t get lost?

As a collection owner, I want to be able to attach some branding to my community to provide some recognition of its identity.

Specifications in this doc: 
https://docs.google.com/presentation/d/1INXmuNfTPFGVC9sMAh8iLYzD2FnBCPkAEKCF3Su4Vqk/edit?usp=sharing

REQUIRED
-append Community description to top of faceted search page
-include collections within that community, and items with no collections, in faceted search
-update labels

IF POSSIBLE
-allow addition of thumbnail image to community in place of icon (referenced in #73 )
-enable HTML in description field
-update breadcrumbs for communities to point pack to browse page
-search for items within community (if not possible, remove search  box)

**Comment by sfbetz** [comment]
from epic #840

**Comment by pbinkley** [comment]
Closed by #1029
