### ISSUE TITLE
Redesign Collections landing page

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/HydraNorth#962]
As a user I want to be able to browse sets of items grouped by collections so I can find related items.

As a user, I want options to sort and refine sets of items, so I can easily find what I’m looking for.

Specifications here: 
https://docs.google.com/presentation/d/195k-GIB4C2W7KFrqna6XMki8IGxvWaZx_HGBXZSYzh8/edit?usp=sharing

Same strategy as Community Page #961, with exceptions:
-no logo or icon required.
-different labels

**Comment by sfbetz** [comment]
part of epic #840

**Comment by weiweishi** [comment]
PR #1029

**Comment by sfbetz** [comment]
Some comments and bugs:

Bug in facets - clicking on "more" in facets doesn't display list when logged in, Public view not allowing faceting
Public view of landing page doesn't include paging and sorting options
Pagination not displaying on either logged in or public view
Don't need description button - can just display description text
Logged in view search results are squeezed into middle of the page.

**Comment by pbinkley** [comment]
Closes #786
