### ISSUE TITLE
Replace zeroclipboard with clipboard.js

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#964]
Sufia uses zeroclipboard.js to provide the click-to-copy functionality to copy urls to the user's clipboard (e.g. in the file list on the user's dashboard). This uses a bit of Flash, which really doesn't belong any more and is frequently blocked by browsers. [clipboard.js](https://clipboardjs.com/) provides the same functionality in HTML5, and its copy function works in all modern browsers except Safari (and it degrades gracefully there). So: let's make the switch. Let's contribute this to Sufia, too.

**Comment by zenorocha** [comment]
+1

**Comment by pbinkley** [comment]
Is this still a problem in Sufia 7?

**Comment by mbarnett** [comment]
Sufia 7 is now using clipboard.js
