### ISSUE TITLE
OAI: double-encoded entities in xml output

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#965]
```
<dc:rights>&amp;#169; University of Alberta, Department of Anthropology</dc:rights>
```
The copyright symbol should be encoded as ```&#169;```, or serialized as UTF-8.

(Found in j9602117h)

**Comment by anayram** [comment]
The problem extends to other entities. E.g.:

In m613mz27v:
`&amp;apos;`highways`&amp;apos;`

In vt150k13w:
reporters`&amp;#8217;`

In rr171x99r:
Twenty control subjects (average age = 56.8`&amp;#177;`12.4) and 19 ALS patients (average age = 56.7`&amp;#177;`13.7) were recruited for the study. Texture features were statistically different in ALS compared to controls (p`&amp;lt;` 0.0001 for T1, and p`&amp;lt;`

In w3763747h
Brazil, Paran`&amp;#225;`

In zc77sq78m:
Ecuador, Pichincha, R`&amp;#237;`o Inga

ns064676b
Heinrich B`&amp;#246;`ll

**Comment by piyapongch** [comment]
I have fixed the double encodings problem. It has been deployed on plano.
