### ISSUE TITLE
OAI: Apache proxy

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#967]
Configure production Apache to proxy from /oai to fedora/rest/oai, to make the oai service available to the public.

**Comment by piyapongch** [comment]
I have worked with Henry and showed him how to set up the Apache Proxy and deploy the OAI Provider. I have deployed the OAI Provider on Gillingham, Fedora 4 test server. Henry is working on the proxy. He has set the redirect to oai provider that working. He will continue to work on domain name overwriting.

**Comment by piyapongch** [comment]
The proxy is working for Identify verb. When I have try, https://era-test.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_dc, I got an error message, 502 Proxy Error. 

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /oai.

Reason: Error reading from remote server

Apache/2.2.15 (CentOS) Server at era-test.library.ualberta.ca Port 443

**Comment by piyapongch** [comment]
The proxy should support HTTP.

**Comment by piyapongch** [comment]
The proxy error has been fixed by changing request timeout and keepalive configuration on the proxy and apache servers.

**Comment by piyapongch** [comment]
ModeShape JCR-SQL2 queries have been optimized using local indexes. All responses take less than 1m to response. The proxy request timeout does not need to be increased. The proxy server is working. The URL for test server is https://era-test.library.ualberta.ca/oai. The URL for production will be https://era.library.ualberta.ca/oai.
