### ISSUE TITLE
OAI: ERA identifiers

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#971]
Current OAI metadata does not include (resolvable) unique ERA identifiers in OAI responses.

[HydraNorth Data Dictionary (OAI tab)](https://docs.google.com/spreadsheets/d/1hSd6kf4ABm-m8VtYNyqfJGtiZG7bLJQ3fWRbF_nVoIw/edit#gid=459268147) contains a mapping of those fields into OAI metadata formats (currently mappings include DC, QDC, and ETDMS only).

**Comment by piyapongch** [comment]
I have added all dc:identifier for oai_dc according to the data dictionary. Please check on plano.

**Comment by anayram** [comment]
Handles are coming through from ERA data but new items created in HydraNorth do not have handles and therefore no permanent identifier.

Example:
http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_dc&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t7jw827d11n

Should we include a permanent link (i.e. usign noids or arks?)

**Comment by leahvanderjagt** [comment]
If we can, I think we should, as these links are prominently displayed in
the LAC record on the interface side. --Leah

On Tue, Mar 29, 2016 at 11:26 AM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> Handles are coming through from ERA data but new items created in
> HydraNorth do not have handles and therefore no permanent identifier.
>
> Example:
>
> http://129.128.67.154:8983/fedora/rest/oai/?metadataPrefix=oai_dc&verb=GetRecord&identifier=oai:era.library.ualberta.ca:ark:/54379/t7jw827d11n
>
> Should we include a permanent link (i.e. usign noids or arks?)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/971#issuecomment-203010744>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by weiweishi** [comment]
To use the current noid link for the identifier before we implement ARKs. And once the arks are in place the records will be updated. We will continue to keep the two identifiers, so that the noid link will continue to work even LAC doesn't update their records.

**Comment by anayram** [comment]
Identifier fields now present in items created in new ERA. Closing ticket.
