### ISSUE TITLE
OAI: LAC identifiers, direct link to PDF

### ISSUE THREAD

**Issue by anayram** [ualbertalib/HydraNorth#972]
LAC requires that descriptive metadata contains an identifier element with a "direct link to PDFs that end with a '.pdf' extension."

**Comment by piyapongch** [comment]
What is object metadata field for the identifier?

**Comment by anayram** [comment]
I looked at examples from other universities and they use one of the following patterns:

repositoryurl/objectid.pdf
where objectid is either TCnumber, noid, ark, or other unique identifier

repositoryurl/objectid/filename
this would work better for theses that have more than one file

**Comment by piyapongch** [comment]
The OAI Provider does not know anything about filename. If I modify the JCR-SQL2 to join more object into query, the response time will be increased. For the ListRecords verb, it takes  ~2-3 m (on era-test with ~40,000 items). It is already slow.

**Comment by weiweishi** [comment]
Can this be fast-tracked to facilitate this need? #848

**Comment by pbinkley** [comment]
And keep in mind that performance on OAI is a very secondary concern. As
long as the requests don't time out, it's ok.

**Comment by weiweishi** [comment]
@pbinkley we also had a discussion at the Sprint Review meeting today, and @henryzhang87 has to increase the timeout limit in both Apache and HAProxy in order for the API call to complete, and he is concerned about this. We also have discussions about the performance for Fedora 4 in general, which I will update you before the next Sprint kickoff on Tuesday.

**Comment by weiweishi** [comment]
We will use the following URL structure for LAC OAI: 
/downloads/noid.pdf. 
@piyapongch will generate the url from the current url structure. 

We will add a route to the OAI URL to redirect to current url.

**Comment by anayram** [comment]
@piyapongch @pbinkley 
All pdf links are ok. Can I close this issue or should we wait until we can test the links?

**Comment by anayram** [comment]
Links working, a bit slow but do work. Closing now.

**Comment by weiweishi** [comment]
@pcharoen the filename is an property available on fedora object:downloadFilename
<info:fedora/fedora-system:def/model#downloadFilename>

**Comment by piyapongch** [comment]
I could not find the property on plano.

**Comment by pbinkley** [comment]
We haven't loaded the pdfs on plano, just the metadata.

**Comment by anayram** [comment]
I think there is a problem with pdf links. Most (if not all) thesis file names contain spaces so the links don't work.

Example:
https://era.library.ualberta.ca/downloads/Davies_Troy_Fall 2013.pdf

See:
https://era-test.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_etdms

**Comment by anayram** [comment]
@piyapongch

**Comment by leahvanderjagt** [comment]
just FYI that file naming convention is a spec from FGSR required of
students when they submit their theses. --Leah

On Fri, May 6, 2016 at 11:05 AM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> @piyapongch <https://github.com/piyapongch>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/HydraNorth/issues/972#issuecomment-217500252>
>



-- 
___________________________________________________________




*Leah VanderjagtDigital Repository Services Librarian University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by anayram** [comment]
Also there will be several non-theses files uploaded by users that contain spaces too.

**Comment by piyapongch** [comment]
It needs a route to PDF on Rails application, #1071.

**Comment by piyapongch** [comment]
I have encoded the download URL. The download URL should be working properly.

**Comment by anayram** [comment]
@piyapongch @pbinkley 

Looks like the links are not working.

I tried 
https://era.library.ualberta.ca/downloads/Davies_Troy_Fall+2013.pdf
and
https://era.library.ualberta.ca/downloads/Petkau_Kristina_Fall+2012.pdf
from:
https://era-test.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_etdms

**Comment by piyapongch** [comment]
This will be working when HydraNorth downloads route deployed on production server.

**Comment by piyapongch** [comment]
I have added noid to the download link. Try again.

**Comment by anayram** [comment]
@piyapongch, the server now throws a 502 error:
https://era-test.library.ualberta.ca/oai?verb=ListRecords&metadataPrefix=oai_etdms

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /oai.
Reason: Error reading from remote server
Apache/2.2.15 (CentOS) Server at era-test.library.ualberta.ca Port 443

**Comment by pbinkley** [comment]
I've got direct access to fedora on Gillingham now, and I can see the new
links. There's still one change needed: the url should have "/files/"
instead of "/downloads/". (This is part of revising the download links to
make them fit Google Scholar's guidelines, with the pdf nested under the
object it belongs to).

Peter


Peter Binkley, Ph.D., MLIS / Digital Initiatives Technology Librarian /
peter.binkley@ualberta.ca
2-10K Cameron Library / University of Alberta / Edmonton, Alberta / Canada
T6G 2J8
phone 780-492-3743 / fax 780-492-9243

**Comment by anayram** [comment]
@pbinkley I assume this change is needed in @piyapongch's code, is that right?

The stylesheet has that change already in case you need a quick fix.

**Comment by pbinkley** [comment]
It will have to be packaged in the application, which either Piyapong or
Henry could do. There's no need for you to do anything. When Henry is back
next week we need to discuss how to deploy it in production. Currently
era-test times out when retrieving the theses from Fedora - the response
take 5 minutes 39 seconds when I retrieve it directly from Fedora. We'll
have to adjust the timeout in Apache, I think, to make it wait longer for
the response; but hopefully it will be a little faster in production.

Peter


Peter Binkley, Ph.D., MLIS / Digital Initiatives Technology Librarian /
peter.binkley@ualberta.ca
2-10K Cameron Library / University of Alberta / Edmonton, Alberta / Canada
T6G 2J8
phone 780-492-3743 / fax 780-492-9243

**Comment by piyapongch** [comment]
I think you need switch to use repository-index.json by copying it over
repository.json and restart tomcat. This will configure the ModeShape index
and allow the OAI provider to use the indexes. For the first time, it might
be a little bit slow because the repository needs to load the indexes into
memory. After that, the response time should be under one minutes (from my
testing, it is about 35 sec.). This step is also in the document.



Piyapong.

**Comment by pbinkley** [comment]
That took care of it! From 5:39 down to 0:26 response time.

Peter

**Comment by piyapongch** [comment]
@anayram I have updated the download link and it seems to be working. Can you try it on Gillingham (era-test)? Thanks,

**Comment by piyapongch** [comment]
Do we need download link for oai_dc?

**Comment by anayram** [comment]
This is working now. All good.

Last time I checked with Sharon and Peter separately there was no immediate need to have pdf links in oai_dc (only for oai_etdms - a LAC requirement).

Right now we have both handles and era permanent links in oai_dc as well as oai_etdms. The latter is the only one with the pdf link requirement.

**Comment by piyapongch** [comment]
Can I close this issue? Is there any other issue?

Piyapong.

**Comment by anayram** [comment]
I found a problem with handles, but it is not related to the OAI work (problematic handles come from Fedora, opening a separate ticket).

Closing this issue.

**Comment by weiweishi** [comment]
Thank you Mariana.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
