### ISSUE TITLE
fedora3uuid should not be tokenized

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#974]
#947  reveals bug in the keyword search of uuids where extra items are included in the result set because fedora3uuid is being tokenized. A fix for this test is straightforward, but causes regressions in the dataverse migration and migration rake specs and requires reindexing for a proportion of the existing items.

**Comment by pbinkley** [comment]
Closed after code merge to ```reindexathon``` branch, whose deployment is handled in #977
