### ISSUE TITLE
dawnscanner report

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/HydraNorth#980]
Scan summary 

| Dawn version | 1.6.0 |
| --- | --- |
| Scan started | 2016-02-22 16:49:29 -0700 |
| Scan duration | 3.856 sec |
| Target | /var/www/sites/hydranorth |
| Framework | rails v4.2.5.1 |
| Applied checks | 227 security checks |
| Skipped checks | 0 security checks |
| Vulnerabilities found in dependencies | 4 |
| Reflected XSS found | 0 |

[third_party_vulnerabilities.txt](https://github.com/ualbertalib/HydraNorth/files/141646/third_party_vulnerabilities.txt)

**Comment by pbinkley** [comment]
Let's rerun the scan under Ruby 2.3.1

**Comment by leahvanderjagt** [comment]
@pbinkley can the dev team please groom this issue and add to IR if high priority, keep in hydranorth2 if in scope of current work, or future if is not immediately pressing

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#109
