### ISSUE TITLE
Compress assets for faster page loading

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#982]
From #186 - e.g. with http://stackoverflow.com/a/34435255

**Comment by leahvanderjagt** [comment]
@pbinkley can the dev team please groom this issue and add to IR if high priority, keep in hydranorth2 if in scope of current work, or future if is not immediately pressing

**Comment by pbinkley** [comment]
I'll move it with the other hydranorth2 issues. I suspect that @murny's work on cleaning up the initial HydraNorth2 rails codebase has already addressed this but we'll confirm.

**Comment by pbinkley** [comment]
This issue was moved to ualbertalib/Hydranorth2#108
