### ISSUE TITLE
User Management: Allow admin to log in as any user

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/HydraNorth#988]
From #833. The intention is to allow admin to edit user profile and manage/upload items for that user. This functionality is supported by Devise.

**Comment by pgwillia** [comment]
https://github.com/plataformatec/devise/wiki/How-To:-Sign-in-as-another-user-if-you-are-an-admin

**Comment by pgwillia** [comment]
@sfbetz @piyapongch do you have screen shots of what this looks like in thesisdeposit?  I could replicate that or if you have any suggestions for improvements?

**Comment by sfbetz** [comment]
I find it a little confusing in thesis deposit. Could we do something like this?
![2016-03-04_14-47-14](https://cloud.githubusercontent.com/assets/12801010/13542733/f94ac376-e221-11e5-9534-da4aecc601c5.png)

Ignore the misplaced table headers! What I'm trying to display are: 

-  inline buttons for each user (only visible to admin, of course) to login as, or delete
-  a way to delete multiple users with a select box

**Comment by pgwillia** [comment]
Great minds... that's where I started too.  I'm thinking once you become a user you have to logout and log back in to become admin again.

**Comment by sfbetz** [comment]
That makes sense. I assume the top right hand "you are logged in as" would change based on who you are logged in as?
